### ISSUE TITLE
Ideas for improvement

### ISSUE THREAD

**Issue by noClaps** [vfsfitvnm/ViMusic#1]
You should add a Liked Songs or similar playlist automatically when someone clicks the heart button. Maybe it can be the default playlist while other playlists can have a separate page.

Also maybe allow the Most Played section to be lowered or collapsed?

If the default playlist from above is implemented, you could also add a Floating Action Button that defaults to shuffle play. Similar to how [Retro Music Player](https://github.com/RetroMusicPlayer/RetroMusicPlayer) have it.

Downloads and offline listening are good features, but I'd understand not having them.

That's all the ideas I have for now. If I come up with more I'll add to this issue. I can't wait to see where this app goes. Cheers!

**Comment by vfsfitvnm** [comment]
Thanks! The Liked Songs section is already here - just tap the two arrow icon near "Most Played". I realized this is not intuitive, so I'll change that.

**Comment by noClaps** [comment]
I think Favorites should be a separate playlist, similar to how it is in most mainstream music apps, like Spotify, and the Most Played/History section should be collapsible.

I also really like the approach in https://github.com/z-huang/music. They have a whole section for songs, one for artists, and one for playlists.

Either one of these options would be nice to have.

**Comment by vfsfitvnm** [comment]
The Most Played/Favorite/History section will be definitely redesigned - I just need to figure out how do it properly.

> the Most Played/History section should be collapsible.

This is true for Favorites and History: if the user has listened to/has liked 10000 songs, the app will create 10000 objects at startup - not a good idea. So I'll probably pick just the first 8 songs, with a "See all" button to expand the list or whatsoever.

> They have a whole section for songs, one for artists, and one for playlists.

I'll add a bottom navigation bar eventually (playlist, explore/search, settings...), as of now it looks useless because there's little data to display.
Also, it's not a good idea to have an "artist" section - youtube returns wrong or missing data quite often. Sometimes it shrinks multiple artists in a single text with a single id. This is very error prone and will cause problems eventually.

Cheers

**Comment by noClaps** [comment]
For the artist section, you can fetch song metadata from Spotify. There's a project called [spotdl](https://github.com/spotDL/spotify-downloader) that does this.

**Comment by vfsfitvnm** [comment]
That idea crossed my mind at a certain point, but it's quite a weak and error-prone approach if you think about it (waste of bandwidth, delayed responses, some songs are not available on spotify and so on).
`spotdl` has a simple mission (download songs), so it can afford this tradeoff.

**Comment by noClaps** [comment]
Is it possible to fetch both lyrics and song metadata from Genius. They usually tend to have more accurate lyrics than the ones built into Youtube Music. And if youre getting lyrics from genius already, it shouldnt be too much slower to get metadata as well.

**Comment by vfsfitvnm** [comment]
The song metadata must be fetched from youtube. Out of question.

Currently, lyrics are retrieved from youtube as well. I know they are disappointing sometimes (e.g. they are wrong or missing), however this isn't a feature I'll be working on personally anytime soon.

I think I could just add a "search lyrics online" text button which opens the browser with a input like "artist song lyrics" or similar. Also, I could store the lyrics in the database, so the user can edit them (if they are wrong or missing). I think this is a good compromise.

I think I'll close this issue soon - we went over topic. Please file a separate issue for every feature request (e.g. the lyrics thing, listen to device songs and so on). Thanks!
