### ISSUE TITLE
More overview at the artists in the library.

### ISSUE THREAD

**Issue by Alliba** [vfsfitvnm/ViMusic#10]
### Feature description

Great job bro. Cool would be a rubric for artists under the songs and albums of the artist are deposited.

### Why do you want this feature?

- To get more order in the songs and albums.

- To be able to play songs or songs of an artist.

- To find specific songs or artists in your library more quickly.

**Comment by vfsfitvnm** [comment]
Closing in favor of #11.
Also: https://github.com/vfsfitvnm/ViMusic/issues/11#issuecomment-1171473898
