### ISSUE TITLE
Lyrics Search not working 

### ISSUE THREAD

**Issue by TheAnonyUnknown** [vfsfitvnm/ViMusic#103]
### Steps to reproduce the bug

Play any song which don't have lyrics
Tap on lyrics tab
Tap on search online

### Expected behavior

It should open search query in browser 

### Actual behavior

It says, no browser app found

### Screenshots/Screen recordings

![Screenshot_2022-07-14-08-29-34-12_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/179000393-eabb67df-83f1-451e-832f-2b4fb28f8c10.jpg)

### ViMusic version

0.2.0

### Android version

Android 12

### Additional information

I'm using Chrome browser.

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/62
