### ISSUE TITLE
No albums are displayed for any artists

### ISSUE THREAD

**Issue by ikanakova** [vfsfitvnm/ViMusic#1033]
### Steps to reproduce the bug

1. Find an artist or go to a saved artist.
2. Go to albums.

### Expected behavior

View the album list.

### Actual behavior

Displayed "This artist didn't release any album." even though he has several albums in Overview

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/38765251/230964424-d7ff8827-edbc-4f58-b666-8af3d0bf4a67.mp4

### ViMusic version

0.5.4 (F-Droid)

### Android version

Android 13

### Additional information

Reinstalling the application or restoring the database did not help.

**Comment by leerhsen** [comment]
Managed to solve?

**Comment by Lanchon** [comment]
i can confirm this happens for some users, while not for others. in particular, i am not affected. i am using android 9 (lineageos).

**Comment by ikanakova** [comment]
I've noticed that if the artist is in saved artists the album list doesn't show up even if I find saved artist as others, but if it's not in saved artists everything works as it should.

**Comment by vfsfitvnm** [comment]
Uhm, I'm pretty sure youtube changed something on their side

**Comment by JeDx420** [comment]
This is still happening to me and with every artist, I have to search up the specific album and enter it from normal search

**Comment by leerhsen** [comment]
@vfsfitvnm do you think you can solve this problem?

**Comment by leerhsen** [comment]
@vfsfitvnm do you think you can solve this problem?

**Comment by Lanchon** [comment]
> Managed to solve?

> @vfsfitvnm do you think you can solve this problem?

@leerhsen please do not post unhelpful messages on issues. either provide useful info, fix the issue yourself, offer money, or keep quiet and avoid distracting everybody. thank you.

**Comment by leerhsen** [comment]
> > Managed to solve?
> 
> > @vfsfitvnm do you think you can solve this problem?
> 
> @leerhsen please do not post unhelpful messages on issues. either provide useful info, fix the issue yourself, offer money, or keep quiet and avoid distracting everybody. thank you.

🖕

**Comment by dainvincible1** [comment]
![Screenshot_2023-04-28-14-33-38-79_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/127825700/235165736-9018e8aa-0b42-4b4f-80ee-7c3053dd3752.jpg)
 

im having this issue

**Comment by franciscoD96** [comment]
issue doesn't happen if when you access the artist go directly to Overview

**Comment by Melonadev** [comment]
> issue doesn't happen if when you access the artist go directly to Overview

Some artists' Overview pages do not list their albums, for example:
![image](https://github.com/vfsfitvnm/ViMusic/assets/66422959/64f8976e-92c6-4dcf-8c85-e3dd7d14445f)

**Comment by Aqmals** [comment]
Waiting the update for this issue. 🫶

**Comment by Lanchon** [comment]
> Waiting the update for this issue. 🫶

what are you waiting for?? we've already said how to side step it. read!

**Comment by dainvincible1** [comment]
anybody managed to solve this?

**Comment by ikanakova** [comment]
The album display works for me again.  If it works for everyone else, this issue can be closed.

**Comment by dainvincible1** [comment]
> The album display works for me again. If it works for everyone else, this issue can be closed.

yes same, its working again
