### ISSUE TITLE
Make playlists layout preference (grid/list view) persistent

### ISSUE THREAD

**Issue by PassionateG1t** [vfsfitvnm/ViMusic#104]
### Feature description

When the user chooses whether to organize their playlists in a horizontal list or a vertical grid, the choice is persistent until it is toggled again.

### Why do you want this feature?

The default view for playlists is in list form but since I have many playlists, I prefer seeing them in sort of a grid style. At the moment when searching for a song, opening settings page, or relaunching the app, the layout defaults back to the list view. This renders changing the layout futile since it will always revert back to the old style.

**Comment by vfsfitvnm** [comment]
I'm currently redesigning that part (#107)
