### ISSUE TITLE
Notification shows that song is still playing when playback is paused by another app

### ISSUE THREAD

**Issue by Fxsch** [vfsfitvnm/ViMusic#1046]
### Steps to reproduce the bug

Play audio in a different app while the app is playing a song

### Expected behavior

Notification should show that the song is paused

### Actual behavior

The song is still shown as playing, eventhough it's actually paused 

### ViMusic version

0.5.4

### Android version

Android 13

**Comment by devlocalhost** [comment]
Cannot replicate. Can you send a screen recording video? (Tested with Spotify)

**Comment by Fxsch** [comment]
In the video I open TikTok and it's happening there

https://user-images.githubusercontent.com/77849217/235927318-38126bc5-491d-436e-ab1a-5e1182e505a9.mp4

**Comment by Fxsch** [comment]
Just noticed this is still open. Issue has been fixed for a while.
