### ISSUE TITLE
Show lyrics above thumbnail

### ISSUE THREAD

**Issue by DavidRLTG** [vfsfitvnm/ViMusic#105]
### Feature description

in my opinion, the Now Playing screen looks just a tiny bit bland and maybe a few customizations and improvements to it wouldn't help!
Some suggestions:
1. When you tap the album cover, Lyrics appear.
2. Maybe the background could be a heavily blurred version of the album image, or a color based off of the album primary color, or just in general something that looks pretty modern and cool
3. Could we have an option to disable the circle behind the Play/Pause button?
4. In my opinion, a few more animations would look pretty cool
5. If the song title is too long to show, it should scroll so that you can see the entire title

### Why do you want this feature?

In my opinion, improving the Now Playing screen would be very visually pleasing.

### Additional information

![Screenshot_20220715-182803_Metro](https://user-images.githubusercontent.com/87834635/179255649-4a71e06d-dfba-4cae-9161-904ca098ee5e.png)
Example of a Now Playing screen that looks really visually appealing to me
(CREDIT: Retro Music Player)

**Comment by vfsfitvnm** [comment]
Thanks for opening this issue.

> When you tap the album cover, Lyrics appear.

Where and how? Would you provide a sketch or an animation?

 > Maybe the background could be a heavily blurred version of the album image, or a color based off of the album primary color, or just in general something that looks pretty modern and cool

Definitely doable for A12+ devices (because jetpack compose provides out of the box support for it). Blurring and color extraction are two relatively expensive operation btw. Also, I was waiting for [this](https://github.com/material-foundation/material-color-utilities) to be released.

> Could we have an option to disable the circle behind the Play/Pause button?

Why?

> In my opinion, a few more animations would look pretty cool

What animations and where?

> If the song title is too long to show, it should scroll so that you can see the entire title

Jetpack compose does not provide a text marquee yet, I could implement it myself bla bla bla, but I think they are gonna do it soon, so I'll just wait

**Comment by DavidRLTG** [comment]
![Screenshot_20220715-184908_BlackPlayer](https://user-images.githubusercontent.com/87834635/179259756-d8a37985-3f1c-4eab-a047-13c666af2259.png)
Here is an example of lyrics over the album cover!
(Credit: Blackplayer)

**Comment by DavidRLTG** [comment]
And I just personally would like the option to disable the circle behind the play button because it could look visually appealing to me, and maybe a few others

**Comment by DavidRLTG** [comment]
And by animations I just mean in general, when you press the play button something happens, when you skip, when you favorite a song, when you enable re-play, stuff like that!
(Examples: Blackplayer has the favorite icon gradually fill when you press it, and Retro Music Player has the play button kind of zoom out quickly then back up when pausing then when unpausing it zooms in then back down, hard to explain)

**Comment by vfsfitvnm** [comment]
Ok, the lyrics thing is definitely possible and it seems a good idea. However I'm not sure how it will look in a squared thumbnail. Let's see what other people think about it.

Regarding the animations, they will improve with time I guess. Saying and imaging "something animate", but coding and thinking is actually the hardest part.

**Comment by DavidRLTG** [comment]
I agree a lot with the second part, I'm sorry if my suggestions are a bit too complicated to actually implement into the app, just came here to give my thoughts, have a good day
