### ISSUE TITLE
Add streaming quality statistic

### ISSUE THREAD

**Issue by C2M6D** [vfsfitvnm/ViMusic#106]
### Feature description

When you hold down on the album civer, display the quality you are streaming at (e.g.  256 kbits/s) 

### Why do you want this feature?

To be able to see at what quality I am streaming my music.

### Additional information

I am not really sure at what quality the current audio is, although I know that YouTube Music is capped at 256 kbits/s.

**Comment by Pruthvi3070** [comment]
Hey how can I increase my stream quality

**Comment by JPGuillemin** [comment]
YTM is streaming OPUS 160kbps if the player ask for it , no matter if the Account is Premium (it's VP9 group of codecs).

OPUS 160kbps is 100% transparent "aka : CD quality" and by far superior to AAC 256kbps. OPUS is even nearly "lossless like" at 128kbps. So for this codec : 160kbps is overkill quality, even on my very high end audiophile audio gear there's no chance to distinguish OPUS 160 from FLAC.

I checked the bandwidth of ViMusic : it's OPUS without any doubt : 20KHz bandwidth.

So don't worry : viMusic is alreeady providing CD quality.



![Screenshot_2023-02-11-19-09-45-579_org intoorbit spectrum](https://user-images.githubusercontent.com/55490396/218274444-7b28a9e4-a6ce-4a76-905d-9f4e474642b3.jpg)
