### ISSUE TITLE
The radio doesn't load similar songs.

### ISSUE THREAD

**Issue by ikanakova** [vfsfitvnm/ViMusic#1067]
### Steps to reproduce the bug

1. Search song: Johnny Cash - God`s Gonna Cut You Down
2. Start radio.
3. There are songs in the queue that are not similar.  God`s Gonna Cut You Down is a folk, country, gospel, but the queue is mostly rock, etc.

### Expected behavior

The songs on the radio will be similar to the original song (such as in the [Nuclear](https://github.com/nukeop/nuclear/) computer app - see screenshot) - only Johnny Cash songs or country classics will be in the queue.

### Actual behavior

There are also rock and other unrelated songs in the radio queue.

### Screenshots/Screen recordings
Comparison of the ViMusic and Nuclear queues.

<img src="https://github.com/vfsfitvnm/ViMusic/assets/38765251/ec5afd25-85d9-421b-807d-44b7e850ea69" alt="ViMusic radio" width="300">
<img src="https://github.com/vfsfitvnm/ViMusic/assets/38765251/e4c8e427-903d-4431-bcd5-e9d11ef8bd88" alt="Nuclear autoradio" width="300">

### ViMusic version

0.5.4 (F-Droid)

### Android version

Android 13

### Additional information

I also often find that when I start the radio on different songs of different genres, several of the same songs appear repeatedly in the queue.

**Comment by Ankan-cyber** [comment]
Could any of you guys provide the jdk or jvm file to run this on an Linux machine with Java command for arm64

**Comment by user88294** [comment]
ViMusic uses Youtube's servers. This is not a ViMusic problem, it's Youtube.
