### ISSUE TITLE
Size of Song "Unknown"

### ISSUE THREAD

**Issue by C2M6D** [vfsfitvnm/ViMusic#108]
### Steps to reproduce the bug

1. I to on a Song in this album
2. I hold to see statistics
3. The size of the song is displaying "Unknow"
4. Therefore, it is not showing in the Cached songs playlist, even though the whole song has been cached

### Expected behavior

It should show me the size of the song, and display the percentage cached.

### Actual behavior

It displays the size as Unknown, and does not show the sing in the cached playlist 

### Screenshots/Screen recordings

![Screenshot_20220716-111020](https://user-images.githubusercontent.com/109240975/179348745-8a97671e-3e58-425e-97b1-ce86d9e30706.jpg)

### ViMusic version

0.2.0

### Android version

Android 12

### Additional information

This hasn't happened with other songs, only songs from that Album.

**Comment by vfsfitvnm** [comment]
This happens sometimes and I don't know why. `v0.1.7` had a button "Fill missing data" to refetch the missing data. Do you remember which version of ViMusic did you have when you played this song for the first time?

**Comment by C2M6D** [comment]
> This happens sometimes and I don't know why. `v0.1.7` had a button "Fill missing data" to refetch the missing data. Do you remember which version of ViMusic did you have when you played this song for the first time?

No, I do not remember.

**Comment by vfsfitvnm** [comment]
That's unfortunate. If you have ADB, would you run this command?
```
adb shell "dumpsys package it.vfsfitvnm.vimusic | grep firstInstallTime"
```
So we can determine the version.

**Comment by C2M6D** [comment]
> 

No I do not have ADB. But I can tell you that I originally dowloaded the app in version 0.1.7.

**Comment by vfsfitvnm** [comment]
Thanks, this is enough. Also, I could reproduce with `0.2.0` - but I don't know how it happened. I'll investigate

**Comment by C2M6D** [comment]
> Thanks, this is enough. Also, I could reproduce with `0.2.0` - but I don't know how it happened. I'll investigate

Any news yet? Do you have an Idea on how I could fix this?

**Comment by C2M6D** [comment]
@vfsfitvnm

**Comment by vfsfitvnm** [comment]
Yeah. I could reproduce - all I had to do is importing an album and then playing the first song.
