### ISSUE TITLE
Missing "LYRICS" Button

### ISSUE THREAD

**Issue by AnkushDebnath00** [vfsfitvnm/ViMusic#1087]
![Uploading Screenshot_2023-06-09-14-34-24-41_b72a20be883aec8a014bd2b7c7038e87.jpg…]()
While playing the song, there is no place for a lyrics button, I can't see the lyrics of the song. Otherwise I would like to, really like to move on from Spotify.

Expected behavior
I visited your reddit where in a comment you wrote that there is a "LYRICS" Button.

Actual behavior
But I can't see any button.

**Comment by ikanakova** [comment]
No need for a lyric button - just tap on the album image to view the lyrics.

**Comment by AnkushDebnath00** [comment]
Ooops...... My bad. I couldn't find any place the lyrics. Now Gotcha. 
Thanks btw.
