### ISSUE TITLE
Expand bottom player on play

### ISSUE THREAD

**Issue by siker498** [vfsfitvnm/ViMusic#109]
### Feature description

Make the player expand when a song is played

### Why do you want this feature?

All streaming apps usually do this and makes it seamless

### Additional information

Music app  from z Huang had this: 
![Screenshot_20220716-131432_Music](https://user-images.githubusercontent.com/21956733/179365348-2cf43938-6796-4b71-9c56-6ab60a8ffd16.png)

**Comment by vfsfitvnm** [comment]
Why did you open another issue about this?

**Comment by siker498** [comment]
My bad I thought my old one got closed but there was just new feature requests above it and I didn't notice. (I don't use GitHub alot) should I close this one?

**Comment by vfsfitvnm** [comment]
Yup :)
