### ISSUE TITLE
Export as CSV

### ISSUE THREAD

**Issue by Krusty27** [vfsfitvnm/ViMusic#1108]
### Steps to reproduce the bug

Would it be possible to export playlists, artists etc... as CSV? It could be useful to visualize that data or import in other apps.

### Expected behavior

Possibility to export as CSV instead of .db

### Actual behavior

Exporting as .db

### ViMusic version

0.5.4

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
No...

**Comment by devcomputer** [comment]
why not?
makes so much sense because ViMusic does not work on desktop and I would want to import my favorite artists to other apps aswell.
