### ISSUE TITLE
Unable to search

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#111]
### Steps to reproduce the bug

1. Open the app.
2. Press the search bar.
3. Search for anything.

### Expected behavior

Normally, the sing you typed in should appear and you should be able to play it.

### Actual behavior

What happened was that I got a java.net.SocketException instead. Not a single song pops up.

### Screenshots/Screen recordings

![Screenshot_20220718-043622](https://user-images.githubusercontent.com/109493802/179437474-1d3e752c-16ee-4a74-9e9f-0755fdffb2b6.jpg)

### ViMusic version

0.2.0

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
I can't reproduce. Is you internet connection working? Are you using a VPN? Do you live in a country where YT Music is not available yet?

**Comment by MountainFlowers** [comment]
>

**Comment by MountainFlowers** [comment]
I am connected. Yes I am using a VPN. Yes ny country has YT music

**Comment by MountainFlowers** [comment]
It works now. Thanks. But why did it not work with a VPN?

**Comment by vfsfitvnm** [comment]
I don't know, maybe you were connected to a country YTM didn't support.
