### ISSUE TITLE
Lockscreen isn't the playing song

### ISSUE THREAD

**Issue by Dridrimoon** [vfsfitvnm/ViMusic#1112]
### Steps to reproduce the bug

Go go settings, Appearence
Scroll down to Lockscreen, show song cover
Go to your lockscreen
(I already gave all permissions possible to the app)

### Expected behavior

The playing song should be used as the lockscreen wallpaper

### Actual behavior

My lockscreen wallpaper stay the same

### Screenshots/Screen recordings

![Screenshot_2023-07-09-13-46-20-000_it vfsfitvnm vimusic](https://github.com/vfsfitvnm/ViMusic/assets/79791353/4309b8f3-42b8-486b-a99f-45f1a0380fdf)
![Screenshot_2023-07-09-13-46-27-650_lockscreen](https://github.com/vfsfitvnm/ViMusic/assets/79791353/4f5e5339-a304-4133-a7d0-d7009d7ab31d)

### ViMusic version

0.5.4

### Android version

Androïd 11

### Additional information

This isn't a big issue but the lockscreen wallpaper option isn't working for me :)
Thanks in advance for your response.

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/975#issuecomment-1441633140
