### ISSUE TITLE
How does ViMusic tell favorites apart from others?

### ISSUE THREAD

**Issue by yephny** [vfsfitvnm/ViMusic#1119]
I'd like to get a list of my favorited songs in order to download them but I can't find a list of just my favorites in the database file I exported. How are they stored, how is ViMusic able to tell they're my favorites when I restore the backup?

**Comment by vfsfitvnm** [comment]
`Song` table has a `likedAt` timestamp. If it's not null, then you liked that song at the reported timestamp

**Comment by yephny** [comment]
Thank you, that works.
