### ISSUE TITLE
Import a playlist

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#112]
### Feature description

So, I have a playlist on spotify that has over 600 song + others. Same with YouTube. And it will be really bothersome to add each song one by one. So i think it would be efficient if you could import a playlist. Be it through a link or connecting to the account.

### Why do you want this feature?

It's really just because I'm too lazy. Not to mention it's just a good thing to have all around. Not to mention it will be easy to migrate between music services. Which means more users.

**Comment by vfsfitvnm** [comment]
You can already import a playlist by its link. However, there's currently a limit of 200 songs. The next release will have this limit removed.

**Comment by MountainFlowers** [comment]
I can't find the import option

**Comment by vfsfitvnm** [comment]
Paste the link somewhere (e.g. Telegram), then open it with ViMusic

**Comment by vfsfitvnm** [comment]
1) What's the link?
2) What does happen instead?

**Comment by MountainFlowers** [comment]
1. The link is (https://youtube.com/playlist?list=PLzG7levEW_EiwfsVfUUaBEMYMK5ZiHqBK)
2. What happens is that it open with Youtube, not ViMusic. I pasted the link on my saved messages on Telegram. I held the link and pressed open.

**Comment by vfsfitvnm** [comment]
That's because Youtube is your default application for opening these links. You have to disable it via app settings

**Comment by MountainFlowers** [comment]
Yeah, I'm sorry. But it is just not working. I disabled YouTube opening the links and made ViMusic able to open all YouTube links. Yet when i open the link, it just opens on my browser

**Comment by MountainFlowers** [comment]
Could you show images on how to import links?

**Comment by vfsfitvnm** [comment]
https://www.androidauthority.com/change-default-apps-android-2-633572/

You can also paste the link to the text field when searching

**Comment by MountainFlowers** [comment]
An m.youtube link worked, but this one didn't.
https://youtube.com/playlist?list=PLzG7levEW_EiwfsVfUUaBEMYMK5ZiHqBK

**Comment by yahyanor** [comment]
Hei um, you could add the (m.) To youtube.com (m.youtube.com) so it can be import to ViMusic, it'working for me👍

**Comment by yahyanor** [comment]
Since the app not support yet the url for "youtube.com"

**Comment by SYCOINFOERNO** [comment]
hi so I have the playlist as a .csv file and when I tried to import it to vimusic it did not allow me to do that

**Comment by ifelixculpa** [comment]
hi i still cant import playlist from yt music. can anyone please help :(

**Comment by MountainFlowers** [comment]
Hello hi. As of the current moment, the app can only import links from the YouTube site, not the app. So search YouTube on Google and find the playlist you want. Look at the url on the top, hold it and press the open button that should hopefully pop up. 

Keep in mind, you have to disable the YouTube app opening it's own types of links and making vmusic able to open YouTube links. You can do this in settings, apps and choosing the app you want to modify.

**Comment by ifelixculpa** [comment]
> Hello hi. As of the current moment, the app can only import links from the YouTube site, not the app. So search YouTube on Google and find the playlist you want. Look at the url on the top, hold it and press the open button that should hopefully pop up.
> 
> Keep in mind, you have to disable the YouTube app opening it's own types of links and making vmusic able to open YouTube links. You can do this in settings, apps and choosing the app you want to modify.

can i do this as that is my personal list , but wanted to move to vimusic as this app is amazing , thankyou so much for guidance

**Comment by SYCOINFOERNO** [comment]
Thanks for spending time in answering my doubts.
  
Hope that this app will get better and better in the future.
  

  
Best Regards,
  
SYCOINFOERNO.
  

  

  

  
  
  
  
>

**Comment by omk12** [comment]
> That's because Youtube is your default application for opening these links. You have to disable it via app settings

Thanks a  lot. Worked like a charm. Was trying to do it for such a long time. Thx a lot

**Comment by SYCOINFOERNO** [comment]
Is there a way to like export the playlists from vimusic to a different vimusic user without the whole database

**Comment by omk12** [comment]
> Is there a way to like export the playlists from vimusic to a different vimusic user without the whole database

U can share individual songs but idt there is a way to share the whole playlist

**Comment by Nicklehert** [comment]
Is it possible to do the opposite? I would like to share a playlist on vimusic to a friend

**Comment by RushilJalal** [comment]
I opened the youtube playlist link in ViMusic but the screen is stuck on this. Pasting screenshot below:
![WhatsApp Image 2023-12-23 at 12 32 39_86831e7f](https://github.com/vfsfitvnm/ViMusic/assets/54212357/95ca99cd-e483-4b3c-b4e4-a4e12514ccd5)

**Comment by AtharvPatil25** [comment]
Does this work for Spotify and Amazon Music?

**Comment by Nishantinsan** [comment]
> An m.youtube link worked, but this one didn't. https://youtube.com/playlist?list=PLzG7levEW_EiwfsVfUUaBEMYMK5ZiHqBK

you can manually add m.youtube.com/ in your link

**Comment by Nishantinsan** [comment]
Hey developer i dont know what it happening some playlist with less songs. show up and i can add it to my library but whenever i try to open a playlist with more than 50 songs it just gets stuck at loading playlist 
![Screenshot (35)](https://github.com/vfsfitvnm/ViMusic/assets/40457243/55f70af7-d6e5-4d77-b77d-ac55071e10aa)

**Comment by itsplawan** [comment]
this is still an issue and has happened to the first playlist I tried to import. 
![Screenshot_20240219_183435.jpg](https://github.com/vfsfitvnm/ViMusic/assets/106014964/8377faec-4b60-4cae-8228-7e356edd082d)

**Comment by RushilJalal** [comment]
@itsplawan same for me

**Comment by Phoe-nix-89** [comment]
how to disable youtube for not opening the youtube links in the app and open in some other apps ??

**Comment by Phoe-nix-89** [comment]
@vfsfitvnm Please help me with this issue...i've got like a playlist with about 150+ songs and it'll be very hard for me to add each and every song manually please cant you create like some inbuilt function that can extract the youtube playlist if the youtube playlist is created into some other form like - csv , db file.....there should be some API out there that would allow you to add this into the app as there are clients for spotify out there , it means this can be done for youtube also

**Comment by Tejas-2704** [comment]
> You can already import a playlist by its link. However, there's currently a limit of 200 songs. The next release will have this limit removed.

How??

**Comment by Tejas-2704** [comment]
> this is still an issue and has happened to the first playlist I tried to import. ![Screenshot_20240219_183435.jpg](https://private-user-images.githubusercontent.com/106014964/305954491-8377faec-4b60-4cae-8228-7e356edd082d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NjE0MDYsIm5iZiI6MTcxNDg2MTEwNiwicGF0aCI6Ii8xMDYwMTQ5NjQvMzA1OTU0NDkxLTgzNzdmYWVjLTRiNjAtNGNhZS04MjI4LTdlMzU2ZWRkMDgyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQyMjE4MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzgzZmE4MWQ3MjhjNjdlMzM3NGIxMTljZWMzYjVjZmEzNTJiZTZmNjY1MmRiZTkzOWEzZTMzNjBmYzdkZWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oRojkzobBgWKayQllNPvpgYmFs2TDGNaYsemFZ-tmvM)

Same happening with me

**Comment by DarkLord25** [comment]
**Here are the steps to successfully import any playlist:**

1. Go to Spotify > Copy playlist link
2. Go to a web browser > Paste the link > Modify the link (next step)
3. Change "_https://open.spotify.com/playlist/_" to "_https://spotifyplaylist.com/_"
4. Follow further instructions on the browser to export the playlist as a **.csv** file
5. CONVERT .CSV FILE TO VIMUSIC FILE FORMAT
6. Import the playlist to ViMusic

:)

**Comment by watashinosoulsociety** [comment]
@DarkLord25 this just doesn't work man i tried importing my yt playlist multiple times like my supporting yt links are turned off too but this just ends up looking like this 
![Screenshot_2024-07-12-16-11-38-76_6f55a3c4de83481ebdee1685416eed82](https://github.com/user-attachments/assets/a9460745-975a-49d4-a2aa-cbd514c7e112)
Can you please upload a video on how to do it and are there no communities like discord or telegram where I can ask if i face any other issues

**Comment by watashinosoulsociety** [comment]
Or just do smth where we can log into our yt accounts

**Comment by watashinosoulsociety** [comment]
Or just do smth where we can log into our yt accounts

**Comment by danial40245** [comment]
> **Here are the steps to successfully import any playlist:**
> 
> 1. Go to Spotify > Copy playlist link
> 2. Go to a web browser > Paste the link > Modify the link (next step)
> 3. Change "_https://open.spotify.com/playlist/_" to "_https://spotifyplaylist.com/_"
> 4. Follow further instructions on the browser to export the playlist as a **.csv** file
> 5. CONVERT .CSV FILE TO VIMUSIC FILE FORMAT
> 6. Import the playlist to ViMusic
> 
> :)

what's vimusic file format . and how do i convert .csv file into that

**Comment by pookdeveloper** [comment]
I'm trying to use this URL to import a playlist but it doesn't work.

https://open.spotify.com/playlist/3yJf6pwvilY5txST6ZqflL?si=a6324c26b0b54f8e
