### ISSUE TITLE
Feature request, hide explicit versions

### ISSUE THREAD

**Issue by GITdatt** [vfsfitvnm/ViMusic#1121]
### Steps to reproduce the bug

N/a

### Expected behavior

Just hoping to play back audio without explicit lyrics when kids are around

I understand some albums already come as Censored or with Parental Advisory version Existing in the YouTube Music servers. 

The difference in my request being that a button enabling such a feature can be switched on and off For when I select "start radio" on a song, which may include a lot of explicit versions on random. 

### Actual behavior

No feature available to switch between explicit and censored versions of songs (parental advisory labeled music)

### Screenshots/Screen recordings

![Screenshot_20230715_122217](https://github.com/vfsfitvnm/ViMusic/assets/139650935/701e48dd-5051-4d2a-861f-29722ddc2931)

### ViMusic version

0.5.4

### Android version

13

### Additional information

Hoping to use app with choice of minimizing bad language when kids are home

**Comment by vfsfitvnm** [comment]
Tracking in #1082 (correct me if I'm wrong)

**Comment by GITdatt** [comment]
Yes that's correct. I realize an entry about this feature request has been addressed. Not planned; does that mean it's not going to be created?
