### ISSUE TITLE
App not functioning as it should

### ISSUE THREAD

**Issue by VeljaIT46** [vfsfitvnm/ViMusic#1139]
### Steps to reproduce the bug

There are multiple bugs that happend suddenly.
More detalis in "Actual behavior" of this post.
Bug No. 1) Search bar is not working at all. 
-To reproduce this bug, just search for any song
Bug No. 2) Any song you try to play, they cannot play at all. 
-To reproduce this bug, just try to play any song
Bug No. 3) When you go to 'Quick Picks' menu and try to tap on recommended playlists, it will try to load them but it will never load them. 
-To reproduce this bug, head to the 'Quick Picks' menu and under section ''Artists'', there should be section "Playlists you might like", tap on any playlist and it wont load.

### Expected behavior

For 1. Bug, the search should work and whatever you type, it should display songs that you searched
For 2. Bug, the songs should play
For 3. Bug, when you click playlists in 'Quick Picks' it should display them really quick.

### Actual behavior

For 1. Bug, the search doesnt work at all (whatever you search, it just says "No results found, please try a different query or category."
For 2. Bug, whatever song you try to play, they cannot play at all (The error is either "The audio is not in playable format" or "The original source of this song is deleted", depending on what song you want to play (i cant remember the exact sentences, since i reinstalled the app and, because of bug no. 1, i cant retype those sentences).)
For 3. Bug, instead of loading playlists in the 'Quick Picks' menu, it will try to load them but it will actually never load them (keep in mind i have really good internet connection).

### ViMusic version

0.5.4

### Android version

Android 13

### Additional information

I have been using this app for year, and this is the best app for music to evet exist, but these bugs started happening a couple of days ago (by the time im writing this), until then, everything was working perfectly. I think it could be either random bug or it could be that YouTube is getting involved in this.
I really hope this app will get fixed and that its just random bug.

**Comment by VeljaIT46** [comment]
Hello developers!
Im happy to say that the app is functioning perfectly again.
The app just fixed itself 🤣 (tried every feature and works like described)
If i need help with anything, im gladly gonna drop a comment!

**Comment by Leoul-crypto** [comment]
Hello
Why not working vimusic app
Earlier i used to play it by vpn 
At the recent day when i open and play it i can't why this happened and how can fix this
