### ISSUE TITLE
Broken on Android 13 ?

### ISSUE THREAD

**Issue by Vexcited** [vfsfitvnm/ViMusic#1150]
### Steps to reproduce the bug

1. Open the app

And that's all, the app closes itself 

### Expected behavior

App should be opened

### Actual behavior

App is closed

### Screenshots/Screen recordings

https://github.com/vfsfitvnm/ViMusic/assets/59152884/0ca798f4-74a8-4253-b670-94ddb38ed289

### ViMusic version

0.5.4

### Android version

Android 13

### Additional information

It happened after my device did an upgrade to Android 13 (official update)

When I was on Android 11 it worked perfectly.

Can't provide ADB logs right now but will do whenever I get back on my PC.

**Comment by VivekKumar432** [comment]
Works fine for me on both of my android devices running Android 13.

**Comment by Vexcited** [comment]
Ok, so for some reason I had to uninstall and reinstall the app after the OS upgrade.

Now it's working fine 🤔

Anyway, thanks for telling me!

**Comment by vfsfitvnm** [comment]
@Vexcited Thanks for reporting. Did you enable "Persistent queue"?

**Comment by Vexcited** [comment]
> Was "Persistent queue" enabled?

yes it was
