### ISSUE TITLE
Follow artists to know about new releases

### ISSUE THREAD

**Issue by dhishkyaon** [vfsfitvnm/ViMusic#117]
### Feature description

It would be great if its possible to add an option to follow artists to know about their new releases.

Also i see there are many requests to make changes to the app which are not important like remove round button, edit songs etc. So please only make those changes which you think are important because i guess you are the only developer on the app and single person can't handle this much of work.

### Why do you want this feature?

Its great to be notified about new releases.

**Comment by vfsfitvnm** [comment]
I don't think this can be implemented - we can't use youtube subscriptions as there's no login system. In other words, there is no way for me to know if an artist has released something new (well, other than spamming network requests every time the user opens the app).
Do you have an idea?

**Comment by dhishkyaon** [comment]
i think spamming network every time user opens the app is the only option here

**Comment by vfsfitvnm** [comment]
I won't do that - I'd have to perform a (hopefully not more than one) network request for each artist you follow and then compare what I got with the previous result. Honestly, this isn't a valid and scalable solution.
I'll leave this issue open for a while, and if it doesn't get traction I'll close it eventually.

That said, if you find a valid solution (maybe after reverse engineering the youtube music apk), I will do a reconsideration

**Comment by Jak2k** [comment]
Maybe only ask youtube only **for the latest song** and then conpare the result.
