### ISSUE TITLE
Apk size

### ISSUE THREAD

**Issue by wiiznokes** [vfsfitvnm/ViMusic#1170]
### Steps to reproduce the bug

Hi, just wanted to ask a question. How did you manage to make such a small apk? i mean, you're using not much dependencies, but is there anything else you use ? like multi module or anything ?
And is there some drow back of not using regular libs like Koin for DI?

Sorry for asking this but there is no discussion tab so i through i'll asking here instead 

### Expected behavior

E

### Actual behavior

E

### ViMusic version

0.5.4

### Android version

Android 13

**Comment by vfsfitvnm** [comment]
Well, there's no special setup - and I do not use DI.
It's a multitude of factors: Jetpack Compose apps have a [smaller](https://developer.android.com/jetpack/compose/ergonomics#apk-size) footprint, R8 (in release mode) removes (almost all) unused classes...

**Comment by wiiznokes** [comment]
hum really interesting, i didn't know about R8. i go from  43,5 to 3,4 :laughing: Thanks!
