### ISSUE TITLE
Radio shouldn't restart song

### ISSUE THREAD

**Issue by Felixnightshade** [vfsfitvnm/ViMusic#118]
### Feature description

When starting a radio of a currently playing song, it shouldn't restart the song. 

### Why do you want this feature?

Often I find myself starting a radio from a song half way through after really feeling the vibe. I don't want to listen to the first half again, though.

**Comment by vfsfitvnm** [comment]
I agree, and we should extend this rule for everything: if the first song of the new queue is actually already playing, then it shouldn't be stopped

**Comment by vfsfitvnm** [comment]
Hmm, the question is how do we make the user know the queue is changed? I think it is better to apply this rule to the radio and albums. What do you think?

**Comment by vfsfitvnm** [comment]
Here is another idea. I can add a "Continue radio" (or "Start radio from here", you tell me what's best) button to the currently playing song instead (the playback isn't interrupted):

https://user-images.githubusercontent.com/46219656/180162663-aca3ae6d-8b39-4392-bcf0-e6970b808031.mp4

**Comment by vfsfitvnm** [comment]
And also here:

<img src="https://user-images.githubusercontent.com/46219656/180169101-2dd3b537-3856-4cab-90f4-a4b2469512a6.png" width="33%"/>

**Comment by Felixnightshade** [comment]
I think applying this behavior as the de-facto behavior for radio, albums, and playlists would be a good idea (for the same reasons why it's a good idea for radio).
I don't think anything extra needs to be done to let the user know that the queue is changed? They can see it just fine after all. But, if anything, opening to the queue automatically would be enough (and maybe that should happen anyway?).

I agree that there should be a radio button from long pressing the currently playing song. All the radio buttons should all behave the same, though, if this is the expected behavior of the radio button.

The default behavior in YouTube Music is to continue the currently playing song when a radio is started. So I believe this behavior will be intuitive to YouTube Music users.

**Comment by vfsfitvnm** [comment]
> The default behavior in YouTube Music is to continue the currently playing song when a radio is started. So I believe this behavior will be intuitive to YouTube Music users.

This isn't true? It just restarts the playback unless you start the radio from basically the equivalent of this: https://github.com/vfsfitvnm/ViMusic/issues/118#issuecomment-1191204583

**Comment by vfsfitvnm** [comment]
I think I should do what the app does first (i.e. implement https://github.com/vfsfitvnm/ViMusic/issues/118#issuecomment-1191175107 and https://github.com/vfsfitvnm/ViMusic/issues/118#issuecomment-1191204583).

However, I think the problem of not being able to understand if the queue has changed is real - so I can't apply this rule to somewhere else. Fortunately, I think implementing #109 should be enough (this is also what the youtube music clients do).

Also, I don't think this behaviour should be applied to playlists as well: you said _"Often I find myself starting a radio from a song half way through after really feeling the vibe."_. This applies to albums as well, but it doesn't make sense for playlists as there's no direct link between the playing song and a playlist.

**Comment by Felixnightshade** [comment]
I agree with #109 being a good solution for applying this rule elsewhere. Though, now that I think about it, there's no feedback on any queue changes right now... Something for a separate issue, I suppose.
I don't really agree with your reasoning on the last part. I don't see how albums and playlists are significantly different. What's the use case for applying this to albums, anyway? The only thing I can see is if you were to play a song and it happened to be the first song in an album. In which case, you could transition smoothly into that album as the song reminded you of it. Why would this not be the case for playlists as well? Why introduce an inconsistency? IMO, anything that starts a new queue that has the currently playing song as the first song should just continue the currently playing song for consistency's sake. That's just my opinionated, keep it simple, view though.

**Comment by vfsfitvnm** [comment]
> there's no feedback on any queue changes right now

The playback is stopped and restarted - this is what makes you think something changed.

> What's the use case for applying this to albums, anyway?

It is a common practice for artists to put songs with the same vibe in an album. You are listening to a song, you are enjoying it, so you may desire to listen to its album, but without losing the playback state. The crucial thing here is you can quickly visit the album.

This is not true for playlists... Let's say you are listening to the same song. What makes you think "Hmm, I like this one, let's start a _playlist_ which contains this song"? How do you find such playlist quickly? Why didn't you play that playlist instead?
I hope you see where I'm going with this. There is a weak link between song and playlist - that "queue merging" (?) shouldn't be applied by default.

**However**, there's a problem when it comes to apply this feature with albums and playlists: you have to start the playback from the exact song you are already listening to - and this is very inconvenient.

So, I think we can do better.

This is the solution I propose:
1) Add a "Start radio" button in the currently playing screen that smoothly starts a new queue ([this](https://github.com/vfsfitvnm/ViMusic/issues/118#issuecomment-1191204583)),
2) Implement #101
3) Extend 1) to any "Start radio" button
4) Add a "merge" button (or whatever) in the playlist and album screen, which replaces the current queue with the playlist/album seamlessly.

However, I'm still uncertain about 4) - especially for the playlists - as I don't know how much often this would be used.

**Comment by Felixnightshade** [comment]
> > there's no feedback on any queue changes right now
> 
> The playback is stopped and restarted - this is what makes you think something changed.
And what about enqueueing and playing next..?

The only thing I'll say about the second half is that it was already such a niche feature that the main point should be have consistency across the app, not how much the feature will be used. Either way, only a handful of people would notice this change applied to albums or playlists, so why not just make it the default behavior for entire queue changes if you're going to change one of them? I personally don't care either way - I'm unlikely to notice the change for albums _or_ playlists - but if I did notice and tried it out in other parts of the app, only to discover it was a one off for albums, I would be very confused.

I could go either way on 4.

**Comment by vfsfitvnm** [comment]
1 and 2 are now implemented. However, due to how the seamless transition from a queue to a radio is performed, I can't expand the player when a radio is started from the playing song (if only ExoPlayer allowed to interact with its listeners...).
So, I don't want to complicate things further - fortunately 1 and 2 are still enough to match the youtube music apk behavior.
