### ISSUE TITLE
Cannot play track that is inappropriate for some users

### ISSUE THREAD

**Issue by qsoulior** [vfsfitvnm/ViMusic#119]
### Steps to reproduce the bug

Just play a track that is marked "inappropriate for some users".

### Expected behavior

A warning dialog should appear (with confirmation/cancellation of the action).

### Actual behavior

An error message appeared and playback didn't begin.

### Screenshots/Screen recordings

The first screenshot shows the behavior of YouTube Music app.

![YT Music dialog](https://user-images.githubusercontent.com/74735618/180232111-1750eee4-c2c5-4298-9a8e-678677786a26.jpg)
![ViMusic error](https://user-images.githubusercontent.com/74735618/180232245-ca8582ce-846b-4379-92e9-a5d089fcc204.jpg)

### ViMusic version

0.2.1

### Android version

Android 11/12

**Comment by vfsfitvnm** [comment]
That song cannot be played without logging in.
Visit its link https://music.youtube.com/watch?v=9FltPGypAdM&list=RDAMVM9FltPGypAdM in incognito mode and you'll see.

However, there is a way to bypass this restriction, but it requires deciphering the signature of that video, and I won't do that as it requires a whole JS engine and it is error prone.

Instead, as I did for #88, I could fetch the source from piped instead. I'll give it a shot asap

**Comment by qsoulior** [comment]
Hmm, I didn't think about the authorization requirement. Now it looks logical.
Thanks for your quick response and good work!

**Comment by vfsfitvnm** [comment]
Done. Unfortunately, few videos cannot be played: I need few parameters (i.e. `loudnessDb`) Piped doesn't return yet.
