### ISSUE TITLE
Collapsible Most Played section

### ISSUE THREAD

**Issue by noClaps** [vfsfitvnm/ViMusic#12]
### Feature description

Allow the Most Played section to be lowered or collapsed.

### Why do you want this feature?

The Most Played section takes up a lot of space on the homepage and is quite useless if I'm just shuffling through my liked songs.

**Comment by vfsfitvnm** [comment]
Would you provide a sketch (or whatsoever) of how you would it to look like?

**Comment by noClaps** [comment]
Kind of like how the currently playing song can be minimised to a single bar at the bottom. I was suggesting allowing the Most played section to be collapsed in a similar way, down to a small bar.

This feature was meant for if you were adding a separate Favorites playlist instead of another section to the Most played area. You can close this if you want, it wouldn't fit well with the current implementation.

**Comment by vfsfitvnm** [comment]
Ok, let's track the home page UI in #11 then!
