### ISSUE TITLE
*Question* Where is the song list stored?

### ISSUE THREAD

**Issue by samuil6996** [vfsfitvnm/ViMusic#1221]
### Steps to reproduce the bug

Title

### Expected behavior

Title

### Actual behavior

Title

### ViMusic version

Latest

### Android version

A13

### Additional information

A few weeks ago I dumped my drive data on to my pc, cause I needed to switch my rom. In the process I forgot to make a backup file for the songs. I have the whole sdcard partition saved, I just need to know where the song list is located : )

**Comment by Shashi9148** [comment]
Songs is stored in the cache, and if you happen to clear the cache of the app all the offline songs will be deleted
Another thing is you cannot download the songs if you listen to a song completely it saves the song in the cache

**Comment by askadityapandey** [comment]
@Shashi9148 said it right, the offline songs you're referring to are stored in CACHE MEMORY; clearing it will delete them too!
