### ISSUE TITLE
Are artists supposed to show all of their music?

### ISSUE THREAD

**Issue by emkay5771** [vfsfitvnm/ViMusic#123]
### Steps to reproduce the bug

1) search for artist
2) open artist page

### Expected behavior

Show albums, as well as bio for artist.

### Actual behavior

Just shows bio... Clicking shuffle seems to work though

### ViMusic version

0.2.1

### Android version

Android 13

**Comment by vfsfitvnm** [comment]
Nope, I didn't implement that part yet (I'll mark this as enhancement). The artist page only shows their songs you already listened to (https://github.com/vfsfitvnm/ViMusic/blob/master/fastlane/metadata/android/en-US/images/phoneScreenshots/4.jpg)

**Comment by Malopieds** [comment]
Hi, I have seen in #107 that you said that you couldn't implement this, is it still the case?
![Screenshot_20220919-194100_Debug](https://user-images.githubusercontent.com/74783202/191080111-0776ba86-0921-4395-9b37-b8dd581fac8e.png)
Here is my take on it, I did not yet implement the database with it, I'm still trying to figure out how does this works with List.
You can find the code [here](https://github.com/Malopieds/Malo-Musique/tree/a747be10cea568f5d4fc47328347b356f91ee56f) if you are interested !

**Comment by vfsfitvnm** [comment]
@Malopieds Thanks, this is much appreciated!

**Comment by vfsfitvnm** [comment]
Implemented
