### ISSUE TITLE
Consistency lacking

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#124]
### Steps to reproduce the bug

![Screenshot_2022-07-21-16-10-30-66_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/180470611-b6af7848-3a1b-4055-97fd-817e57632845.jpg)

The corners of Playlists are not rounded, as rounded corners are everywhere in the app, only this section lacks it, which doesn't look a consistent design.

### Expected behavior

Corners of the playlists' thumbnail should be rounded.

### Actual behavior

They are flat disrespecting Thumbnail Roundness Setting.

![Screenshot_2022-07-21-16-09-19-49_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/180471151-ab8c4860-66e6-4a10-a8ed-06b067e613db.jpg)

### ViMusic version

0.2.1

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
This is a design choice, 4 images attached to each other (i.e. the playlist preview) looks ugly with rounded corners

**Comment by vfsfitvnm** [comment]
That said, in order to add rounded corners over there, the playlist preview should be redesigned (adding a white border is probably enough)
