### ISSUE TITLE
Show song cover isn't working

### ISSUE THREAD

**Issue by Raghav-Sharma26** [vfsfitvnm/ViMusic#1241]
### Steps to reproduce the bug

Settings
Appearance 

### Expected behavior

This feature boasts of applying the playing song cover as the lock screen wallpaper.

### Actual behavior

But nothing happens after turning it on or off.

### ViMusic version

0.5.4

### Android version

11

### Additional information

I have a Realme Android tablet with Android 11 and using Microsoft launcher

**Comment by omkaar87** [comment]
![image](https://github.com/vfsfitvnm/ViMusic/assets/30948641/83a9e28e-8ae6-413f-bf05-4428f680fda7)
This bug is not reproducible
