### ISSUE TITLE
Legibility issue

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#125]
### Steps to reproduce the bug

When in light mode/theme, the text Favorites on favorites playlist isn't legible, when the same playlist is empty.

### Expected behavior

It should be visible clearly in both light and dark modes.

### Actual behavior

It's only visible in dark mode.

Reference:
![Screenshot_2022-07-21-16-10-30-66_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/180471899-cd751b9e-3a91-4d68-a5c4-7072d4467199.jpg)

### ViMusic version

0.2.1

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
Whoops, thanks for reporting, this is a regression!
