### ISSUE TITLE
Favourite & unfavorite a song via the long press action menu from everywhere 

### ISSUE THREAD

**Issue by BluePixel4k** [vfsfitvnm/ViMusic#127]
### Feature description

Please add the option to add and remove a song to the favorites via the long press action menu from everywhere.

<img src="https://user-images.githubusercontent.com/77979781/180645484-9592ffe4-9d5c-47e4-bb71-ba43bae9e4a8.png" width="300" />

### Why do you want this feature?

Its faster to add known or recently listend songs to the favorites.

**Comment by vfsfitvnm** [comment]
The menu is already big enough. But I can add that here:

<img src="https://user-images.githubusercontent.com/46219656/182695398-1e0a39ed-7ff5-4dff-a00a-f621decfe59e.png" width="30%"/>

**Comment by BluePixel4k** [comment]
That's a great idea.
So, then do you rename the category to "Add to playlist / favorites" or something similar? :)

**Comment by vfsfitvnm** [comment]
I think "Add to playlist" is ok given "Favorites" is part of the "your playlists" section

**Comment by vfsfitvnm** [comment]
Ops, I meant to reference issue 172 :P
