### ISSUE TITLE
search results - play the songs next to the chosen result

### ISSUE THREAD

**Issue by BluePixel4k** [vfsfitvnm/ViMusic#129]
### Feature description

When I search for an artist and play a song, I would expect that after the selected song, the next one from the results would be played. 
But I think currently a radio is started automatically?

Search results:
<img src="https://user-images.githubusercontent.com/77979781/180647062-fb746d5b-c27f-4d42-a7b4-04f2a64a6941.png" width="250" />

Queue:
<img src="https://user-images.githubusercontent.com/77979781/180647065-3cbed97d-1a74-4707-bde4-d57588d81b6a.png" width="250" />

### Why do you want this feature?

It's more intuitive.

**Comment by vfsfitvnm** [comment]
A radio is started automatically.

**Comment by BluePixel4k** [comment]
Ok I understand. But isn't it more intuitive when the results are played through?
Since you can start the radio as well via the long press menu.

Can you possibly add a setting to switch between these modes?
Or to disable it completely, so that only the selected song is played and then nothing more?

Thx :)

**Comment by vfsfitvnm** [comment]
> Ok I understand. But isn't it more intuitive when the results are played through?

No, this is how youtube music works...

> Can you possibly add a setting to switch between these modes?

No, I don't think I will...

> so that only the selected song is played and then nothing more?

There's a "Play single" menu entry already :)
