### ISSUE TITLE
Feature Request: lyrics

### ISSUE THREAD

**Issue by szarza** [vfsfitvnm/ViMusic#1297]
### Steps to reproduce the bug

It would be great to have the ability to see the lyrics of each song like on Spotify.

(It's not a bug)

### Expected behavior

It's not a bug

### Actual behavior

It's not a bug

### ViMusic version

0.5.4

### Android version

Android 13

**Comment by computersandstuff** [comment]
This feature already exists (for most of my songs at least), just tap on the album cover when playing a song

**Comment by szarza** [comment]
Oh my god! It even includes synchronization and editing options!!!

Definitely, your app is GREAT!
Congratulations!!! Excellent job!!
