### ISSUE TITLE
Better lyrics

### ISSUE THREAD

**Issue by noClaps** [vfsfitvnm/ViMusic#13]
### Feature description

You should fetch lyrics from a better, more accurate source such as Genius or Musixmatch. Either do this by default or provide an option to enable this for those who want it.

### Why do you want this feature?

The lyrics currently in the app are fetched from YT Music, but they're often inaccurate or simply not available for many songs. By comparison, Genius as a *huge* database of lyrics, and they're often much more accurate.

**Comment by vfsfitvnm** [comment]
Genius and Musixmatch do not have a public api so I definitely won't interact with them.

(copied from #1)

I think I could just add a "search lyrics online" text button which opens the browser with a input like "artist song lyrics" or similar. So you could fetch the lyrics from whatever service you prefer.

Then, I could store the lyrics in the database, so the user can edit them (if they are wrong or missing).

I think this is a good compromise.

**Comment by vfsfitvnm** [comment]
> I think I could just add a "search lyrics online" text button which opens the browser with a input like "artist song lyrics" or similar. So you could fetch the lyrics from whatever service you prefer.

Then, I could store the lyrics in the database, so the user can edit them (if they are wrong or missing).

Implemented in `v0.1.5`.

**Comment by noClaps** [comment]
Which database are you referring to? If I make changes to lyrics will they be available to all other users, or are they locally stored in the app? If the former, where are you storing the edits/lyrics, and is there a moderation process to protect against trolls?

**Comment by vfsfitvnm** [comment]
It's your local (private) database
