### ISSUE TITLE
Unable to load playlist 

### ISSUE THREAD

**Issue by SreerajPitta** [vfsfitvnm/ViMusic#1316]
### Steps to reproduce the bug

1.Go to search.
2.Pasted my youtube url or search my playlist.
3.View or open the playlist in search menu.
4.Playlist starts loading and never ends

### Expected behavior

Playlist loads and shows the songs in that playlist 

### Actual behavior

Playlist loads continuously 

### Screenshots/Screen recordings

https://github.com/vfsfitvnm/ViMusic/assets/150555176/866c6a53-d27b-40f7-9a88-f0b79bf9f755

### ViMusic version

0.5.4

### Android version

Android 13

**Comment by SreerajPitta** [comment]
Fixed by removing videos from playlist

**Comment by zyqunix** [comment]
> Fixed by removing videos from playlist

some songs are videos or some files are just too big for the app/phone to "download".
