### ISSUE TITLE
Transfer/save files

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#133]
### Feature description

I'm going to be changing phones in this coming week, and thought of this. If I change, there's a chance that all my songs now won't exist in the new phones ViMusic. So i thought, why not save a file that says what songs you have, so you can then transfer that file to the new phone. Effectively having all songs. Maybe creating an account is also a viable measure, although I remember you stating in a previous request that subscriptions are a problem?

### Why do you want this feature?

Will make my life easier, not having to go back and forth between apps and links to get all the songs back.

**Comment by vfsfitvnm** [comment]
Settings > Backup & Restore
