### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Arthianandan05** [vfsfitvnm/ViMusic#1333]
### Steps to reproduce the bug

Actually i need to ask the font name since the app is so cute and i love it..thanks to thw whole team who is working on this..have a good day!

### Expected behavior

Neec font name
![194817295-dae20a15-c7f2-41f7-9794-a166f38527c1](https://github.com/vfsfitvnm/ViMusic/assets/151962185/c56b9850-9a30-43f4-b4ed-a8b829594933)

### Actual behavior

Nothing happened 

### ViMusic version

0.5.4

### Android version

Android 11

**Comment by bartoostveen** [comment]
It's the [Poppins](https://fonts.google.com/specimen/Poppins) font.
