### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#134]
### Steps to reproduce the bug

Play any song
Open main player screen

### Expected behavior

There's a little gap left in bottom, see screenshot below:
![Screenshot_2022-07-26-15-25-40-11_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/180979503-d032de4e-a8eb-426f-9778-497e76513d28.jpg)

Zoomed:

![IMG_20220726_152641](https://user-images.githubusercontent.com/87353286/180979527-9a5e7041-f2db-4ee6-b520-63cb4b9f404b.jpg)

### Actual behavior

That left gap should be matching app background color.

### ViMusic version

0.2.1

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
Already fixed for the next release
