### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#135]
### Steps to reproduce the bug

Tap on search bar
Go back

### Expected behavior

Everything should appear as it was before opening search bar.

### Actual behavior

Instead, few songs loads everytime opening search bar and closing it.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/87353286/180981822-10208b63-4b6b-4cfc-ae0b-bceaec63cc41.mp4

Don't know why, but the video I uploaded isn't playable.😔

Here's the mirror [link](https://mega.nz/file/fMpWyb6L#9EUnxOwRGPl5jbvv_pJWSSRgiS1Gv4sm8qLjSukXG7w) 

### ViMusic version

0.2.1

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
This is a jetpack compose bug:
https://issuetracker.google.com/issues/209947592
https://issuetracker.google.com/issues/235259330
