### ISSUE TITLE
An option to choose "favourites" as home screen instead of showing all the songs played.

### ISSUE THREAD

**Issue by rishitraii** [vfsfitvnm/ViMusic#136]
### Feature description

An option to choose "favourites" as home screen instead of showing all the songs played. 

### Why do you want this feature?

Home screen doesn't actually feel "home" when you don't see your selected favourites. Its not aesthetically pleasing to see all the songs (like the ones you don't know or don't like) as soon as you open the app. This is just visual perspective though. You can add an option to choose favourite as your prefered home page.

**Comment by vfsfitvnm** [comment]
I won't add such option - people want favorites to be a playlist - but you can change the songs to display though (e.g. the ones you listened to the most).
Also, a UI redesign is currently in progress (#107), please leave a feedback there.
