### ISSUE TITLE
Scrobbling Support

### ISSUE THREAD

**Issue by onnyyonn** [vfsfitvnm/ViMusic#138]
Last.fm is a popular service for keeping a log of your listening history.  They have an Android app for automatic logging (which is known as scrobbling). But it does not support every music player, and is sometimes buggy. To get around that, some music players implement scrobbling support directly inside the player. Spotify is one such example. It would be great if there is built-in support for scrobbling in ViMusic.

**Comment by vfsfitvnm** [comment]
After a quick online research, the _scrobbling_ is just user profiling (i.e. it gives you recommendations based on what you recently listened to or whatever), isn't it? If so, it is hard to impossible to implement. Let me know if you were referring to something else.

**Comment by onnyyonn** [comment]
No, what I mean is sending my listening history to Last.fm. This is preferably done by logging in to Last.fm via oauth, but a simple username-password login to Last.fm works too. ViMusic doesn't need to deal with recommendations or any other thing. All it needs to do is sending every track being played to the user's Last.fm account.

**Comment by vfsfitvnm** [comment]
Oh. I'm not considering to implement this feature (same reasons and similar context as #46).
However, it seems there are different applications that are doing this "scrobbling" by reading the notification content. I think at least one of them should work.

**Comment by onnyyonn** [comment]
I have been using Last.fm for years and probably tried every scrobbler app there is. They don't work well and lose data. This is the only reason I have to stick with Spotify, because they support it natively.

But I understand why you may not want to implement it. Thanks for your consideration.

**Comment by C0deBr3ak3r** [comment]
Simple Scrobbler works completely fine with ViMusic

**Comment by Korb** [comment]
> I think at least one of them should work.

I tried them all: Pano Scrobbler, Scrobble Droid и Simple Scrobbler. All of them have long been abandoned, and at the end of 2022 they are not working. At least on Android 13. The problem of not being able to collect complete music listening statistics and view visualizations of my musical taste trends by month and year, taking into account mobile listening, is still relevant.

**Comment by stragu** [comment]
Would be wonderful to allow scrobbling to ListenBrainz, given that it is open source, produces open data, and keeps getting new features added: https://listenbrainz.org/
API docs: https://listenbrainz.readthedocs.io/en/latest/index.html

**Comment by crse** [comment]
I hope this feature is implemented as well.

Last.fm scrobbling (and other similar service like Libre.fm) are often considered as essential feature among music enthusiast and audiophile.

Music player like VLC, AIMP, Clementine, Audacious, Amarok and SongBird support them natively. Basically Also available on Foobar2000 via components support.
Even Spotify used to have official setting for Last.fm scrobbling (not sure why they remove them).

If you still not convinced why Last.fm is important, it's basically like personalized music diary and social media with various statistic.
You can go revisit what kind of music you listen in specific date one decade ago, or simply looking for friends who enjoy similar niche music taste with you.
