### ISSUE TITLE
Singular volume edit (feature)

### ISSUE THREAD

**Issue by BananaCat68** [vfsfitvnm/ViMusic#1386]
### Steps to reproduce the bug

Sometimes songs are louder than others even though the phone volume is low. So while playing a Playlist while sleeping or something a song is louder than the others and can wake someone up.

### Expected behavior

Add a volume edit to singular songs without lowering the master volume.

### Actual behavior

. 

### Screenshots/Screen recordings

.

### Logs

.

### ViMusic version

5.4

### Android version

Samsung galaxy m12

**Comment by vfsfitvnm** [comment]
There's a "loudness normalization" feature you can enable in the settings, did you turn it on?
