### ISSUE TITLE
No artist name showing

### ISSUE THREAD

**Issue by marcecfilip** [vfsfitvnm/ViMusic#1389]
### Steps to reproduce the bug

1. search for a song you want
2. when search results come back you should see artist name under song name

### Expected behavior

artist name should show

### Actual behavior

it doesnt show artist name

### Screenshots/Screen recordings

![Screenshot_20231222_171511](https://github.com/vfsfitvnm/ViMusic/assets/111235216/f4cdf95e-7741-48c6-a450-a44f54dade1b)

### ViMusic version

0.5.4

### Android version

Android 14

**Comment by marcecfilip** [comment]
duplicate

**Comment by Weichei0** [comment]
may I ask if there's any solution for this?
