### ISSUE TITLE
Minimized control board shown after re-opening the app

### ISSUE THREAD

**Issue by juniorpainkiller** [vfsfitvnm/ViMusic#141]
### Feature description

Being able to continue on playing songs from the last played.

### Why do you want this feature?

It would be great to have this feature if you're playing a long playlist

**Comment by vfsfitvnm** [comment]
I think the persistent queue option (Settings > Player & Audio > Persistent queue) is what you are looking for. Am I correct?

**Comment by juniorpainkiller** [comment]
> I think the persistent queue option (Settings > Player & Audio > Persistent queue) is what you are looking for. Am I correct?

That's right! Sorry I haven't seen that option. But it still doesn't work for me, even if I enable it

**Comment by vfsfitvnm** [comment]
You have to make sure the application does not have battery optimizations enabled (Settings > Other > Ignore battery restrictions)

**Comment by vfsfitvnm** [comment]
If it doesn't work even after that option, would attach a screenrecord with your device manufacturer name (and OS/ROM)?

**Comment by juniorpainkiller** [comment]
Yes, it worked! Thanks!

**Comment by BluePixel4k** [comment]
@vfsfitvnm Do you considered to enable the persistent queue by default (with opt- 
out option)?
I think that would help much users.

**Comment by vfsfitvnm** [comment]
@BluePixel4k Nope, as the user needs to disabile the battery optimizations first. I added a dot notification no guide the user to Settings > Other, but it doesn't seem much effective.

**Comment by BluePixel4k** [comment]
I have already realized by average consumers, that the dot notification doesn't make a good effect. 
The most follow him and going back when it is away - without reading or changing anything. 

I think the best option is a dialog at the startup, where they get explained all additional options. So they can directly and easily agree or disagree this options.
