### ISSUE TITLE
Can you add check for updates in settings/About ?

### ISSUE THREAD

**Issue by amrelhossieny48** [vfsfitvnm/ViMusic#142]
### Feature description

Update the app via check for update button to make the app up-to-date more easier 

### Why do you want this feature?

This will help users to check for updates without everytime they check GitHub

**Comment by vfsfitvnm** [comment]
#48 

You can install the F-Droid version (as long as you have a F-Droid client) if you want to receive updates - remember to backup the database before doing so!

**Comment by amrelhossieny48** [comment]
I know but not all users have F-Droid I am suggesting you to make this option.

**Comment by vfsfitvnm** [comment]
Well, I'm not implementing it then. Alternatively, I think GitHub can send you an email whenever a new release occurs.
