### ISSUE TITLE
Quickly enqueue Songs by swiping them to the right

### ISSUE THREAD

**Issue by mityax** [vfsfitvnm/ViMusic#143]
### Feature description

It would be pretty handy to be able to quickly enqueue songs by swiping them to the right in a playlist/album/other song list - similarly as in Spotify.

Additionally, there could also be another shortcut for adding them to the favorites, e.g. by swiping to the left.

### Why do you want this feature?

It's just quicker than having to use the long press menu all the time. This UX also feels pretty smooth in comparison to the menu

**Comment by SebiderSushi** [comment]
Something i've really grown accustomed to is the feature in Vanilla Music to customize what clicking on an entry does. Particularly the "Play if paused; Enqueue if playing" option. It makes it easy to build a playing queue and minimizes the risk of accidentally tapping on a song, replacing the queue and stopping the current song right in the middle.

I could see this to fit in here if this were to be imemented as an overall configuration of interactions with songs.

**Comment by arfanmrafeek** [comment]
Swipe gesture show implement within the app, Were they can change it weather right or left swipe, My request For swipe features is when we are selected a song from the search we get random selection of songs in queue, It would be easy to remove some of them when we have option for swipe right or left to remove them from our queue then removing individually.

**Comment by vfsfitvnm** [comment]
Hmm, I'm not incline to implement this one - it complicates the code a little for no tangible advantage. I may be wrong because I barely use the play next and add to queue features, but in which situation do you "quickly" need to concatenate a lot of songs?

**Comment by vfsfitvnm** [comment]
(The same goes for the _swipe to remove from queue_)

**Comment by mityax** [comment]
I think the benefit of this feature on the UX is quite big, and though I can't really estimate what impact it'd have on your code, I'm pretty sure it's worth it for a lot of users.

Two scenarios I've experienced 
 1. Playing DJ at a party/hangout - you regularily geht dozens of song requests and need to enqueue them. You have to be quick here because otherwise you'll be too occupied all the time to really enjoy the party.
 2. Hanging out with a friend/during a long drive you often listen to music together and need to play a good mix between both of your music tastes - you quite likely won't just always have the perfect playlist at hand. While you don't exactly need to be "quick" here, it's still annoying to use the long press menu 40 times in a row.

I'm sure there's more situations this feature would really shine in, but also it's just a nice touch to the app's UI and feels really smooth in daily use.

**Comment by vfsfitvnm** [comment]
Uhm, I see, but I honestly don't see any major annoyance with the menu.
I mean, in both occasions, you eventually (and quickly) reach an amount of playback time that "ok, let's decide later what we listen to in 30 minutes" (you know what I mean) - so you don't actually have to stack 40 songs in a row.

However, the reason why I'm "against" this is I don't want to complicate the code base further. Moreover, doing such thing has a light impact on performance if implemented smartly; but the deal breaker (for me) is implementing the gesture detection in such way it can't be triggered for mistake (see https://github.com/vfsfitvnm/ViMusic/issues/154#issuecomment-1207278649).

**Comment by vfsfitvnm** [comment]
That said, we can think of another way to "quickly enqueue songs". For example, after a long press, there could be system that lets you select a menu entry without releasing the finger - that would be less annoying.

**Comment by vfsfitvnm** [comment]
Closing as *won't fix*. However, a player UI redesign is being discussed in #496.
