### ISSUE TITLE
Stuck in pause button (Can't play anything)

### ISSUE THREAD

**Issue by MrUNKNOWNN7** [vfsfitvnm/ViMusic#144]
Hi bro! I really love the ui of the app🔥 but I am stuck on an issue. I don't know if it's just with me, but I can't get it to play anything. I try tapping the play button but does nothing. It just stays at pause. I am new to the app, so maybe I am missing something like enabling an option or something. Please! I wanna enjoy the app, but I am stuck at this issue!

![screenshot.jpg](https://user-images.githubusercontent.com/83583700/181820558-e224b5f6-ca27-4d39-b70e-0628897dea75.jpg)

**Comment by vfsfitvnm** [comment]
Would you provide a screenrecord?

**Comment by vfsfitvnm** [comment]
PS - you should try disable the VPN also

**Comment by MrUNKNOWNN7** [comment]
> Would you provide a screenrecord?

I don't know what I did, but today when I checked, it fixed itself. If I recall, I restarted my device in the morning, may be that fixed the issue. Thanks for the reply though. 😇

P.s - even with the vpn active, it's working flawlessly. 👌🏻🔥

**Comment by vfsfitvnm** [comment]
Glad to know, some mysteries should remain unsolved!
