### ISSUE TITLE
Same song repeats again and again

### ISSUE THREAD

**Issue by Niranjan8262** [vfsfitvnm/ViMusic#1441]
### Steps to reproduce the bug

1. when I play a song and about to end 
2. It should play the next song from the list
3. Instead it plays the same song again and again

### Expected behavior

Sound play the next song

### Actual behavior

Repeatedly plays the same song

### Screenshots/Screen recordings

https://github.com/vfsfitvnm/ViMusic/assets/157314241/554b7f12-e18c-4491-808d-22a71b928b38

### ViMusic version

V0.5.4

### Android version

Android 13

**Comment by Driftinginfinitely** [comment]
Seems you have repeat on? Turn off the loop/infinity symbol at the bottom
next to the forward button.
