### ISSUE TITLE
Sorting Playlist By Artists Name

### ISSUE THREAD

**Issue by deblood3** [vfsfitvnm/ViMusic#145]
### Feature description

Sorting Playlist By Artists Name

### Why do you want this feature?

Been navigating around in the app and trying to find out best way of sorting songs in playlist by Artists name? If not is there a way to add that feature. It makes managing and organizing list of songs on the playlist by the artist very easier.

**Comment by vfsfitvnm** [comment]
Uhm, how can you sort playlists by artists? 🤔
Would you provide an example?

**Comment by deblood3** [comment]
I am just asking as l have created play list and sometimes would like to listen to just songs in the playlist by particular artists, so l am just asking if there is a way. I have attached a screenshot for your perusal. ![SmartSelect_20220729-160844.jpg](https://user-images.githubusercontent.com/93008977/181836681-4a45661c-3e4a-4ee3-bc0c-638fdf132831.jpg)

**Comment by vfsfitvnm** [comment]
Oh, so you need a filter feature. I think this is related to #39, then.

**Comment by deblood3** [comment]
Yes!!! Kind of

**Comment by vfsfitvnm** [comment]
Closing as duplicate - let's track this feature there. However, you can already retrieve all the songs (you listened to) of a specific artist by visiting the artist itself (long press on song > view George Howard) :)
