### ISSUE TITLE
UI Related 

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#147]
### Steps to reproduce the bug

👇

### Expected behavior

Doesn't the logo at the top looks weird?

### Actual behavior

![Screenshot_2022-07-30-08-34-47-86_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/181870190-8a4c82be-b2ba-4a74-890b-e3d1f95acc4a.jpg)

### ViMusic version

0.3.0

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
No, it looks fine - the "V" turns white on purpose (otherwise it would be ugly). However, I can understand you don't like it - I'll see if I can improve it.
