### ISSUE TITLE
Merge Playlists

### ISSUE THREAD

**Issue by vixpr** [vfsfitvnm/ViMusic#149]
### Feature description

A feature to merging playlist. 
 
Basically, it adds songs from X playlist to Y playlist. 

### Why do you want this feature?

I want to add many songs to the playlist but it is very difficult to add them one by one.

**Comment by vfsfitvnm** [comment]
This looks like an edge case, so I don't know if I will do it. However, I think adding the multi selection can also be a viable solution.

**Comment by vfsfitvnm** [comment]
Tracking in #161
