### ISSUE TITLE
Amoled theme

### ISSUE THREAD

**Issue by jojobozo** [vfsfitvnm/ViMusic#15]
### Feature description

I want the app to have a black theme

### Why do you want this feature?

I want this feature for amoled displays

**Comment by vfsfitvnm** [comment]
Why do you need a black theme when there is a dark one already - can you elaborate?

Based on my findings, dark grey consumes a negligible amount of battery if compared to total black. Also, this is not a social media app that needs to stay on foreground for many hours a day.

Moreover, total black goes hard on eyes and reduces readability if compared to dark grey.

**Comment by Fatcakes** [comment]
I'm not op, but it's simply a preference.

**Comment by jojobozo** [comment]
> Why do you need a black theme when there is a dark one already - can you elaborate?
> 
> Based on my findings, dark grey consumes a negligible amount of battery if compared to total black. Also, this is not a social media app that needs to stay on foreground for many hours a day.
> 
> Moreover, total black goes hard on eyes and reduces readability if compared to dark grey.

On most amoled phones, there's the green tint/uniformity issue which is in gray background so that's annoying

**Comment by jojobozo** [comment]
And for "the black goes hard on eyes" it's true but if you use darker text colors instead of white, it'll be better

**Comment by vfsfitvnm** [comment]
Added in `v0.1.3` is now live. I don't have an amoled screen so I don't know if colors are ok.

**Comment by jojobozo** [comment]
> Added in `v0.1.3` is now live. I don't have an amoled screen so I don't know if colors are ok.

Thanks!

**Comment by vfsfitvnm** [comment]
@jojobozo  Of course, let me know if it's fine, so we can close this issue.

**Comment by jojobozo** [comment]
> @jojobozo Of course, let me know if it's fine, so we can close this issue.

Sorry for the late reply, yes it's fine but I think it would look better if the bottom bar and "up next" "lyrics" was black

**Comment by jojobozo** [comment]
Like that for example:

For the bottom bar
![Screenshot_20220703-023751](https://user-images.githubusercontent.com/98482700/177020161-c08c9dbe-2fb6-4b83-849b-ca48b5a2e2e4.png)

For "up next" and "lyrics"
![Screenshot_20220703-023808](https://user-images.githubusercontent.com/98482700/177020164-4f06fcd7-c67b-48f9-acc1-f54e41670f0e.png)

**Comment by jojobozo** [comment]
Also if you can add the possibility to swipe between lyrics and up next like in YT Music, it's better for people with big phones
