### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by Amitk003** [vfsfitvnm/ViMusic#1509]
### Steps to reproduce the bug

"Even when I close and remove the app from the background, the music keeps playing."

### Expected behavior

When I close app from background, music should stoo

### Actual behavior

Yup, music should stop when I remove from background 

### ViMusic version

0.5.4

### Android version

Android 13

**Comment by sandraev** [comment]
This is effectively not a bug, just a design choice. Please close this issue.

**Comment by Amitk003** [comment]
Okay, isn't there any other way to do that

**Comment by sandraev** [comment]
Of course! You first have to pause the song currently playing and **then** close the app in the background.
It should work 😉

**Comment by Amitk003** [comment]
Ok thanks 👍
