### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#152]
### Feature description

Here's a simple landing page made using AMP:

https://vemusic.github.io/

### Why do you want this feature?

No such intention, just wanna share!

**Comment by VedxP** [comment]
@vfsfitvnm Have a look, sir!

**Comment by vfsfitvnm** [comment]
Yes, I will probably do in future. Not interested now

**Comment by vfsfitvnm** [comment]
Closing as I don't think this should be an issue. I will look into this sooner or later.
