### ISSUE TITLE
Music not stopped when closing application 

### ISSUE THREAD

**Issue by fardeen619** [vfsfitvnm/ViMusic#153]
### Steps to reproduce the bug

Music not stopping when I close application from background

### Expected behavior

It should stop playing after we clear it from background 

### Actual behavior

It still playing song

### ViMusic version

0.3.0

### Android version

12

**Comment by vfsfitvnm** [comment]
Could you provide a screen record?

**Comment by fardeen619** [comment]
Uploading vidma_recorder_02082022_004045.mp4…

**Comment by fardeen619** [comment]
https://user-images.githubusercontent.com/60790859/182228515-0495d7c9-9336-4946-98a4-7bd927b1f35b.mp4

**Comment by vfsfitvnm** [comment]
Well, this is expected. You have to pause and dismiss the notification.

**Comment by fardeen619** [comment]
> Well, this is expected. You have to pause and dismiss the notification.

Lol but in other apps song stopped automatically

**Comment by sebsebseb9b** [comment]
Yea every other music app stops when you quit 😂
