### ISSUE TITLE
Next and previous button after minimizing song

### ISSUE THREAD

**Issue by John189903** [vfsfitvnm/ViMusic#154]
### Feature description

Can you add next and previous button after minimizing the current playing song?

### Why do you want this feature?
N/A

**Comment by 21Ironman** [comment]
Can you add download option for this app

**Comment by NR8124** [comment]
> Can you add download option for this app

If u want any feature please check whether it was previously raised or not and than if not.. raise an new issue..
Don't comment on any random issue

**Comment by vfsfitvnm** [comment]
I don't think I will, three buttons down there are too much. I can only add a next button, but let's see how much traction this request gets first.

**Comment by John189903** [comment]
Next button will also work, current play/pause button is too close to the bazel. On OnePlus 8 curve screen, its hard to press that button.

**Comment by vfsfitvnm** [comment]
Thanks for letting me know, I'll add few more dp of padding to buttons close to the bazel

**Comment by vfsfitvnm** [comment]
@John189903 What if you can change the song using a swipe?

https://user-images.githubusercontent.com/46219656/183263204-9e3888c0-6f36-49b1-ab05-907d4565efe3.mp4

**Comment by John189903** [comment]
Yes, @vfsfitvnm that works!!

**Comment by vfsfitvnm** [comment]
Corrigendum: after trying the swipe gesture on my real phone and using my real thumb, it doesn't feel good: now you have to be very precise when it comes to drag the player upwards. So, it may happen to change song instead of expanding the player. I'll just add the button as originally planned.
