### ISSUE TITLE
Quick Picks not loading completely 

### ISSUE THREAD

**Issue by PrakunjKhandekar** [vfsfitvnm/ViMusic#1549]
### Steps to reproduce the bug

Showing out of nowhere, even after downloading again
And restarting phone

### Expected behavior

Full quick pick page

### Actual behavior

Only one song is showing

### Screenshots/Screen recordings

![Screenshot_20240418-165336](https://github.com/vfsfitvnm/ViMusic/assets/127516037/01446b6d-d37b-488c-bd55-8756a0f661ac)

### ViMusic version

0.5.4

### Android version

Android 11

**Comment by HundredHitman007** [comment]
I have the same issue as well

**Comment by Superstrikerz** [comment]
![Screenshot_2024-04-19-10-33-55-01_6f55a3c4de83481ebdee1685416eed82](https://github.com/vfsfitvnm/ViMusic/assets/164223399/e80e67d2-12f6-4cc2-9dc4-ce3bbb91ec7a)
bro actually I too have the issue do we have a solution to resolve it

**Comment by HundredHitman007** [comment]
> ![Screenshot_2024-04-19-10-33-55-01_6f55a3c4de83481ebdee1685416eed82](https://private-user-images.githubusercontent.com/164223399/323838566-e80e67d2-12f6-4cc2-9dc4-ce3bbb91ec7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDM4MTAsIm5iZiI6MTcxMzUwMzUxMCwicGF0aCI6Ii8xNjQyMjMzOTkvMzIzODM4NTY2LWU4MGU2N2QyLTEyZjYtNGNjMi05ZGM0LWNlM2JiYjkxZWM3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNTExNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmY1MWEzYjk2MzBjMmY1NjUyNTIyNzQyODgwMTE5MmY4NjA1Y2RjZTFkZmE5ZmY5NmE0OTllNzY2N2VjMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.28u3rKVaueBIuTsCik3fwLE58yTRdYJPUrEcISOluF0) bro actually I too have the issue do we have a solution to resolve it

I started using a fork of ViMusic called RiMusic and imported a backup of ViMusic into it with all my playlists and searches and songs listened but it has the same issue as well. It's either a problem in the source code or a YouTube music server-side update that's making it behave this way. It should be fixed in the next update of RiMusic but the issue will be permanent on ViMusic because it doesn't receive updates anymore.

**Comment by Superstrikerz** [comment]
> > ![Screenshot_2024-04-19-10-33-55-01_6f55a3c4de83481ebdee1685416eed82](https://private-user-images.githubusercontent.com/164223399/323838566-e80e67d2-12f6-4cc2-9dc4-ce3bbb91ec7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MDM4MTAsIm5iZiI6MTcxMzUwMzUxMCwicGF0aCI6Ii8xNjQyMjMzOTkvMzIzODM4NTY2LWU4MGU2N2QyLTEyZjYtNGNjMi05ZGM0LWNlM2JiYjkxZWM3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwNTExNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmY1MWEzYjk2MzBjMmY1NjUyNTIyNzQyODgwMTE5MmY4NjA1Y2RjZTFkZmE5ZmY5NmE0OTllNzY2N2VjMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.28u3rKVaueBIuTsCik3fwLE58yTRdYJPUrEcISOluF0) bro actually I too have the issue do we have a solution to resolve it
> 
> I started using a fork of ViMusic called RiMusic and imported a backup of ViMusic into it with all my playlists and searches and songs listened but it has the same issue as well. It's either a problem in the source code or a YouTube music server-side update that's making it behave this way. It should be fixed in the next update of RiMusic but the issue will be permanent on ViMusic because it doesn't receive updates anymore.

ok bro 
now what  about Rimusic is that same as vi music

**Comment by Superstrikerz** [comment]
ok bro I got it 
alternate of Vimusic is Rimusic 
thanks for the update

**Comment by PrakunjKhandekar** [comment]
Now working as usual 🤝
