### ISSUE TITLE
Cache songs only when user wants it

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#156]
### Feature description

It would be better if we can get an option in settings to toggle the feature of caching the song.
i.e. whether user wants to cache the song and use the storage or just to stream.

### Why do you want this feature?

not everyone want to  use storage and wants songs to be available offline

**Comment by vfsfitvnm** [comment]
This is unlikely to be done.
If there's a space concern, just give it the smallest space possible.
Otherwise, there's no reason to disable the cache or letting the user decide so.

**Comment by NR8124** [comment]
> just give it the smallest space possible

So can u add some more options i.e. 50mb as minimum 
Or as least as possible

**Comment by vfsfitvnm** [comment]
Yes, I can probably put 0 MB (or something very close to it)

**Comment by NR8124** [comment]
Sounds perfect

**Comment by vfsfitvnm** [comment]
After some thinking, I decided `32 MB` to be the smallest size possible.

**Comment by NR8124** [comment]
@vfsfitvnm 
the playlist is already in compact mode.. so the text of button should be 'expand' and vice versa
![image](https://user-images.githubusercontent.com/88180887/182607606-433576ad-46d9-49ed-8a58-349cf687875c.png)

Also can u help me to do this.. i m new to development and contributions
