### ISSUE TITLE
Cast audio

### ISSUE THREAD

**Issue by Reed-Schimmel** [vfsfitvnm/ViMusic#158]
### Feature description

Add functionality to cast music to devices like smart TVs. I use SmartTube on my smartTV so that could grab the YouTube music link without needing a YouTube music account.

### Why do you want this feature?

Required to reach feature parity with standard music streaming apps. I also want to play music on my TV.

**Comment by vfsfitvnm** [comment]
Unfortunately I won't implement that. Please read #38

**Comment by Jak2k** [comment]
Why not implement it for KODI? That's FOSS.

**Comment by vfsfitvnm** [comment]
@Jak2k Do you have some resources for that? Also, I don't have such device so I couldn't implement it anyway

**Comment by Jak2k** [comment]
In NewPipe it's handeled by the *Kore*-App:
```
public static void playWithKore(final Context context, final Uri videoURL) {
        final Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setPackage(context.getString(R.string.kore_package));
        intent.setData(videoURL);
        intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startActivity(intent);
    }
```

You can download Kodi on: https://kodi.tv/download
It even runs on Windows.

**Comment by vfsfitvnm** [comment]
@Jak2k That's not casting. It just forwards the casting problem to a third party app. Moreover, it requires a video url, which I don't necessarily have as the playback often relies on the cache (i.e. private disk files).

**Comment by caveman1973** [comment]
I use AirMusic app to play from my Android to my Apple HomePod. Maybe it'll work to play on your TV.

**Comment by CrepeTF** [comment]
There is a MicroG version of the API

https://github.com/microg/GmsCore/tree/master/play-services-cast-api

**Comment by vfsfitvnm** [comment]
@CrepeTF Thanks, I will take a look.

**Comment by vfsfitvnm** [comment]
I'm leaving here other resources I found for general purpose casting (google cast excluded).

https://developer.android.com/training/connect-devices-wirelessly/wifi-direct
https://github.com/android/media-samples
https://developer.android.com/guide/topics/media/mediarouter

Keywords: upnp, dlna.

**Comment by vfsfitvnm** [comment]
microG or third party libraries won't be used. If it can be done using the android sdk, I'm not personally against it

**Comment by vfsfitvnm** [comment]
That said, I have zero knowledge in this field and I never used it once in my life, so I will implement it only if it requires zero effort

**Comment by vfsfitvnm** [comment]
Tracking in #597
