### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by loviuz** [vfsfitvnm/ViMusic#1597]
### Steps to reproduce the bug

I would like to use a recent version, with multi-language, but the last release is on 2022

### Expected behavior

I expect to have a recent release to download and install :-)

### Actual behavior

I cannot use an updated version :-(

### ViMusic version

0.5.4

### Android version

Android *

**Comment by Clyde6790pGIT** [comment]
Use RiMusic, it is a fork of ViMusic that is still having weekly updates.
