### ISSUE TITLE
Invidious instances

### ISSUE THREAD

**Issue by Terkyz** [vfsfitvnm/ViMusic#16]
### Feature description

The ability for the app to use Invidous instances instead of interacting with Youtube servers directly, increasing user privacy.

Obviously not being something mandatory or activated by default, but an option that can be enabled in the settings.

### Why do you want this feature?

Increase user privacy, mainly.

### Additional information

Keep up the hard work please!

**Comment by vfsfitvnm** [comment]
AFAIK Invidious (and piped) does not provide an API to YouTube Music, so this cannot be done.

**Comment by IceDBorn** [comment]
@vfsfitvnm Piped supports Youtube Music searches. The official Piped instance has this functionality and the android app called `Libretube`.

**Comment by vfsfitvnm** [comment]
@IceDBorn The API is far for complete - there are some missing endpoints I actually need:
- [Music search suggestions](https://github.com/vfsfitvnm/ViMusic/blob/master/youtube-music/src/main/kotlin/it/vfsfitvnm/youtubemusic/YouTube.kt#L377)
- [Queue info](https://github.com/vfsfitvnm/ViMusic/blob/master/youtube-music/src/main/kotlin/it/vfsfitvnm/youtubemusic/YouTube.kt#L412)
- [Radio](https://github.com/vfsfitvnm/ViMusic/blob/master/youtube-music/src/main/kotlin/it/vfsfitvnm/youtubemusic/YouTube.kt#L478)
...

https://beatbump.ml is more suitable for this - that's actually what I used when I started - however there were (and are?) some playback problems, but this is something I should consider in future.

Also, adding an extra layer in between may slow down things a bit.

**Comment by vfsfitvnm** [comment]
I'm closing as there's no way to use any other endpoint other than youtube (unfortunately).
