### ISSUE TITLE
An Unknown Playback Error has occurred

### ISSUE THREAD

**Issue by copinthearea** [vfsfitvnm/ViMusic#1607]
### Steps to reproduce the bug

I played the song Be Kind, and others too, i am having the same error.

### Expected behavior

The song Be Kind By Halsey, and others too, the same error!

### Actual behavior

It does not play the whole song.

### Screenshots/Screen recordings

![Screenshot_20240530-193644](https://github.com/vfsfitvnm/ViMusic/assets/101258929/c026ead1-682b-4ebd-b482-ff403b3900c8)

### ViMusic version

0.5.4

### Android version

Android 11

### Additional information

Smartphone Motorola

**Comment by Enigma1309** [comment]
switch to other forks like ViTune or RiMusic

**Comment by copinthearea** [comment]
Thank you! @Enigma1309

**Comment by Enigma1309** [comment]
welcome <3
