### ISSUE TITLE
Played songs are not being stored in the Offline Mode.

### ISSUE THREAD

**Issue by ghost** [vfsfitvnm/ViMusic#1611]
### Steps to reproduce the bug

1. Go to "Playlists".
2. Click on "Offline".
3. See that music is not available/stored.

### Expected behavior

Played songs should be available in offline mode to stream without internet.

### Actual behavior

But the songs are not stored/appearing to stream in offline mode.

### ViMusic version

0.5.4

### Android version

Android 13

**Comment by LuckySilver0021** [comment]
Mine works perfectly even in offline mode.
Maybe check in some other device.
