### ISSUE TITLE
Offline Playlist Without Expanding

### ISSUE THREAD

**Issue by JustNaturalCake** [vfsfitvnm/ViMusic#162]
### Feature description

Offline Playlist to the Compact section

### Why do you want this feature?

Would be nice to see Offline playlist without expanding half my screen.

### Additional information

![Screenshot_20220803-015036](https://user-images.githubusercontent.com/108516353/182498009-7effed83-6d9a-44c2-8107-8147d7db0bc1.jpg)
![Screenshot_20220803-015011](https://user-images.githubusercontent.com/108516353/182498016-097c62ed-9b84-41a6-a46e-7907718fc83b.jpg)

**Comment by vfsfitvnm** [comment]
At first the Offline playlist was always visible, however I can reconsider reverting that change

**Comment by JustNaturalCake** [comment]
Would be great seeing it back thank you.
