### ISSUE TITLE
Add button to fetch lyrics again

### ISSUE THREAD

**Issue by JustNaturalCake** [vfsfitvnm/ViMusic#163]
### Feature description

Little bar on the right side when editing lyrics to scroll down.

### Why do you want this feature?

Would be great to use when scrolling down.

### Additional information

![Screenshot_20220803-024525](https://user-images.githubusercontent.com/108516353/182500704-ee02875a-7be7-4a20-9bed-8f308fcc3fcf.jpg)

(If possible could you add a revert button to reset the lyrics to original when messing up something)

**Comment by vfsfitvnm** [comment]
I won't add a scrollbar as you can already smoothly scroll the text.
Regarding the a "refetch" button, I'll add it for sure.
PS - I also need to make the "new line" keyboard button actually make a new line instead of submitting the text.

**Comment by JustNaturalCake** [comment]
Oh I just found out how to scroll my bad, but reverting/resetting text would be amazing I keep messing up lyrics.
