### ISSUE TITLE
Add songs within the Playlist

### ISSUE THREAD

**Issue by JustNaturalCake** [vfsfitvnm/ViMusic#164]
### Feature description

Open any Playlist and click the + button to select multiple songs in the Songs tab on the main screen to add to the Playlist.

### Why do you want this feature?

Would make adding songs really easy since all you need to simply do is make a Playlist and just click the + button and add multiple songs by just selecting some.

### Additional information

![Screenshot_20220803-025427](https://user-images.githubusercontent.com/108516353/182501503-6c1c4959-1fd2-4469-811c-77af330ce908.jpg)

**Comment by vfsfitvnm** [comment]
#161 already covers this use case
