### ISSUE TITLE
Clear Song Cache

### ISSUE THREAD

**Issue by JustNaturalCake** [vfsfitvnm/ViMusic#165]
### Feature description

Adding clear song cache in settings.

### Why do you want this feature?

Some people may run out of storage after using it for a while and since we can clear images maybe be able to remove songs too.

### Additional information

I feel like this was suggested before or either not possible though. 
![20220803_121702_808](https://user-images.githubusercontent.com/108516353/182585235-7075892c-665f-424e-a726-541705914f3d.jpg)

**Comment by NR8124** [comment]
u can go to app info and clear all the caches right there 
![image](https://user-images.githubusercontent.com/88180887/182609727-60f23cde-39eb-4bac-b22b-63b652d9dbc7.png)

**Comment by vfsfitvnm** [comment]
Well, I think I should remove the clear cache option as it rather useless
