### ISSUE TITLE
Swipe to change songs

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#166]
### Feature description

Basically, you can change the song by swiping left and right.
![Uploading Screenshot_20220803-132638.jpg…]()

### Why do you want this feature?

It's a nice thing to get

**Comment by MountainFlowers** [comment]
![Screenshot_20220803-132638](https://user-images.githubusercontent.com/109493802/183022954-54ea7e46-710b-4a50-9325-98ab0d4b6e13.jpg)
Reuploading the screwnshot, cause it didn't work last time

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/154#issuecomment-1207278649
