### ISSUE TITLE
Manual change playlists oreder

### ISSUE THREAD

**Issue by GabrieleFranca** [vfsfitvnm/ViMusic#167]
### Feature description

Drag and drop playlists in oreder to change their order

### Why do you want this feature?

Would be possibile reorder album in their cronological oreder

**Comment by NR8124** [comment]
We Already have options to reorder the playlist in 3 diff ways
Use them and re order or playlist as u wants

**Comment by vfsfitvnm** [comment]
Exactly, I don't want to add a positioning system also for playlists. However, I can easily add a "pin" feature, so the playlists you pin always stays at the top.
