### ISSUE TITLE
AppName ,search Icon and setting button and "Your Playlist" should be pinned to their positions

### ISSUE THREAD

**Issue by John189903** [vfsfitvnm/ViMusic#169]
### Feature description

If you large number of songs in the songs list  and you are scrolling down. Now if I want to search any new song or access the playlist, I have to scroll all the way up.

### Why do you want this feature?

Accessibility

**Comment by vfsfitvnm** [comment]
I already tried doing that and it doesn't look good - the layout type should be changed too (#107)

**Comment by John189903** [comment]
The design in #107 looks good, are you going to incorporate that in future release?

**Comment by vfsfitvnm** [comment]
Closing - this is related to a major redesign issue. #172
