### ISSUE TITLE
Vi music's albums and playlists

### ISSUE THREAD

**Issue by Vimusic77** [vfsfitvnm/ViMusic#1699]
### Steps to reproduce the bug

Unknown Albums
Unknown Playlists

### Expected behavior

Dovrebbe apparire e riprodurre l'elenco delle canzoni degli album e delle playlist.

### Actual behavior

Non esce l'elenco di canzoni degli album e delle playlist. Da due settimane esce solo "unknown".

### ViMusic version

0.5.4.1

### Android version

Android 11

**Comment by riorom73** [comment]
Anche a me!

**Comment by muimota** [comment]
A patch was released by LlinksRechts at https://github.com/vfsfitvnm/ViMusic/pull/1654

**Comment by Vimusic77** [comment]
> A patch was released by LlinksRechts at #1654

Funziona! Grazie!
