### ISSUE TITLE
For features request

### ISSUE THREAD

**Issue by max5354** [vfsfitvnm/ViMusic#17]
### Feature description

Hello developer i just found the app. In my opinion this app will be a greatest alternative of YouTube music, blackhole, libertube, ymusic etc. You don't know how much i happy after finding this app. I have some features request for this app i hope you'll add this features.😊😊😊😊

1) add quality control option to change quality of songs (like 64kbps, 128kbps,256kbps)

2) add option to bookmark playlists (so we don't need to frequently search for playlists we can directly play from bookmark playlists option)

3) add option to import youtube music playlists.

4) add fully "black amoled" theme 

5) add sleep timer

6) and if possible please make one Telegram group so we can discuss about bugs and feature request.

7) show related songs on main screen.

8) add "repeat" and "shuffle" option.

9) add option to use system equalizer.

10) add option "double tap to seek" songs.

11) add option to change accent colors.

12) make songs page thumbnail rectangular and playlists page thumbnail rounded. 

13) it will be great if you add log in or sign in option with gmail.

14) add "bouncy" or "stretch OverScroll" animations.

It's too many features request but i hope you will add it in next/later beta updates...😊😊😊

And once again extremely thanks for making this type of app that fetch songs and playlists from youtube music....😊😊😊😊

Keep It Up Bro...

### Why do you want this feature?

Because i love this app...

**Comment by vfsfitvnm** [comment]
I'm sorry but I'll have to close this one. I really appreciate your feedback on the app, but this is not how feature requests should be made for this repository.

The template **clearly** states that only one feature should be requested per issue, so please take your time to split this big list of features in many issues and then we can start examining them one by one.

Moreover, some of your feature requests are already implemented or exist in the issue tracker already.
