### ISSUE TITLE
Add support of Music Thumbnail show on lockscreen

### ISSUE THREAD

**Issue by romiero** [vfsfitvnm/ViMusic#170]
### Feature description

Please add the support of music Thumbnail show at lockscreen. 
Like this from YoutubeMusic and other app like RetroMusic
![Screenshot_20220805-013323](https://user-images.githubusercontent.com/108507531/182914690-39ae8be6-c13e-4c34-bb0d-843dee484b82.png)

When i used Vimusic it doesn't show.
![Screenshot_20220805-013311](https://user-images.githubusercontent.com/108507531/182914930-4ef6b356-2326-4f75-9d2d-e16f15eb5759.png)

### Why do you want this feature?

Cuz why not? It would be great too.

### Additional information

My OS now Android 11

**Comment by vfsfitvnm** [comment]
? I can see the thumbnail in the second pic

**Comment by romiero** [comment]
> ? I can see the thumbnail in the second pic

I mean "Media Art" like the blurry version of Thumbnail.  Its on lockscreen not the music notification. Sorry if i confused you. 
Like this when i play YT music. which I scribbled red.
![Screenshot_20220805-124254~2](https://user-images.githubusercontent.com/108507531/183003374-e9537cb0-e554-4036-a9b6-a70d2f4f271b.png)

Or this knob to activate the feature on RetroMusic
![Screenshot_20220805-124433_Retro_Music](https://user-images.githubusercontent.com/108507531/183003535-4ced4a4b-229c-434d-8971-51999a7c091d.png)

Tq

**Comment by vfsfitvnm** [comment]
Thanks, I didn't know this thing existed :)

**Comment by romiero** [comment]
> Thanks, I didn't know this thing existed :)

You are welcome 🤗. Love this app. Better alternative to yt music as it still play music when app not in backgr.
