### ISSUE TITLE
Layout Redesign Suggestions

### ISSUE THREAD

**Issue by PassionateG1t** [vfsfitvnm/ViMusic#172]
Following #107, I thought I want to help you find a good design that balances between the minimalist power user style and a more user-friendly style. (Apologies for not following the templates but this can only be done this way.)

**1. Preliminaries**

I'm trying my best to visualize my ideas with mediocre designing skills so be patient with me. This is a draft that you can take inspiration from, I'd be happy to know your feedback. All icons used aren't particularly appealing but you can substitute with what you find more suitable. And this will be somewhat long so please bear with me.

**2. Tabs**

Some hate the current design because it crams everything in one place (a power move imo) but others equally hate the big number of confusing and inefficient tabs. Well it seems like having more than one tab will be inevitable, but let's try to minimize the number of used tabs.

Following my design, there will be only three tabs:

- Library (place for your songs, playlists and followed artists)
- Search 
- Genres/trending (in case you're looking to execute #36)

_pic.1 - Tabs that will be used_
![vimusic 1](https://user-images.githubusercontent.com/107609269/183072116-4f760790-ae8e-43f3-b108-f5a7926416b0.jpg)

Before diving into the contents of each tab, there should be some configurations that can be done to customize the user's experience:

 - Tabs location: Top of page/ bottom of page
- Tab label: show label of each tab/ hide label
- Default tab at launch

**3. Library**

_pic.2 - Library tab_
![vimusic 2](https://user-images.githubusercontent.com/107609269/183072815-329db53e-3013-4d81-84ad-971f317ce9fa.jpg)

The library tab, at surface, will contain your playlists and followed artists. But what about song? It will have its own page when you click on the icon to the left of search button (pic.2 & pic.3) The search button isn't to browse new music like on the older design but to search through your playlists and artists and added songs. Followed artists can similarly be viewed in vertical or horizontal modes.

_pic.3 - Added songs, similar to old design but has its own space_
![vimusic 3-01](https://user-images.githubusercontent.com/107609269/183073473-6ff010d8-9d83-4ff5-bdd7-4e4e67152cac.jpeg)

Finally, the settings button will be only present in library tab; other tabs won't have it.

**4. Other tabs**

Search tab is pretty straight forward, it will look exactly like the old design but it will have its own tab. If you didn't notice by now, the proposed design is inspired from Spotify.

As for the genres tab, I will leave that for you. I personally don't mind (nor particularly desire) such a tab. So do whatever you and other users want.

One last thing, I prefer the ViMusic logo to appear only in the genres tab.

This brings us to the end of this issue. If something that I showcased doesn't seem clear, please do not hesitate to ask me.

**Comment by vfsfitvnm** [comment]
> Well in that case, let's replace the trending tab with one only for songs

In such case, what's the difference between this and #107? Just the navigation being at the bottom, playlist and artists being merged and the search being a separate tab? Is there enough to say "I don't like #107, but I like this one"?

> Why have albums when there are playlists?

This is true, but they aren't the same thing (the user creates the playlist, the artist creates the album), That is, if we add artists, we should add albums as well. Just for the sake of being complete.

**Comment by vfsfitvnm** [comment]
(not related to this)

This is another experimental concept I came up with a couple if weeks ago (after looking at dribbble for inspiration):

https://user-images.githubusercontent.com/46219656/183710858-073ff9f6-ade8-4991-ad89-62d31f346ba8.mp4

**Comment by Malopieds** [comment]
Even though I'm not a big fan of vertical bar on the left (not easily accessible by one hand), this is more convenient than having multiple tabs !

**Comment by caveman1973** [comment]
> (not related to this)
> 
> This is another experimental concept I came up with a couple if weeks ago (after looking at dribbble for inspiration):
> 
>  untitled.mp4

Loved the idea. I would just make it a little thinner to give more space for the content.

Is it possible to add Genres to the list?


Not related but I'm loving ViMusic. Such a nice player and at only 2mb! I'm deleting Vanced YouTube Music now.

**Comment by VedxP** [comment]
> (not related to this)
> 
> This is another experimental concept I came up with a couple if weeks ago (after looking at dribbble for inspiration):
> 
>  untitled.mp4

Very unique design for a music player 🎉

**Comment by vfsfitvnm** [comment]
> The thing is, this seems like a disadvantage when you add a lot of songs, but a disadvantage that isn't exclusive to your app. Think about it: in every single music app (spotify, yt music or whatever) the more songs you have the harder it is to maintain your library. There's a couple of ways to mitigate this which are not so related to the layout: first, having a separate search feature to browse only through your library. Second, limit the amount of loaded songs; when you scroll down you'll find a button that when you press it will load more songs (can have an option in settings to auto load maybe). Third, change the way songs are sorted; instead of "last added" we'd sort them as "last listened to" which makes it easier to remember when was the last time you listed to a certain song and locate it.

@PassionateG1t
I think your idea of having a separate screen for "added songs" is actually good. As of now, I just put **all** the songs in the home screen, but considering my own (current) usage, it's rather useless.
So, a "song archive" page (where one can see, sort and filter all the songs) would be more appropriate.

However, I still believe that, when opening the app, there should be something "ready to play". Unfortunately, displaying a "dumb" song list (the current one) is not enough - we should build something more sophisticated instead. 
E.g. add the ability to start the radio from the songs you listened recently.
E.g. you listened to a specific a lot? Here you can listen to its artist or its album.

In order to do so, I have to plan a "weight system" which classifies songs by their recent playback duration (so that it can determine if you lost interest in something).

**Comment by vfsfitvnm** [comment]
Thanks for your valuable feedback :)

**Comment by Malopieds** [comment]
I agree with you on the idea that something has to be ready to play. What I was thinking is a mix of two things, the first one is sorting into lists of songs with the same "genres", and adding some similar songs, in order to discover other songs? 
I also do like your idea of songs you listen a lot !

**Comment by vfsfitvnm** [comment]
Yep, showing similar songs is planned already (but, unfortunately, it requires a network request).

The biggest challenge here is finding the algorithm for those recommendations (i.e. doing the math). I have zero knowledge on this topic unfortunately

**Comment by Jak2k** [comment]
Maybe fetch the most popular songs of artists which are similar to the artistsy which are already in the library. The similar artist should benprovided by yt-music.

**Comment by jerryop** [comment]
![attachment](https://user-images.githubusercontent.com/72891716/191575599-5091b1e9-45cf-479f-b6c1-8c178fb034b7.png)
Is this possible to get this type of player and layout design

**Comment by ikanakova** [comment]
I would like it if there was an offline button in the player for an view of which songs are in offline playlist.

**Comment by LupSpie** [comment]
Since this has become the default place to discuss layout stuff, I'd like to throw in some of my nitpicks :p

- Add to favorites button color doesn't match the repeat

- The top bar doesn't stick when scrolling

- Previous tracks could go slightly darker on the queue

- Can't see the albums an artist has released on their page

**Comment by vfsfitvnm** [comment]
Here's a little preview of the redesign:

https://user-images.githubusercontent.com/46219656/192363794-f22ebae3-f6c3-493b-826e-68041f4e83d6.mp4


I'm very satisfied :smile: 

Things to do left:

- [ ] Add "Recommended" tab in the initial screen (https://github.com/vfsfitvnm/ViMusic/issues/172#issuecomment-1235782372)
- [ ] Redesign the artist screen and add albums, singles etc (#123 )
- [ ] Redesign the playlist screens
- [ ] #204
- [ ] (maybe) redesign the player screen to match the new "look & feel"

**Comment by Malopieds** [comment]
Wow really nice !!
+1 for the modifiable tabs!
And therefore maybe add there the explore functionality?

**Comment by vfsfitvnm** [comment]
> Will it still be possible to import albums as playlists

I removed such option because albums have their own space now - you can use the bookmark function instead. Also, #161 would cover this use case as well.

> And will tabs be modifiable (as in their order + hide unwanted tabs) ?

Nope, it requires too much effort.

> And therefore maybe add there the explore functionality?

Yeah, it's possibile now that there aren't UI problems anymore :)

**Comment by yant0** [comment]
would it be possible to not rotate the icons? We can have the text sideways but i think not rotating the icon gives more integrity that its meant to be used vertically.

Also can you add these to the new ui?
- change tab position (left / right & top / bottom, makes the ui easier to use witg one primary hand)
- only show icon

**Comment by vfsfitvnm** [comment]
Yep, I van definitely show icons only (without rotation). I didn't try that yet so I don't know how it looks, but it was my plan already

**Comment by Malopieds** [comment]
> Nope, it requires too much effort.

Would you accept a PR for this if I can make this work?

**Comment by vfsfitvnm** [comment]
> Would you accept a PR for this if I can make this work?

I don't think I would, honestly. If you don't plan to use a tab, just don't open it - how can you consider it wasted space? Regarding the possibility to move the tabs, it just doesn't make sense - what are its advantages?

(The following is only applied to the home and search results screens) At the current state, the selected tab is saved to the disk, so the next time you open the app, it will show the tab that was previously opened. However, I could add an option to display a default tab instead, regardless the one that was opened for last.

**Comment by jerryop** [comment]
> Here's a little preview of the redesign:
> 
>  device-2022-09-26-212752_edit.mp4 
> I'm very satisfied 😄
> 
> Things to do left:
> 
> * [ ]  Add "Recommended" tab in the initial screen ([Layout Redesign Suggestions #172 (comment)](https://github.com/vfsfitvnm/ViMusic/issues/172#issuecomment-1235782372))
> * [ ]  Redesign the artist screen and add albums, singles etc ([Are artists supposed to show all of their music? #123](https://github.com/vfsfitvnm/ViMusic/issues/123) )
> * [x]  Redesign the playlist screens
> * [x]  [Scroll to top #204](https://github.com/vfsfitvnm/ViMusic/issues/204)
> * [ ]  (maybe) redesign the player screen to match the new "look & feel"

@vfsfitvnm Looks very cool only if the words aren't sideways(is the sideways word, toggleable?)

**Comment by BluePixel4k** [comment]
> > Also can you add these to the new ui?
>  > - change tab position (left / right & top / bottom, makes the ui easier to use witg one primary hand)
>
> Regarding the bar position, I don't know yet

I would also prefer on option to move the tabs to the bottom, like this:
<img src="https://user-images.githubusercontent.com/77979781/192862540-ba1ff4e7-899c-4746-ac9d-1ed40a1dfcd2.png" width="300" />

Yes its a matter of taste, but I don't see a real benefit for the navigation an the left side - only for the landscape mode.
There is a tendency for new phones to be taller, not wider. And I think in one hand mode its a bit uncomfortable.

But thx for improving the app continuously.

**Comment by vfsfitvnm** [comment]
Such component (called bottom navigation bar - or whatever horizontal bar) isn't suitable because it's tied to the destinations of the whole app (not the ones of the displaying screen).

However I can probably add an option to move the vertical bar to the right. Also, I can implement some sort of gesture to be honest

**Comment by BluePixel4k** [comment]
> Such component (called bottom navigation bar - or whatever horizontal bar) isn't suitable because it's tied to the destinations of the whole app (not the ones of the displaying screen).

Yes, that's true, but I think its not a deal breaker. 
The dynamic is a bit limited, but mainly for the search, or?

Maybe you can merge your current design with the navigation bar, like this:
<img src="https://user-images.githubusercontent.com/77979781/192886305-b9347584-023d-45a5-8a59-6021e346762b.png" width="250" />
And an suggestion for an "All" search result (a short overview of the top results - pressing the more button could auto switch to the right section):
<img src="https://user-images.githubusercontent.com/77979781/192886377-615b2bd8-9bf9-47ef-83ed-649ea5832674.png" width="250" />

In the player section, the navigation bar could be hidden. Like other music players do it too.

**Comment by sidsharths1245** [comment]
> Yep, showing similar songs is planned already (but, unfortunately, it requires a network request).
> 
> The biggest challenge here is finding the algorithm for those recommendations (i.e. doing the math). I have zero knowledge on this topic unfortunately

Can't you use the same algorithm or function that the "radio" uses. You can take songs from the "radio playlist" that the user recently played or "most played" and recommend those. I'm sorry i don't anything about coding or algorithms but thought this might help.

**Comment by NR8124** [comment]
> However I can probably add an option to move the vertical bar to the right. Also, I can implement some sort of gesture to be honest

@vfsfitvnm  I think this would be best solution because your current implementation is making this app unique from other alternatives ... 
And changes suggested by @BluePixel4k will lead to make it almost similar to [z-huang/Music](https://github.com/z-huang/music)

**Comment by yant0** [comment]
Just tried the new redesign. Would like to add additional thoughts (& questions) on the design
- can you replace the search using the tab's titles as search button. I personally think the button makes it difficult to see stuff (especially when its on artist page) unless padding were added.
- can you add toasts on icons when being held? It gives information as to what that icon is (eg the time icon and the other "time" icon on albums, and also the asterisk icon).
- can you add 3 rows display? Would be beneficial on albums if you had a thousand of them.
- will the alignment of tab titles be the same even when the "bar" was for example to the right? I think the current alignment of tab title is kind of too jumpy and reliant on how long the titles are.

**Comment by yant0** [comment]
> > will the alignment of tab titles be the same even when the "bar" was for example to the right? I think the current alignment of tab title is kind of too jumpy and reliant on how long the titles are.
>
>I don't really get what's your concern 😅 Would you clarify?

Its more of a question rather than a concern tbh. But right now i find myself constantly moving my eyes back and forth and i also found the start of the title changes based on how long the title is a tad bit jarring (Eg artist name can be longer than the artists tab title so the start position of the title changes a bit to the left).

I dont really think thats a huge problem (for me) but shouldve asked, will the stuff alignment be inverted if the bar were to the right.

**Comment by vfsfitvnm** [comment]
Right now the title is aligned to the right. If the vertical tab would have been to the right of the screen, then I think the title would be aligned to the left

**Comment by Pentaphon** [comment]
I must say, I'm not a fan of the vertical menu with the text on the side. It really confused the people who I showed the app to, especially older people. They kept turning the phone to read the menu. It was clearly annoying them. 

I really think there need to be a way to have all the text being read from left to right, such as a bottom menu as others have suggested. It would greatly simplify the look and usage of the app, which is important in such a popular type of app such as a music app.

**Comment by yephny** [comment]
I agree with @Pentaphon, not only the text on the menu is hard to read, the layout makes little sense. Phones are larger in the vertical, not horizontal. The bar that used to take up a tiny portion of the screen now covers so much space that everything has to be a compressed. I simply can't see what's wrong with a bottom bar.

I also loved (at least it grew on me) how everything could be found in a single dashboard, but I get the reason to change it. Now, you have to go to `Playlists` to find your favorite songs. It makes sensey, as the saved playlists were difficult to find/see/manage in the main dashboard. Favorites could be in `Songs`, but technically it's a playlist, and this is just a light pet peeve of mine.

**Comment by arfanmrafeek** [comment]
I agree with both @Pentaphon and @yephny.
@vfsfitvnm , I know it's hard to bring old layout back, And I'm actually liking the new layout too, The request I want to make is, Add an option in setting to change menu layout to Vertical or Horizontal.

**Comment by Pentaphon** [comment]
> Phones are larger in the vertical, not horizontal.

This is another problem with the new layout: everything looks too squished if you use a newer phone with a thinner profile and a taller screen.  The side text is also very small and makes it harder for people to read unless they already have their settings set to have a larger system font.

**Comment by yephny** [comment]
I feel like many of us have gotten used to it.
