### ISSUE TITLE
As cache file is there, Please add download button.

### ISSUE THREAD

**Issue by arfanmrafeek** [vfsfitvnm/ViMusic#174]
### Feature description

As the cache file is available in app data, Request please add Download option, I tried to locate cache location couldn't find. It's a great stone. 

Thanks for providing such an amazing application. 

### Why do you want this feature?

So, It's easy to keep the file data, If possible add music library of the phone. I use simple music player, But like your music player UI.

**Comment by vfsfitvnm** [comment]
Duplicate of #83

**Comment by arfanmrafeek** [comment]
Sorry, Found better alternative app for these app, Let VImusic be itself. 

Next time someone ask this feature mention this project. 

https://sangwan5688.github.io/
