### ISSUE TITLE
Playlist issue 

### ISSUE THREAD

**Issue by Ayushcricfan21** [vfsfitvnm/ViMusic#1741]
### Steps to reproduce the bug

Open any YouTube music playlist or albums

### Expected behavior

After clicking on the YouTube music album it should show the tracks of that playlists

### Actual behavior

Gets a loading screen and not opening 

### Screenshots/Screen recordings

Uploading Record_2024-07-13-08-39-55.mp4…

### ViMusic version

0.5 .4

### Android version

Android 14

**Comment by DevDotDev** [comment]
Duplicate of several issues already opened. Pull request #1654 aims to fix this bug. Also your "Screenshots/Screen recordings" is just text. Please close issue
