### ISSUE TITLE
Album issue

### ISSUE THREAD

**Issue by Bipulai** [vfsfitvnm/ViMusic#1742]
### Steps to reproduce the bug

Go to an album
Click to open it

### Expected behavior

After opening the album it should show the song in that particular album

### Actual behavior

The album is opening but not displaying any content of it

### ViMusic version

v0.5.4

### Android version

13

**Comment by DevDotDev** [comment]
Duplicate of several issues already opened. Pull request #1654 aims to fix this bug. Please close issue
