### ISSUE TITLE
Album error

### ISSUE THREAD

**Issue by Jkcrpats** [vfsfitvnm/ViMusic#1748]
### Steps to reproduce the bug

1. Clicking to an album/releases of an artist (it can be from the artist, form the quick picks or the albums on the search

### Expected behavior

This should have a list of songs inside the album/single
![Screenshot_2024-07-14-07-52-29-88_6f55a3c4de83481ebdee1685416eed82](https://github.com/user-attachments/assets/7041746f-528a-4278-9b69-bd0befc0462c)
(This album is from Taylor Swift -TTPD. You can see clearly that there is the name of the album and he list of the songs in it )

### Actual behavior

The title and the songs aren't there.

![Screenshot_2024-07-14-07-51-18-45_6f55a3c4de83481ebdee1685416eed82](https://github.com/user-attachments/assets/9d20e942-38c8-4775-b196-4b28355b9766)
(This album supposed to be 'Cry' from cigarettes after sex, but there is an 'Unknown' in the title, and loading animation in the list.

### ViMusic version

0.5.4

### Android version

Android 14

**Comment by Jkcrpats** [comment]
I wish that this error will be fixed soon. Many users complained about this same issue.

**Comment by DevDotDev** [comment]
Pull request #1654 aims to fix this bug. Please close issue
