### ISSUE TITLE
Change the 'add to favorites' icon to an outline if not active.

### ISSUE THREAD

**Issue by LupSpie** [vfsfitvnm/ViMusic#175]
### Feature description

Change the icon of the 'add to favorites' button in the now playing screen to be an outline instead of filled, when the button is not in an active state.

### Why do you want this feature?

Some people may find the 'add to favorites' button confusing if the unselected icon is filled, as it commonly appears as unfilled to indicate a deactivated state in other music apps.

Besides, as it currently stands the button might appear to be in the same state to people with colorblindness, especially people with Red-Green colorblindness / Achromatopsia (partial or total absence of color vision).

### Additional information

Here's a visualisation of what I'm suggesting:

![Suggestion](https://user-images.githubusercontent.com/49603837/183234060-8cc41180-8352-4190-90d9-3a1cf1db24a2.jpg)

**Comment by vfsfitvnm** [comment]
<p align="center">
  <img src="https://user-images.githubusercontent.com/46219656/183262786-bd7d5bb0-6b21-4c48-b1b8-ad21eaff2c76.png" width="30%" />
  <img src="https://user-images.githubusercontent.com/46219656/183262788-b155ae09-e21a-4283-a055-56c811d91890.png" width="30%" />
</p>

**Comment by vfsfitvnm** [comment]
There's something that looks off with the outlined heart, and I can't really figure it out :/

**Comment by LupSpie** [comment]
Can't really say it _feels_ off. Matter of fact, for me, the filled icon feels off, actually lol

**Comment by vfsfitvnm** [comment]
Let's see what other people think. We can also think of another solution, of course

**Comment by yant0** [comment]
I agree with it being an outline. Makes visual balance from the very right button being a line too.

**Comment by vfsfitvnm** [comment]
@yant0 Thanks, I got what looks off!

It's true the "repeat" icon at the right is a line - but you also have to consider the whole screen.
In fact, at the bottom left of the screen there are no icons - but at the bottom right there are 3.
The filled hearth somehow compensates this unbalance.

If I use my finger to cover the bottom (where you tap to open the queue), the outlined heart looks balanced

**Comment by yant0** [comment]
Hmm. I personally dont mind that. And im not an expert at design or anything but, maybe add a seperator for those button at the corner and for the queue list. Maybe a lighter color.

At first when using 3.0 i dont know where the queue list was but do know where the placement was. So maybe its a better thing the bottom to be highlited.

But thats just my take on this. A *not so professional* take :p

**Comment by vfsfitvnm** [comment]
I'm implementing #159 right now; I will change the color of the bottom thing so it's more clear it can be tapped :)

**Comment by NR8124** [comment]
> (Although I guess this would be another Feature Request entirely :p)

Yeah i and @vfsfitvnm  have already discussed regarding this in my  recent opened issues

So i guess he will be  implementing something very similar to this
