### ISSUE TITLE
Shuffle adjustements.

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#177]
### Feature description

What I want us for the shuffle button to be an on and off button. Reason is, it's really annoying when you press a specific song and have to manually shuffle. It would be easier if you had the shuffle button on and press a song, automatically shuffling the queue.

### Why do you want this feature?

It's annoying having to do this. Would be much easier

**Comment by vfsfitvnm** [comment]
I explained [here](https://github.com/vfsfitvnm/ViMusic/issues/130#issuecomment-1193373647) why I won't do this.
