### ISSUE TITLE
Stop queue from closing from drag

### ISSUE THREAD

**Issue by yant0** [vfsfitvnm/ViMusic#179]
### Feature description

Stop queue list from closing from quick drag or long drag. I personally think, the queue list needs to be at the top first then can be closed. After the list reach the top, queue list can be closed from dragging anywhere.

### Why do you want this feature?

Better ux...?

### Additional information

Current behaviour :
[Video](https://bun.filedit.ch/xWGFdXnTVOurLgcNiEbz.mp4)

**Comment by vfsfitvnm** [comment]
I'm not sure I understood what your desired behavior would be. The queue is opened at the current playing song - it makes no sense to open it at the top. You can close it by pressing your device back button (or whatever) or pressing the big space at the bottom (maybe this one isn't clear at all)

**Comment by yant0** [comment]
Nvm i tested with my other phone its just lag from scrolling too fast on queue list i thought it closes right after it reach the top

Closing 👍
