### ISSUE TITLE
Lyrics Icon suggestion

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#180]
### Feature description

change lyrics icon in player view to

![image](https://user-images.githubusercontent.com/88180887/183299815-9a828f02-c663-458b-a931-66d486c963a6.png) or ![image](https://user-images.githubusercontent.com/88180887/183299787-798bb406-45c9-426f-a434-56cc2fe5d264.png)

or somethings similiar to this which clearly indicates that it is for lyrics

### Why do you want this feature?

The current "Aa" doesn't indicates that it is used for song lyrics
hence something relevant should be used

**Comment by vfsfitvnm** [comment]
That's the icon for a playlist 😅

https://ionic.io/ionicons
These are the icons I use. I can only combine them / do small modifications

**Comment by NR8124** [comment]
so i think these icons can be used and combined to make something we want

![image](https://user-images.githubusercontent.com/88180887/183300481-fdbb951c-f66c-48a0-94be-6969a80bb0f7.png) ![image](https://user-images.githubusercontent.com/88180887/183300457-50cb5585-3561-43d6-9337-4e4bd6f4f891.png)

**Comment by vfsfitvnm** [comment]
What if se combine the "A" with the musical note?

**Comment by NR8124** [comment]
Great!!

**Comment by NR8124** [comment]
Also there r few more UI suggestions 

1. The song info button should be shifted inside the menu 
Again as we already have tap n hold gesture feature so dont need to be in player section... So if possible shift it into menu section

2. After above shifting the info button.. move remaining two buttons ( i.e. menu and lyrics) to the right top corner of player ..... Cause it looks very good and familiar 

3. Lastly for the bottom part i.e.  upcoming next along with the next song name could be a option
![Screenshot_2022-08-08-01-04-08-69_7f804ff8cbc5258ebf6dfbfe93e73d67](https://user-images.githubusercontent.com/88180887/183308021-3cedccc3-f791-43c4-b656-e0a0b0e1f275.jpg)

**Comment by vfsfitvnm** [comment]
What if I remove the lyrics and info buttons? Lyrics and stats for nerds will appear after tapping / long tapping the song cover, respectively.

I want to keep the menu button at the bottom so it stays in the range of a human thumb

**Comment by NR8124** [comment]
> What if I remove the lyrics and info buttons?

I thought of that too ... It will also be a nice idea.....

PS: 
What if ??. thumbnails consists 
Single tap - lyrics
Double tap - song info
Tap and hold - opens menu

**Comment by vfsfitvnm** [comment]
It may work, but may be too much imho. Also, adding a double tap listener introduces an annoying delay when you just want to single tap

**Comment by ggdorman** [comment]
I think you should just re-add the the bottom bar with queue and lyrics. It was better.

**Comment by NR8124** [comment]
> What if I remove the lyrics and info buttons? Lyrics and stats for nerds will appear after tapping / long tapping the song cover, respectively.
> 
> I want to keep the menu button at the bottom so it stays in the range of a human thumb

Ok, So avoid double tap and all
And Continue with this as u suggested above
