### ISSUE TITLE
Refresh button in Offline section 

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#181]
### Feature description

There should be a refreshing button or feature
Which refreshes and  shows the latest cached songs

### Why do you want this feature?

Not able to see Newly cached songs in the offline section

**Comment by vfsfitvnm** [comment]
Nope, it's not possible due to [this](https://github.com/vfsfitvnm/ViMusic/issues/60#issuecomment-1181671363)
