### ISSUE TITLE
Loading issues in Albums of any artist

### ISSUE THREAD

**Issue by Unmooooll** [vfsfitvnm/ViMusic#1810]
### Steps to reproduce the bug

Open the album of any artist 

### Expected behavior

Supposed to show me list of songs 

### Actual behavior

Not loading 

### Screenshots/Screen recordings

![Screenshot_2024-07-27-10-57-03-546_it vfsfitvnm vimusic](https://github.com/user-attachments/assets/e1fd1fb3-0f7c-433f-b89d-4609ed358b38)

### Logs

Loading issues in Albums of any artist

### ViMusic version

0.5.4

### Android version

Android 10

### Additional information

Loading issues in Albums of any artist

**Comment by Unmooooll** [comment]
Loading issues in Albums of any artist

**Comment by Unmooooll** [comment]
Loading issues in Albums of any artist

**Comment by Maaz0900** [comment]
Not solve yet 😞

**Comment by JohnRFirst** [comment]
Here, try this https://github.com/vfsfitvnm/ViMusic/issues/1835#issuecomment-2265174909
