### ISSUE TITLE
albums issue

### ISSUE THREAD

**Issue by elguapoita** [vfsfitvnm/ViMusic#1816]
### Steps to reproduce the bug

1.search a group 2.select the albums section 3.click on one of the albums 4.the songs don't load

### Expected behavior

it should play the album I decide ro listen

### Actual behavior

a loading Page appear

### Screenshots/Screen recordings

![Screenshot_20240729_131450_it vfsfitvnm vimusic](https://github.com/user-attachments/assets/7c5a2ff6-34ba-4366-8ab0-1c9337ee72a0)
![Screenshot_20240729_131430_it vfsfitvnm vimusic](https://github.com/user-attachments/assets/927efe11-7981-48d7-b4ee-b5462c44cd5e)

### ViMusic version

V. 0.5.4

### Android version

android 9

**Comment by JohnRFirst** [comment]
Same. Try this https://github.com/vfsfitvnm/ViMusic/issues/1835#issuecomment-2265174909

**Comment by elguapoita** [comment]
thanks. It worked

**Comment by ashirbad23** [comment]
> thanks. It worked

is it safe??

**Comment by JohnRFirst** [comment]
> > thanks. It worked
> 
> is it safe??
> 

It is. It's an identical app to vimusic with the exception of the API fix and a larger font for lyrics.

**Comment by RakshanthG** [comment]
How about queue issue. It's behavior was same. When I try to rearrange the order of songs in my Playlist. It's falling back to the same place again. I can't re-arrange the queue list. If you have any solution regarding. Please share.

**Comment by adserasinghe** [comment]
How can slove that bug please tell me?

**Comment by adserasinghe** [comment]
How can slove that bug please tell me?

**Comment by JohnRFirst** [comment]
> How about queue issue. It's behavior was same. When I try to rearrange the order of songs in my Playlist. It's falling back to the same place again. I can't re-arrange the queue list. If you have any solution regarding. Please share. 

Oh, what a bummer... Sadly, I couldn't find a solution to that. Since we can't expect the dev to update the app, the only "solution" is to look for similar apps... I have seen someone reccomending Vitune, which is yet another fork app with slightly different features. You could try that.

But yeah, unfortunately, no promises...
