### ISSUE TITLE
Use system font

### ISSUE THREAD

**Issue by yant0** [vfsfitvnm/ViMusic#182]
### Feature description

Custom fonts

### Why do you want this feature?

I would like to change the current font. 

Users may also be in another country that rarely uses the latin alphabet and would like to change to their preferred font.

### Additional information

Import .ttf or .otf into the app

**Comment by vfsfitvnm** [comment]
> Import .ttf or .otf into the app

No, I won't add such option for sure. I could add an option to use the system font instead.

However, what's the issue with the current font?

**Comment by yant0** [comment]
There is not a major issue with the current font. I thought it would be cool to have other fonts included / installed. Ill be happy to have the option to have system font as the app's font. Ill rename the issue to use system font.

**Comment by dhishkyaon** [comment]
+1 for system fonts

**Comment by vfsfitvnm** [comment]
Implemented. If it doesn't work, please let me know.
