### ISSUE TITLE
CSV playlist import

### ISSUE THREAD

**Issue by StraggleCraft** [vfsfitvnm/ViMusic#185]
Hello, I'd like to request a feature for CSV playlist import.   Since my CSV would be coming from other services, ideally it would figure out what the correct YT music track is, based on track title artist etc.

**Comment by vfsfitvnm** [comment]
Hmm, I'm not planning to add this in the near future. Meanwhile, you can use any service to create a youtube (hopefully music) playlist given a csv file, then make the playlist public and finally import it in vimusic

**Comment by deepu2** [comment]
> and finally import it in vimusic

How do I import playlist like this? I searched the issues but didn't find anything.

**Comment by vfsfitvnm** [comment]
There are 2 ways:

https://user-images.githubusercontent.com/46219656/183670924-5f627c75-7de3-439e-a090-738bcaf91612.mp4

**Comment by deepu2** [comment]
Didn't know I can paste the link. Thanks for the quick video!

**Comment by vfsfitvnm** [comment]
After some thought, I decided to not include this feature. [This](https://github.com/vfsfitvnm/ViMusic/issues/185#issuecomment-1208401778) workaround saves me a lot of boring work and code base pollution.
