### ISSUE TITLE
Animating bottom sheet

### ISSUE THREAD

**Issue by samstone19943** [vfsfitvnm/ViMusic#187]
### Feature description

The original YT music app has some sophisticated animations when opening the bottom sheet. I think they use MotionLayout, but they may be doing custom math. I am going through the motionlayout codelab to see if it is possible to do with motionlayout. If you can figure out how to replicate it, I would be greatly appreciative!

### Why do you want this feature?

I want to use it in my app - that is the amazing thing about open source!

**Comment by vfsfitvnm** [comment]
?

**Comment by Malopieds** [comment]
> What are these sophisticated animations you are talking about?

I think those are the animations
>https://user-images.githubusercontent.com/74783202/183836240-4aeb4cde-66b5-4d17-8775-21cff10e59c2.mp4

**Comment by vfsfitvnm** [comment]
Considering how I handle the collapsed/expanded player, this is a so called "shared element transition". At the current state, it requires too much hassle to implement. I'm closing as I don't consider this one as an issue. Animations will improve with time
