### ISSUE TITLE
"Start Radio" creates a 1 big playlist

### ISSUE THREAD

**Issue by Jan9103** [vfsfitvnm/ViMusic#188]
### Steps to reproduce the bug

Im not sure.
1. fresh install
2. set image cache to 2gb and song cache to 8gb
3. play music (for ~a week - i had over 1gb music cache)

Or the fast method:
1. load my database file http://0x0.st/o2q0.db

### Expected behavior

It should continue to work

### Actual behavior

- Songs will no longer be added to the "Songs" list on the homescreen
- "Start Radio" only finds the current Song
- Online search still works
- Playlists still work

Attempted fixes:
- restrict the cache size, kill the app, extend cache size
- clear image cache
- create backup, clear cache and data via system settings, restore backup

### ViMusic version

0.3.0

### Android version

Android 12 aarch 64

**Comment by vfsfitvnm** [comment]
Already fixed in master (#186), please wait for the next release
