### ISSUE TITLE
Radio feature stopped working.

### ISSUE THREAD

**Issue by saiffydhanjal** [vfsfitvnm/ViMusic#189]
### Steps to reproduce the bug

Nothing

### Expected behavior

It should show the recommended songs on radio feature

### Actual behavior

But nothing is showing in radio feature 

### Screenshots/Screen recordings

![Screenshot_20220810-162247](https://user-images.githubusercontent.com/110978156/183884188-b9f8f500-9830-48c0-be7c-98ce78e7186c.jpg)

### ViMusic version

0.3.0

### Android version

12

### Additional information

Really love the app....I hope this could be fixed in next update.

**Comment by vfsfitvnm** [comment]
Already fixed, please wait for the next update. (#186)
