### ISSUE TITLE
Import share link

### ISSUE THREAD

**Issue by uGeek** [vfsfitvnm/ViMusic#19]
### Feature description

Is there a possibility that when you are in any application, when you give the share option, ViMusic appears as an option?

### Why do you want this feature?

When they share a link to me via telegram or I share from the browser itself, ViMusic does not appear as an option, instead if I open the link, the default application opens, in my case NewPipe.

**Comment by Jak2k** [comment]
What avout music.youtube.com links?

**Comment by vfsfitvnm** [comment]
They are supported as well:
https://github.com/vfsfitvnm/ViMusic/blob/master/app/src/main/AndroidManifest.xml#L38-L52

```
https://www.youtube.com/watch?v=[videoId]{&list=[playlistId]}
https://music.youtube.com/watch?v=[videoId]{&list=[playlistId]}
https://www.youtube.com/playlist?list=[playlistId]
https://music.youtube.com/playlist?list=[playlistId]
```

**Comment by Hazy0n3** [comment]
Hi.. I tried importing my playlist from yr music but vimusic gave me 0 results. Am I getting an error?

**Comment by vfsfitvnm** [comment]
Closing in favor of #22

**Comment by saiyaswanth007** [comment]
How to import playlist from Spotify
