### ISSUE TITLE
Issue with Import Backup in latest Debug APK

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#190]
### Steps to reproduce the bug

1. go to settings -> Backup & Restore -> Restore
2. select the backup file

### Expected behavior

Backup process completed with app crash

### Actual behavior

app crashes but after reopening i cant see my backup
tried 3-4 times to restore 
everytime noticed the same response 
butt then 

After 10 minutes i opened the app and the backup process was completed

### ViMusic version

"0.3.0 (Latest Debug Build)"

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
I cannot reproduce. Would you share your database?

**Comment by vfsfitvnm** [comment]
And would you share the `logcat`? Otherwise this issue is useless

**Comment by NR8124** [comment]
Yes it just took some time to restore but the process was completed so i closing this issue
