### ISSUE TITLE
Musixmatch API to fetch Lyrics

### ISSUE THREAD

**Issue by sidsharths1245** [vfsfitvnm/ViMusic#192]
### Feature description

As far as i know Musixmatch is the biggest library of lyrics, you can give it a try.

### Why do you want this feature?

Bigger lyrics database than the current one that's being used.  Also i noticed that synced lyrics aren't available for many songs.

### Additional information

Attaching the link to the API source page. [Musixmatch](https://developer.musixmatch.com/documentation) 

I'm sorry but i don't know anything about coding or programming so I'm not sure if this will work but do check it out.

**Comment by vfsfitvnm** [comment]
Not possible - just read their [API Terms & Conditions](http://musixmatch.com/apiterms/).
