### ISSUE TITLE
Functionality Issue

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#199]
### Steps to reproduce the bug

![Screenshot_2022-08-11-19-18-53-40_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/184150450-fa5ea1fb-c482-4059-849a-c413ca5e0206.jpg)

Is 32 mb option for song cache intentional?

### Expected behavior

It makes no sense in my opinion when image cache is still have a least of 128 mb caching.

There could be a lesser caching option for image cache too, if the same is added intentionally.

### Actual behavior

.

### ViMusic version

0.4.0

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
There's no functionality issue: the 32MB limit was added for those who want to stream only.

**Comment by VedxP** [comment]
> There's no functionality issue: the 32MB limit was added for those who want to stream only.

Ok, got it.

But wouldn't it be better if the same option be available for image cache too?
