### ISSUE TITLE
Music ID

### ISSUE THREAD

**Issue by Andy3914** [vfsfitvnm/ViMusic#1990]
### Steps to reproduce the bug

I was searching for songs and it tells me the song ID doesn't match the music.

### Expected behavior

![Screenshot_20240924-122730](https://github.com/user-attachments/assets/f986739d-53b3-4777-8850-4e4affd30a79)

### Actual behavior

This happened when I download the app.

### Screenshots/Screen recordings

![Screenshot_20240924-122730](https://github.com/user-attachments/assets/ef395f02-8032-48a3-8320-849e6452a6b1)

### Logs

The music is not playing i'm trying to listen the music.

### ViMusic version

 I don't know what version

### Android version

Nokia x100

### Additional information

The music does not play

**Comment by sparklingnites** [comment]
Do you solve it?
