### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by fgs45678** [vfsfitvnm/ViMusic#2]
Please consider socks5 and https proxy in software. Thanks

**Comment by vfsfitvnm** [comment]
I won't include an IP spoofing feature in this application. You can either use an existing service you trust or wait for YouTube Music to be released in your country, I apologize.

**Comment by vfsfitvnm** [comment]
I'm closing this as there's nothing I can do. An alternative could consist in not fetching `youtube.com` but a proxied service. See #16 for updates.
