### ISSUE TITLE
Add quality control option

### ISSUE THREAD

**Issue by max5354** [vfsfitvnm/ViMusic#20]
### Feature description

add quality control option to change quality of songs (like 64kbps, 128kbps,256kbps) 

### Why do you want this feature?

Because it's necessary.

**Comment by vfsfitvnm** [comment]
Could you elaborate? "_Because it's necessary._" is not enough to convince me to implement this feature.

**Comment by biqqles** [comment]
@vfsfitvnm should I open a new issue or is providing a proper reason here sufficient to reopen?

> Why do you want this feature?

I have a plan with limited mobile data and would prefer to stream low quality versions off WiFi to save data. YT Music appears to allow this to be configured.

Thanks for a genuinely stunning app btw.

**Comment by Kingzplay** [comment]
I have the same reason. I was streaming with this app using mobile data for a total of 1h40m or 2 hours, not sure, it still used more than 350mb. Adding the option to control the bitrate would save the users a lot of data for those who are streaming on a mobile data plan.
