### ISSUE TITLE
Play and pause button is not working properly from notification panel

### ISSUE THREAD

**Issue by John189903** [vfsfitvnm/ViMusic#202]
### Steps to reproduce the bug

1.  Play any song and pause the song from notification panel music control.
2. Song does pause but the pause button doesnt chane to play 
3. After this play/pause button doest nothing when pressed.

### Expected behavior

N/A

### Actual behavior

1.  Play any song and pause the song from notification panel music control.
2. Song does pause but the pause button doesnt chane to play 
3. After this play/pause button doest nothing when pressed.

### ViMusic version

0.4.0

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
I cannot reproduce. Would you attach a video?

**Comment by John189903** [comment]
https://user-images.githubusercontent.com/110436305/184221913-cf72f7ef-2d65-412e-baa3-abccacb39235.mp4

**Comment by vfsfitvnm** [comment]
I guess it worked in `0.3.1`?

**Comment by John189903** [comment]
yes

**Comment by vfsfitvnm** [comment]
Thanks, very strange. I don't remember touching that code and I can't reproduce.
Would you try the debugs apks (https://github.com/vfsfitvnm/ViMusic/actions) from the latest one? So at least I know the commits that introduced this bug.

**Comment by John189903** [comment]
Ok , sure

**Comment by John189903** [comment]
I am getting the same error on 0.3.0 as well, I installed version 0.2.1 it is working properly there

**Comment by John189903** [comment]
I was getting the same error in 0.3.0 as well , so I started downloading older versions, looks like it is working correctly on 0.1.7, after that version I am facing this issue

**Comment by vfsfitvnm** [comment]
That make sense. Unfortunately I cannot reproduce on A12 emulator, so I can't fix it

**Comment by John189903** [comment]
Ok, closing the issue
