### ISSUE TITLE
Crash on album search

### ISSUE THREAD

**Issue by alvi-se** [vfsfitvnm/ViMusic#203]
### Steps to reproduce the bug

- Search an album
- Press on the "Albums" button
- Select the searched album

### Expected behavior

It should open without crashing and show the album songs.

### Actual behavior

At the first time it crashes. If you do again these steps on the same album, it shows you the album page with no song, no matter if the songs are cached or not.

### Logs

```
08-11 20:34:40.939  1322  1336 I InputDispatcher: Focus entered window: Window{c5aa682 mode=0 rootTaskId=1 u0
Application Error: it.vfsfitvnm.vimusic} in display 0
08-11 20:34:40.942   656  2172 I BufferQueueProducer: [Application Error:
it.vfsfitvnm.vimusic#0](id:2900001d048,api:1,p:1322,c:656) disconnect(): api=1
08-11 20:34:40.943  1322  1339 D View    : [Warning] assignParent to null: this = DecorView@358c2b0[vimusic]
08-11 20:34:40.945  1322  1339 W WindowManager: Changing focus fromWindow{c5aa682 mode=1 rootTaskId=1 u0 Application
Error: it.vfsfitvnm.vimusic EXITING} to null displayId=0
Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:473
com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6209
com.android.server.wm.WindowState.setupWindowForRemoveOnExit:2516
com.android.server.wm.WindowState.removeIfPossible:2485
```

### ViMusic version

0.4.0

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
> At the first time it crashes

What's the album?

>  it shows you the album page with no song

Press the three dots and then "refetch"

**Comment by infinite-007** [comment]
I faced this exact same issue with the previous version. Not sure with new update.

**Comment by vfsfitvnm** [comment]
Wat's the album name? I need to reproduce the crash

**Comment by alvi-se** [comment]
In my case it happened with In Waves by Trivium and The Last Stand by Sabaton. Also when I refresh on the album screen the app crashes

**Comment by infinite-007** [comment]
For me it was- Barfi

**Comment by infinite-007** [comment]
But after fresh install the album opened.

**Comment by vfsfitvnm** [comment]
I cannot reproduce. Where are you guys from? Also, can you share the logcat? So I can fix the issue.

**Comment by infinite-007** [comment]
As of now didn't face the issue. Will share the logs if I face the issue again.

**Comment by infinite-007** [comment]
I didn't report it as I faced the issue only once till now.

**Comment by alvi-se** [comment]
I tried again on the previous albums and it worked, but with some others it still crashed. I'll send more logs as soon as I can

**Comment by yant0** [comment]
Having same issues i crashed with opening song's album from queue and this one. The search album shows timeout error and the queue one shows 500

https://hastebin.com/inirulahup
https://hastebin.com/popaduceva

**Comment by vfsfitvnm** [comment]
Oh. That happens when trying to reach piped (https://pipedapi.kavin.rocks), which I use for #88. It looks like they are having technical issues

**Comment by vfsfitvnm** [comment]
I found another workaround to implement #88. However, I still use piped to play age restricted videos - unfortunately there's no simple workaround for that

**Comment by yant0** [comment]
![image](https://user-images.githubusercontent.com/80298071/184345132-a7d42a7b-9fc8-4b22-becf-8cd55730cbb7.png)

**Comment by vfsfitvnm** [comment]
v0.4.1 released
