### ISSUE TITLE
Vi music 

### ISSUE THREAD

**Issue by khasim171** [vfsfitvnm/ViMusic#205]
### Steps to reproduce the bug

Some songs not coming form new release movie songs YouTube 
But not showing vimusic app

### Expected behavior

First day first show movie songs telugu not showing vimusic 

### Actual behavior

![Screenshot_2022-08-13-08-55-05-53_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/78673822/184466671-5f1e7d2c-4efa-4d2f-a4f0-afd15e26110d.jpg)
While typing this song name showing different songs 

### Screenshots/Screen recordings

![Screenshot_2022-08-13-08-55-05-53_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/78673822/184466715-3e9c0567-4eff-4bc2-a4d3-299928745446.jpg)

### ViMusic version

0.4.1

### Android version

11

**Comment by vfsfitvnm** [comment]
The search results are identical to the ones returned by youtube music. Also, I don't really understand what you are trying to say
