### ISSUE TITLE
Functionality Issue

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#208]
### Steps to reproduce the bug

Open Vimusic
Sometimes, created/saved playlists don't appear.

### Expected behavior

I've to close Vimusic and reopen then it does show.

After reopening:

![Screenshot_2022-08-14-07-49-26-88_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/184519866-747a2306-be24-46fd-ba6f-64909d9f2a70.jpg)

### Actual behavior

Before reopening, the bug:

![Screenshot_2022-08-14-07-49-21-90_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/87353286/184519885-adbd35e3-a89f-461b-a187-be6a5c6779ad.jpg)

### ViMusic version

0.4.1

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
Yeah, I don't know why it happens. I think it's aa jetpack compose bug (closiing). The annoying thinng is I cannot reproduce systematically.

However, you don't need to close the app, you should be able to.trigger the fix by i.e. opening the pop-up to reorder the items. In fact, the playlists are loaded, they are just not displayed by the jetpack compose runtime (this problem also happens with songs, too).

However, please don't use a vague issue title, it makes dofficult to find issues.

**Comment by VedxP** [comment]
> 

Okay, got it!
