### ISSUE TITLE
Sync across devices

### ISSUE THREAD

**Issue by marcecfilip** [vfsfitvnm/ViMusic#211]
### Feature description

Can there be like a account feature or something else that allows you to have the same songs on multiple devices ex. On your phone and tablet

### Why do you want this feature?

I have two phones and would like my music synced

**Comment by vfsfitvnm** [comment]
This is challenging to implement as it requires some sort of server or whatever, which I don't intend to purchase.

**Comment by Jak2k** [comment]
Maybe automatic import/export to file system. Then I could set the location inside my Nextcloud folder.

**Comment by vfsfitvnm** [comment]
It is also impossible because the app must be closed after importing

**Comment by Jak2k** [comment]
Maybe add the importing into the startup-routine.

**Comment by BluePixel4k** [comment]
> @vfsfitvnm This is challenging to implement as it requires some sort of server or whatever, which I don't intend to purchase.

Maybe you could use [Piped](https://github.com/TeamPiped/Piped) for playlist syncing. Its a YouTube frontend with an account feature. 
The account don't need an E-Mail address or mobile number. You have to choose only a username and password. With it you can sync your playlists.
[LibreTube](https://github.com/Libre-tube/LibreTube) and [Hyperpipe](https://codeberg.org/Hyperpipe/Hyperpipe) are using this frontend.
Currently there are 20 official servers you can choose between.

The second benefit is that you can reach your playlists from the browser with Hyperpipe and listen to the music from PCs and notebooks.

**Comment by vfsfitvnm** [comment]
I already added a button to sync the playlists (#196)

**Comment by BluePixel4k** [comment]
> I already added a button to sync the playlists (#196)

But this button only updates playlists from YouTube and not between different devices, or?

**Comment by vfsfitvnm** [comment]
Actually, yes - it's not the same thing

**Comment by BluePixel4k** [comment]
So, can you please take a look into the account feature of Piped? 😇

**Comment by vfsfitvnm** [comment]
I don't think I will honestly. A lot of code just to sync playlists? What about the rest of the database? Also, I don't want to rely on an instance that may go down anytime. So I will definitely avoid piped.

I know having an account which lets you to not worry about the database if super important. But as I stated before, it requires too much effort, money and responsibility.

**Comment by piemanau** [comment]
Is there a chance you could add an option to autosync the playlists on open or something like that? @vfsfitvnm
