### ISSUE TITLE
Remove unsynchronized lyrics

### ISSUE THREAD

**Issue by vfsfitvnm** [vfsfitvnm/ViMusic#212]
Version `0.4.0` introduced the synchronized lyrics, which are obtained from kugou, a chinese music streaming service. The quality of the lyrics is good - so I was questioning myself if we could remove the "non-synchronized" lyrics, which are served by youtube.
In such case, if one wants to read the lyrics regardless of the playback position, he can just scroll the text to stop the synchronization. To resume it, a button would appear.

Pros:
- Code/maintenance simplification
- Better UX

Cons:
- Slower load times when fetching the lyrics for the first time
- Lyrics are not fetched from youtube

:+1: = I like it OR I don't care
:-1: = I don't like it because (leave a comment - otherwise your vote will be ignored)

**Comment by vfsfitvnm** [comment]
@PassionateG1t Well, what could go wrong? I mean, all they can get about you is the IP address and what you searched for - I see no difference from google

**Comment by yant0** [comment]
Personally, I would prefer if there is no synchronized lyrics it would fall back to unsynchronized lyric instead.

And also a nice addition imo would be to click a part of the lyric to put back playhead at that time.

**Comment by deepu2** [comment]
Will it fall back to the unsynchronized lyrics if no synced lyrics were found? I rarely get synced lyrics for my language. Although i saw that "Harmonoid" has a pretty good synced lyrics source, it has the most support for my language. Haven't looked into what they use

**Comment by ShashaankHari** [comment]
It's better to have unsynced lyrics, some songs' can have multilingual lyrics and it's much better that it's editable.

**Comment by vfsfitvnm** [comment]
> Personally, I would prefer if there is no synchronized lyrics it would fall back to unsynchronized lyric instead.

This is feasible I guess

> And also a nice addition imo would be to click a part of the lyric to put back playhead at that time.

Yep, many lyrics timings are slightly delayed

> It's better to have unsynced lyrics, some songs' can have multilingual lyrics and it's much better that it's editable.

Synchronized lyrics are editable as well

**Comment by Jak2k** [comment]
I don't want to rely on chinese services.

**Comment by LupSpie** [comment]
I'm personally against moving towards _only_ having synchronized lyrics, as some tracks that don't have them in Kugou, such as 'BOOGIE' by BROCKHAMPTON, have them in YTM. But wouldn't mind @yant0's suggestion of having unsynchronized lyrics be a fallback for such cases.

**Comment by vfsfitvnm** [comment]
Ok - I decided to leave things as they are.

Regarding the IP concern, we can certainly use cloudflare workers (or whatever, like https://github.com/lujjjh/lyrics-api)

**Comment by ZingyTomato** [comment]
@vfsfitvnm There's also this : https://api.textyl.co/api/lyrics?q=tyler%20herro

I've used it for a small cli tool of mine and it seems to work well.

**Comment by vfsfitvnm** [comment]
@ZingyTomato It doesn't seem to be well furnished; it doesn't have the lyrics of three songs that crossed my mind when I tried (one of them having 500mln views on youtube...)
