### ISSUE TITLE
Lyrics in sync with the song

### ISSUE THREAD

**Issue by romiero** [vfsfitvnm/ViMusic#213]
### Feature description

Maybe you should check a desktop multiplatform app named Harmonoid, it's on GitHub too. Harmonoid.com is the website, the app could playing song with Synced lyrics.

### Why do you want this feature?

It will look good to add. I love the dynamic and it would be fun to record the song with the synced lyrics.

### Additional information

![image](https://user-images.githubusercontent.com/108507531/184542826-f62042b1-a800-4c7d-88b4-4f962b9885e8.png)

**Comment by vfsfitvnm** [comment]
Already implemented in 0.4.0
