### ISSUE TITLE
Update on F-Droid

### ISSUE THREAD

**Issue by AdrienChd** [vfsfitvnm/ViMusic#215]
### Steps to reproduce the bug

Download the Vimusic package on F-Droid (https://f-droid.org/packages/it.vfsfitvnm.vimusic/)

### Expected behavior

We should have version 0.4.1

### Actual behavior

Current version is still 0.3.0. 

### ViMusic version

0.3.0

### Android version

11

### Additional information

I don't know what the workflow to update the release on f-droid repos is supposed to be, so my bad if this is already being done (I didn't see that on F-Droid gitlab though).
This would help to solve duplicate issues like #195, if F-Droid suggested to update the app as soon a release is on the air.

**Comment by vfsfitvnm** [comment]
Afaik, the updates on fdroid are out of my control. They just take few days - if this will continue to be a problem, I'll just unpublish it from fdroid

**Comment by AdrienChd** [comment]
Some documentation can be found [here](https://f-droid.org/docs/Update_Processing/), I don't know if there has been a change between 0.3.0 and 0.4.0 in the source repo…

**Comment by vfsfitvnm** [comment]
The matadata is correctly updated (https://github.com/f-droid/fdroiddata/commit/7d14b971189652135e33f16fdf6cc926bf910243)

Please read https://forum.f-droid.org/t/how-long-for-an-app-to-be-available-for-download-once-metadata-are-updated/12740/10.
