### ISSUE TITLE
Please add a contribute option.

### ISSUE THREAD

**Issue by arfanmrafeek** [vfsfitvnm/ViMusic#216]
### Feature description

A button to contribute to your project in about tab. 
For the wonderful work you do.

### Why do you want this feature?

Help you financially viable and it's give you and interest to give time in this project, I know you do give lot of the time on this project, But free not good. I mean, If you are good at something don't give it for free but this project is FOSS, It's good to have contribute option. 

### Advice to remove issue and request option from app.

Some advice, For these things you do for us, And the issue and suggestion option within the app will always bring so many requests, It's better only experts in this field enter the issue entry. 

Other than all, Your work is amazing. 
Thanks for providing such an amazing app.

**Comment by vfsfitvnm** [comment]
I don't think I will ever do this - for like 10$ a month I'd rather not involve money (and all the hassle it brings)

**Comment by vfsfitvnm** [comment]
> Some advice, For these things you do for us, And the issue and suggestion option within the app will always bring so many requests, It's better only experts in this field enter the issue entry.

This idea crossed my mind many times actually. You know,  I got tired of seeing duplicate or low effort requests. But sometimes there are good ideas. 
Also, I need to receive feedback from users: if you want to contribute, please partecipate actively whenever a new issue is opened.

(However, I already know I will close the issue tab sonner or later)
