### ISSUE TITLE
Lockscreen wallpaper 

### ISSUE THREAD

**Issue by fardeen619** [vfsfitvnm/ViMusic#217]
### Steps to reproduce the bug

It's not working 

### Expected behavior

It did nothing i enabled option but nothing happens

### Actual behavior

Can you tell me it is a bug or how it works 

### ViMusic version

4

### Android version

12

**Comment by deepu2** [comment]
Which device are you using? Some devices for eg. Xiaomi doesn't support changing lockscreen wallpapers from music players.

**Comment by fardeen619** [comment]
I am using samsung phone android version 12 and i tried in my other phones too

**Comment by vfsfitvnm** [comment]
Perhaps you also have to enable a system setting, that is _Display > Lockscreen > Show album cover_ in my phone

**Comment by Somraj-234** [comment]
I have same issue. I'm using realme phone and I don't see any option like show album cover

**Comment by Freakinyou** [comment]
Well developer can you add downloading features it would be awesome btw i really like the UI
