### ISSUE TITLE
A link import option

### ISSUE THREAD

**Issue by Jak2k** [vfsfitvnm/ViMusic#22]
### Feature description

I would like to see a simple textbox, where I can past a youtube.com or music.youtube.com. On submit the song, playlist or album should be opened.

Maybe you could build it in the search.

### Why do you want this feature?

It would be easier to open links I copied.

### Additional information

It's already a very good app. I'm almost replacing the offical app with it completely.

**Comment by vfsfitvnm** [comment]
That's definitely feasible, however why the open intent does not fit your use case? Where are you copying the links from?

**Comment by Jak2k** [comment]
Sometimes links aren't recognized as links, then I copy the text.
Currently I have to..
1. Open the link in my browser
2. Share with openwith...
3. Select ViMusic

**Comment by vfsfitvnm** [comment]
Could you provide a video where it doesn't work as expected?

**Comment by Jak2k** [comment]
From such a text-link or how I workaround?

**Comment by vfsfitvnm** [comment]
Well, unless I missed something, the workaround is actually the expected behavior. ViMusic can handle youtube links, in order to do so you must click (or share) a youtube link of course.

**Comment by Jak2k** [comment]
For example: ``

**Comment by vfsfitvnm** [comment]
Yes, it won't open that link. What is supposed to do? That link doesn't contain any video or playlist.

**Comment by Jak2k** [comment]
But this libk isn't clickable. Imagine it's a link to a playlist. Then you would have to copy it.

**Comment by vfsfitvnm** [comment]
`https://music.youtube.com/` is not a link to playlist, hence ViMusic can't open it.
Could you provide a screenrecord so you can show me what's going on?

**Comment by Jak2k** [comment]
You can't click this: `https://music.youtube.com/playlist?list=PL4TSLN9VnhEQDlR5lFf5Y0B_MeE1LwRtc&feature=share`

When I use App with user generated text and without link detection, it's takes to much steps to open the link in the app.

**Comment by vfsfitvnm** [comment]
> When I use App with user generated text and without link detection, it's takes to much steps to open the link in the app.

Yep. Out of curiosity, what's you use case? I expect urls to be shared among social apps (which detect urls)

**Comment by Jak2k** [comment]
In other apps (NewPipe), it works 😔.

**Comment by vfsfitvnm** [comment]
Coming with the next release:

![Screenshot_20220611-170409918](https://user-images.githubusercontent.com/46219656/173193653-0bf915e8-fa5e-4b5f-9496-4e603a28e9b9.jpg)

**Comment by seltix5** [comment]
My use case is to import my own playlist and I do not want to uninstall (disable) YouTube... One input somewhere to manually paste a link and import would be great. Thanks.

**Comment by Jak2k** [comment]
> My use case is to import my own playlist and I do not want to uninstall (disable) YouTube... One input somewhere to manually paste a link and import would be great. Thanks.

It's implememted. Paste it in the search.

**Comment by seltix5** [comment]
> > My use case is to import my own playlist and I do not want to uninstall (disable) YouTube... One input somewhere to manually paste a link and import would be great. Thanks.
> 
> It's implememted. Paste it in the search.

Fantastic! Works great and easy to use but most users would never know about it =p maybe a more descriptive placehold =) thanks!
