### ISSUE TITLE
Can't open a youtube link

### ISSUE THREAD

**Issue by yant0** [vfsfitvnm/ViMusic#220]
### Steps to reproduce the bug

1. Copy this [youtube](https://www.youtube.com/watch?v=fLI3IH3C_Y8) link.
2. Paste it inside the app search bar and press open link
3. Error

### Expected behavior

Open the video

### Actual behavior

Does not open the video

### Screenshots/Screen recordings

![IMGPP_418](https://user-images.githubusercontent.com/80298071/184991554-d5a2d03b-586e-4964-85ac-c5d18a3bb67c.jpg)

![IMGPP_419](https://user-images.githubusercontent.com/80298071/184991964-d605193d-83d6-4ebb-a4d3-0ca2cc896900.jpg)

### ViMusic version

"0.4.1"

### Android version

"Android 11"

### Additional information

I tried opening [this](https://www.youtube.com/watch?v=fLI3IH3C_Y8) and it shows at the video tab. For the link that doesnt show, i can open it in browser without an account and play normally.

Also i did not use vpn. For both apps (browser and vimusic).

**Comment by vfsfitvnm** [comment]
That video is not recognized as music (https://music.youtube.com/watch?v=fLI3IH3C_Y8)

**Comment by yant0** [comment]
Wrong reference 😅 this was the other link mentioned
https://www.youtube.com/watch?v=bLdXapM22Tw
It shows up in the video tab but not for the submitted link

But it sure is not available is music.youtube, is a workaround too much of a hassle to implement a workaround?
