### ISSUE TITLE
Can't edit lyrics or disable it after failed sync attempt

### ISSUE THREAD

**Issue by JustNaturalCake** [vfsfitvnm/ViMusic#221]
### Steps to reproduce the bug

1. Play any song
2. Click the three dots
3. Tap sync lyrics

### Expected behavior

Syncing either works or you should tap the 3 dots again and tap sync lyrics

### Actual behavior

If syncing fails you cant edit or listen to the normal not synced lyrics, you're forced to wait until lyrics are synced then you're able to edit lyrics or listen normally or even turn it off

### ViMusic version

v0.4.1

### Android version

Android 12, One UI 4.1

### Additional information

Some songs seem to work fine but if some songs dont work id like to listen to the lyrics normally instead of the app forcing me to sync lyrics

**Comment by vfsfitvnm** [comment]
The operation fails when an error occurs (e.g. you don't have network connection) - that's why I don't show the menu. However, I realized it may be annoying when the error is out of your control (e.g. the third party provider is having technical issues).
