### ISSUE TITLE
When searching, suggested items 'arrow' appears black

### ISSUE THREAD

**Issue by LupSpie** [vfsfitvnm/ViMusic#224]
### Steps to reproduce the bug

1. Search for a song
2. Suggestion has a fully black arrow to the right

### Expected behavior

Expected it to be a similar colour to previously searched items (aka: the ones with a clock to the left)

### Actual behavior

It appears fully black, even in the PureBlack theme

### Screenshots/Screen recordings

|Light mode|Dark mode|PureBlack|
|--|--|--|
|![Light mode dynamic colors](https://user-images.githubusercontent.com/49603837/185230597-2d13241c-3439-45a7-b558-ea6dcf8e5fbe.png)|![Dark mode dynamic colors](https://user-images.githubusercontent.com/49603837/185230588-3aa7d75c-3d93-414d-a6da-877d0d95dfa6.png)|![Pureblack](https://user-images.githubusercontent.com/49603837/185232337-ad447173-8f24-459d-baf6-537e3824ee81.jpg)|

### ViMusic version

0.4.1

### Android version

Android 7.1.1

**Comment by vfsfitvnm** [comment]
Yup, I forgot to change the color of a couple of icons - I already solved few commits ago
