### ISSUE TITLE
Add a collection of unsorted songs

### ISSUE THREAD

**Issue by SebiderSushi** [vfsfitvnm/ViMusic#227]
### Feature description

Add a collection similar to "Offline" that contains all items from the "Songs" list that are not present in any playlist.

### Why do you want this feature?

When listening in radio mode it can get hard to keep track of recently discovered songs.
Sorting the "Songs" list by "date added" helps, but it can get inconvenient to scroll past any songs from recently added playlists.
An "Unsorted" collection would be helpful to keep track of all the individual songs that were discovered in radio mode, which don't have any convenient way to find as-is. It could be a useful place to remove unwanted songs that radio mode brought up. Once added to a playlist songs would no longer show up in the collection and keep it nice and tidy.

**Comment by vfsfitvnm** [comment]
I don't think this is a valuable feature - it just clobbers the interface in my opinion.
But I understand the reason why you desire this feature (the same applies to #225).
However, I didn't design this application to be a "music manager", where each song has its own place and its existence is always justified. I mean, the whole purpose of this application is playing music, not handling some sort of "music wallet" or whatever you want to call it. Who cares if there's a song you don't like?

(continue in #225)
