### ISSUE TITLE
One more theme option

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#228]
### Feature description

One more theme option i.e. current playing theme
Which sets the theme of current playing song to whole UI until changed 

![Screenshot_2022-08-18-22-52-27-65_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/88180887/185457885-379837b3-d9f6-415f-94cf-f23fbeca7b72.jpg)

### Why do you want this feature?

Sometimes your dynamic theme algorithm produces very unique and best looking theme to the UI

Which user wishes to use it as regular theme

Hence this option will fullfill many customisation requests

**Comment by vfsfitvnm** [comment]
This idea crossed my mind, but honestly it doesn't add much value.
