### ISSUE TITLE
More settings

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#229]
### Feature description

What I would like is a more extensive settings menu. We have all the basic stuff you'd need, but there can always be more. E.g. disabling/enabling mono
audio and crossfade.

### Why do you want this feature?

Honestly, what I really want is for both earbuds to be able to play their own sounds, cause that just makes the music more immersive.

**Comment by vfsfitvnm** [comment]
Not sure what you mean, my pairs of headphones already play in stereo mode

**Comment by MountainFlowers** [comment]
Then it must be a problem with mine

**Comment by vfsfitvnm** [comment]
Yes, you can install the app of your headphones (if there's one) and set the preference you desire.
