### ISSUE TITLE
Importing YouTube-only music (Unofficial uploads/Music that isn't marked properly by the YTM API)

### ISSUE THREAD

**Issue by Jinux-1** [vfsfitvnm/ViMusic#236]
### Feature description

An extension of the videos tab that queries regular youtube or a simple + button somewhere that lets the user paste a link that gets manually added to your library. If not one of these than just some way to add songs only available on YouTube and *not* YouTube Music

### Why do you want this feature?

I listen to a few songs that aren't available on YouTube Music for whatever reason. Examples are [GOOD ENOUGH! - Atsuover](https://www.youtube.com/watch?v=thZqzBtnXCY?t=0) or [Good Morning from OMORI - Jami Lynne](https://www.youtube.com/watch?v=1yIcUg5FyIs?t=0) . Both of these songs are uploaded by their official authors but aren't available under the song or videos tab.

### Additional information

If this feature would require a complete rewrite of the backend i understand if it doesn't get implimented. 
Unrelated but do you guys have a place for donations? Other than the fact i'm missing a few songs (which isnt your guys' fault, I place blame on the youtube music bot that decides what is and isn't music) this app is absolutely amazing and I don't see myself going back to any other app at the moment.

**Comment by vfsfitvnm** [comment]
As you said, doing such thing requires too much work unfortunately. Maybe you can try to contact the publishers of these videos and ask them if they can do something - I found old reviews of people lamenting they couldn't find certain videos on youtube music, but today those videos are available.

> you guys have a place for donations

See https://github.com/vfsfitvnm/ViMusic/issues/216
