### ISSUE TITLE
Android 12 Material design 3 (wallpaper based theming) support

### ISSUE THREAD

**Issue by arysinh** [vfsfitvnm/ViMusic#237]
### Feature description

Add support for android 12 material you wallpaper based theming.
Feature can be accomodated by either :
1. Making the default theme(settings->appearance) apply material design 3 theme if supported or,
2. Adding another option(wallpaper-based) in the theme(settings->appearance) section to apply material design 3 theme.

### Why do you want this feature?

1. Will make the user interface more cohesive with the rest of the Android UI.
2. It is the Latest material design paradigm.

**Comment by arysinh** [comment]
btw, the app is great and VERY usable.

**Comment by vfsfitvnm** [comment]
I don't actually follow the material design guidelines (aka I don't use `material`/`material3` libraries). Also, I think this isn't needed as the `Dynamic` theme is already enough - but I will accept contributions (pull requests).
