### ISSUE TITLE
Automatically change region(or change to Youtube.com) if Youtube Music does not support the region.

### ISSUE THREAD

**Issue by duyvip6a4** [vfsfitvnm/ViMusic#238]
### Feature description

Currently I'm in Vietnam, which Youtube Music is not available in. So I have to use a VPN to switch region to Hong Kong so I can use the app to search for music.

### Why do you want this feature?

So I could be accessible for more people in the world :)

### Additional information

Here it is if I search sth with region being Vietnam
![Screenshot_2022-08-22-07-50-56-13](https://user-images.githubusercontent.com/51393859/185819269-7c8619e7-1551-44cd-8640-40b4a1054c7e.png)

**Comment by vfsfitvnm** [comment]
See #2

**Comment by nateRiver111** [comment]
If you're open to you could use a cloudflare worker as frontend of music.youtube.com to fetch all JSON data and use a piped instance to stream audio data, this successfully will bypass country restrictions.

**Comment by vfsfitvnm** [comment]
I won't do that.
