### ISSUE TITLE
Equalizer not working 

### ISSUE THREAD

**Issue by Sameky** [vfsfitvnm/ViMusic#241]
### Steps to reproduce the bug

1. I click on the equalizer shortcut
2. Shortcut opens normally
3. I apply the configurations 
4. Configurations are applied but make no difference on the sound (no bass boost or equalization whatsoever)

### Expected behavior

1. You should click on the equalizer shortcut
2. Shortcut opens normally
3. You apply the configurations
4. Sound quality should change based on the configurations applied (bass boost, and all sorts of equalization)

### Actual behavior

It just doesn't change the sound quality 

### ViMusic version

0.4.2

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
Can you try another music player app (e.g. retro music player) and see if it works?

**Comment by sandraev** [comment]
It's right, I have the same problem, with the same Android version and the same ViMusic version. So I tried with Retro Music Player (5.8.5), and it worked just perfectly...

**Comment by vfsfitvnm** [comment]
Unfortunately I cannot reproduce on the A12 emulator

**Comment by vfsfitvnm** [comment]
@sandraev Would you try the latest debug build and see if it works?

**Comment by sandraev** [comment]
Yes, I'm going to do it now...

**Comment by sandraev** [comment]
It's OK ! Everything works now perfectly ! Congratulations ! 😉
