### ISSUE TITLE
Voice Search 

### ISSUE THREAD

**Issue by jerryop** [vfsfitvnm/ViMusic#245]
### Feature description

To be able to search by voice.

### Why do you want this feature?

Would be easier for me whiles I'm at work and might be helpful to others.

**Comment by Jak2k** [comment]
I think that would be bad for privacy reasons.

**Comment by jerryop** [comment]
> I think that would be bad for privacy reasons.

Why bad all apps having voice search feature

**Comment by vfsfitvnm** [comment]
Would you add some details so I can understand how this feature should work?

**Comment by Wave6677** [comment]
Hey, not OP here but if I were to assume they're probably asking for a microphone in the search bar that when pressed will transcribe what the users says and searches for it. There is a FOSS library for the voice recognition called VOSK but the practicality of using it inside of this app is questionable at best.

It'd definitely be useful though lol

**Comment by vfsfitvnm** [comment]
I definitely won't add a third party library for such thing.

Aren't keyboards already capable of doing so? Also, I could male the app accessible, so one could technically control the app by voice (as it would a blindless person)

**Comment by z-huang** [comment]
> Would you add some details so I can understand how this feature should work?

I think it's the microphone button that appears in the search bar of YouTube. The implementation document is [here](https://developer.android.com/training/wearables/user-input/voice).

**Comment by vfsfitvnm** [comment]
Thanks for providing the documentation. However, I'm reluctant to implement this feature. I mean, I understand it can be used to search a song (online) by voice, but the user needs his device nearby to tap the icon and select the song to play...

**Comment by jerryop** [comment]
Search by voice is very handy feature in my opinion we should get this feature this will surely enhance user experience

**Comment by Wave6677** [comment]
> Search by voice is very handy feature in my opinion we should get this feature this will surely enhance user experience

Not the dev but I feel like their response to this would be asking for more information. You're being very vague about what you're asking for.
