### ISSUE TITLE
Remove song from playlist

### ISSUE THREAD

**Issue by uggrin** [vfsfitvnm/ViMusic#246]
### Feature description

At the moment there is no way to remove a song from a playlist, which is a very important functionality i think.

### Why do you want this feature?

It makes sense to be able to remove songs from a list

**Comment by vfsfitvnm** [comment]
You can (of course), just long press it and press "remove"

**Comment by uggrin** [comment]
Lol well that's embarrassing... Sorry :) and thanks! The app is great!
