### ISSUE TITLE
Weblate/Crowdin ?

### ISSUE THREAD

**Issue by MXC48** [vfsfitvnm/ViMusic#247]
Hello, I would like to be able to translate the application into my language, to 1 contribute to the project and 2 an experience for me and my loved ones who use it

**Comment by MXC48** [comment]
> Hello, I would like to be able to translate the application into my language, to 1 contribute to the project and 2 an experience for me and my loved ones who use it

So I think that putting the project on weblate or crowdin (even transifex) could facilitate the contribution

**Comment by vfsfitvnm** [comment]
Hi, tracking in #100
