### ISSUE TITLE
Vimusic don't work with tor network 

### ISSUE THREAD

**Issue by Mederim** [vfsfitvnm/ViMusic#248]
### Steps to reproduce the bug

1. Use orbot app and active the vpn mode and select vimusic to be used
2. Use vimusic 

### Expected behavior

Slow loading for songs because the tor network

### Actual behavior

Can't play any song

### Logs

An unknown playback error hás occured

### ViMusic version

0.4.2

### Android version

12

**Comment by vfsfitvnm** [comment]
That's because you can't visit music.youtube.com using tor. I can't do nothing about this.
