### ISSUE TITLE
Remember current playlist queue and current track and position after system reboot or application restart.

### ISSUE THREAD

**Issue by mafrailea** [vfsfitvnm/ViMusic#251]
### Feature description

After the application is restarted or the entire system is rebooted:
- Remember the current play queue.
- Remember the current track being played
- Optionally, remember the time on the current track (useful if you have long tracks in your queue).

### Why do you want this feature?

I usually play long playlists (400+ items) and it's difficult to remember the current song if the application gets closed or you need to reboot your phone after a system upgrade.

**Comment by vfsfitvnm** [comment]
See https://github.com/vfsfitvnm/ViMusic/issues/141

**Comment by mafrailea** [comment]
> See #141
Well, it's not exactly the same.

If you reboot your phone, you lose your current queue and position.

I think the application should be able to remember your current queue and the current track being played.

**Comment by vfsfitvnm** [comment]
Did you enable this option as well? https://github.com/vfsfitvnm/ViMusic/issues/141#issuecomment-1198542366

**Comment by mafrailea** [comment]
Yep, I removed the battery optimizations in "Settings --> Applications --> ViMusic" and even enabled the "Invincible service" setting in the app.

If I close the application from the task menu **while the queue is paused**, the application gets completely closed and the playback controls don't appear in the notification any longer.

Obviously, if I completely reboot the phone, no matter if the queue is playing or paused, it's unable to remember the current queue and position when reopening the application after the reboot.

**Comment by vfsfitvnm** [comment]
> If I close the application from the task menu while the queue is paused, the application gets completely closed and the playback controls don't appear in the notification any longer.

This is expected and it is the desired behavior.  However, is the queue preserved once you open the app again?

> Obviously, if I completely reboot the phone, no matter if the queue is playing or paused, it's unable to remember the current queue and position when reopening the application after the reboot.

I'm pretty sure you are rebooting the device **before** closing the app and dismissing the notification, vimusic gets killed and the queue **can't** be saved.

**Comment by mafrailea** [comment]
> This is expected and it is the desired behavior. However, is the queue preserved once you open the app again?

No, I don't see the queue after restarting the app.
Confirmed with both Fdroid version (v0.4.1) and Github release, v0.4.2
> I'm pretty sure you are rebooting the device **before** closing the app and dismissing the notification; in such case vimusic gets killed and the queue **can't** be saved.
No, I tested once again after closing the app from task list, then rebooting, and queue doesn't get restored.

Let me know if any logs would be useful.

**Comment by mafrailea** [comment]
Forget it, I'm a new user of your app and I didn't notice the option in the app for "Persistent queue".

It works perfectly, the only case that doesn't work is when rebooting the phone without closing the app first, minor nuissance.

Thanks a lot for the patience and sorry for the time taken to reply me, I'm definitely moving from NewPipe to Vimusic for music playing. Kudos!!
