### ISSUE TITLE
Download feature 

### ISSUE THREAD

**Issue by jerryop** [vfsfitvnm/ViMusic#252]
Add download option so we can download songs and stored in offline tab in offline tab it automatically cache songs but in two or three days it automatically cleared.

**Comment by vfsfitvnm** [comment]
#83

**Comment by jerryop** [comment]
Bro you should consider as plan because cache songs is automatically gets cleaned in two three days 🙏

**Comment by vfsfitvnm** [comment]
@jerryop no, it doesn't. You are probably using an app tbe clear it.

**Comment by jerryop** [comment]
No bro I'm not using any cleaner app in many phones ram management is automatically clears cache in a week
