### ISSUE TITLE
Android 13 progress bar

### ISSUE THREAD

**Issue by Elim707** [vfsfitvnm/ViMusic#254]
Would be cool if we have wavy progress bar like android 13 in the music player

**Comment by Elim707** [comment]
'Wavy" progress bar

**Comment by vfsfitvnm** [comment]
It will be part of a major A13 redesign once and if the time will come

**Comment by Elim707** [comment]
> It will be part of a major A13 redesign once and if the time will come

I didn't got u sir can u pls explain properly

**Comment by BluePixel4k** [comment]
> > It will be part of a major A13 redesign once and if the time will come
> 
> I didn't got u sir can u pls explain properly

It's a design decision of Android 13. 
If you have A13, you can already see the waves in the notification:
<img src="https://user-images.githubusercontent.com/77979781/187257278-392e0302-e3a6-4150-bea2-9ac56666cb0d.png" width="300" />

**Comment by mahozad** [comment]
Hi,

I'm doing a self-promotion here :)
Please ignore it if you are not interested.

Would you like to use the [wavy-slider](https://github.com/mahozad/wavy-slider) in your app?

[Demo](https://mahozad.ir/wavy-slider).
