### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by edl2** [vfsfitvnm/ViMusic#257]
Is there a way to contact you other than through github issues?
such as a matrix account, discord, email etc. 
Thank you in advance :)

**Comment by vfsfitvnm** [comment]
No; do you need something?

**Comment by caveman1973** [comment]
I don't know the reason he wants to contact you but what about a donate button in Settings/About?

Maybe a Bitcoin address if you don't want to use conventional methods like PayPal, etc.

**Comment by arfanmrafeek** [comment]
@caveman1973 Even I wish that was available a donation option. But this is his reply check #216
