### ISSUE TITLE
Material You theme

### ISSUE THREAD

**Issue by ItamiWasTaken** [vfsfitvnm/ViMusic#258]
### Feature description

A theme that would follow Material You colors

### Why do you want this feature?

it would allow the app to be a bit more uniform with the OS

**Comment by vfsfitvnm** [comment]
Duplicate of #55

**Comment by ItamiWasTaken** [comment]
ahhh, I see. I didn't see it was a closed issue and I didn't think it would require a complete rework. I'm not a dev, rather just an ordinary user so forgive my lacking request
