### ISSUE TITLE
Equalizer 

### ISSUE THREAD

**Issue by jerryop** [vfsfitvnm/ViMusic#259]
### Steps to reproduce the bug

Not working  

Uploading agniteman-20220828-0001.mp4…

### Expected behavior

Should work

### Actual behavior

Not working 😕 

### ViMusic version

4

### Android version

12

**Comment by jerryop** [comment]
Check video
https://www.veed.io/view/05ae971d-c1aa-4941-9dd5-a6aefa361916?sharingWidget=true

**Comment by vfsfitvnm** [comment]
Duplicate of #241

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/241#issuecomment-1228754710
