### ISSUE TITLE
Profile

### ISSUE THREAD

**Issue by Harimsd** [vfsfitvnm/ViMusic#260]
### Feature description

Please add creating profile option to access playlist

### Why do you want this feature?

I want to use my playlist in different devices

**Comment by NR8124** [comment]
U have option to export the whole db and then import the same in another device/reinstalling app...

**Comment by jerryop** [comment]
I think spotify playlist import feature will be a great if it possible

**Comment by NR8124** [comment]
@jerryop  it Would be better if u open a new issue on your feature request.. rather then commenting on random issues

Also check whether this feature is being already asked or not

**Comment by vfsfitvnm** [comment]
Duplicate of #211 or #97
