### ISSUE TITLE
Icon Themed A12+

### ISSUE THREAD

**Issue by SkyDevstronger** [vfsfitvnm/ViMusic#262]
### Feature description

![Screenshot_20220828-115741~01](https://user-images.githubusercontent.com/97104388/187085977-e97b0e1d-1569-437b-a2f6-dab40cf53e28.png)
The developers are creating their thematic icons of their apps for a12+, I think it's time for vimusic to have its thematic icon.

### Why do you want this feature?

aesthetic improvement

**Comment by vfsfitvnm** [comment]
Will do once google releases the android 13 aosp system image for emulators

**Comment by vfsfitvnm** [comment]
Note to self: https://proandroiddev.com/implement-themed-icons-android-13-d20b89233681

**Comment by vfsfitvnm** [comment]
Transfer to #267
