### ISSUE TITLE
Play a youtube channel's uploads

### ISSUE THREAD

**Issue by visceralchokehold** [vfsfitvnm/ViMusic#263]
Would it be possible to add this feature?
I know its a rather odd one so I understand if you'd rather not implement it! My solution for this problem if searching for a channel and playing all its upload is not possible would be to add an option to add playlists to the "Your playlists" section with a link, since all channel upload playlists are usually hidden.

English is not my first language, so if I wasn't clear please let me know!

**Comment by vfsfitvnm** [comment]
Not possible as "channels" and "uploads" are not a thing for youtube music. There's a shuffle button already, which plays the songs of a given artist
