### ISSUE TITLE
Wi-fi/mobile data cache download

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#264]
### Feature description

Basically, put a button where you can choose if you want to have the songs cached with both wi-fi and mobile data or only wi-fi.

### Why do you want this feature?

I'm in the bus currently and just realized I'm downloading songs by default.

**Comment by vfsfitvnm** [comment]
It doesn't make sense, you still have to download songs if you play them and you didn't listen to them already.
If you don't want to use mobile data, the "Offline" playlist got you covered.
