### ISSUE TITLE
Android 13 buggy notification picture / song cover

### ISSUE THREAD

**Issue by BluePixel4k** [vfsfitvnm/ViMusic#265]
### Steps to reproduce the bug

1. Play a song
2. Look at the notification picture
3. Switch between songs

### Expected behavior

The correct song cover should be displayed.

### Actual behavior

Often the cover of the previous song is displayed. Not the one from the current song.
After starting the app, sometimes no cover is displayed.

### Screenshots/Screen recordings

<img src="https://user-images.githubusercontent.com/77979781/187187919-f0ec07ce-0cc0-4638-9168-5a22e4aa1429.png" width="200" /> <img src="https://user-images.githubusercontent.com/77979781/187187951-5edbf21e-05e7-495d-904b-13ba46e84421.png" width="150" />
<img src="https://user-images.githubusercontent.com/77979781/187187935-a9adb8af-521e-4bd7-bce5-1b01e1c51d63.png" width="200" /> <img src="https://user-images.githubusercontent.com/77979781/187187960-3a480e5f-ce67-46e4-8102-a63cfc1cac51.png" width="150" />

After starting the app, no picture is displayed:
<img src="https://user-images.githubusercontent.com/77979781/187188744-a661029d-fe9d-469a-92fe-1263badddf0b.png" width="200" />

### ViMusic version

0.4.2

### Android version

Android 13

**Comment by vfsfitvnm** [comment]
Transfer to #267
