### ISSUE TITLE
Android 13 - size of thumbnail / song cover in the notification is too low

### ISSUE THREAD

**Issue by BluePixel4k** [vfsfitvnm/ViMusic#266]
### Steps to reproduce the bug

1. Play a song
2. Look at the notification picture

### Expected behavior

A clear picture.

### Actual behavior

The resolution of the thumbnails is too low. It's very pixelated.

### Screenshots/Screen recordings

![resolution A13 Memories](https://user-images.githubusercontent.com/77979781/187192150-73e6f93d-bcea-4326-866c-c0c3dfb015b9.png)

### ViMusic version

0.4.2

### Android version

Android 13

**Comment by vfsfitvnm** [comment]
Transfer to #267
