### ISSUE TITLE
Android 13 support

### ISSUE THREAD

**Issue by vfsfitvnm** [vfsfitvnm/ViMusic#267]
Will do once google releases the android 13 aosp system image for emulators

- [x] #262
- [ ] #265
- [x] #266

**Comment by BluePixel4k** [comment]
So in my Android Studio I can already download the image of the API 33 and start it as an emulator 😃:
<img src="https://user-images.githubusercontent.com/77979781/187209340-ceca8177-26f8-4f6e-8d84-a527f1d8d408.png" width="350" />

**Comment by vfsfitvnm** [comment]
Yes you can, but it's the one with google play services in it. For your interest, google provides the pure aosp images with a certain delay (they are considered less important somehow).

**Comment by BluePixel4k** [comment]
Ok I understand, thanks for your explanation.

**Comment by BluePixel4k** [comment]
I tried out the latest debug apk ([65 - Link](https://github.com/vfsfitvnm/ViMusic/actions/runs/2949093177)) and there the bug #266 seems to be gone. And the bug #265 is a lot better. 
Compered to the latest 0.4.2, the notification layout looks a bit different and tidy.

<img src="https://user-images.githubusercontent.com/77979781/187257278-392e0302-e3a6-4150-bea2-9ac56666cb0d.png" width="400" />

Did you change anything fundamental, since the last release version?

**Comment by vfsfitvnm** [comment]
I think it is due to [this](https://github.com/vfsfitvnm/ViMusic/commit/6dc04cca90acb59da3a88df71b1d2ec2b53a89f7). This is a win-win solution honestly - I don't have to deal with the nonsense changes A13 introduced.

However I'm still looking forward to fix the notification cover mismatch.

**Comment by BluePixel4k** [comment]
Sounds good, can you please publish a new release version for the meantime, so that the app can be used better under A13 again? 

Maybe you can dare to make the A13 changes again, if the function #131 became impertinent, then I think it wouldn't look so empty anymore.

**Comment by BluePixel4k** [comment]
We were happy too early. With the new version v0.4.3 the two bugs (#266 & #265) have not improved for me. 

I have now cloned the app into my Work profile and there the bug #266 no longer occurs. Then I grabbed another debug apk ([63 - Link](https://github.com/vfsfitvnm/ViMusic/actions/runs/2935522475)) and there the bug #266 is also gone. It seems that there is a problem with the database and it is not the API version 33?!

Possibly it is because I have been with ViMusic since almost the first version? Have there been any fundamental changes to the database since launch?

BTW: With the new installation, the problem #59 seems to be gone for me. Up to now it still occurred.

**Comment by BluePixel4k** [comment]
Very strange behavior... I have now opened the app from the Work profile again, after a long break, and now the two bugs, with the notification, are present there too.... 😕

**Comment by vfsfitvnm** [comment]
It just finished building the aosp system image.
Ok.

#266: The debug version worked because of the option _System > Appearance > Show song cover_, which is enabled by default. Without that option, the thumbnail is low res (somehow). You release version has that option disabled.

#265: Reproduced

**Comment by vfsfitvnm** [comment]
#265 Looks like a bug: https://issuetracker.google.com/issues/243778594

**Comment by vfsfitvnm** [comment]
However, how is your notification responsiveness? Mine is pathetic - i.e. I press any button (play, skip or whatever) and the notification gets updated after 5 seconds. Not sure if it's a emulator/system image thing (I hope so)

**Comment by vfsfitvnm** [comment]
Note to self: sometimes the PlayerService has some sort of crash in A13 when destroyed - in fact the process is re-started afterwards (it should not). Other than wasting resources, this will cause the "persistent queue" to not work

**Comment by BluePixel4k** [comment]
> It just finished building the aosp system image.

Awesome 🚀 

> https://github.com/vfsfitvnm/ViMusic/issues/266: The debug version worked because of the option System > Appearance > Show song cover, which is enabled by default. Without that option, the thumbnail is low res (somehow). You release version has that option disabled.

Thx, good to know.

> https://github.com/vfsfitvnm/ViMusic/issues/265 Looks like a bug: https://issuetracker.google.com/issues/243778594

Strange, i don't have that bug with Spotify.

> However, how is your notification responsiveness? Mine is pathetic - i.e. I press any button (play, skip or whatever) and the notification gets updated after 5 seconds. Not sure if it's a emulator/system image thing (I hope so)

For me, the speed is fine. I also think this is an emulator problem.

https://user-images.githubusercontent.com/77979781/187751808-ce86d783-b92a-481e-9c10-67989515188c.mp4

**Comment by vfsfitvnm** [comment]
Would you make a screen record of spotify's notification (when you skip the next song)?

**Comment by BluePixel4k** [comment]
> Would you make a screen record of spotify's notification (when you skip the next song)?

https://user-images.githubusercontent.com/77979781/188261447-27078ebc-c146-4c3a-9aec-55b8f356b5d4.mp4

>>#265 Looks like a bug: https://issuetracker.google.com/issues/243778594
>
>Strange, i don't have that bug with Spotify.

Now I noticed that sometimes, after a restart of the app, the first song also displays a wrong picture in Spotify.
From the next song on, however, the bug disappears.
<img src="https://user-images.githubusercontent.com/77979781/188261513-a14e898d-ae28-4375-a051-2db8d37803b2.png" width="300" />

**Comment by vfsfitvnm** [comment]
Ok, I think it's time to target A13. The bug in https://issuetracker.google.com/issues/243778594 has been fixed, however I will still apply a workaround for A13 devices. Also, to avoid duplicates such as #470, the "Show song cover" will be enabled by default on A13

**Comment by vfsfitvnm** [comment]
This is how it looks like with the workaround (it may rarely display the previous cover and the text always refresh now...)

https://user-images.githubusercontent.com/46219656/196741026-ef89be9d-dfa1-4f0f-a54b-aa97b28deb77.mp4

**Comment by vfsfitvnm** [comment]
Unfortunately it still occurs sometimes, but it's not consistent though.

**Comment by BluePixel4k** [comment]
Thx you for the improvement! Its working a lot better then before. 👍🏼 

> Unfortunately it still occurs sometimes, but it's not consistent though.

Thats true. For me the bug occur most commonly at the startup of the app -> no notification picture displayed.

**Comment by vfsfitvnm** [comment]
> Thats true. For me the bug occur most commonly at the startup of the app -> no notification picture displayed.

Does it still occur to you?! :/

**Comment by BluePixel4k** [comment]
Yes sadly, but not very often. Currently I'm fine with it. :)

**Comment by vfsfitvnm** [comment]
Damn :/ The first song is always displayed fine in the emulator
