### ISSUE TITLE
SoundCloud support?

### ISSUE THREAD

**Issue by mhmdanas** [vfsfitvnm/ViMusic#269]
### Feature description

Add support for [SoundCloud](https://soundcloud.com).

### Why do you want this feature?

Most of my music collection is actually in SoundCloud, and if ViMusic supports SoundCloud, then I would be able to use it to listen to my music on Android. However, I would understand if adding support for websites other than YouTube/YouTube Music is out of scope.

**Comment by vfsfitvnm** [comment]
Yup, it is out of scope. Maybe in the future, if necessary.

**Comment by Jak2k** [comment]
Maybe it would ve possible to make a piece of code which handels youtube and a other for soundcloud and both have the same interface. Then maybe make a dropdown in the search.

**Comment by mhmdanas** [comment]
I'd like to add SoundCloud support in a fork for my personal usage, and I would appreciate pointers on where I should start.
