### ISSUE TITLE
Random music like "Discover weekly" in spotify

### ISSUE THREAD

**Issue by Sweaboy** [vfsfitvnm/ViMusic#270]
### Feature description

There is a feature/ playlist in spotify created by spotify where they add music they though i would love.  

### Why do you want this feature?

Makes the listening experience more vivid

### Additional information

And if you could add google account login as well, it would be perfect

**Comment by vfsfitvnm** [comment]
Not feasible

**Comment by vfsfitvnm** [comment]
#36

**Comment by CollarAndres** [comment]
F, está funciona hubiera Sido muy buena ya que puedes escuchar las canciones sin buscarlas con las listas de reproducción automáticas o recomendadas
