### ISSUE TITLE
Playlist Covers

### ISSUE THREAD

**Issue by poodooroo** [vfsfitvnm/ViMusic#272]
### Feature description

I think it's self explanatory but I just wanna say thank you so much for this amaizing free app 🙏🙏

### Why do you want this feature?

It'd be a cool, customization feature..

**Comment by vfsfitvnm** [comment]
Do you want to set a custom image as playlist cover? If so, I won't do that

**Comment by Jak2k** [comment]
I think setting a song's cover as playlist cover.
