### ISSUE TITLE
Proposition to change license from Apache-2.0 to GPLv3

### ISSUE THREAD

**Issue by PickleNik** [vfsfitvnm/ViMusic#273]
Hello, I'd like to propose to swap the license to a more protective [GPLv3](https://opensource.org/licenses/GPL-3.0) :)

The main motivation for this change is to provide protection against the future distribution of the app in a proprietary form, while at the same time maintaining all of the freedoms to use, change or share the project which are currently in-place.

Some links on GPLv3:
https://www.gnu.org/licenses/quick-guide-gplv3.html
https://choosealicense.com/licenses/gpl-3.0/
https://opensource.org/licenses/GPL-3.0

What's required for the swap to occur:
- [x] All past and current contributors to the codebase agree with the change.
- [x] Replace the main license file with GPLv3.

**Comment by vfsfitvnm** [comment]
Thanks.
I'm the only one who contributed to the codebase - others made changes to external files (https://github.com/vfsfitvnm/ViMusic/graphs/contributors), however let me know if we should notify them as well; I'm already sure they will happily agree with the change.

**Comment by PickleNik** [comment]
<img width="432" alt="Screen Shot 2022-08-31 at 11 45 38 AM" src="https://user-images.githubusercontent.com/31113245/188152526-08650df9-d95f-4f77-9788-109c757aa6ed.png">
