### ISSUE TITLE
Sleep timer don't save the queue

### ISSUE THREAD

**Issue by BluePixel4k** [vfsfitvnm/ViMusic#279]
### Steps to reproduce the bug

1. Play a playlist, a radio or something else
2. Start the sleep timer
3. Wait until the timer expired
4. Open the app and there is no queue anymore

### Expected behavior

The queue and the last played song should be saved (if the setting is active) #35.

### Actual behavior

The queue is lost.

### ViMusic version

0.4.3

### Android version

Android 13

### Additional information

I think the expired timer stops the app and no queue could be saved. It's a known error of this queue implantation #35.

**Comment by vfsfitvnm** [comment]
Yes, this is the intended behavior to be honest. I don't think it makes sense to save the queue if you plan to sleep with it...

**Comment by BluePixel4k** [comment]
Okay I understand, but is there any downside to saving the queue? 
If it is saved, you can decide for yourself if you want to continue listening there next time or if you want to start something new.

**Comment by vfsfitvnm** [comment]
The proper:tm: way to handle this case is pure boilerplate.
Genuinely asking, were you sad to see the queue hasn't been saved or were you just doing bug hunting?

**Comment by BluePixel4k** [comment]
> Genuinely asking, were you sad to see the queue hasn't been saved or were you just doing bug hunting?

Sry, for the late response. 
I wasn't on bug hunting, but looking for new features. So I tested it and wondered / found it pity, why the queue wasn't saved.

**Comment by vfsfitvnm** [comment]
These tests doesn't count actually :stuck_out_tongue_closed_eyes: 
Let's wait for someone who stumbled upon this (for real)

**Comment by BluePixel4k** [comment]
It was real 😁
