### ISSUE TITLE
Check for updates in the settings.

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#282]
### Feature description

I would like it if there was a button in the settings where you could check if there's a button or it tells you automatically when there's an update to the app.

### Why do you want this feature?

F-droid doesn't tell me when the app updates anymore. I downloaded 0.43 6 days after it was released.

**Comment by vfsfitvnm** [comment]
Such feature isn't planned - and even if it was, you would have to wait for the fdroid release.
If you want faster updates, you can add the izzyondroid's repo.

**Comment by MountainFlowers** [comment]
How

**Comment by vfsfitvnm** [comment]
I don't know (I don't use fdroid), but I know it's possible. Also, make sure to backup the database before doing the migration
