### ISSUE TITLE
Scroll to top if shuffle

### ISSUE THREAD

**Issue by MountainFlowers** [vfsfitvnm/ViMusic#283]
### Feature description

When you press the shuffle button, either all the other songs should be shuffled under the currently playing song or the entire playlist is shuffled and the currently playing song is brought up. You shouldn't have to manually scroll up yourself.

![Screenshot_20220905_212806](https://user-images.githubusercontent.com/109493802/188505268-581eed45-c6f6-486c-a374-518218b60416.jpg)
![Screenshot_20220905-212812](https://user-images.githubusercontent.com/109493802/188505271-ad1ff7f8-c8f1-4e96-8e95-948c2dabeb98.jpg)

As you can see by the images, when I press the shuffle button, I am still at the same point in the queue, I don't get brought to the top.

### Why do you want this feature?

It's easier if the song scrolls by itself instead of you doing it, as it gets boring if you have a long playlist.

**Comment by vfsfitvnm** [comment]
Yes, I can certainly make it scroll to the top once shuffled
