### ISSUE TITLE
Some apps such as kwgt or klwp can't detect ViMusic as music player

### ISSUE THREAD

**Issue by dragekk** [vfsfitvnm/ViMusic#285]
### Steps to reproduce the bug

1. Play any music
2. create kwgt widget and add text that displays song name, time or author
3. grant notification permission to kwgt
4. save widget

### Expected behavior

The widget should show the song name, time or author

### Actual behavior

The widget shows nothing

### ViMusic version

v0.4.3

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
Problems with third party (closed source) applications are not problems of mine. You should contact the author(s) of the app having the problem instead
