### ISSUE TITLE
No image

### ISSUE THREAD

**Issue by vhic1** [vfsfitvnm/ViMusic#292]
Images don't show when offline

**Comment by vfsfitvnm** [comment]
It's because they aren't cached yet

**Comment by BluePixel4k** [comment]
Oh I thought, that the thumbnails / covers are also cached. 😦
So then the behavior from #59 is currently normal and not a bug?

**Comment by vfsfitvnm** [comment]
No, they are of course. All he said is "_Images don't show when offline_"

**Comment by BluePixel4k** [comment]
Okay. He didn't really describe it in detail. There is a lot of room for interpretation. 😅

**Comment by vfsfitvnm** [comment]
Yeah, and such low effort descriptions also receive low effort interpretations :3

**Comment by BluePixel4k** [comment]
Haha, yes I can understand that well. 😄
