### ISSUE TITLE
Show time over thumb when scrubbing through a song

### ISSUE THREAD

**Issue by Pentaphon** [vfsfitvnm/ViMusic#294]
### Feature description

When scrubbing through audio, your thumb gets in the way of the current time you've scrubbed to...unless there is some overlay that appears above your thumb when you scrub through a song. Newpipe has such an overlay to make it easy to see what time you are scrubbing to. This is very useful for one handed use and has a pleasing visual effect. Below is Newpipe's implementation. Admittedly, this is even more useful for long content like podcasts but it's still useful for anything that you can scrub through. Players like Blackplayer also have this feature. 

![74095390-9a2db480-4aa4-11ea-8316-61fcc4478928](https://user-images.githubusercontent.com/49374058/189631282-edfe9403-1eb0-4c57-8ef0-75994109c05d.png)

### Why do you want this feature?

Makes it easier to see what time you are scrubbing to during a song by not letting your thumb get in the way of the current time on the left end of the progress slider. 

### Additional information

N/A

**Comment by vfsfitvnm** [comment]
I see what you are saying but I don't think the current implementation is problematic as you can move your thumb upwards/downwards as you drag the progress bar (so the time is always visible):

https://user-images.githubusercontent.com/46219656/189668103-8d9a8bdf-45ac-41fa-8f1b-4c05081e5970.mp4

**Comment by Pentaphon** [comment]
@vfsfitvnm Ah you're right. I do prefer the nice big overlay instead of having to move my thumb to look at the time on the left that is still relatively small, though. I'd still like to request the time overlay because I think it would look good and make scrubbing to another time easier to see (especially for older people) but if you don't think it is worth pursuing, I'll just close my request.

**Comment by vfsfitvnm** [comment]
My point is scrubbing isn't that important: this isn't a video/podcast player, so I'd rather leave things as they are
