### ISSUE TITLE
̶c̶o̶n̶t̶a̶c̶t̶ - Follow up!

### ISSUE THREAD

**Issue by edl2** [vfsfitvnm/ViMusic#299]
Hey, I was earlier asking if there is a way to contact you, you asked why. 

1. instant messaging like matrix/discord would be really nice for bouncing around ideas for the app compared to github issues. 

2. I am the guy from beatbump apk talk. I have been following this project since before it was even public, and I just wanted to thank you so much! The app is amazing and has constantly been improving at an incredible rate, and i wanted to congratulate you :tada: 

edit: your app was just featured in a sam beckman video!!!! expect an influx of users :)
(although he did get a few things wrong, he called this a modded version of the youtube music app)

**Comment by vfsfitvnm** [comment]
Thanks, but as I said here (https://github.com/vfsfitvnm/ViMusic/issues/209), I won't do so :face_exhaling:
