### ISSUE TITLE
Improve thumbnail.

### ISSUE THREAD

**Issue by max5354** [vfsfitvnm/ViMusic#30]
### Feature description

Make now playing screen's thumbnail "gradient" color. Not default solid black color. In short change thumbnail's  "solid black color" to "gradient" color. It will looks awesome with "gradient" color.

### Why do you want this feature?

It's necessary 

### Additional information

![Uploading Screenshot_20220608-225015.jpg…]()``

**Comment by vfsfitvnm** [comment]
> It's necessary

_It's really not._

The UI will improve, eventually. Please do not file similar issues.
