### ISSUE TITLE
Music doesn't stop when app is conpletely closed

### ISSUE THREAD

**Issue by sebsebseb9b** [vfsfitvnm/ViMusic#305]
### Steps to reproduce the bug

1. Play a song
2. Enable task changer
3. Quit vimusic
4. But the music keeps playing

### Expected behavior

It should stop playing music

### Actual behavior

It keeps playing

### ViMusic version

0.4.3

### Android version

12

**Comment by Malopieds** [comment]
duplicate of #153

**Comment by sebsebseb9b** [comment]
Are you going to fix it?

Also can you implement a way to disable recent song listened to from home page. And just show or hide stuff anything

**Comment by vfsfitvnm** [comment]
Not a bug, this is just how a music player should work

**Comment by sebsebseb9b** [comment]
Literally every music player stops wjen you quit.. Every one.. You're the first i ever seen

**Comment by sebsebseb9b** [comment]
It would be great if you could implement the option to do this.

**Comment by sebsebseb9b** [comment]
Others have brought up this issue too. Im not the only one
