### ISSUE TITLE
Region issue

### ISSUE THREAD

**Issue by Aounwick1** [vfsfitvnm/ViMusic#306]
### Steps to reproduce the bug

I downloaded the app and it wasn't working as it should've been 

### Expected behavior

I expected the app to work properly and for me to be able to listen to songs 

### Actual behavior

Instead the app wasnt working until i turned on the vpn when it started working just fine

### Screenshots/Screen recordings

![Screenshot_2022-09-16-04-31-31-253_it vfsfitvnm vimusic](https://user-images.githubusercontent.com/113646402/190526228-719cbff5-1ed9-481f-aace-568aea040219.jpg)

### ViMusic version

0.4.3

### Android version

Android 12

**Comment by Malopieds** [comment]
Does Youtube Music works in your country? Please refer to #111 or #94

**Comment by Aounwick1** [comment]
No it does not
