### ISSUE TITLE
Download to Listen offline 

### ISSUE THREAD

**Issue by MrConqueror** [vfsfitvnm/ViMusic#31]
### Feature description

Can we have this Feature, is it possible?

### Why do you want this feature?

So i never use Spotify anymore lol

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/9#issuecomment-1148620897

What do you think?

**Comment by MrConqueror** [comment]
> [#9 (comment)](https://github.com/vfsfitvnm/ViMusic/issues/9#issuecomment-1148620897)
> 
> What do you think?
Thank You! so we just have to play it to the end, unique. Anyway are you planning on adding categories in search section? and then in the Homepage as well? Something like Spotify you know? idk it's possible.

**Comment by vfsfitvnm** [comment]
Oh, you mean something like a "explore"/"discover" section (https://music.youtube.com/explore). It's possible but not planned - so I'll leave this for contributors. However we are going OT (the original feature request is _Download to Listen offline_), so please close this issue if you are satisfied with the current offline playback system.

Regarding the explore/discover section, you can file another feature request!
