### ISSUE TITLE
Can we have lyrics back? 

### ISSUE THREAD

**Issue by DanteJenzie** [vfsfitvnm/ViMusic#314]
### Feature description

Being able to see lyrics was really cool

### Why do you want this feature?

It was a feature in the previous versions. Don't know why it was removed. Honestly was a crucial feature for me

**Comment by LupSpie** [comment]
> Don't know why it was removed.

Wdym by this? It is still there. The only thing that changed is that you now need to press the album art for it to show up

**Comment by vfsfitvnm** [comment]
Yup

**Comment by DanteJenzie** [comment]
> > Don't know why it was removed.
> 
> Wdym by this? It is still there. The only thing that changed is that you now need to press the album art for it to show up

Thanks, it was different earlier. When I saw lyrics was no longer an option from the 3 dots menu. I thought it was completely removed.
My bad
