### ISSUE TITLE
Cant play any video from youtube

### ISSUE THREAD

**Issue by rancidfrog** [vfsfitvnm/ViMusic#315]
When entering url in search, cant find it
App does not appear in list of apps when sharing url link.
So unable to play any youtube url

**Comment by vfsfitvnm** [comment]
An example url?

**Comment by rancidfrog** [comment]
The errors come frequently, sometimes they work later. Maybe app needs to retry more.
But, I get frequently all kinds of errors,

![](https://i.imgur.com/GwpfPNi.jpg) 

And for the same link it sometimes gives another error,
![](https://i.imgur.com/0JNj840.jpg)

Here are a few with the errors,

https://www.youtube.com/watch?v=_y8CQZs9f8s

https://www.youtube.com/watch?v=AGWdvc9jvos

**Comment by vfsfitvnm** [comment]
Both videos aren't available on YouTube music. There's a closed issue for that, but i can't find it right now
