### ISSUE TITLE
Option to swipe to remove songs from the "Songs" on the home page.

### ISSUE THREAD

**Issue by Fatcakes** [vfsfitvnm/ViMusic#316]
Would be nice. It takes forever to remove them by press and hold. It would be easier if you could multi select but you can't.

**Comment by Malopieds** [comment]
Multi select has already been discussed in #161 and nobody agree on what to do when swiping songs, some wants to enqueue the song, other add it to the queue, etc... Please see #143

**Comment by vfsfitvnm** [comment]
+1 @Malopieds
