### ISSUE TITLE
An unknown playback error has occurred

### ISSUE THREAD

**Issue by TMAstrider** [vfsfitvnm/ViMusic#317]
### Steps to reproduce the bug

1. using a proxy (clash for android)
2. Click on Vimusic app
3. Search any song and play that song will prompt a sentence which is "An unknown playback error has occurred"

### Expected behavior

this should act as youtube music do.  but it works abnormally tho.

### Actual behavior

An error occurred

### Screenshots/Screen recordings

![Screenshot_2022-09-18-21-48-44-774_it vfsfitvnm v](https://user-images.githubusercontent.com/76558255/190910694-2f8d417d-7759-45cb-9640-1c938556cf6a.jpg)

### ViMusic version

0.4.3

### Android version

Android 12

### Additional information

using Redmi K30 Pro Zoom Edition, and I can access youtube music and play the music

**Comment by TMAstrider** [comment]
I've solved it because users in China do not have access to the outside internet, just turn the proxy mode to global which is accessing the internet all through a proxy, then I can shuffle music.

**Comment by vfsfitvnm** [comment]
Yup, IP address problem
