### ISSUE TITLE
Music keeps playing

### ISSUE THREAD

**Issue by sebsebseb9b** [vfsfitvnm/ViMusic#318]
### Steps to reproduce the bug

1.play song
2. Completely quit app
3. But the music keeps playing

### Expected behavior

It sbould stop playing

### Actual behavior

It keeps playing

### ViMusic version

0.4.3

### Android version

Android 12

### Additional information

Hey i commented about this before but i got locked out if my account before i could see what you wrote. Please tell me this is being worked on. 

Also it would be cool to change  the layout  and what shows on main screen. And the playlists should be before the offline and favorites

I am willing to pay you 20 to 30 dollars if you implement this right now. 

My email is seby9b@gmail.com

If you can it would be great

**Comment by sebsebseb9b** [comment]
No joke.. I am willing to pay you if you add these features

**Comment by vfsfitvnm** [comment]
#139 #153 and others
