### ISSUE TITLE
Submit to F-Droid

### ISSUE THREAD

**Issue by offa** [vfsfitvnm/ViMusic#32]
### Feature description

It would be great to get this app through [F-Droid](https://f-droid.org/).

### Why do you want this feature?

F-Droid is *the* app store for open source apps.

### Additional information

- [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy/)
- [How to submit](https://f-droid.org/en/contribute/#submit-applications)

I can provide some helping hands, if you are ok with F-Droid.

**Comment by vfsfitvnm** [comment]
I think we are ready - `v0.1.6` includes `androidx.media3:1.0.0-beta01` which fixed most of the annoying notification bugs that Android 10/11 were facing.

If someone could do the dirty work for me, it would be very appreciated.

**Comment by offa** [comment]
@offa Now as we have the fastlane files, we need a release (at least as far as I know). Once we have it I'm going to file a RFP on F-Droid with the necessary metadata.

**Comment by vfsfitvnm** [comment]
Do you mean a release like [this](https://github.com/vfsfitvnm/ViMusic/releases/tag/v0.1.7) (e.g. a Git tag)?

**Comment by offa** [comment]
Yes, I think a git tag is needed so the build can use a version with metadata.

**Comment by vfsfitvnm** [comment]
I think `v0.1.7` is a good start then? Do I need to do something in particular?

**Comment by offa** [comment]
It doesn't include the fastlane files, I was a little to late for that version :smile:.

A new tag, which includes my commit (eg. current master) would be good. But no need to rush here, create a release whenever it fits and ping me :-)

**Comment by vfsfitvnm** [comment]
Oh, it makes sense 😅 - Thanks, I'll mention you when the next release comes out!

**Comment by offa** [comment]
Perfect, thanks! :-)

**Comment by vfsfitvnm** [comment]
@offa 
I'm ready, `v0.2.0` is out. I also added the missing files @licaon-kter pointed out.

**Comment by offa** [comment]
Thanks, I'm working on the F-Droid submission PR. :+1:

**Comment by licaon-kter** [comment]
@vfsfitvnm afaik non-final Gradle versions are not FOSS, in my recipe we downgrade to 7.4

But that's no solution:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/it.vfsfitvnm.vimusic/app/build.gradle.kts' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'com.android.application']
> Failed to apply plugin 'com.android.internal.version-check'.
   > Minimum supported Gradle version is 7.5-rc-2. Current version is 7.4. If using the gradle wrapper, try editing the distributionUrl in /home/vagrant/build/it.vfsfitvnm.vimusic/gradle/wrapper/gradle-wrapper.properties to gradle-7.5-rc-2-all.zip
```

**Comment by vfsfitvnm** [comment]
@licaon-kter 
Hmm, is this still a thing?
E.g. The download from https://gradle.org/next-steps/?version=7.5-rc-2&format=all also includes the source code (also [this](https://github.com/gradle/gradle/tree/v7.5.0-RC2)?)

**Comment by licaon-kter** [comment]
If it's not FOSS we can't use it.

Anyway, the app builds fine now: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11364/diffs?commit_id=ecee6355ee2368644230b7b6a4f1ef739f72589b
