### ISSUE TITLE
Add option to automatically play sent playlist URL from intent

### ISSUE THREAD

**Issue by mqwec43as** [vfsfitvnm/ViMusic#321]
### Feature description

Vimusic automatically plays sent URL in background without showing UI.

### Why do you want this feature?

If the option were to be adopted, i could use Tasker to send URL to ViMusic and have ViMusic automatically play in background. For the time being i can't have the app play the url automatically since i have to manually press play button.

### Additional information

Additionally, it would be nice if there were option to opt whether user want to shuffle and saved sent playlist URL as well.

**Comment by vfsfitvnm** [comment]
Well, I won't add that as it's an edge case. However, I don't know how such "Tasker" app works, but I think it can click buttons if they have a provided "content description", that is generally used by assistant apps to click buttons for blind people.

**Comment by vfsfitvnm** [comment]
But I'm unsure how complicated it would be to implement, honestly. Opening the url will cause the activity to open as well.
See https://github.com/OxygenCobalt/Auxio/issues/244

**Comment by OxygenCobalt** [comment]
It's generally safer to open the UI since you have interaction and thus more time to initialize without a crash. At least, that's the conclusion I came to. Your app streams though, so you might be able to fully start playback before the 5 second limit in `startForegroundService`.

**Comment by mqwec43as** [comment]
Newpipe had similar topic and was resolved by this pr commit [Newpipe/pull/1018](https://github.com/TeamNewPipe/NewPipe/pull/1018/commits/a1ddc17927186a403eca019aaa420584d39b63bc) would you mind taking a look?

However I'm not sure if this were helpful since I have no programming background and it seems that NewPipe has its own player so it may play a factor as well.

**Comment by mqwec43as** [comment]
> But I'm unsure how complicated it would be to implement, honestly. Opening the url will cause the activity to open as well. See [OxygenCobalt/Auxio#244](https://github.com/OxygenCobalt/Auxio/issues/244)

**Comment by mqwec43as** [comment]
My bad, i'm a bit sleepy

**Comment by vfsfitvnm** [comment]
After a little bit of thinking I decided to not work on this feature because it requires too much code for just saving a tap. Also, none else was interested.
