### ISSUE TITLE
Option to disable the search history

### ISSUE THREAD

**Issue by Bnyro** [vfsfitvnm/ViMusic#324]
### Feature description

Suggested feature: an option to disable the search history completely, which means
1. no new history will be saved
2. the history won't be shown when focusing the search view, even if the history isn't empty/didn't get cleared
3. of course the search history should stay enabled by default!

The option could be located next to https://github.com/vfsfitvnm/ViMusic/commit/b0e53445607081500065f2b24000494b24295af0 in the other settings screen.

### Why do you want this feature?

I personally dislike when an app stores data it wouldn't need without providing an option to prevent it. I often find myself removing the search query manually after each search or deleting the app data it's not possible to clear it. Having an option to disable the search history would save me (and others possibly too) a lot of time.
Apart from that I usually don't need a search history since all the songs I searched and listened to before will automatically be cached and added to my library, therefore searching the same query again seems kinda unnecessary to me. That's an other reason why I'd prefer to not use it, it just takes space search suggestions should fill in my eyes.

### Additional information

Since https://github.com/vfsfitvnm/ViMusic/commit/b0e53445607081500065f2b24000494b24295af0 there is an option to clear the search history, however I think it'd be better to be able to disable the search history completely instead of having to clear it each time.

The previous arguments were only my personal opinion, however, since it would only be an option that is disabled by default, the app's normal behavior wouldn't change and nobody who doesn't want it would be affected.

**Comment by vfsfitvnm** [comment]
Ok, enough people want it. 
Would a combination of "Clear history" and "Pause history" be good? Alternatively we can do as per your implementation, i.e. "Disable history" which also clears the history when enabled.

**Comment by Bnyro** [comment]
> Ok, enough people want it. Would a combination of "Clear history" and "Pause history" be good? Alternatively we can do as per your implementation, i.e. "Disable history" which also clears the history when enabled.

Really happy that it'll be added now, thanks for not forgetting about and reconsidering it <3

I think it would probably be the most intuitive way for users to have both options, one to clear the history and one to pause it temporarily without clearing it (pausing means it will neither add new items to the history nor show them in the search).
I don't know if you want me to, but I could implement it tomorrow symbolically ;) , otherwise feel free to do it yourself :)

Cheers

**Comment by vfsfitvnm** [comment]
If you want to do it because you desire so, sure, go ahead - alternatively I would have done it myself and I would have added you as co-author. However, a new section "SEARCH HISTORY" should be added to `OtherSettings` and it should contain the switch to pause the history and the entry to clear the history as well (moved from `Database Settings`)
