### ISSUE TITLE
Search does not show any results. Is it region locked like the youtube music app?

### ISSUE THREAD

**Issue by 1yusufjee** [vfsfitvnm/ViMusic#330]
### Steps to reproduce the bug

Tried searching for the song I wanted to listen to.

### Expected behavior

Search results should show up for any of the words I searched.

### Actual behavior

Nothing at all happened. The "No results found" message was displayed every time I made a search.

### ViMusic version

0.4.3

### Android version

Android 12

### Additional information

I am trying to use in Pakistan.

**Comment by Malopieds** [comment]
Yes, if youtube music isn't available in your country, you won't be able to use the app.
proxy or any method to bypass it will not be implemented. You can still use a vpn to bypass restrictions.

**Comment by vfsfitvnm** [comment]
See #2

**Comment by vfsfitvnm** [comment]
I must find a way to tell the user youtube music isn't available in his country, there are too many issues about this
