### ISSUE TITLE
Investigate Innertube as NewpipeExtractor alternative?

### ISSUE THREAD

**Issue by Pentaphon** [vfsfitvnm/ViMusic#334]
### Feature description

The [Music app](https://github.com/z-huang/music/releases/tag/v0.4.0) has moved to Innertube and the benefits are:

>In this version, we are saying goodbye to NewPipe Extractor and introducing a new library: Innertube! This change makes more powerful features possible! The primary updates are as follows:

- Browse everything as in YouTube Music
- New home page to browse suggestions and find new music releases https://github.com/z-huang/music/issues/43 https://github.com/z-huang/music/issues/68 https://github.com/z-huang/music/issues/124
- Search result summary tab
- Loading stream is faster

If all of these are viable, it may be worth pursuing Innertube over NewpipeExtractor since the latter is more for Youtube videos rather than Youtube Music.

### Why do you want this feature?

Innertube seems to be able to do more than NewpipeExtractor for Youtube Music and it might make ViMusic the kind of open source Youtube Music alternative people are excited to get.

**Comment by z-huang** [comment]
[Music](https://github.com/z-huang/music)'s innertube library is based on ViMusic's youtube music library. Also, ViMusic isn't using NewPipe Extractor.

**Comment by Pentaphon** [comment]
> [Music](https://github.com/z-huang/music)'s innertube library is based on ViMusic's youtube music library. Also, ViMusic isn't using NewPipe Extractor.

Are you saying ViMusic does not use Innertube?

**Comment by z-huang** [comment]
Technically, both Music's innertube library and ViMusic's youtube music library are using YouTube's private API, and this API is also called innertube in YT's internal code.

**Comment by Pentaphon** [comment]
Ah, I wasn't aware. Closing this issue then. Thanks for letting me know.

**Comment by vfsfitvnm** [comment]
I'm going to rename the `youtube-music` module to `innertube` since it's more precise :)

**Comment by ARBoyGo** [comment]
https://hyperpipe.surge.sh/

This is a YouTube music client based on both api YouTube Music api and piped

`This message is just for reference incase you want to make it truly privacy friendly. Or maybe someone will do in the future, Who knows? `
