### ISSUE TITLE
Suggestion for Playlist 

### ISSUE THREAD

**Issue by Ravan9996** [vfsfitvnm/ViMusic#338]
### Feature description

Can you please add a way to import my youtube music playlist to Vimusic

### Why do you want this feature?

Its hard and time consuming to creating a playlist from scratch. A way to get my old playlist there would be nice.

**Comment by vfsfitvnm** [comment]
You can already do it

**Comment by Ravan9996** [comment]
Is there any guide or something?, I am not able to find the option.
