### ISSUE TITLE
Like a song via the status bar

### ISSUE THREAD

**Issue by BluePixel4k** [vfsfitvnm/ViMusic#34]
### Feature description

It would be handy if there was an option to be able to like a song via the status bar.

For example:
<img src="https://user-images.githubusercontent.com/77979781/173181080-c5828c21-83c9-49cf-b717-633a8a085b14.png" width="300" />

### Why do you want this feature?

When you use the radio function, you sometimes discover new songs that you want to save quickly.

### Additional information

BTW: Awesome App! Thank you

**Comment by vfsfitvnm** [comment]
Yup, that's something I'll definitely do - I'll add a toggle for that

**Comment by vfsfitvnm** [comment]
Unfortunately I can't do it right now because of https://github.com/androidx/media/issues/82, however next `androidx.media3` release should arrive soon.

**Comment by vfsfitvnm** [comment]
`androidx.media3` got a new update, but unfortunately we are not there yet: I don't know how to invalidate the notification (see https://github.com/androidx/media/issues/33). The approach I just tried is laggy. 

Relying in `androidx.media3` was probably a mistake, I feel bamboozled lol... It's definitely an improvement, but in practice I ended up writing the same amount of code, plus there are notification bugs...

**Comment by BluePixel4k** [comment]
It's a pity that the function is not yet included in `androidx.media3`. 
But thanks for the info!

**Comment by vfsfitvnm** [comment]
Closing in favor of #131
