### ISSUE TITLE
SSLHandshakeException while searching

### ISSUE THREAD

**Issue by Henry-Hiles** [vfsfitvnm/ViMusic#344]
### Steps to reproduce the bug

1. Open the app
2. Search something

### Expected behavior

I should get search results

### Actual behavior

An error occurs:

![Screenshot_20220926-224729545 (1)](https://user-images.githubusercontent.com/71790868/192420037-88d55bad-177e-472a-9253-94d67385a5ae.jpg)

### Screenshots/Screen recordings

![Screenshot_20220926-224729545 (1)](https://user-images.githubusercontent.com/71790868/192420037-88d55bad-177e-472a-9253-94d67385a5ae.jpg)

### ViMusic version

0.4.3

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
Duplicate of #325

**Comment by Henry-Hiles** [comment]
> Duplicate of #325

No, youtube music is available in my country, I live in Canada.

**Comment by Henry-Hiles** [comment]
Also, mine is a different error, correct?

**Comment by vfsfitvnm** [comment]
Ops, sorry!
I don't know what the cause it. Other than a `ktor` bug, given it is a SSL thing I think there's an issue with the certificates your device has installed.

**Comment by Henry-Hiles** [comment]
Yep, that seems to be the issue, thanks!
