### ISSUE TITLE
Home page recommendation 

### ISSUE THREAD

**Issue by piyush-software** [vfsfitvnm/ViMusic#346]
### Feature description

The app has currently no home page music so, introduce home page music recommendations like YouTube music ,Spotify, jio savan or any other music apps

### Why do you want this feature?

Due to not home page recommendation I have to search all music whenever I want to listen music

### Additional information

One with recommendation is blackhole music and other is  vimusic 
![Screenshot_20220927-163027](https://user-images.githubusercontent.com/85888663/192510255-6b2d5f3d-99cb-4810-bbb7-3160a8711834.png)
![Screenshot_20220927-163353](https://user-images.githubusercontent.com/85888663/192510268-718f36c2-85c8-4e95-a7e2-0aef2fe533c6.png)

**Comment by vfsfitvnm** [comment]
Tracking in #172
