### ISSUE TITLE
Import playlist 

### ISSUE THREAD

**Issue by peruca14** [vfsfitvnm/ViMusic#348]
### Feature description

Copy link from YouTube of a playlist and import then

### Why do you want this feature?

It's more comfortable

### Additional information

Also a good function could be put your account to have your own recommendations from YouTube

**Comment by Malopieds** [comment]
You can already do that.
Click on a playlist url, it will redirect you to ViMusic if no youtube/youtube music version is install, click on the three dots => import.

**Comment by ruben-hude** [comment]
> You can already do that.
> Click on a playlist url, it will redirect you to ViMusic if no youtube/youtube music version is install, click on the three dots => import.

It is just opening the link in my browser for my part
It would be nice to have a button to do this, having to open a link from another app and making sure it's not opening yet another app is not convenient at all

**Comment by neekt** [comment]
> You can already do that.
> Click on a playlist url, it will redirect you to ViMusic if no youtube/youtube music version is install, click on the three dots => import.

Except it doesn't. In my case, YouTube links open in NewPipe, which is exactly where I want YouTube videos to open.

It's also not what's being requested here, so I'm not sure why it's been given the `invalid` label. The request is specifically asking for link copy and paste functionality, which does not currently exist in the app. If there's no intention of implementing it, `wontfix` seems more appropriate.

**Comment by leira** [comment]
I think a middle ground is just to show ViMusic in the "Share" list of apps from either browser or YouTube/NewPipe app. I don't see ViMusic in the Share list at the moment. I do see NewPipe in the list.

BTW, does ViMusic support arbitrary YouTube playlist? It doesn't seem so. Some playlist doesn't show any video or only some video, some playlist couldn't even be opened. Is this a deliberate choice?
