### ISSUE TITLE
Play next feature

### ISSUE THREAD

**Issue by Echolazy** [vfsfitvnm/ViMusic#349]
### Feature description

Can you add "play next"  feature? When you're playing music and want to play this music next, you will click a button on the side of the music and select "play next". I think it's so useful. By the way, thank you for this app, very nice app without annoying ads haha. That's what I want the most on this app.

### Why do you want this feature?

Because I can't choose what I want to play next.

### Additional information

![orca-image--574754273](https://user-images.githubusercontent.com/114549730/192677714-9c6457da-853c-4f32-9dd3-2e650eccbffa.jpeg)

**Comment by vfsfitvnm** [comment]
Just long press the song to show the menu

**Comment by Malopieds** [comment]
You can long press on a song and then select "play next"
