### ISSUE TITLE
Some albums won't show upon searching(exam

### ISSUE THREAD

**Issue by luffy009-b** [vfsfitvnm/ViMusic#352]
### Steps to reproduce the bug

Example..
Search J.Cole's Album 4 your Eyes  only..it doesn't show up

### Expected behavior

Should have listed the songs or the album

### Actual behavior

Shows other albums fine

### ViMusic version

0.4.3

### Android version

12

**Comment by vfsfitvnm** [comment]
🤷‍♂️

![Screenshot_20220929-072112664](https://user-images.githubusercontent.com/46219656/192945617-d60d99e6-24e4-4b14-b55e-0a013946016f.jpg)
