### ISSUE TITLE
Support Realme Real HD Sound

### ISSUE THREAD

**Issue by eeriemyxi** [vfsfitvnm/ViMusic#353]
### Steps to reproduce the bug

Go to app settings > Player & Audio > Equalizer > Try turning your Real HD Sound by Realme & Dirac on and then turn it off. You shouldn't notice a difference.

### Expected behavior

The audio enhancements to actually work, like it does on Spotify.

### Actual behavior

Everything appeared to be alright when I first downloaded the application, with the exception of the native equalizer's malfunction. When I played one of my favorite songs, I became quite aware of the audio's difference from Spotify. The music sounded the same whether I turned the equalization on or off when I accessed the equalizer in this app's settings and checked it out.

I believe the problem can be resolved with a custom in-app audio equalization implementation (or fix the bug).

### ViMusic version

0.4.3

### Android version

Android 11

### Additional information

Phone: RMX1971, 11th version of Android

**Comment by vfsfitvnm** [comment]
Unfortunately, this is something I can't fix. I follow the official documentation already when it comes to enabling/disabling the equalizer effects.

I'm marking this as enhancement because Realme didn't follow the guidelines. Contributions are welcome.

**Comment by vfsfitvnm** [comment]
https://c.realme.com/in/post-details/1289567790180597760
https://c.realme.com/in/post-details/1255057407571132416
https://c.realme.com/in/post-details/1123599252304429056
https://r.nf/r/Realme/comments/jda9f2/why_is_real_sensaround_on_realme_6_such_a_useless/
https://r.nf/r/Realme/comments/i7pswr/has_anyone_noticed_that_the_inbuilt_equalizer_on/

> Hey, the Real Original Sound Technology will work only with Music players and platforms like Gaana, JioSaavn and others. It will not work with Video Platforms like YouTube. 

It looks like it's the vendor who decides whether enable its equalizer for a certain app or not, so no action can be taken.
