### ISSUE TITLE
Sort playlist items (by date added, by title...)

### ISSUE THREAD

**Issue by jumeny** [vfsfitvnm/ViMusic#355]
### Feature description

Add an option to automatically sort items in the playlist (by date added, by title ..)

### Why do you want this feature?

It would greatly improve the user experience (or so I thought).

**Comment by vfsfitvnm** [comment]
> Add an image of your liking as playlist cover

Won't do

> Remove one feature where choosing the previous song in queue cause

I don't understand what you are referring to

Renaming issue to:
> Add an option to automatically sort items in the playlist (by date added, by title ..)

**Comment by vfsfitvnm** [comment]
After a little bit of thinking, I decided to not include any sorting options to playlist.
