### ISSUE TITLE
Like music from search results

### ISSUE THREAD

**Issue by AHayBagPant** [vfsfitvnm/ViMusic#356]
### Feature description

When you search for a music in the search bar, you have to play the song to tap on the heart or assign it to a playlist. The feature I want is swiping or tap-holding the search result to add it to a playlist or add it to favorites.

### Why do you want this feature?

Easier to mark my music in this app after I listen to it on YouTube or after I Shazam it. It is faster and not need to pause my music on the other app just to add the same song on Vimusic.

**Comment by vfsfitvnm** [comment]
Long press -> Add to playlist -> Favorites :)
