### ISSUE TITLE
Playback speed 

### ISSUE THREAD

**Issue by jerryop** [vfsfitvnm/ViMusic#357]
### Feature description

Can we get playback speed feature to adjust the speed of the song

### Why do you want this feature?

Can we get playback speed feature to change the speed of the song. If you think it's useful then implement :)

### Additional information

![Screenshot_20221002-133251](https://user-images.githubusercontent.com/72891716/193444301-f26c9d77-37b5-4be5-b52d-b451a1af5a4f.png)

**Comment by vfsfitvnm** [comment]
Nah, I don't think I will add this.

**Comment by arfanmrafeek** [comment]
@vfsfitvnm I think, Listening some song in speed/slowed is trend and it has different feeling and Emotions. 

@jerryop BTW, You are using Blackhole, It's good app but updation is slow, It has some features that Vi music doesn't have, But to be honest, Vi Music is clear and easy navigation, BlackHole is fully unfinished look. UI for ViMusic, BTW, I use both app, Majority ViMusic.

**Comment by jerryop** [comment]
> @vfsfitvnm I think, Listening some song in speed/slowed is trend and it has different feeling and Emotions.
> 
> @jerryop BTW, You are using Blackhole, It's good app but updation is slow, It has some features that Vi music doesn't have, But to be honest, Vi Music is clear and easy navigation, BlackHole is fully unfinished look. UI for ViMusic, BTW, I use both app, Majority ViMusic.

I use blackhole for download songs becoz vimusic doesn't have that feature
