### ISSUE TITLE
Rearrange songs in favorite section

### ISSUE THREAD

**Issue by tampos4** [vfsfitvnm/ViMusic#358]
### Steps to reproduce the bug

1. Mark some songs as Favorites
2. Open Favorites Section
3. Try to arrange songs

### Expected behavior

Just like in Playlists one should be able to re arrange favorite songs

### Actual behavior

Unable to arrange favorite songs

### ViMusic version

0.4.3

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
Tracking in #172
