### ISSUE TITLE
Debug apk installation 

### ISSUE THREAD

**Issue by NeeRaj-2401** [vfsfitvnm/ViMusic#369]
Why do we have to uninstall the previous debug apk before installing the new one? 
Cause there is no such case with [Z-huang/music](https://github.com/z-huang/music)

**Comment by vfsfitvnm** [comment]
Probably because you previously built the debug apk yourself; the CI just uses a different signing key - so just stick with one (either your manual build or the CI) and you will be fine

**Comment by NeeRaj-2401** [comment]
@vfsfitvnm  But i also tried by only downloading by CI and install but still its showing 
![Screenshot_2022-10-06-17-43-13-30_e5d3893ac03954c6bb675ef2555b879b](https://user-images.githubusercontent.com/88180887/194309654-b29ab36f-0fb8-48c3-bcfc-7b592aed8cdf.jpg)
Until i delete the existing debug application and then try to install the recently downloaded from the same CI

**Comment by vfsfitvnm** [comment]
Would you install it via `adb`? So it shows you the error

**Comment by NeeRaj-2401** [comment]
> Would you install it via `adb`? 

No

**Comment by NeeRaj-2401** [comment]
> Would you install it via `adb`? 

i will try this and report u back soon

**Comment by NeeRaj-2401** [comment]
@vfsfitvnm again i tried the latest build under actions tab and tried installing
![image](https://user-images.githubusercontent.com/88180887/194328866-5667d148-de69-4a38-9cfe-a2caec54e3bb.png)

**Comment by vfsfitvnm** [comment]
Oh, you are right.

**Comment by vfsfitvnm** [comment]
Uhm, I honestly don't know why it happens and I can't find anything searching online

**Comment by NeeRaj-2401** [comment]
This is not the case with z-huang/music so i think we should see his CI or talk to him regarding this

**Comment by NeeRaj-2401** [comment]
Also i need to mention that i tried z-huang/music in nox player android emulator so the debug.apk installed upon the already existing one but when i tried the same on my phone then i m facing the same issue with zhuang/music too.

**Comment by vfsfitvnm** [comment]
Oh, I guess it's how things should work then...

**Comment by vfsfitvnm** [comment]
So, the only solution I can think of is letting the CI generate and cache the same key somewhere. However I don't have the patience or will to understand how to make this work.

**Comment by z-huang** [comment]
@vfsfitvnm [for reference](https://github.com/z-huang/music/commit/6586ff3ce1a145f42fd8d0bb8f731aa2706c770b)

**Comment by NeeRaj-2401** [comment]
@vfsfitvnm  Here is another [Reference](https://github.com/libre-tube/LibreTube/pull/1639) for you from libretube-debug apk signing
