### ISSUE TITLE
"This song cannot be played due to server restrictions" when trying to play some songs.

### ISSUE THREAD

**Issue by matchboxbananasynergy** [vfsfitvnm/ViMusic#376]
### Steps to reproduce the bug

1. Search for songs like System of a Down's "Fuck the System" (https://music.youtube.com/watch?v=RST4ExJTRH4).
2. The song doesn't play, and you get a message that says "This song cannot be played due to server restrictions" on the top of the album art.

### Expected behavior

The song should play.

### Actual behavior

The song never plays and the above error is shown.

### ViMusic version

0.4.3

### Android version

13

**Comment by vfsfitvnm** [comment]
This is not a bug, some songs cannot be played because they require age verification.

**Comment by vfsfitvnm** [comment]
Piped or similar can be used as a workaround, however they don't return important data I need (format, loudness etc) so I don't use them when I can't retrieve such data in other ways

**Comment by vfsfitvnm** [comment]
I made a small change and now that song can be played :)

**Comment by vfsfitvnm** [comment]
:yum: 

<img src="https://user-images.githubusercontent.com/46219656/194764250-af4c03f3-5336-40ee-9ce8-e244dcd68c2c.jpg" width="30%"/>

**Comment by vfsfitvnm** [comment]
Yes, these are new changes. That behavior was indeed expected, however I figured out I was missing a parameter to bypass such restriction on _some_ videos.
