### ISSUE TITLE
Cast 

### ISSUE THREAD

**Issue by owencz1998** [vfsfitvnm/ViMusic#38]
Able to cast to Google , alexa and (ect)if possible 😄

**Comment by vfsfitvnm** [comment]
Thanks for opening this issue.

Unfortunately you ignored the template, but there's another reason why I'm closing this issue.

It looks like casting requires `com.google.android.gms:play-services-cast-framework`, which is closed sourced. But even if it wasn't, ViMusic will **never** deal with any of those spywares :+1: .

**Comment by owencz1998** [comment]
Sorry the template wasn't working for me for some reason I'll try and redownload github and no worries mate 🤟

**Comment by dommy1985** [comment]
Hi sorry if I ask again but I'm not well understood why you won't add Chromecast feature? Why is a problem that Google lib is  closed source ?

**Comment by Jak2k** [comment]
> Hi sorry if I ask again but I'm not well understood why you won't add Chromecast feature? Why is a problem that Google lib is closed source ?

It a problem because then would be code in the app, nobody knows what it really does.
