### ISSUE TITLE
Support YouTube Music Korea

### ISSUE THREAD

**Issue by buranden** [vfsfitvnm/ViMusic#383]
Searching for songs always display no results despite the fact that I am currently in South Korea, where YouTube Music is now supported. Albums, artists, and playlists show up, but clicking on them also does not show any songs.

**Comment by vfsfitvnm** [comment]
Are you using a VPN?

**Comment by buranden** [comment]
No. I'm staying in South Korea for the time being. I don't really want to use a VPN every time I open up the app.

**Comment by vfsfitvnm** [comment]
That's fine: if youtube music is available in your country, a VPN is not needed then. However some users had problem because of they were using a VPN.

I don't know how to help, really. Can you visit https://music.youtube.com and browse things correctly? Also, would you try https://github.com/z-huang/music and see if it works?

**Comment by buranden** [comment]
@vfsfitvnm the website works fine without any problems but I have tried the other app you recommended and that has the same problems as ViMusic. I'm guessing something about YouTube Music Korea just doesn't mesh well with apps. I'll try using a VPN then.

**Comment by vfsfitvnm** [comment]
I think youtube music korea has additional mandatory parameters I have to fulfill when setting up a network request. Unfortunately I cannot verify that with ease (as I'm not in korea). If you know how to use the network inspector of your web browser, then it's like a 10 minutes thing.

**Comment by vfsfitvnm** [comment]
Oh, look at this: https://github.com/Shabinder/SpotiFlyer/issues/1027#issuecomment-1203412530

Do you confirm? If so, there's nothing I can do!

**Comment by buranden** [comment]
Oh. That would probably explain it. I've always used the premium version. Okay yeah, well thank you for looking into it though!

**Comment by vfsfitvnm** [comment]
That's it then! There's nothing I can do unfortunately
