### ISSUE TITLE
Cache SD-Card

### ISSUE THREAD

**Issue by siggi1984** [vfsfitvnm/ViMusic#384]
### Feature description

Would it be possible to move the cache to the SD card.

### Why do you want this feature?

For people where the cell phone storage space is not so high.

### Additional information

Otherwise, the new version is really cool.

Keep it up.

**Comment by vfsfitvnm** [comment]
This is a good question - it may be possible indeed - but I honestly don't think I will implement it. The effort would not be worth in my opinion.

**Comment by Jak2k** [comment]
It would definitely be worth it.

**Comment by Jak2k** [comment]
I don't have much space in my phone, so I need it. Just only a setting, where I can set a position with the Storage-Access-Framework, and with a default-cach fallback would be great.

**Comment by CasparNuel** [comment]
@matchboxbananasynergy @vfsfitvnm I disagree that SD-Card support is a thing of the past.

I currently use ViMusic on both my smartphone and my FiiO M16 music player.

The ViMusic app is perfect, but the handling of cache is frustrating at best.

You can't manually add "offline available" songs, so you have to hope that all the songs in your song overview are cached if you'll be offline for a while (e.g. a hike, a vacation where your dataplan is not accessible, daily commute with a limited access to lte and/or internet ...).

I have also noticed that android (and whatever tweaks my smartphone vendor added) can be very careless about internal cache. It has happened more than once that I open the ViMusic app and that the last few songs I listened to the day before are not available the morning after.

For my M16 it's a completely different story. FiiO is not aggressive on internal cache, but the 64gb of internal memory is limiting -- especially considering I already have my own purchased records on there. I do however have a 1TB sd card in there that ViMusic sadly can't make use of.

**Comment by junior-aghosh** [comment]
Well it all boils down to personal preference. I am using motorola and I prefer Vimusic the way it is and adding the songs in cache for later use is something that I have never came across and find this extremely useful, although I understand running a system wide storage/cache clean will wipe out the songs but I usually whitelist Vimusic.
Nevertheless it's 2022 the days of saving the songs in sd cards are long gone and most phones now a days don't even have the support

**Comment by much-doge** [comment]
@Alliba @Jak2k I have a solution for those who have root with Magisk,

You need to install fbind magisk module. 
https://github.com/VR-25/fbind

Open your vimusic app, backup the database then clear data from android app settings

Add these lines to fbind config file (use file manager that can explore root directory)
fbind config file is located at /data/adb/vr25/fbind-data/config.txt

add the line: bind_mount /storage/9016-4EF8/data/data/it.vfsfitvnm.vimusic data/data/it.vfsfitvnm.vimusic

REPLACE 9016-4EF8 with your sdcard name

Save the file, then reboot

The data directory of vimusic is now located in sdcard, restore your database backup, done


That being said, its sad not having the option, many MODERN apps still offer storing cache on sdcard such as RedReader, AntennaPod, Osmand, etc.

**Comment by siggi1984** [comment]
I close it. Nothing seems to happen here anymore anyway.
