### ISSUE TITLE
Crash when search result has duplicate items

### ISSUE THREAD

**Issue by jojobozo** [vfsfitvnm/ViMusic#387]
### Steps to reproduce the bug

Go to ViMusic and search for 3500 and the app will crash

### Expected behavior

It shouldn't crash

### Actual behavior

It crashed

### ViMusic version

0.5.0

### Android version

Android 13

**Comment by vfsfitvnm** [comment]
<img src="https://user-images.githubusercontent.com/46219656/194764892-6613a240-a7ac-4da7-afa4-7a1684875dd5.png" width="30%"/>

Can't reproduce. Would you grab the `logcat`?

**Comment by jojobozo** [comment]
> <img alt="" width="30%" src="https://user-images.githubusercontent.com/46219656/194764892-6613a240-a7ac-4da7-afa4-7a1684875dd5.png">
> 
> Can't reproduce. Would you grab the `logcat`?

Just tried to use a VPN and it worked, connect to France using VPN and it'll crash
