### ISSUE TITLE
Search in playlist 

### ISSUE THREAD

**Issue by owencz1998** [vfsfitvnm/ViMusic#39]
### Feature description

Able to search for a song that are in your playlist.

### Why do you want this feature?

Helpful for finding a song in you playlist if you have a loads of songs.

**Comment by vfsfitvnm** [comment]
Yep, a filter feature is something I'm gonna implement sooner or later

**Comment by vfsfitvnm** [comment]
Tracking in #172.

I will introduce a separate tab in the search screen (instead of the playlist screen)
