### ISSUE TITLE
One Handed and RTL Supported Nav

### ISSUE THREAD

**Issue by VedxP** [vfsfitvnm/ViMusic#394]
### Feature description

1. It would be pretty useful if there's an option in the settings to toggle the Navigation bar from Left side to Right side.

>Which would look something like this after toggling:

<details>
<summary>Show/Hide</summary>

![RTL](https://user-images.githubusercontent.com/87353286/194795770-df35e2c1-930d-49ba-b806-2d8c181d7636.jpg)

</details>

---

3. And another option to toggle the Navigation bar for One Handed Use.

>Which would look something like this after toggling:

<details>
<summary>Show/Hide</summary>

![One Handed](https://user-images.githubusercontent.com/87353286/194795826-36e1521f-5e38-4bb4-9b12-6265557a7c12.jpg)

</details>

### Why do you want this feature?

1. RTL Support Would be really helpful for who are Right Handed as default Navigation Bar is always in Left side.

2. Shifting items in Navigation bar a little bottom would be helpful for One Handed Usage.

**Comment by LupSpie** [comment]
> 1. It would be pretty useful if there's an option in the settings to toggle the Navigation bar from Left side to Right side.

I actually remember this being discussed as a possibility before the redesign rolled out. Personally I think this is a great idea.

**Comment by VedxP** [comment]
> 

Nice, implementing gestures would work perfect.

**Comment by Fatcakes** [comment]
@vfsfitvnm if you put it at the bottom the player window will stack on top of it correct? That should look slick.

**Comment by vfsfitvnm** [comment]
Tracking in #398
