### ISSUE TITLE
Make persistent queue feature less disruptive

### ISSUE THREAD

**Issue by PassionateG1t** [vfsfitvnm/ViMusic#396]
### Feature description

When starting the app, instead of fully opening the player screen,  leave the player minimized.

### Why do you want this feature?

Persistent queue is a nice feature, yet when starting the app I don't particularly want to *immediately* continue playing what I was listening to so it's very disruptive seeing the player pop up suddenly (especially that it takes couple of moments before doing so). Keeping it minimized seems like a wiser option because you could still resume the player eitherway.

### Additional information

BTW I never got to congratulate you on supassing 1k stars 🥳

**Comment by vfsfitvnm** [comment]
Good spot!
