### ISSUE TITLE
Relatively Adjust Font Size of Titles

### ISSUE THREAD

**Issue by PassionateG1t** [vfsfitvnm/ViMusic#397]
### Feature description

(Don't know the feasibility of this but) adjusting the font size of titles (playlist, artist or album) in relation to how many characters there are (to a certain extent of course). So the more characters there are, the smaller the font will be. 

### Why do you want this feature?

The design is nice but the side bar takes some space and the font size is so big which doesn't give much space for playlist and album titles and artist names (Refer to screenshot).

In case such feature isn't possible, I bet there are alternatives to it.

### Additional information

![Screenshot](https://user-images.githubusercontent.com/107609269/194817295-dae20a15-c7f2-41f7-9794-a166f38527c1.jpg)

**Comment by vfsfitvnm** [comment]
Unfortunately it's not possible yet. Jetpack compose is working on this (same as #278), so I think it will be possible soon. However, I won't make the titles auto resizing, but auto scrolling.
