### ISSUE TITLE
Sort broken

### ISSUE THREAD

**Issue by yant0** [vfsfitvnm/ViMusic#399]
### Steps to reproduce the bug

1. Add album / artist
2. Go back to library
3. See bug

### Expected behavior

Make the latest addition on top

### Actual behavior

Does not

### Screenshots/Screen recordings

https://m1.afileditch.ch/zEwaxGObdlkRSaiCrtty.mp4

### ViMusic version

0.5.0

### Android version

11

### Additional information

I dont think the albums thats above what i just added in the video are stuck there. I tried to add a few more and it put it in random order.

**Comment by vfsfitvnm** [comment]
Good spot!
