### ISSUE TITLE
Crossfade songs

### ISSUE THREAD

**Issue by owencz1998** [vfsfitvnm/ViMusic#40]
### Feature description

A setting to allow crossfading music if possible.

### Why do you want this feature?

Be cool to listen to music without a pause between the next song.

**Comment by vfsfitvnm** [comment]
Same as https://github.com/z-huang/music/issues/54#issuecomment-1119163328

> without a pause between the next song

The playback is already gapless. The next release will have a skip silence feature, so any pause is likely to be removed.

**Comment by owencz1998** [comment]
Nice one dude can't wait for the release 🤟
