### ISSUE TITLE
Hide status bar when playing song

### ISSUE THREAD

**Issue by adxmjcc** [vfsfitvnm/ViMusic#400]
### Feature description

Hey there, loving the app. A suggestion I'd give would be to give an option to hide the status bar on devices when in the playing song menu/always inside the app. Would look even cleaner that way. Not urgent, but would be a cool feature to have.

### Why do you want this feature?

Thought it would help make the UI look a little more clean.

**Comment by vfsfitvnm** [comment]
The status bar can't be hidden because it would cause the items to "jump" some pixels suddenly - that would be very ugly. I could just make the icons on the status bar of the same color of the background instead, but again that should be smooth (and expensive), so I don't know if the effort it really worth it.

I'm not incline to implement this one, but let's see...

**Comment by arfanmrafeek** [comment]
I use lawnchair 12 beta version, as my home launcher, There is a option called "Show status bar" As default it's enabled, I disable it.

**Comment by arfanmrafeek** [comment]
Reference


https://user-images.githubusercontent.com/69381592/196012309-46151029-4e65-4dd1-b77b-4aaa7720aac4.mp4

![Screenshot_2022-10-16-05-56-25-330_app lawnchair](https://user-images.githubusercontent.com/69381592/196012312-7c29e608-aeca-476a-b818-92807d055840.jpg)

To look like this. 

![Screenshot_2022-10-16-05-56-32-518_app lawnchair](https://user-images.githubusercontent.com/69381592/196012321-a10a17bf-d8c4-49e5-90ac-0298ea223c65.jpg)

In ViMusic (Graphically Edited)

![Screenshot_2022-10-16-05-51-00-503_it vfsfitvnm vimusic](https://user-images.githubusercontent.com/69381592/196012335-6ced3c7f-0df6-4d2a-8ddc-f178d7d97f79.jpg)

![Screenshot_2022-10-16-05-51-10-613_it vfsfitvnm vimusic](https://user-images.githubusercontent.com/69381592/196012340-8e760414-323d-479d-b2b0-61c50d85ff4a.jpg)

Try to implement it, I love to see my Status bar is hidden).

BTW, When Sync lyrics can you stop screen from turning off?

**Comment by vfsfitvnm** [comment]
I won't implement this feature as it's not clear how to do it; the solution in https://github.com/vfsfitvnm/ViMusic/issues/400#issuecomment-1273073528 is definitely not something a music player app should do.

> BTW, When Sync lyrics can you stop screen from turning off?

Please file a separate feature request
