### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by AndrewNoonan2004** [vfsfitvnm/ViMusic#402]
Hello, I was wondering how I could donate to the project! Thanks in advance.

**Comment by arfanmrafeek** [comment]
Even, I would like that option but this is his response. 

> I don't think I will ever do this - for like 10$ a month I'd rather not involve money (and all the hassle it brings).

#216 - reference

**Comment by vfsfitvnm** [comment]
Thanks for your support anyway!
