### ISSUE TITLE
SponsorBlock support

### ISSUE THREAD

**Issue by xsm2** [vfsfitvnm/ViMusic#404]
### Feature description

The [official page](https://sponsor.ajay.app/) explains what is SponsorBlock far better than I can, but basically is an API used to skip specific (and annoying) parts of youtube songs/videos

### Why do you want this feature?

There are a lot of songs/music videos with intros or outros which are not part of the song it's self, but it will specially help when using the app for podcast listening. It will also serve as a "skip silence feature" but instead of one based on an algorithm it would be community curated. I don't know of any music players with this feature, but other popular apps like Vanced used to have it.

### Additional information

If you never used SponsorBlock before the skipable segments are categorized so you can choose what you don't want to watch, the deafult config of the browser extensions is to only skip sponsors segments, while in apps it's usually off by default and you have to enable in the settings. I personally enable all the categories, but the most important will be "section without music"

Example of a song that benefits from SponsorBlock: https://www.youtube.com/watch?v=lWA2pjMjpBs (SponsorBlock works in https://music.youtube.com too, but its less visual as it doesn't appear in the progress bar)

There is a fork of newpipe with SponsorBlock support, maybe it can be usefull to see how it's implemented and to try the feature: [https://github.com/gilbsgilbs/NewPipeSponsorBlock](https://github.com/gilbsgilbs/NewPipeSponsorBlock)

**Comment by vfsfitvnm** [comment]
Thanks for filing this detailed issue.
However, I won't add such feature: youtube music "songs" don't have non-music parts already. 
E.g: https://music.youtube.com/watch?v=4mVo93E9wpU

Playing songs within their "video" counterpart is highly discouraged: you get ambient noises and you miss the album link and thumbnail.

**Comment by xsm2** [comment]
It's true that officially uploaded songs don't have those segments but unnofficially ones usually do: cover artists, remixes, ost from movies/series/games/anime, live concerts, complilations that are not a playlist and even some classical music would benefit of the feature. It can also help with region lock, when one song it's not available in your region but an unofficial version is uploaded. I get that is discouraged to use non "songs" even on the official apps, but sometimes it's the only choice.

**Comment by TalOrenshtein** [comment]
> Thanks for filing this detailed issue. However, I won't add such feature: youtube music "songs" don't have non-music parts already. E.g: https://music.youtube.com/watch?v=4mVo93E9wpU
> 
> Playing songs within their "video" counterpart is highly discouraged: you get ambient noises and you miss the album link and thumbnail.

There are a lot of music content that doesn't appear at yt music. In addition, you can use SB APIs only for content that doesn't being fetch from yt music.

**Comment by KaKi87** [comment]
Hello,
Please reconsider this suggestion.
Thanks
