### ISSUE TITLE
Edit Song

### ISSUE THREAD

**Issue by MrConqueror** [vfsfitvnm/ViMusic#41]
### Feature description

Hi, Could you add this Feature, where I can edit the the song.

### Why do you want this feature?

Because some Title is too long like, Like they add the Featuring, Acoustic Version, etc with the title. I usually cut them. and Sometimes the artist is not right So i change it to the real singer of that Music. And lastly i sometimes change the Song/Album Cover or Thumbnail with my Celebrity crush Picture LoL. 

### Additional information

![IMG_20220614_061847](https://user-images.githubusercontent.com/102837820/173457833-0f03c86e-f3dc-4e76-8eac-71aa44f3d4e9.jpg)

**Comment by MrConqueror** [comment]
![Screenshot_2022-06-14-06-29-47-55_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/102837820/173458235-93d240e9-228e-4f20-8fa1-dcb382226c04.jpg)
Now, Look at this the title is "The way you look at me" but they add Acoustic Version Word. and when the song title is long will you add scroll so we can read it. Like it scroll itself.

**Comment by vfsfitvnm** [comment]
> and when the song title is long will you add scroll so we can read it. Like it scroll itself.

Please file a separate issue about this

**Comment by MrConqueror** [comment]
> > and when the song title is long will you add scroll so we can read it. Like it scroll itself.
> 
> Please file a separate issue about this

ha? No, They're the same, and I don't think it's an issue it's just a Feature request. I wanna cut out "Acoustic Version" wich was included in title.

**Comment by vfsfitvnm** [comment]
> > > and when the song title is long will you add scroll so we can read it. Like it scroll itself.
> > 
> > 
> > Please file a separate issue about this
> 
> ha? No, They're the same, and I don't think it's an issue it's just a Feature request. I wanna cut out "Acoustic Version" wich was included in title. Therefore I want edit track/song if it's possible to add.

I was referring to the (auto)scrolling thing!

Regarding the ability to edit a song, I will probably do something - but things like thumbnails/images can't be changed

**Comment by MrConqueror** [comment]
> > > > and when the song title is long will you add scroll so we can read it. Like it scroll itself.
> > > 
> > > 
> > > Please file a separate issue about this
> > 
> > 
> > ha? No, They're the same, and I don't think it's an issue it's just a Feature request. I wanna cut out "Acoustic Version" wich was included in title. Therefore I want edit track/song if it's possible to add.
> 
> I was referring to the (auto)scrolling thing!
> 
> Regarding the ability to edit a song, I will probably do something - but things like thumbnails/images can't be changed

Hey, I'm so sorry for requesting late, But i think we need a Feature being able to change Thumbnail. 
![Screenshot_2022-06-19-07-22-27-55_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/102837820/174460004-46c25896-7981-492b-af1e-f1042a2dbc62.jpg)
Look at this. i wanna change it something Cool Photo from Pinterest. Please make it possible.

**Comment by vfsfitvnm** [comment]
Closing as edge-case (not planned): no further interest was manifested from other users.
