### ISSUE TITLE
Loudness Normalization

### ISSUE THREAD

**Issue by haernerdy** [vfsfitvnm/ViMusic#410]
### Steps to reproduce the bug

Go to 'Settings'
Click on 'Player'
Turn on 'Loudness normalization'
It'll lower music volume pass the standard level (like half on it) 

### Expected behavior

This happens when you turn on 'Loudness normalization'

### Actual behavior

When loudness normalization is turned on, music volume reduces so much that you can barely hear it playing..

### ViMusic version

0.5.1

### Android version

Android 12

### Additional information

It didn't happen in the previous versions, started after I installed V 0.5.1

**Comment by vfsfitvnm** [comment]
You have to increase your device volume. I know the volume difference is noticeable when loudness normalization is turned on, but that's the only way to make very quiet songs (-10dB) as important as loud songs (+10dB).

However, would you share the song you are having trouble with?

**Comment by haernerdy** [comment]
In NF Songs and in almost every songs mostly when I'm playing through BT Speaker. It seems to sound normal for a while after I force stop the app but reduces once I turn off Loudness normalization and turn it back on...

**Comment by vfsfitvnm** [comment]
I played a bunch of NF songs through a BT speaker and I couldn't reproduce. The "loudness normalization" will affect the volume (as I said in my previous comment) so you have to increase the device volume using the hardware buttons.
If you are wondering why it didn't behave like this in the previous version, it's because the algorithm wasn't implemented well (I can't say the new one it is, but it's better) - in fact you could still hear the loudness difference between a -10dB song and a +10dB one.

**Comment by haernerdy** [comment]
Ok I'll try uninstalling and reinstall it and see if it'll get back to normal. Thanks for the response though 😊 you guys' doing a great job and I've already recommended your app to many people 👍

**Comment by vfsfitvnm** [comment]
@haernerdy 
I kind of understand what you are saying now, I apologize. I tried the loudness normalization with ambient noises (cars etc) and I had to increase the hardware volume to the max value!

The good news is I found a better approach to normalize the audio. I think it won't lower the volume too much

**Comment by haernerdy** [comment]
Thanks 😊 for finding out n wanting to looking into it ❤️ I really enjoy your app. In fact, it's my default music app.. Kudos to the hardwork you're putting into making it better at all times
