### ISSUE TITLE
A more varied music queueing 

### ISSUE THREAD

**Issue by jydev-0** [vfsfitvnm/ViMusic#412]
### Feature description

Hello,

It would be nice if there was more variation in the music that gets queued, because the queue that is populated always contains similar songs irrespective of the first song selected. So there is no way of discovering new songs based on user's interests. The same songs pops up over and over again in the queue. It would be better if we could avoid this. Instead more variety of songs gets recommended to the user.
Maybe we could add a like and dislike option just like in YouTube music, just to better understand user's interest .

### Why do you want this feature?

The repetition of heard songs over and over again in the autoplay list.

**Comment by vfsfitvnm** [comment]
I never get the same songs to be honest (however it may depends on your region). However, no action can be taken. The queue entirely depends on youtube.
