### ISSUE TITLE
Quick picks keeps showing loading placeholder

### ISSUE THREAD

**Issue by Bazixv13** [vfsfitvnm/ViMusic#414]
It happens when I open the app this bug was also in 0.50 (v.051  Android 11)

Quick picks are not being loaded up (animation of loading works)

![Screenshot_20221012-211147.png](https://user-images.githubusercontent.com/83003002/195429566-626b02d6-cba4-47db-b9c6-65328738999a.png)

**Comment by vfsfitvnm** [comment]
Thanks for reporting, would you attach a screen recording so I have a clear idea of what's going on?

**Comment by Bazixv13** [comment]
https://user-images.githubusercontent.com/83003002/195434004-8576b98a-ec29-454b-a8d2-58855fa79568.mp4

**Comment by vfsfitvnm** [comment]
I think it's just a visual bug, I'll fix it soon

**Comment by arfanmrafeek** [comment]
I have encountered those Bugs.

**Comment by arfanmrafeek** [comment]
I have encountered such bug.
![Uploading Screenshot_2022-10-13-09-37-06-905_it.vfsfitvnm.vimusic.jpg…]()

**Comment by arfanmrafeek** [comment]
I have encountered such bug. 
![Screenshot_2022-10-13-09-37-06-905_it vfsfitvnm vimusic](https://user-images.githubusercontent.com/69381592/195497341-0fb0724a-f402-4d6e-9707-88542cd17a8b.jpg)
