### ISSUE TITLE
Media session doesn't handle controls in Android < 26

### ISSUE THREAD

**Issue by trollman64** [vfsfitvnm/ViMusic#415]
### Steps to reproduce the bug

1. Start playback on device
2. Try to change song with skip button on bluetooth device

### Expected behavior

Song should be skipped

### Actual behavior

Either nothing happens or a different app starts playing music such as Spotify

### ViMusic version

0.5.1

### Android version

Android 7.0

### Additional information

Also affects skip back button and the play/pause button

**Comment by vfsfitvnm** [comment]
Mine works - and honestly the bluetooth device command delivery is out of my control. Would you add more info? The bluetooth device you have and what does work...

**Comment by trollman64** [comment]
First noticed this with my car stereo but it also happens with a bluetooth keyboard. When I hit skip it wakes whatever app I was playing music on before. I tested this with 3 different apps: Spotify, AIMP, and Audials Play and whatever app I used last starts playing and ViMusic stops even when it's currently playing and in the foreground. It may have something to do with the Android version.

**Comment by vfsfitvnm** [comment]
And what happens if you play the skip button when e.g. spotify is playing?

**Comment by trollman64** [comment]
Spotify skips the current song

**Comment by vfsfitvnm** [comment]
Ok, thanks for reporting. Unfortunately there's nothing I can do. However, how these buttons are supposed to work (looking at other apps)? Do they only work if the app is in the foreground?

**Comment by trollman64** [comment]
They do not work at all. I did find this however: https://developer.android.com/guide/topics/media/media-controls
It's possible that this bug only affects devices running Android 10 and earlier.

**Comment by vfsfitvnm** [comment]
I was referring to a working app, e.g. spotify

**Comment by trollman64** [comment]
In other apps the buttons work on any screen and also work when the screen is off

**Comment by vfsfitvnm** [comment]
Ok, thanks for letting me know!

**Comment by vfsfitvnm** [comment]
Does the play/pause button work?

**Comment by trollman64** [comment]
In other apps yes, in ViMusic no

**Comment by vfsfitvnm** [comment]
Thanks, I downloaded the emulator for Android 7 and could reproduce. Fixing it asap

**Comment by vfsfitvnm** [comment]
Fixed! It was a stupid forgetfulness of mine - I should have checked the android version immediately. Thanks for your patience!

**Comment by trollman64** [comment]
Installed the latest debug build and can confirm that the controls now work properly.
