### ISSUE TITLE
Country selection

### ISSUE THREAD

**Issue by brnwlshubh** [vfsfitvnm/ViMusic#416]
### Feature description

Country list selection in ViMusic app will be good to select most selective music experience otherwise we have to search for the appropriate playlist or songs.

### Why do you want this feature?

Songs list vary from country to country. It'll be good if there is country selection to get better result.

### Additional information

[Music](https://github.com/z-huang/music) has option to change the country.

**Comment by vfsfitvnm** [comment]
I didn't implemented it yet because setting the `gl` parameter makes little to no difference: it just changes the order of the results (afaik). So I'd rather not give this (pointless) choice. But I don't know if it really makes difference elsewhere.

**Comment by brnwlshubh** [comment]
@vfsfitvnm Ok no issue I've solved my issue by reading #413
