### ISSUE TITLE
Band/Album bio displayed within thumbnails when press and hold similar to lyrics

### ISSUE THREAD

**Issue by Fatcakes** [vfsfitvnm/ViMusic#418]
**Feature Description**
Have the band bio show up when you press and hold the thumbnail on the band over page, and similarly on the album overview page.

**Why do you want this feature**
The only reason would be to have the option, and for app polishing I guess.

**Comment by vfsfitvnm** [comment]
Unfortunately it cannot be implemented. Nested scrolling is not supported yet so I can't show a long text over the thumbnail (the artist bio is typically long). All I can do is showing the id for artists and the id and release year for albums

**Comment by Fatcakes** [comment]
Maybe just include the info on their respective pages life youtube music does? 🤔

**Comment by vfsfitvnm** [comment]
Where do you think it suits the most? Maybe at the end of the "Overview" tab?

**Comment by Fatcakes** [comment]
@vfsfitvnm yeah I think that's what makes the most sense. At the very bottom underneath the album pages as well beneath the album tracks.

**Comment by vfsfitvnm** [comment]
Yep it's possibile (that's how I did it in the very first versions!), however there's a minor nuissance: I'd have to add a placeholder for that (for when the content is loading), but not all the artists have the bio, so when the content actually loads there will be a misalignment between the placeholders and the content

**Comment by Fatcakes** [comment]
@vfsfitvnm Well, if it's going to make the app less polished I'd say don't invest your time in it. While the bio stuff is nice sometimes it's not essential honestly. I just thought it would be slick if you could have it work like the lyrics, and stats for nerds info does by press and holding the thumbnail.

**Comment by vfsfitvnm** [comment]
I'll just add the bio at the bottom for now.

> I just thought it would be slick if you could have it work like the lyrics, and stats for nerds info does by press and holding the thumbnail.

 I had this precise idea when I was redesigning the artist screen, but soon I realized it couldn't be implemented.
