### ISSUE TITLE
Half cut text in chips

### ISSUE THREAD

**Issue by MrAdityaAlok** [vfsfitvnm/ViMusic#419]
### Steps to reproduce the bug

1. Click search
2. Type something
3. Chip showing `clear` text is half cut on large screens

### Expected behavior

Full text should be shown.

### Actual behavior

Half cut text is shown.

### Screenshots/Screen recordings

![Screenshot_2022-10-13-11-54-31-020](https://user-images.githubusercontent.com/73517616/195518874-00517a79-8e9f-4e8e-ac9b-9ebd615ff028.jpeg)

### ViMusic version

Latest: 0.5.1

### Android version

9

### Additional information

Similar thing happens in playlist tab.

**Comment by vfsfitvnm** [comment]
Thanks for reporting
