### ISSUE TITLE
"Unknown" artist page

### ISSUE THREAD

**Issue by Erik-vdb** [vfsfitvnm/ViMusic#423]
### Steps to reproduce the bug

I found this issue with some Nightcore channels

Taking as an example [Artemes](https://music.youtube.com/channel/UC1CWQYYSBaGdAzgTkSNfLbQ) and [Kenke](https://music.youtube.com/channel/UCBVVFXMWtQJzneuuWOg6j4g) (My 2 favs on Nightcore)

On both of them, long pressing any song shows "More of null" instead of "More of Kenke" (in this case)

![Screenshot_20221013-130453](https://user-images.githubusercontent.com/88503855/195648457-2ad5b831-f9a5-43a1-8ca2-753c5263997b.png)

Actually tapping the button shows an "Unknown" artist page

![Screenshot_20221013-130459](https://user-images.githubusercontent.com/88503855/195648516-6dc651dc-6c31-49c3-9ac9-1dea22b2d1e9.png)

It also seems unstable, since some minutes ago the button correctly said "More of Kenke" but sent me to the "Unknown" page regardless.

### Expected behavior

"More of [Artist]" button should redirect to the artist page

### Actual behavior

Button is labeled "More of null" and redirects to an "Unknown" labeled artist page

### ViMusic version

0.5.1

### Android version

Android 10

**Comment by vfsfitvnm** [comment]
Thanks for reporting!

**Comment by vfsfitvnm** [comment]
<img src="https://user-images.githubusercontent.com/46219656/195663587-4839a307-b46a-4a99-9635-f4e4a1693d5c.png" width="30%"/>

Fixed! Unfortunately this isn't an "official" channel, so the page is empty - I could add the "Videos" section to fill the blank space

**Comment by Erik-vdb** [comment]
Well, that was quick
