### ISSUE TITLE
Add a "search for new update" button

### ISSUE THREAD

**Issue by alvaroasllani** [vfsfitvnm/ViMusic#424]
### Feature description

The button to check for updates would be very good, I was with and old version until today I entered the repository. 
Maybe also in the future it would be nice to somehow export my existing playlist from YouTube music or Spotify account. 

### Why do you want this feature?

To make updating the app easier and to be able to export existing playlists from other platforms somehow ( the app and how it works is amazing anyway) 

### Additional information

Love the app!!!!

**Comment by vfsfitvnm** [comment]
Duplicate of #48
