### ISSUE TITLE
"Show song cover" doesn't work on poco m3

### ISSUE THREAD

**Issue by Soumyadyuti** [vfsfitvnm/ViMusic#427]
### Steps to reproduce the bug

![Screenshot_2022-10-14-01-52-56-216_it vfsfitvnm vimusic](https://user-images.githubusercontent.com/115742286/195703155-9c4a5bdd-2234-409a-b937-21e6d6a2bf8b.jpg)
![Screenshot_2022-10-14-01-53-03-700_lockscreen](https://user-images.githubusercontent.com/115742286/195703183-cfb36dc8-72e8-4a45-a2d8-9e8114daa84e.jpg)

### Expected behavior

The cover should be used as lockscreen wallpaper.

### Actual behavior

The lockscreen remains to be the same.

### ViMusic version

0.5.1

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
Is your device capable of such feature? You might have to enable in the system settings as well.
