### ISSUE TITLE
Add a  share button

### ISSUE THREAD

**Issue by arfanmrafeek** [vfsfitvnm/ViMusic#428]
### Feature description

**Add a button for individual music share.**
I can't share any song individually, Only options for Artists, Album and Playlist.
I want that option it would be awesome. (Especially to share with my friends) 
And the playlist we create in ViMusic, Can you implement something like that? For example Newpipe has a option to create playlists when we Share that playlist, The whole videos in the playlist goes like individual link for each and every song/video in the playlist. 

### Why do you want this feature?

To share with friends and sometimes I want to play that song with my friends in discord VC which is very hard to select that particular song. 
Hope it's just small implementation, Not going to cost your time.

**Comment by vfsfitvnm** [comment]
You can already share everything except for playlists created by you.
To share a song, long press it (a menu appears), then tap the song again.

**Comment by arfanmrafeek** [comment]
@vfsfitvnm Thank you, It was confusing, In Newpipe you can share the playlist we created but it'll be individual links for the each video in the playlist we created. Nevermind if it's hard to implement, I got what i need mainly.
