### ISSUE TITLE
A few questions about release v0.5

### ISSUE THREAD

**Issue by thornySoap** [vfsfitvnm/ViMusic#431]
I just got a little confused with this update, so I want to ask:

1. Can I still import playlists (not bookmark) so I can change the order of the songs?
2. Can I still play a song single since I couldn't find an option to not let the queue loop?
3. What if I don't need to use the quick picks tab?

I'm sorry, maybe my use practices are just obsolete ...

**Comment by thornySoap** [comment]
1. Okay, I see
2. Before the update playback stopped after reaching the end of the queue. But now it will start again from the beginning. So if you have just one song in the queue, it will repeat continously no matter whether loop icon is checked
3. Ok, that makes sense :D

**Comment by thornySoap** [comment]
2. There used to be an option to play a song single when long pressing on it. It would put only that one to the queue and after the song ended, playback ended as well

**Comment by vfsfitvnm** [comment]
You can still play a single song: all you have to do is select "Play next" or "Enqueue" when no songs are playing (you can clear the queue/playback by swiping down the collapsed player). However, I removed the "loop none" option, i.e. now the queue always loops (#276). So yeah, the playback never ends until you either clear the queue, close the app and dismiss the notification or set a sleep timer.

**Comment by thornySoap** [comment]
Ok thanks
