### ISSUE TITLE
listen with me

### ISSUE THREAD

**Issue by MarceloFerrante** [vfsfitvnm/ViMusic#434]
### Feature description

Some way to make two or more people listen the same music at distance.

### Why do you want this feature?

I have friens scattered all around thats loves brazilian music, and can be nice just to listen  music together when doing work or studying, even from Far away

### Additional information

I think a link will suffice. Like, i send a link to someone and when he opens we connect p2p and send the music id from youtube onw to another in a transparent way,.
Both can control reproduction, pausing, nex music, etc.. like a remote control maybe?

**Comment by vfsfitvnm** [comment]
I'll admit, this is actually an original idea! Unfortunately, it requires too much effort to be implemented, and I feel like it would be hardly ever used. I'm closing this issue for now as I don't feel like it will be ever worked on, but I'll certainly think about it from time to time. Thanks for submitting your feature request!
