### ISSUE TITLE
Quick picks don't load or take a long time to load

### ISSUE THREAD

**Issue by sidsharths1245** [vfsfitvnm/ViMusic#438]
### Steps to reproduce the bug

Open the app and click on quick picks tab

### Expected behavior

The suggestions should load

### Actual behavior

The page just keeps loading

### Screenshots/Screen recordings

![Screenshot_20221015-034039](https://user-images.githubusercontent.com/64619769/195951307-e87bc583-8dc3-4c54-b628-b7d981f06129.png)

### ViMusic version

0.5.1

### Android version

Android 13

### Additional information

p.s. The YouTube music is not blocked in my country so that should not be the problem here.

**Comment by arfanmrafeek** [comment]
Duplicate - #414

The error is resolved, In the next release version you won't encounter it. Hopefully.

**Comment by vfsfitvnm** [comment]
This is a bit different, though. @sidsharths1245 Would you share your database?

**Comment by vfsfitvnm** [comment]
Yep, I could reproduce, this is a bug. It happens when you quickly switch tabs.
