### ISSUE TITLE
Crash when playing certain song

### ISSUE THREAD

**Issue by teemue** [vfsfitvnm/ViMusic#44]
### Steps to reproduce the bug

Search for a song Bon Jovi - Born to be my baby and start playing. Link to the song: https://music.youtube.com/watch?v=8EnPHiXmhXs

### Expected behavior

Shouldn't crash

### Actual behavior

ViMusic crashes after ~1sec of playing

I reinstalled VIMusic and tried again, no luck.

### ViMusic version

0.1.4

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
I cannot reproduce. Could you add a logcat?

**Comment by teemue** [comment]
[2022-06-14-20-46-11.log](https://github.com/vfsfitvnm/ViMusic/files/8902215/2022-06-14-20-46-11.log)

Recorded with AppManager.

I noticed that if I add the song to a playlist and play it from the list, it works. But not straight from the search results.

**Comment by vfsfitvnm** [comment]
The logcat is incomplete, there's no stack stacktrace

**Comment by teemue** [comment]
OK, i tried to [catch again using adb logcat.](https://pastebin.com/mDfnZSQw). Is there anything?

**Comment by vfsfitvnm** [comment]
Yup, now there is.

This is very odd. Does it also happen when tapping "Play single" (three dots > play single)?

**Comment by teemue** [comment]
>  Does it also happen when tapping "Play single" (three dots > play single)?

No, only if I click the list item!

**Comment by vfsfitvnm** [comment]
Would you try to reproduce the bug with the debug apk (https://github.com/vfsfitvnm/ViMusic/releases/download/v0.1.5/app-debug.apk) and then send the logcat?

**Comment by teemue** [comment]
> Would you try to reproduce the bug with the debug apk (https://github.com/vfsfitvnm/ViMusic/releases/download/v0.1.5/app-debug.apk) and then send the logcat?

[Here you go!](https://pastebin.com/Uuhchiqf)

**Comment by vfsfitvnm** [comment]
Thanks, the fix is already done
