### ISSUE TITLE
Instant Crush - Daft Punk stops playing midway through BC of some sort of source code issue

### ISSUE THREAD

**Issue by VantageP01NT** [vfsfitvnm/ViMusic#444]
### Steps to reproduce the bug

1. search up Daft Punk - Instant Crush
2. Play the first one that pops up, it has the daft punk helmet ad the cover
3. Skip to about halfway through the song 

### Expected behavior

This should happen; the song should play regularly from the selected time.

### Actual behavior

Instead the song freezes and doesn't play 

### Logs

ADB logcat

### ViMusic version

0.4.3

### Android version

Android 12

**Comment by Fatcakes** [comment]
Can't reproduce. Make sure it's not caused by software like blokada or ad blocking software.
