### ISSUE TITLE
Bring back share song

### ISSUE THREAD

**Issue by quinnzbellz** [vfsfitvnm/ViMusic#445]
### Feature description

I'm recent updates, when long holding on a song, there used to be an option to share a link to that, but now there isn't.

### Why do you want this feature?

Its extremely useful when sharing songs with friends.

**Comment by vfsfitvnm** [comment]
You can still share a song: just tap the song when the menu appears!

**Comment by vfsfitvnm** [comment]
However I should maybe do something to make it clearer!

**Comment by vfsfitvnm** [comment]
<img src="https://user-images.githubusercontent.com/46219656/195996434-faea7790-d970-493b-b5c2-26fb40782c7b.png" width="30%"/>

Maybe like this?

**Comment by arfanmrafeek** [comment]
Thank you 😊

**Comment by quinnzbellz** [comment]
Thanks!
