### ISSUE TITLE
Open full player when playing a song

### ISSUE THREAD

**Issue by PassionateG1t** [vfsfitvnm/ViMusic#446]
### Feature description

When you click on a song, the full player should pop up instead of the mini-player.

### Why do you want this feature?

I am not sure if this feature was present before the latest update (it could potentially be caused by my previous request). Either way you'd expect that the full player opens to give you this immersive feeling; details like this, despite their mundaneness, exponentially enhance the UX.

Extra + if you can make this an option in settings to wether open the full player or the mini-player when playing a song.

**Comment by vfsfitvnm** [comment]
Uhm, it should be already expanding. Would you add a screen recording?
