### ISSUE TITLE
PureBlack Theme Search buttons Color

### ISSUE THREAD

**Issue by Fatcakes** [vfsfitvnm/ViMusic#447]
**Bug Description**

When you rotate from portrait to landscape mode the gray buttons switch from gray to black like the background. Rotating back to portrait doesn't turn them back.

**Expected Behavior**

For the buttons to remain gray when the screen orientation is rotated.

**Comment by vfsfitvnm** [comment]
Good catch!

**Comment by Fatcakes** [comment]
@vfsfitvnm I think it also changes the Heart "like song" icon from red to blue?

**Comment by vfsfitvnm** [comment]
Yes
