### ISSUE TITLE
Suggestions never finish loading

### ISSUE THREAD

**Issue by Eri1320** [vfsfitvnm/ViMusic#448]
### Steps to reproduce the bug

I've been listening to my favourite songs. It suggests new related ones, but now it never finishes loading the suggestions.

### Expected behavior

It should load all suggestions and not remain in an infinite load.

### Actual behavior

It happens every time I go to the "home" page.

### Screenshots/Screen recordings

![Screenshot_20221015-154036](https://user-images.githubusercontent.com/111612989/196006820-f04c11c0-fded-4b7e-a1eb-8c4e3cbf13fe.png)

### ViMusic version

V0.5.1

### Android version

Android 11

**Comment by arfanmrafeek** [comment]
Tracking - #413 

The error is resolved, In the next release version you won't encounter it. Hopefully.

**Comment by arfanmrafeek** [comment]
@vfsfitvnm Please release next version 0.5.2 if bugs are fixed.

**Comment by vfsfitvnm** [comment]
Yes, the next version is going to be released in a day or two
