### ISSUE TITLE
Update f-droid repo

### ISSUE THREAD

**Issue by filipkamenski** [vfsfitvnm/ViMusic#449]
### Feature description

I'm not sure if its intended and if you have any power over it but the latest version available on f-droid is 4.3. I've been using that version for several months and just recently decided to check you out on GitHub. Imagine my surprise when i found out that there is newer, much improved version. Please release the newer version there. Your app is great and deserves to be seen.

### Why do you want this feature?

It will lead to higher exposure.

**Comment by vfsfitvnm** [comment]
Yup ^
