### ISSUE TITLE
Home page loading issue

### ISSUE THREAD

**Issue by figo2001** [vfsfitvnm/ViMusic#451]
![Screenshot_2022-10-16-11-39-47-385_it.vfsfitvnm.vimusic.jpg](https://user-images.githubusercontent.com/78696850/196021010-50f4718f-dc22-4dfe-99fe-391a22fea60d.jpg)

**Comment by figo2001** [comment]
Can you please help me out of this bug? 
It still happens after I reinstalled the app and forced to stop option.

**Comment by vfsfitvnm** [comment]
Duplicate of #414
