### ISSUE TITLE
Album Art/Thumbnail in Persistent Notification Doesn't Update

### ISSUE THREAD

**Issue by Ao1Pointblank** [vfsfitvnm/ViMusic#456]
### Steps to reproduce the bug

The artwork in the pulldown notification doesn't always update when a song changes or is skipped. Sometimes it corrects itself when fast forward is pressed twice or three times. 
The hue/transparent accent color of the notification _does_ change, however.

### Expected behavior

image in the notification should change to match the one displayed in the app

### Actual behavior

image thumbnail does not change

### ViMusic version

0.5.1

### Android version

Android 13 with GrapheneOS on Pixel 5

**Comment by vfsfitvnm** [comment]
It's a know bug of A13. Duplicate of #267
