### ISSUE TITLE
Show artists subscribers count in overview tab

### ISSUE THREAD

**Issue by arfanmrafeek** [vfsfitvnm/ViMusic#460]
### Feature description

This is not a important features to add just to let know their subscribers count, It's visible in Quick Pick. 
So good to add it in Overview. 

### Why do you want this feature?

Not so important. It's all up to you. I respect your choice.

**Comment by vfsfitvnm** [comment]
Yup, thanks for reminding me, however I don't store that information yet, so you will have to re-visit the artists to make the subscriber count show up

**Comment by arfanmrafeek** [comment]
I think no one want this, Well if it's easy just do it. Other case just ignore. No of really going to look at the subscribers count.
