### ISSUE TITLE
Crash when opening large video playlist

### ISSUE THREAD

**Issue by DaniAndTheWeb** [vfsfitvnm/ViMusic#468]
### Steps to reproduce the bug

1. Open a large video playlist like Nightblue Music Playlist
2. Song starts
3. When the app is put in background it suddently crashes

### Expected behavior

The music should keep playing as usual

### Actual behavior

The app crashes

### ViMusic version

0.5.2

### Android version

Miui 13 on Android 12

**Comment by vfsfitvnm** [comment]
Hi, sadly this is a know bug (Read #401 for a workaround).
