### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by zachvlat** [vfsfitvnm/ViMusic#47]
### Feature description

If this app gets Android auto compatibility, it will effectively kill my Spotify app. So, don't do it please! 😝 

### Why do you want this feature?

Many of us listen music when driving and Android Auto helps a lot in this matter

**Comment by zachvlat** [comment]
Also I 've never tried this before! I 'll try to fork it and see if I figure something out.

**Comment by zachvlat** [comment]
I closed it by accident!

**Comment by urmomsangus** [comment]
In case it helps someone, I have another app that only shows up on Android Auto if you enable developer settings in Android Auto. I haven't tried with this app, and I sorta doubt it will work without further integration somehow (but I'm not a dev so I don't know).

Steps are:
- Launch the Android Auto app
- Tap the top left menu and select About.
- Tap About Android Auto 10 times to unlock Developer Mode. 
- Select top right menu and check if there's Developer settings. 
- Select Developer settings and scroll down to Unknown sources and enable

**Comment by zachvlat** [comment]
> In case it helps someone, I have another app that only shows up on Android Auto if you enable developer settings in Android Auto. I haven't tried with this app, and I sorta doubt it will work without further integration somehow (but I'm not a dev so I don't know).
> 
> Steps are:
> 
> * Launch the Android Auto app
> * Tap the top left menu and select About.
> * Tap About Android Auto 10 times to unlock Developer Mode.
> * Select top right menu and check if there's Developer settings.
> * Select Developer settings and scroll down to Unknown sources and enable

I know but this doesn't work on this app. You must at least enable it from the xml files.

**Comment by nonetrix** [comment]
You can emulate Android auto with DHU might make it easier for people that don't own a car with it 

Although looks like a pain to setup I don't know why it isn't just in the Android Studio emulator that can emulate a phone or a tablet or watch even I think

https://developer.android.com/training/cars/testing#test-auto

**Comment by sriio** [comment]
I will take a look to support Android Auto (already did it for newpipe)

**Comment by sriio** [comment]
Some progress :blush:

![Capture d’écran du 2022-09-16 14-29-29](https://user-images.githubusercontent.com/8983976/190639864-9d834e22-0f0e-494b-bff9-544040a88e91.png)

![Capture d’écran du 2022-09-16 14-29-40](https://user-images.githubusercontent.com/8983976/190639885-ab72a45d-3a36-4796-a5d3-8252dc7a0cc8.png)

![Capture d’écran du 2022-09-16 14-29-45](https://user-images.githubusercontent.com/8983976/190639896-d89647d3-8906-4a99-9700-c0d297597d5f.png)

**Comment by zachvlat** [comment]
I already build it to test it in my car, be back with more info! :D

**Comment by sriio** [comment]
> I already build it to test it in my car, I 'll be back with more info! :D

It's not finished, it lacks the datasource and some adjustments (icon, cover, check enqueue, etc...) but all feedbacks is welcome. I'll do a build when this is all done

**Comment by zachvlat** [comment]
![signal-2022-09-16-20-01-46-529](https://user-images.githubusercontent.com/28532979/190703339-d4c7ed1f-1ce1-4541-a29f-2a112528b564.png)
Unfortunately it didn't work. I enabled developer settings and unknown sources just in case but nothing. Should I do something else? Maybe mess with the Application mode?

**Comment by sriio** [comment]
> ![signal-2022-09-16-20-01-46-529](https://user-images.githubusercontent.com/28532979/190703339-d4c7ed1f-1ce1-4541-a29f-2a112528b564.png) Unfortunately it didn't work. I enabled developer settings and unknown sources just in case but nothing. Should I do something else? Maybe mess with the Application mode?

Hmm no, that's what I did to get access to the application. Have you tried restarting your phone? Sometimes non-gstore apps disappear, but restarting is enough to restore them. Otherwise, I don't see why... 😕

**Comment by zachvlat** [comment]
![Screenshot_20220919-130810_Trebuchet](https://user-images.githubusercontent.com/28532979/190995441-fd4722f4-fa08-47fc-b018-8d8e42c717f9.png)
I 'm gonna try it again later in the evening, but it worries me that I don't have the option to put it with the rest of the apps... Maybe someone other can test it again, with his car, when you have an apk to give.

**Comment by sriio** [comment]
Working implementation for test available here : https://github.com/sriio/ViMusic/releases/tag/test1.

You can play a playlist or a specific song (favorite). What it miss atm : 

- Random favorite songs
- Recent songs
- Cover
- Icons
- Enqueue list

**Comment by zachvlat** [comment]
![Screenshot_20220922-182052_Package installer](https://user-images.githubusercontent.com/28532979/191790654-c90450d2-cd15-445f-b28f-ea238c40036d.png)
I guess it's time to ditch it then! It works for the small amount of time I used it in my car, I 'll use it more extensively tomorrow (in more of a real life situation) and come back with any bugs/weird stuff I 'll found! Thank you!

**Comment by sriio** [comment]
New build here : https://github.com/sriio/ViMusic/releases/tag/test2.

Added : 

- Icon and thumbnail 
- Random play for favorite songs
- Add recent songs (same as in homepage) + random play

Missing :

- Cover (missing extra/flag maybe ?)
- Enqueue list (not sure about it, queue are not in mediaSession but in player ...)
- Clean/refacto then PR and review by @vfsfitvnm 
- Anything else ?

**Comment by sriio** [comment]
Last build available here : https://github.com/sriio/ViMusic/releases/tag/lastest

Added :

- Implement queue in MediaSession and seek on it
- Add cover in view (to not break anything and display it, you need to enable "Show song cover" in settings

This is my last build, I won't have enough time to continue working on it.

**Comment by vfsfitvnm** [comment]
I merged his work to the `androidauto` branch: https://github.com/vfsfitvnm/ViMusic/tree/androidauto.
Here you can find the apks: https://github.com/vfsfitvnm/ViMusic/actions?query=branch%3Aandroidauto

**Comment by vfsfitvnm** [comment]
I'm currently using the android auto app with desktop head unit (DHU) from my pc. Vimusic works well so far! The android auto support is gonna make it soon :) Thank you @sriio!

**Comment by vfsfitvnm** [comment]
Merged to master. @zachvlat I'm not an android auto user so I don't know if what I changed is fine, but would you take a look to see if it's ok feature-wise?

**Comment by vfsfitvnm** [comment]
Forgot to mention the "Android auto" feature is disabled by default - you need to enable it in Settings > Other

**Comment by zachvlat** [comment]
ok I m gonna check it out and come back with some feedback!

**Comment by zachvlat** [comment]
it works. I build from source the latest master branch.

**Comment by vfsfitvnm** [comment]
Perfect. Closing as completed - let me know if you have further considerations!

**Comment by mafrailea** [comment]
@vfsfitvnm, just a comment, it wasn't initially working for me until I enabled "Unknown sources" in the Developer Settings of Android Auto.

Not sure if it's the way it's intended to work but, if so, it would make sense to inform the user in some way.

Or, even better, invoke the "Developer settings" dialog of Android Auto and urge the user to manually enable "Unknown Sources" there.

**Comment by vfsfitvnm** [comment]
Yep, it must be enabled in the android auto settings.

> Or, even better, invoke the "Developer settings" dialog of Android Auto and urge the user to manually enable "Unknown Sources" there.

I can't do this, I'll just add a red text instead. Thanks for the idea!

**Comment by Fatcakes** [comment]
Anyone having an issue with the album art not showing?

**Comment by vfsfitvnm** [comment]
@Fatcakes https://github.com/vfsfitvnm/ViMusic/issues/47#issuecomment-1265388281
