### ISSUE TITLE
Can't Load anything without VPN (I'm in Bangladesh)

### ISSUE THREAD

**Issue by AgentX69** [vfsfitvnm/ViMusic#472]
### Steps to reproduce the bug

Open this app and it's not load anything

### Expected behavior

First day with 1.1.1.1 this app is running fine but next day it stop working without a VPN app of Usa/Singapore or etc 

### Actual behavior

😕 

### Screenshots/Screen recordings

![Screenshot_20221019-123037_ViMusic](https://user-images.githubusercontent.com/116145739/196613955-4a458d10-ad64-4451-8b6b-8701f992ac47.png)
![Screenshot_20221019-123030_ViMusic](https://user-images.githubusercontent.com/116145739/196613964-bfaecdea-2275-43f7-9f6c-2d2e27220364.png)

### Logs

Can't manage logs

### ViMusic version

0.5.2

### Android version

Android 10

### Additional information

Nothing more

**Comment by vfsfitvnm** [comment]
YouTube music is not available in your country. You need to use a vpn

**Comment by arfanmrafeek** [comment]
@vfsfitvnm Can you implement Proxy for those region.
