### ISSUE TITLE
Donation support

### ISSUE THREAD

**Issue by wylsend** [vfsfitvnm/ViMusic#477]
### Feature description

I'd like to support the author, but in app i can't do this, can you please add ways to help you?

### Why do you want this feature?

Page, which contains addresses to cryptowallet or something else.
It can be link to page in app, or donation page directly in app.

**Comment by arfanmrafeek** [comment]
Even, I would like that option but this is his response.

> I don't think I will ever do this - for like 10$ a month I'd rather not involve money (and all the hassle it brings).

#216 - reference

**Comment by vfsfitvnm** [comment]
Hi, thanks for willing to support me financially. However, as stated in #216, it is a _won't do_
