### ISSUE TITLE
MediaSession dies too quickly

### ISSUE THREAD

**Issue by rhynec** [vfsfitvnm/ViMusic#481]
### Steps to reproduce the bug

1. Start playing any song.
2. Pause the song, and exit the app or lock your screen.
3. Wait a few seconds/minutes (random) until ViMusic doesn't appear in the notification bar.

### Expected behavior

ViMusic remains in the notification bar indefinitely to continue playing the song you were listening to, and remembers the progress of the song (at least while the app is open, if it doesn't yet have a persistent queue).

This is similar to #401, but the app doesn't appear to crash during these tests, nor is the problem related to playlists. Furthermore, music keeps playing normally in the background if it is never paused (unless a network error occurs), unlike the other issue.

### Actual behavior

ViMusic disappears from the notification bar, so you can't resume playing a song you were listening to. Moreover, opening the app will not show the previous song you were listening to either. Pressing back on the screen brings up the previous song you were listening to, but there is not progress/artwork on the player, and pressing play doesn't work.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/86078431/197082813-3b2b2b66-bf8f-4703-8ed5-27d448bb9806.mp4

### ViMusic version

0.5.2

### Android version

Android 13 (Pixel 6a)

**Comment by vfsfitvnm** [comment]
Hi, you need to tap on "disable battery restrictions" in settings > other.

**Comment by rhynec** [comment]
Thanks! Out of curiosity, how do apps like Spotify avoid needing to disable battery restrictions? I've noticed that on Android 13, if Spotify has been in the background for a while its notification will switch from having play/forward/backward/seek, to only have a play button. I wonder if this is related to how they circumvent needing to disable battery restrictions.

**Comment by vfsfitvnm** [comment]
They host the playback service in a separate process (I guess). I opted for a workaround because this "proper" solution requires some effort to implement.
