### ISSUE TITLE
Cannot exit the application in the standard way

### ISSUE THREAD

**Issue by ikanakova** [vfsfitvnm/ViMusic#483]
### Steps to reproduce the bug

1. Open ViMusic and play playlist.
2. Stop playlist playback (or disconnecting from the bluetooth speaker stops the music).
3. Go back to the main page and swipe down to close the playlist.
5. Close app.

### Expected behavior

ViMusic is properly terminated.

### Actual behavior

After a few minutes, ViMusic appears in the notification bar (in the state of playing music, but nothing is heard). Can't stop music and close app with swipe. It must be quit in system settings using Force stop.

### ViMusic version

0.5.2 (since 0.5.0)

### Android version

Android 10

**Comment by vfsfitvnm** [comment]
Thanks for reporting. Would you provide a screen recording? Also, how many songs does contain the playlist you are listening to?

**Comment by ikanakova** [comment]
It is e.g. this playlist: https://music.youtube.com/playlist?list=RDCLAK5uy_n05lDmPMt7E5gHWyYhY5cw3zsHDpFHsfg

**Comment by vfsfitvnm** [comment]
Would you provide a screen recording? So I precisely know what's going on (perhaps a duplicate of #401).
Also, the stale notification indicates a crash occurred. I need the logs (connect your phone to the pc, then `adb logcat`) so I know what's happened

**Comment by ikanakova** [comment]
[logcat.log](https://github.com/vfsfitvnm/ViMusic/files/9838280/logcat.log)



https://user-images.githubusercontent.com/38765251/197179810-88c401ee-cd24-4f72-b1d9-cbd8c01df82c.mp4

**Comment by ikanakova** [comment]
I installed debug apk and here is logs:
[event.log](https://github.com/vfsfitvnm/ViMusic/files/9839861/event.log)
[logcat.log](https://github.com/vfsfitvnm/ViMusic/files/9839863/logcat.log)

**Comment by vfsfitvnm** [comment]
Were you able to reproduce? I see no logs for `it.vfsftvnm.vimusic.debug`.

**Comment by ikanakova** [comment]
Yes, but the app doesn't crash, it just behaves strangely. But this time I didn't do Force stop, so that's probably why it didn't appear in the log. Sometimes it takes a very long time for the stoped ViMusic to appear in the notification bar, and sometimes it is immediately like in the screenrecord above.

**Comment by vfsfitvnm** [comment]
Got it. However I can't do anything without the logs (for `it.vfsftvnm.vimusic.debug`)! Please report them here when you they are ready.

**Comment by ikanakova** [comment]
I tried it with headphones and there is also force stop.
[logcat.log](https://github.com/vfsfitvnm/ViMusic/files/9840341/logcat.log)
Could this not be the problem? - it appears often:
10-21 17:11:55.424 D/InterruptionStateProvider(19842): shouldHeadsUp() : false entry.importance = 2 0|it.vfsfitvnm.vimusic.debug|1001|null|10771

**Comment by vfsfitvnm** [comment]
Nope. This is how a crash should look like:
```
09-13 14:57:40.970 E/AndroidRuntime(23966): FATAL EXCEPTION: main
09-13 14:57:40.970 E/AndroidRuntime(23966): Process: it.vfsfitvnm.vimusic, PID: 23966
09-13 14:57:40.970 E/AndroidRuntime(23966): (other stuff here for many lines)
```

**Comment by vfsfitvnm** [comment]
@ikanakova Hi, did you make any progress regarding the logs? I really want to fix it before the next release

**Comment by ikanakova** [comment]
@vfsfitvnm Since battery optimization is enabled, I have no problem with the app. In addition, the application never crashed, it just couldn't be turned off and had to be force stop which probably cannot be read from the log.
