### ISSUE TITLE
Keep playlist after closing and opening the app

### ISSUE THREAD

**Issue by topgunbg** [vfsfitvnm/ViMusic#485]
### Feature description

After killing the app, and new opening again the last played song or playlist is no longer available to continue playing.

I feel it's a simple thing, maybe I'm missing something?

It feels intuitive that it would keep the song and position after a few hours of inactivity, but it doesn't for some reason. 

### Why do you want this feature?

Easy and intuitive

**Comment by vfsfitvnm** [comment]
> maybe I'm missing something?

Yes, enable "Persistent queue" in Settings > Player!
