### ISSUE TITLE
Just a thank you letter

### ISSUE THREAD

**Issue by Bseg277** [vfsfitvnm/ViMusic#487]
### Feature description

This application is amazing. I just wanted to thank you for your efforts to the world! You are an amazing coder!

### Why do you want this feature?

Just because

**Comment by YarostheLaunchpadder** [comment]
I want to say the same, but don't want to open another "issue".
This app is awesome!

**Comment by Bseg277** [comment]
Do you know how to enable for Android auto

**Comment by arfanmrafeek** [comment]
Change the issue topic to Off topic chat/ Open Chat.

**Comment by Bseg277** [comment]
I did that and it didn't work

**Comment by YarostheLaunchpadder** [comment]
@Bseg277 Then open another issue on this repository reporting the problem.

**Comment by vfsfitvnm** [comment]
@Bseg277  You also need to enable "unknown sources" in the android auto app

**Comment by arfanmrafeek** [comment]
I'm thinking of making FAQ
But As the questions is very less in issue, I think to get more questions we need to add question relating app in About Tab.

**Comment by vfsfitvnm** [comment]
@arfanmrafeek Yes, FAQ are necessary. Unfortunately it's a boring thing to do lol. Also, I'm not sure if it makes sense to put them in the app, probably on github is better

**Comment by YarostheLaunchpadder** [comment]
FAQ can be on the README of the GitHub repository, and then a link inside the app or something similar.
