### ISSUE TITLE
App crashes when opening offline playlist 

### ISSUE THREAD

**Issue by miloisblue** [vfsfitvnm/ViMusic#488]
### Steps to reproduce the bug

1. Open ViMusic app
2. Select offline playlist 
3. App crashes 

### Expected behavior

This should open the offline playlist and I will be able to listen to music offline without app crashing 

### Actual behavior

Instead the app crashes 

### Screenshots/Screen recordings

Uploading Screen_Recording_20221022_084200_One UI Home.mp4…

### Logs

https://drive.google.com/file/d/1Dx3TXkA-vHC7JJ3zzLmCqc8HhbgmF3mi/view?usp=drivesdk

### ViMusic version

Version 0.5.2

### Android version

Android 12

### Additional information

Hi, I am having a problem when opening the offline playlist because every time I select it, the app always crashes.

•All the other things in the app are functioning right except the offline playlist.

•I have plenty of storage.

•I forced it to stop, and even uninstalled and reinstalled, but it still crashes when opening the offline playlist. (After I installed it, I restored my database.)

•I also restarted my phone.

•Then I uninstalled and installed it again (I did not restore my database) and this time I opened an offline playlist and the app did not crash.

•And I recently installed the debug apk but it still crashes when opening offline playlist.

I don't know why it happens. :( Help, please.

(I hope the log I gave is the one you're looking for..)

Please excuse my bad English.

Thank you.

**Comment by miloisblue** [comment]
https://user-images.githubusercontent.com/116041569/197309098-52cfd7fc-07c0-4334-a633-b134880ad113.mp4

**Comment by vfsfitvnm** [comment]
Thank you! Very helpful :)
