### ISSUE TITLE
A Lyrics Tab in the Music Player

### ISSUE THREAD

**Issue by Diatonic-Fire** [vfsfitvnm/ViMusic#489]
### Feature description

A Lyrics Tab if possible , please add it in the Music Player , The Music and UI is Crazy good and Excellent but the lyrics tab helps me ....

### Why do you want this feature?

I would like this feature for two reasons ...
1. sometimes I just like to sing along to songs but forget the lyrics so I read and sing....
2. the Lyrics Tab would help if I was listening to a new song ...

### Additional information

Thanks for listening me out!!

**Comment by Diatonic-Fire** [comment]
sorry it took me a bit of time to find it sorry......

**Comment by arfanmrafeek** [comment]
There lyrics tab is available already, Check tap on time on the thumbnail of the music you're listening in player. You'll get it.

**Comment by arfanmrafeek** [comment]
> sorry it took me a bit of time to find it sorry......

Aha okay, Please close this issue. If you don't mind.
