### ISSUE TITLE
"Couldn't reach the internet" prompt when trying to open a playlist

### ISSUE THREAD

**Issue by TalOrenshtein** [vfsfitvnm/ViMusic#49]
### Steps to reproduce the bug

* Go to "https://www.youtube.com/playlist?list=PLUsousxOOgsYnVbgkjGhLUFGXKX9tyIQM"
* Click "Open on app"
* Choose "ViMusic"

### Expected behavior

The app should open the playlist

### Actual behavior

The app shows "Couldn't reach the internet" prompt.

### ViMusic version

0.1.6

### Android version

Android 10

**Comment by vfsfitvnm** [comment]
The error "Couldn't reach the internet" is displayed by mistake (an error still occurs, but it's not a network one).

It is caused by a couple of deleted videos:
![Screenshot_20220619-112048596](https://user-images.githubusercontent.com/46219656/174474275-caaf95b7-8ea8-4a53-985a-7673deb5f873.jpg)

**Comment by TalOrenshtein** [comment]
Alright, can't the app recognise that a video got deleted and just skip it or something?

**Comment by vfsfitvnm** [comment]
@TalOrenshtein Yes, that's how I fixed it - please wait for the next release.

**Comment by TalOrenshtein** [comment]
Tnx!

On 19 June 2022 14:49:41 GMT+03:00, vfsfitvnm ***@***.***> wrote:
***@***.*** Yes, that's how I fixed it - please wait for the next release.
