### ISSUE TITLE
"Share" functionality

### ISSUE THREAD

**Issue by Tylasian** [vfsfitvnm/ViMusic#492]
### Feature description

Ability to share the Youtube source link that the song is from. 

### Why do you want this feature?

Other music streaming apps have this feature, so why not implement it here. I know this is kind of a luxury and a low-priority feature, just would be nice to have so it's more convenient to share music.

**Comment by vfsfitvnm** [comment]
You can already do that (long press a song to show the menu). See #445

**Comment by Tylasian** [comment]
@vfsfitvnm Ahhh thank you! You still may want to consider making a dedicated button because it's not clearly communicated to the users that you can do that in the UI.
