### ISSUE TITLE
Button to clear current queue 

### ISSUE THREAD

**Issue by AndiLeni** [vfsfitvnm/ViMusic#495]
### Feature description

I'd like to have a button to clear the current queue. 

### Why do you want this feature?

When I accidentally enqueued a whole playlist I don't want to remove ever song individually. 

### Additional information

A "swipe to remove from queue" might be another option. It would be at least faster than now.

**Comment by vfsfitvnm** [comment]
Swipe down the collapsed (or mini) player to stop the playback and clear the queue

**Comment by AndiLeni** [comment]
Thanks, this is working.

**Comment by dAtA-TRoN** [comment]
> Swipe down the collapsed (or mini) player to stop the playback and clear the queue

When I swipe the collapsed player down it's gone, but the music just keeps playing. It shouldn't be like that, should it 🤔?
