### ISSUE TITLE
Automatically resume play

### ISSUE THREAD

**Issue by AndiLeni** [vfsfitvnm/ViMusic#497]
### Feature description

It would be nice, if the queue would continue playing as soon as the smartphone reconnects to a Bluetooth device, f.e. when getting in the car. 

### Why do you want this feature?

I would do it with tasker, but vimusic does not seem to react to taskers "play" event.

**Comment by vfsfitvnm** [comment]
Thanks for the suggestion - implemented!

**Comment by Jak2k** [comment]
Is it possible to disable that?

**Comment by vfsfitvnm** [comment]
Yes, it is disabled my default (the toggle is in Settings > Player > Resume playback).
