### ISSUE TITLE
Incorrect album/song cover is displayed on lock screen & notifications

### ISSUE THREAD

**Issue by YarostheLaunchpadder** [vfsfitvnm/ViMusic#504]
### Steps to reproduce the bug

1. Create a custom playlist with at least 3-5 songs.
2. Play one of the songs.
3. Lock the device
The image is displayed correctly.
4. Go back into the app and change the song
5. Lock the phone
Now the image displayed in the player in notifications area is showing the song cover image from the previous song, but the title and artist name is updated to the new song (correctly)

### Expected behavior

It should also update the background image of the player to the new song cover image.

### Actual behavior

After changing the song from the app, the background image in the notifications are stays the same, while all other data is updated.

### Screenshots/Screen recordings

https://photos.app.goo.gl/sZogVoeC3dM1zX9s6

### ViMusic version

V0.5.2

### Android version

Android 13

### Additional information

Google Pixel 6 running Android 13 (Build TP1A.221005.002)

**Comment by vfsfitvnm** [comment]
I can't watch the video, however this is a known A13 bug (see #267). `v0.5.3` will include a workaround to partially mitigate this unwanted behaviour

**Comment by vfsfitvnm** [comment]
PS: you can try the latest debug build - you will notice some improvements!
