### ISSUE TITLE
app crashes whenever I try to play my favorite songs 

### ISSUE THREAD

**Issue by hasseltuff** [vfsfitvnm/ViMusic#505]
### Steps to reproduce the bug

Tried to play favourite songs

### Expected behavior

Play favourite songs 

### Actual behavior

App crashed

### ViMusic version

0.5.2

### Android version

Android 12

**Comment by hasseltuff** [comment]
![Uploading Screenshot_2022-10-24-19-26-45-867_com.google.android.apps.photos.jpg…]()

**Comment by vfsfitvnm** [comment]
Hi, can you provide the logcat? (`adb logcat`)
