### ISSUE TITLE
Swipe down on Mini player window to close/stop the song

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#51]
### Feature description

![image](https://user-images.githubusercontent.com/88180887/174472435-eba1ed49-bfdb-4aa6-95e9-48ea002f7478.png)

we already have swipe up action on this mini player window.
just want an additional feature i.e. SWIPE DOWN on this mini player window to close the player or stop playing song.

### Why do you want this feature?

1. It is the latest feature of both  YT & YT Music. 
2. It is useful and convenient
so it would be better if get implemented in vimusic too.

**Comment by vfsfitvnm** [comment]
I don't think I'll implement it, what are its advantages?

**Comment by Jak2k** [comment]
We need a quick way to stop the playback.

**Comment by NR8124** [comment]
yeah !!!

**Comment by vfsfitvnm** [comment]
You can already stop the playback by clearing the notification - it takes 0.5s more

**Comment by NR8124** [comment]
Fine! i will to fix it or add this feature in future..

**Comment by vfsfitvnm** [comment]
Thanks for the interest in contributing (I really appreciate that).

I want to keep the code base as simple as possible and so the app should be as minimal as possible: few things done right.
This project will eventually enter in maintenance mode - you know - people move on another projects. Moreover, I should get a job very soon. Therefore, the less code, the better.

That's why I'm very peaky when it comes to feature requests: some of them just clobber the code because their advantages are negligible. A minor feature will **not** be implemented unless it costs few lines of code. Lot of lines of code for a negligible advantage is not a acceptable tradeoff.

**Comment by NR8124** [comment]
Yes i can understand what u trying to convey 
i will keep  that in mind and i would love to contribute

**Comment by owencz1998** [comment]
If people was contributing are they aloud to add bigger features for example a new navigation bar with a home page with new releases and charts and ect if they was to maintain it.

**Comment by NR8124** [comment]
Yeah it would be completely fine! Thanks

**Comment by NR8124** [comment]
Btw waiting for you next release eagerly 🙌

**Comment by BluePixel4k** [comment]
> Would a simple swipe to the left (like a notification) do it? Probably easier to implement if looking at how I currently manage things

But a swipe to the left (and to the right) would be more intuitive to play the next song / the previous ones.
This would also be a nice feature.

**Comment by NR8124** [comment]
Yeah, i know about this.  it is implemented in [Blackhole](https://github.com/Sangwan5688/BlackHole).

**Comment by vfsfitvnm** [comment]
> > Would a simple swipe to the left (like a notification) do it? Probably easier to implement if looking at how I currently manage things
> 
> But a swipe to the left (and to the right) would be more intuitive to play the next song / the previous ones. This would also be a nice feature.

I'm referring to the mini player (the collapsed one)...

**Comment by BrightDV** [comment]
> > > Would a simple swipe to the left (like a notification) do it? Probably easier to implement if looking at how I currently manage things
> > 
> > 
> > But a swipe to the left (and to the right) would be more intuitive to play the next song / the previous ones. This would also be a nice feature.
> 
> I'm referring to the mini player (the collapsed one)...

The swipe to the left or to the right should be available for both. The mini player's swipe could be like that:


https://user-images.githubusercontent.com/92821484/175776057-c685feeb-81ec-4e18-a4d2-d677d8782a6a.mp4

**Comment by BluePixel4k** [comment]
>I'm referring to the mini player (the collapsed one)...

Yes, me too.

> The swipe to the left or to the right should be available for both. The mini player's swipe could be like that:
>
>  ScreenRecording.2022_06_25_153634.mp4

Yes, exactly like that. 👍🏼

**Comment by NR8124** [comment]
@vfsfitvnm  ,  If u r planning to implement the swipe left/right to stop the music...

can u add the same swipe left/right gesture to remove the song from up next queue section?
 
If u dont mind and have time to do it
