### ISSUE TITLE
App layout briefly flashes as RTL on launch before going back to LTR

### ISSUE THREAD

**Issue by mhmdanas** [vfsfitvnm/ViMusic#518]
### Steps to reproduce the bug

1. Switch phone to a language with an RTL script (e.g. Arabic)
2. Completely close ViMusic if it's already open, then launch it

### Expected behavior

The layout should be properly displayed in LTR from the app's launch.

### Actual behavior

The layout briefly flashes in RTL before it is switched back to LTR.

### Screenshots/Screen recordings

I realize a screen recording would be very helpful here, but my phone's screen recorder isn't working for some reason. Please tell me if that's an issue for you and I'll try to somehow make a screen recording of the issue.

### ViMusic version

0.5.2

### Android version

Android 12

### Additional information

The phone is a Galaxy A51.

**Comment by ItamiWasTaken** [comment]
I was not able to reproduce

**Comment by mhmdanas** [comment]
@ItamiWasTaken are you sure that you've switch your phone to a language with an RTL script (e.g. Arabic), and that ViMusic was not already open when you launched it?

**Comment by mhmdanas** [comment]
@vfsfitvnm thank you for the swift fix. Cheers.
