### ISSUE TITLE
Default app

### ISSUE THREAD

**Issue by ashuuxoo** [vfsfitvnm/ViMusic#519]
### Feature description

This need to add categories to music app to add to default music app in android

### Why do you want this feature?

Its help to quick play with wireless connected device with just one tap

**Comment by vfsfitvnm** [comment]
Would you elaborate?

**Comment by ItamiWasTaken** [comment]
I believe they are referring to things like this
![Screenshot_20221027-112451](https://user-images.githubusercontent.com/99271684/198331983-78d88918-b939-4862-9165-34a1035b0b63.png)
ViMusic should appear here, but it is not configured properly as a music app

**Comment by ItamiWasTaken** [comment]
As of right now, any app would not see ViMusic as a "music player" what the original issue and my screenshot are referring to are byproducts of this misconfiguration
