### ISSUE TITLE
Cant play or find any song

### ISSUE THREAD

**Issue by SalehAhmedShakib** [vfsfitvnm/ViMusic#520]
![Screenshot_2022-10-26-12-38-37-515_it vfsfitvnm vimusic](https://user-images.githubusercontent.com/31382650/197953812-8629fe91-f31a-4fa2-b115-783ad9bf94a9.jpg)

**Comment by SalehAhmedShakib** [comment]
I have searched several other song but result is same ...

**Comment by vfsfitvnm** [comment]
Use a VPN, YouTube isn't available in your country
