### ISSUE TITLE
Sound is lower

### ISSUE THREAD

**Issue by gcpragnesh** [vfsfitvnm/ViMusic#524]
### Steps to reproduce the bug

I have reproduced it with some wireless devices and my mobile as well but it is giving lower voice for the songs 

### Expected behavior

It would have to stream with high quality and huge sounds 

### Actual behavior

It is not getting as expected quality and volume also even i give 100%volume 

### ViMusic version

0.5.2

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
I don't know what to say. Make sure "Loudness normalization" is Settings > Player is disabled

**Comment by vfsfitvnm** [comment]
@gcpragnesh So, did you have "Loudness normalization" enabled?

**Comment by gcpragnesh** [comment]
Yes but the problem persists

**Comment by vfsfitvnm** [comment]
That's unfortunate then, exoplayer already has 100% volume when the loudness normalization is disabled :/

**Comment by BluePixel4k** [comment]
I noticed the lower sound too. 
The loudness normalization is activated and compared to older ViMusic versions the sound is lower. 
Its really annoying when I listen music in my car or via a sound system. So I have to raise up the volume much.

Within the nerd stats, you can see, that the volume are different over the time. In the past, the volume was good.

Release version 0.5.3:
<img src="https://user-images.githubusercontent.com/77979781/199000129-731b349d-77c8-483a-964d-83d9de4c12cd.png" width="200" />

Debug version [76](https://github.com/vfsfitvnm/ViMusic/actions/runs/3062544325):
<img src="https://user-images.githubusercontent.com/77979781/198999676-faafee72-3fa7-4dae-894d-8883a3a5b687.png" width="200" />

**Comment by vfsfitvnm** [comment]
@BluePixel4k As I said [here](https://github.com/vfsfitvnm/ViMusic/issues/410#issuecomment-1293715683), I already pushed a new implementation. The new one is perfect - it _really_ normalizes the volume - without lowering it much. It normalizes the volume to +5dB, it means songs with an higher loudness will face a loudness decrease. I can set the level any value, so +6dB and +7dB are valid candidates!

**Comment by BluePixel4k** [comment]
Thank you! 👍 I didn't seen this command.
