### ISSUE TITLE
Implement codec unlock patch from ReVanced project to ViMusic for better audio quality

### ISSUE THREAD

**Issue by tvnmguy** [vfsfitvnm/ViMusic#527]
### Feature description

ReVanced codec unlock patch results better audio quality in YT Music, because it enables opus 251 codec. I hope the implementation of codec unlock patch results better audio quality in ViMusic too.

### Why do you want this feature?

For better audio quality!

### Additional information

ReVanced codec unlock patch enables opus 251 codec which results better audio quality in YT Music.

**Comment by vfsfitvnm** [comment]
I already pick 251 when available
