### ISSUE TITLE
YouTube/YouTube music link not opening

### ISSUE THREAD

**Issue by spaulll** [vfsfitvnm/ViMusic#529]
Can't open YouTube/YouTube music links directly by sharing the link. There is no option to share with Vi music. 
<img src="https://user-images.githubusercontent.com/85858522/198334971-82680edb-6c6f-4268-94df-2c4ca0554836.jpg" width="20%"/>

**Comment by vfsfitvnm** [comment]
Duplicate of https://github.com/vfsfitvnm/ViMusic/issues/433. You need to open the url instead of sharing it.
