### ISSUE TITLE
Replay Gain Normalization

### ISSUE THREAD

**Issue by nikhilCad** [vfsfitvnm/ViMusic#53]
### Feature description

Some songs are louder than others in a playlist. Replay Gain Normalization can be used to make them equally loud

### Why do you want this feature?

Variable loudness is annoying and some songs are nor even audible unless you manually pump up volume for that specific song only

### Additional information

If you open "stats for nerds" in a video it shows volume/normalized for that video. I don't know if this is helpful or not.

**Comment by vfsfitvnm** [comment]
Youtube returns a `AudioConfig` object (https://github.com/vfsfitvnm/ViMusic/blob/master/youtube-music/src/main/kotlin/it/vfsfitvnm/youtubemusic/models/PlayerResponse.kt#L23), but I don't know how to use them with ExoPlayer

**Comment by vfsfitvnm** [comment]
Note to self:

_volume_/_normalized_ (nerd stats)

- `WEB_REMIX`
  - _loudnessDb_ > 0:
  _normalized_ = _volume_ - (1 + _volume_ * _loudnessDb_ / 10)
  - _loudnessDb_ <= 0:
  - _normalized_ = _volume_
  
It looks like youtube never reaises the volume.

**Comment by vfsfitvnm** [comment]
Ok, I think I found a solution. I'll just try it in the following days and see if the result is acceptable

**Comment by vfsfitvnm** [comment]
I added a youtube-like normalization in `v.0.1.7`, it's far from perfect, but it's decent.
https://github.com/vfsfitvnm/ViMusic/releases/tag/v0.1.7
