### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by k3rnelPan1c228** [vfsfitvnm/ViMusic#531]
### Feature description

Can you make widget for this app please also thank you for making a wonderful app

### Why do you want this feature?

I usually have all my music stuff in the home screen for quick access, it also helps me to scroll through music and select a one specific song in a big playlist

**Comment by arfanmrafeek** [comment]
Duplicate of #234 

@Bnyro , He may contribute but busy with vacation and he is now more centred towards his repo Libretube.

**Comment by Bnyro** [comment]
I wouldn't assign that to me at the moment, as for know I'm really just too busy with IRL stuff and maintaining LibreTube :/
