### ISSUE TITLE
Status bar readability issues

### ISSUE THREAD

**Issue by ThatTakashi** [vfsfitvnm/ViMusic#532]
When the user scrolls through a list that is long enough it interferes with the status bar(shown below) and causes the text of both the status bar and app contents to become unreadable

![Screenshot_20221028-183854.jpg](https://user-images.githubusercontent.com/45578020/198511969-f940b42b-2c1e-49c7-9bfe-7a72798a1815.jpg)

**Comment by arfanmrafeek** [comment]
I'm saying for long, To hide both, So you don't need to bother it.

**Comment by ThatTakashi** [comment]
> I'm saying for long, To hide both, So you don't need to bother it.

I would say adding a gradient to the top of the screen would work well enough

**Comment by arfanmrafeek** [comment]
This is the reply from Dev on hiding it. 

> I won't implement this feature as it's not clear how to do it; the solution in #400 (comment) is definitely not something a music player app should do.

If you want to see the effect of hiding it check [This 'My comments'](https://github.com/vfsfitvnm/ViMusic/issues/400#issuecomment-1279858983)

**Comment by vfsfitvnm** [comment]
@arfanmrafeek That's another thing

**Comment by vfsfitvnm** [comment]
This behavior is on purpose. Adding a translucent background makes things better only when there's something underneath and such content is not moving (i.e. the perfectly crafted screenshot you attached!). It is unnecessary complicated to add a background when this condition is met.

Also, I think you seldomly need to read the status bar while you are staring at a still list of songs. In such scenario, however, you can scroll the list by just a little so it doesn't overlap a song title.

**Comment by vfsfitvnm** [comment]
Sorry, I closed by accident. I think I can just add a gradient as you proposed, it is definitely feasible and it is a better solution I couldn't think of!

**Comment by vfsfitvnm** [comment]
| With gradient  | Without gradient  |
| ------------- | ------------- |
| <video src="https://user-images.githubusercontent.com/46219656/198573350-a2f11053-5600-4f96-b6fd-b0b0447bf5f5.mp4" />  | <video src="https://user-images.githubusercontent.com/46219656/198573354-11ca1504-8785-41ad-8eb5-7188924923f2.mp4" />  |

I honestly prefer how it looks like now (without gradient)

**Comment by ThatTakashi** [comment]
I love it with the gradient. In my opinion it is not in your face however it does add just enough contrast to the top of the screen to keep everything legible.

**Comment by vfsfitvnm** [comment]
#496 will not make it in the short time

**Comment by arfanmrafeek** [comment]
> I honestly prefer how it looks like now (without gradient)

As you know, I like completely without status bar, But I think it's unnecessary for a music player, So I really like without gradient, Gradient making it more like old fashioned, This is my personal opinion.
