### ISSUE TITLE
Unable to restore backup in app v0.5.3 (backup file greyed out)

### ISSUE THREAD

**Issue by t4628dev** [vfsfitvnm/ViMusic#536]
![Screenshot_20221028-205032_Files](https://user-images.githubusercontent.com/116290452/198673710-f8dc5cfe-9d81-48fb-a27d-3b775d5bb3f4.jpg)

From the screenshot, that I have shared, it is visible that the backup file is greyed out. I am unable to select it. It seems as if the current version (v0.5.3) does not support '.db' format.

Regards,
@t4628dev

**Comment by vfsfitvnm** [comment]
Thanks for reporting. What's your android version?

**Comment by Nekobibu** [comment]
Same problem here. Android 13.
Thanks! 😉

**Comment by t4628dev** [comment]
> Thanks for reporting. What's your android version?

Android 12
Samsung SM-M015G/DS

**Comment by vfsfitvnm** [comment]
Fixed. If you need to restore the database now, download mixplorer from [here](https://forum.xda-developers.com/attachments/mixplorer_v6-58-5_b22090510-apk.5704797/)

**Comment by Nekobibu** [comment]
> Fixed. If you need to restore the database now, download mixplorer from [here](https://forum.xda-developers.com/attachments/mixplorer_v6-58-5_b22090510-apk.5704797/)

Thanks, but ViMusic doesn't appear in the list of apps that can open the file in mixplorer (or other file explorers, for that matter). For now, the best solution is to import with 0.5.2 and then update to 0.5.3.

**Comment by vfsfitvnm** [comment]
> Thanks, but ViMusic doesn't appear in the list of apps that can open the file in mixplorer

It's because vimusic doesn't have to open the file. When you select "restore database", use mixplorer instead of the system file manager to pick the database file

**Comment by Nekobibu** [comment]
> It's because vimusic doesn't have to open the file. When you select "restore database", use mixplorer instead of the system file manager to pick the database file

Mmh... Unless I'm missing something, I can't pick anything when trying to restore the database. ViMusic defaults to the system file manager and doesn't let me choose what to open the file with.
But it's no big deal, I don't need to do it right now. 🙂

Thanks for the great app, by the way!

**Comment by vfsfitvnm** [comment]
> and doesn't let me choose what to open the file with.

That's another great A12 addition, lol. You need to unselect the system file manager as the default app in the system settings

**Comment by Nekobibu** [comment]
> > and doesn't let me choose what to open the file with.
> 
> That's another great A12 addition, lol. You need to unselect the system file manager as the default file manager app in the system settings

Oh, I see! 🤣
Thanks!!

**Comment by t4628dev** [comment]
> > and doesn't let me choose what to open the file with.
> 
> That's another great A12 addition, lol. You need to unselect the system file manager as the default file manager app in the system settings

That's the problem!
`Samsung does not provide such options to default to another file manager.`
(Though options to change other default apps does exist.)

So I am left with no other option, but to get forced to the system file manager.

**Comment by vfsfitvnm** [comment]
At this point you can do what @Nekobibu suggested, but it won't let you downgrade the app without uninstall it first, so you will lose the cache (I don't think it matters: if you need to restore the database you already cleared the app data).

**Comment by t4628dev** [comment]
> At this point you can do what @Nekobibu suggested, but it won't let you downgrade the app without uninstall it first, so you will lose the cache (I don't think it matters: if you need to restore the database you already cleared the app data).

Yes, I cleared the app data after I backed up the data. I wanted to see if the restore feature worked.
I actually found that your app is one of its kind. So I gave it a try. But see the restore feature does not work on my Samsung device.

How about changing the .db file to another file type like .csv?
See, if the restore feature is not working on my Samsung phone, then isn't that it may not work on other Samsung models too?

**Comment by vfsfitvnm** [comment]
Unfortunately the android file manager is flawed. In v0.5.3 I set it to pick only `application/vnd.sqlite3` files, which is the correct mime type for sqlite databases (instead of every binary file (`application/octet-stream`)). Guess I shouldn't have touched it... Changing the file extension won't make any difference

**Comment by t4628dev** [comment]
Or else I can use `ADB` to clear system file manager's data and then try to select a different file manager.

**Comment by t4628dev** [comment]
> Or else I can use `ADB` to clear system file manager's data and then try to select a different file manager.

Didn't work.
For now, it's best to follow what @Nekobibu suggested.
