### ISSUE TITLE
Songs missing in playlist search

### ISSUE THREAD

**Issue by nikhilCad** [vfsfitvnm/ViMusic#54]
### Steps to reproduce the bug

1. Search anything generic like "song" or "90s song
2. Go to playlist tab
3. Open a big enough playlist with like 40-50 songs
4. Now count the songs inside playlist
5. They are less than the shown amount

### Expected behavior

All songs in playlist load

### Actual behavior

Few are not loaded

### Screenshots/Screen recordings

![Screenshot_20220621-092615](https://user-images.githubusercontent.com/47214394/174713226-3034e1fc-60f7-4d41-a0f6-6de975ebadd6.png)
![Screenshot_20220621-092626](https://user-images.githubusercontent.com/47214394/174713233-20c0ae26-8a17-4050-9f08-15b99a673b24.png)

### ViMusic version

0.1.6

### Android version

10

**Comment by vfsfitvnm** [comment]
Working as intended: this is the same playlist in youtube music: https://music.youtube.com/playlist?list=PLJuI8TslmruBRWm261lqlaLZqQ8asSM3V.

As you can see, among the first 200 songs (I'll remove this limit) only 3 songs are playable.

**Comment by nikhilCad** [comment]
So as far I have understood, the app only fetches from youtube music and not from the main youtube website right? In that case in makes sense

**Comment by vfsfitvnm** [comment]
Yep. YouTube music
