### ISSUE TITLE
Import playlists

### ISSUE THREAD

**Issue by Akash23q2** [vfsfitvnm/ViMusic#546]
### Feature description

It will be very nice if one can import their yt music or YouTube playlist directly into app using its url.

### Why do you want this feature?

It is very cumbersome to search for each song and group them one by one.

**Comment by vfsfitvnm** [comment]
You can already do that. Search for similar issues, you'll eventually the holy grail!

**Comment by omk12** [comment]
> You can already do that. Search for similar issues, you'll eventually find the holy grail!

Can u pl tell how to to that. I am not able to find a solution.
