### ISSUE TITLE
Lyrics Caching

### ISSUE THREAD

**Issue by Subtilizer28** [vfsfitvnm/ViMusic#547]
### Feature description

Make it so that the synchronised lyrics gets cached along with the song

### Why do you want this feature?

Would be great as we can access the lyrics when we are offline as well. 

### Additional information

As caching lyrics might increase the cache size of the song itself. So maybe an toggle to enable it or disable it would be great

**Comment by ARBoyGo** [comment]
@vfsfitvnm, I think he is trying to separate it from song cache and an option to limit the cache just like we do to thumbnail and song cache.

**Comment by vfsfitvnm** [comment]
I think this is avoidable... lyrics are already saved once they are fetched for the first time; not sure how many lines of code the scenario "I already listened to this song in the past and never read its lyrics; and now I want to see the lyrics but I don't have internet access" is worth.

**Comment by ARBoyGo** [comment]
> "I already listened to this song in the past and never read its lyrics; and now I want to see the lyrics but I don't have internet access" is worth.

That will consume more data right?
