### ISSUE TITLE
Material you

### ISSUE THREAD

**Issue by ansarimohammed422** [vfsfitvnm/ViMusic#55]
### Feature description

Could you implement material you and wallpaper theming in your app it would me great

### Why do you want this feature?

Because android 12.1 users can benefit from this and it will be more inline with android 12 whole ui

### Additional information

Please add this feature

**Comment by vfsfitvnm** [comment]
I agree the UI should be improved, but I won't adopt it for many reasons I don't want to discuss now.
You can fork this project and re-write the whole UI code to adopt the unstable and incomplete components google has to offer, of course.

**Comment by ThatOneCalculator** [comment]
Could you please elaborate on how it's "unstable"? At least on Pixel phones, all Material You apps seem to work great, if not better than MD2 apps.

**Comment by vfsfitvnm** [comment]
When I tried `androidx.compose.material3` I had to re-implement from scratch the very first components I used (TabRow, HorizontalPager). This isn't a good sign.

Moreover, I don't appreciate low effort suggestions like this - there isn't any magic switch which enables MD3 automatically, but I have to redesign the whole UI (and UX). So, I only listen to who tells me *how* to do things. That is, if you want me to adopt MD3, you have to provide sketches (or whatever) of this application in MD3. You aren't a designer? Me neither.

**Comment by ThatOneCalculator** [comment]
No need to be so hostile. Because it's a different design system, of course there's going to be some re-implementation needed (I'm a developer too, I know how these things go...)

The Material Design foundation already has migration guides, UI/UX guides, design guides, etc. I'd recommend checking it out. https://m3.material.io/

**Comment by Jak2k** [comment]
@vfsfitvnm sayed right. m3 is **not stable** for jetpack compose. it's only in alpha.
