### ISSUE TITLE
Can't find certain YT videos

### ISSUE THREAD

**Issue by THEVINDICATOR** [vfsfitvnm/ViMusic#555]
### Steps to reproduce the bug

1. Search ‘Omar Jabbie’
2. Can't find videos relating to his recitation of the Qur'an even though their are plenty on YouTube/YT Music

### Expected behavior

I should be able to view these videos as they are widely available on YouTube 

### Actual behavior

Though I cannot find them even if I search through related terms

### ViMusic version

0.5.3

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
I can't find those videos on YouTube music: https://music.youtube.com/search?q=omar+jabbie

**Comment by THEVINDICATOR** [comment]
Oh I see, though I can't seem to find the Artist name and the following
tracks that are on YT Music (see screenshot).
