### ISSUE TITLE
Importing playlists from spotify

### ISSUE THREAD

**Issue by rickviper** [vfsfitvnm/ViMusic#557]
### Feature description

Please introduce a feature to import playlists to Vimusic from other music apps like Spotify (if it's possible to do so).

### Why do you want this feature?

This is a very useful feature as it'll allow to switch to Vimusic very easy and smooth and save us a lot of time and hassle to recreate our favourite playlist within seconds instead of searching and adding the songs one by one.

**Comment by vfsfitvnm** [comment]
Duplicate of #295
