### ISSUE TITLE
Please update the app so that we are able to play both youtube songs and videos on this app

### ISSUE THREAD

**Issue by nitant96-24** [vfsfitvnm/ViMusic#558]
### Feature description

Please update the app so that we are able to play both youtube songs and videos on this app

### Why do you want this feature?

It make the app better than Spotify

**Comment by Barina** [comment]
Such a great feature.
I wonder why are you insist not to include it?

**Comment by Driftinginfinitely** [comment]
> Such a great feature. I wonder why are you insist not to include it?

This feature is available on another app on Github if that's what you prefer. I find that the app is fine as it is right now. Lightweight and quick.

**Comment by Barina** [comment]
> I find that the app is fine as it is right now.

Understood. :)
That means you will also not accept a PR for that, right?
Thanks

**Comment by Driftinginfinitely** [comment]
> 

Hey, I think you are referring to my reply and just to clarify that I am app user and I didn't make this app! I was just responding because I wanted to say that there is another app that you could look at that has both, but that I find this one more lightweight and fast.

**Comment by Barina** [comment]
> > 
> 
> Hey, I think you are referring to my reply and just to clarify that I am an app user and I didn't make this app! I was just responding because I wanted to say that there is another app that you could look at that has both, but that I find this one more lightweight and fast.

Oh my bad lol
The other app is black hole by any chance?

**Comment by Driftinginfinitely** [comment]
I'm referring to Vibe Music
