### ISSUE TITLE
Pls update v0.4.3

### ISSUE THREAD

**Issue by abdulrahmanjahari** [vfsfitvnm/ViMusic#561]
![sketch1667232640y840.png](https://user-images.githubusercontent.com/117058084/199055551-ba7e419b-e2ac-40c0-b600-921e5f5c4ce7.png)

This is just my idea. I'm still using v0.4.3 but search sugestion is not working anymore. I like simple. The side bar just took so much place and artist and albums are useless. 
and I kinda hate the recommended song on quick pick.
But after all I like it👍

**Comment by ARBoyGo** [comment]
Wait... We are using version 5.3 
The UI request you made kinda look like new UI. 
The apk is available in release page. If you don't know how to open click [Here](https://github.com/vfsfitvnm/ViMusic/releases) 

If you need quick download click [Here](https://github.com/vfsfitvnm/ViMusic/releases/download/v0.5.3/app-release.apk)
