### ISSUE TITLE
Custom volume level for Loundness Normalization option

### ISSUE THREAD

**Issue by Ao1Pointblank** [vfsfitvnm/ViMusic#568]
### Feature description

Please add a slider for the decibels users would like their music to play at when the normalization option is enabled.

### Why do you want this feature?

This is important to me, because many songs in my main playlist have different volume levels, which forces me to use loudness normalization. However, this changes the overall loudness to a much lower volume which negatively impacts user experience, particularly in cars, I've noticed. 
When I get a phone call through bluetooth to my car, I have turned up my car's speakers so high to compensate for the normalization that my eardrums get thoroughly *annihilated* 😂. 
Normal speaker volume in my car is "15" and if I'm driving with windows open, I turn it up to 28-32. I know these number may be pretty arbitrary, but when I use Vimusic with Loudness Normalization, 30 becomes the normal "windows up" volume level... 

I'm curious what the current volume is (in decibels, if that is how it is coded), which the app tries to achieve.

**Comment by vfsfitvnm** [comment]
Don't worry, the next release will fix this! (see https://github.com/vfsfitvnm/ViMusic/issues/524#issuecomment-1296990221!)

**Comment by vfsfitvnm** [comment]
This happens because my current approach consists in lowering the volume, so loud songs have like 10% of the volume, while quiet songs have 100%. However, this approach is imprecise and has the drawback you are facing.

**Comment by vfsfitvnm** [comment]
Almost every youtube music song has a loudness within the range -10dB, +10dB. The current approach just makes every song sound like -10dB (:-1:). The new one will make every song sound like +5dB.
