### ISSUE TITLE
Search suggestions not working

### ISSUE THREAD

**Issue by trollman64** [vfsfitvnm/ViMusic#569]
### Steps to reproduce the bug

1. Click search button and type anything

### Expected behavior

Search should show results

### Actual behavior

Nothing shows up

### ViMusic version

0.5.3

### Android version

Android 7.0

### Additional information

Due to the way the app works you cannot search without suggestions. Thus this bug renders the app impossible to use.

**Comment by vfsfitvnm** [comment]
Hi, youtube music limited the search suggestions to logged in accounts only. You can verify it yourself by visiting youtube music in incognito mode

**Comment by trollman64** [comment]
I just found out I can still search on my phone but the physical enter key on my tablet doesn't do anything.

**Comment by NeeRaj-2401** [comment]
> Hi, youtube music limited the search suggestions to logged in accounts only. You can verify it yourself by visiting youtube music in incognito mode

[InnerTune](https://github.com/z-huang/InnerTune)'s dev implemented login feature in [this commit](https://github.com/z-huang/InnerTune/commit/144801789de75e117c884eefd7676330643a9d31). which not only helped in search suggestions but also many YTM features like listen again, mixed for you, recommended etc etc

**Comment by rancidfrog** [comment]
@vfsfitvnm 
Why use youtube music?
I am curious, as music is just limiting youtube capabilities.
Why not use same api newpipe uses?
That why users are not blocked, search works, etc.

Links from app are just replacing youtube links from
Www.youtube.com
To
Music.youtube.com

I do not understand the usefulness of an api with serious limitations, not all videos can be played in app, search does not work properly, ... and countless other cons

What are the benefits?

**Comment by vfsfitvnm** [comment]
@rancidfrog There are many reasons why youtube music is better than youtube if you want to listen to music (artists, albums, clean audio tracks, radio, related... I could continue). There is only one reason to choose yt over ytm

**Comment by vfsfitvnm** [comment]
As I already knew, search suggestions are working again ¯\\_(ツ)_/¯
