### ISSUE TITLE
Shuffle button in songs cache

### ISSUE THREAD

**Issue by cryptolux** [vfsfitvnm/ViMusic#570]
### Feature description

The shuffle button disappeared from the songs cache list.  Maybe there are plans to move it to the quick launch screen in the form of "my radio station" type of thing?  Or maybe I just can't find it?  Anyway, love the app and all the enhancements!   Keep up the good work!

### Why do you want this feature?

I miss it.

**Comment by vfsfitvnm** [comment]
The button disappears when you scroll downward and reappesrs when you scroll upwards

**Comment by cryptolux** [comment]
Unless i am completely missing it, not on mine.  Not under the songs catrgory at least.  What i get is a search button and a back to top button that appears.  Thanks
![Screenshot_20221103-101201](https://user-images.githubusercontent.com/14266772/199744823-bf1a908d-e3f0-43c1-8044-d53c4e8a144c.png)

**Comment by vfsfitvnm** [comment]
Oh, if you meant the song list (the one in the home screen), then no, there's no shuffle button. You typed "songs cache list" so I thought you were referring to the "Offline" playlist.

**Comment by cryptolux** [comment]
Thank you!  Thats what i was looking for!
