### ISSUE TITLE
Make a new Offline Music player 

### ISSUE THREAD

**Issue by Iam-Eshwar** [vfsfitvnm/ViMusic#574]
Hii brother new suggest for u ..
Make a new Offline Music Player app as u created ViMusic and keep it as  below UI design I attached below image ![Screenshot_2022-11-03-18-37-07-001_it.vfsfitvnm.vimusic.jpg](https://user-images.githubusercontent.com/45062300/199728713-00560532-a584-450b-b613-b334339c0891.jpg)

**Comment by vfsfitvnm** [comment]
If you are reading this, I blocked you for spamming. I already deleted 3 or 4 low effort, useless, no sense issues submitted by you in the past 24 hours.

**Comment by ARBoyGo** [comment]
This dude is controlling telegram 🤦
