### ISSUE TITLE
Its a Maybe, but a pc app sounds pretty interesting

### ISSUE THREAD

**Issue by WizardNight7718** [vfsfitvnm/ViMusic#576]
### Feature description

![16675266435295888661231745083809](https://user-images.githubusercontent.com/70345477/199867921-ef60e563-1d6e-4e53-959b-90a797fb3041.jpg)

### Why do you want this feature?

I just want to listen to music with no distractions and also like the additions

**Comment by vfsfitvnm** [comment]
Yeah, it would be cool, but as I said in #268, I'm not planning to do so now. It will be worked on once I need it
