### ISSUE TITLE
Android Auto

### ISSUE THREAD

**Issue by danytheghost** [vfsfitvnm/ViMusic#579]
### Steps to reproduce the bug

....

### Expected behavior

Icon should appear into Android Auto

### Actual behavior

Icon of ViMusic is not appearing in the list of apps available on my car

### Screenshots/Screen recordings

...

### Logs

...

### ViMusic version

0.5.1

### Android version

Android 12

### Additional information

...

**Comment by vfsfitvnm** [comment]
Please read the full discussion here #47

**Comment by danytheghost** [comment]
I Red it but cannot get how I should enable the icon in Android Auto

Il ven 4 nov 2022, 16:54 vfsfitvnm ***@***.***> ha scritto:

**Comment by vfsfitvnm** [comment]
https://androidaps.readthedocs.io/en/latest/Usage/Android-auto.html#settings-in-android-auto-app-on-your-phone
