### ISSUE TITLE
automatic backup

### ISSUE THREAD

**Issue by Alliba** [vfsfitvnm/ViMusic#58]
automatic backup of favorites, playlists, APP settings would be cool...
which is carried out in the background once a day or once a week.

this would save manual backup.

**Comment by vfsfitvnm** [comment]
The backup is intended for restoring the database whenever you change device or wipe its data - in both these cases there's no benefit in doing a scheduled automatic database, as you would still need to transfer the backup file to somewhere else (a manual operation) - at this point you could take few seconds extra to manually save the backup as well.
