### ISSUE TITLE
See all option

### ISSUE THREAD

**Issue by tvnmguy** [vfsfitvnm/ViMusic#581]
### Feature description

Give see all option for 'Related album', 'Similar artist' and 'Playlists you might like' as a list or grid manner

### Why do you want this feature?

For better reachability, easiness and convenient

### Additional information

![IMG_20221105_085633](https://user-images.githubusercontent.com/116799295/200099167-19639e8f-e192-4e66-adbc-e4dbfd1135ee.jpg)

https://user-images.githubusercontent.com/116799295/200099179-cad80e54-3ca6-4a37-b1e5-8303f9b2927d.mp4

**Comment by vfsfitvnm** [comment]
I like the UI, but it doesn't make sense for those items - there are like 10 albums/playlist etc at most. It would be appropriate for the artist page instead

**Comment by tvnmguy** [comment]
> I like the UI, but it doesn't make sense for those items - there are like 10 albums/playlist etc at most. It would be appropriate for the artist page instead (the artist songs/albums/singles may be more than 20)

The horizontal scroll little bit annoying for me.
