### ISSUE TITLE
Tags are not correct [v.0.5.4]

### ISSUE THREAD

**Issue by rancidfrog** [vfsfitvnm/ViMusic#585]
Album cover and song tags are incorrect.

Example,
https://youtu.be/GP_LpUoNx-I

App,
![](https://i.imgur.com/CDrHEhQ.png)

This version does not include ed sheerans

Browser,
![](https://i.imgur.com/BMiwZN5.jpg)

**Comment by vfsfitvnm** [comment]
https://music.youtube.com/watch?v=GP_LpUoNx-I

The music version does
