### ISSUE TITLE
Switch between sync and unsync lyrics 

### ISSUE THREAD

**Issue by sidrockzz98** [vfsfitvnm/ViMusic#587]
### Feature description

Option to swipe and switch between synced and unsynced lyrics. 

### Why do you want this feature?

A lot of songs i prefer either don't have synced or unsynced lyrics. But a lot of time they have atleast one of the two. An option to just swipe between lyrics option would be cool.

**Comment by vfsfitvnm** [comment]
? Why isn't the button in the menu enough?

**Comment by sidrockzz98** [comment]
Too much steps just to switch to lyrics. It would be cool if it was just 1
step process. Maybe "Sync"/"Unsync" button on the lyrics page.

**Comment by vfsfitvnm** [comment]
Won't implement a gesture for this thing. Sorry
