### ISSUE TITLE
Make a self-updating APK

### ISSUE THREAD

**Issue by Penknife0915** [vfsfitvnm/ViMusic#589]
### Feature description

It would be great to have a self-updating version of the APK.

### Why do you want this feature?

This would be helpful for those who choose not to run Android with F-Droid (https://wonderfall.dev/fdroid-issues/) but also want to use always newest version of APK.

### Additional information

CloudStream, NewPipe and Signal are a great examples of an apps that provides a self-updating APK.

**Comment by rancidfrog** [comment]
You can look at the following code to see a working example of update detection and notification:
- https://github.com/libre-tube/LibreTube/pull/391
- https://github.com/M66B/FairEmail/commit/055f16368755031280e4a626059eef2e70570ef9 


These apps implemented an update checker and notifier.
So, when a new update is released, a notification appears which either points to release section or directly to latest apk

**Comment by faustaahmad** [comment]
If you used a lots of apps that can only downloaded from github release, consider using [Obtainium](https://github.com/ImranR98/Obtainium)[^1]
It's still in early phase, but the apps does it's job quite well but it's far from perfect
[^1]: Fdroid, IzzyOnDroid, Gitlab release also supported

**Comment by vfsfitvnm** [comment]
I can't add this feature while the app is published on FDroid and I won't create app flavors to do so. Sorry
