### ISSUE TITLE
Search Suggestion

### ISSUE THREAD

**Issue by 11xjas** [vfsfitvnm/ViMusic#594]
### Feature description

It would be really helpful if we get search suggestions while typing in search bar.

### Why do you want this feature?

![Screenshot_20221106-160137](https://user-images.githubusercontent.com/93155066/200165877-c01d29f2-1da7-486d-a375-d288f4703cb2.jpg)

### Additional information

![Screenshot_20221106-160137](https://user-images.githubusercontent.com/93155066/200165891-65807a92-fd1d-4b3e-a028-f6353e1cb5d5.jpg)

**Comment by vfsfitvnm** [comment]
See #569
