### ISSUE TITLE
Suggestions are not showing up 

### ISSUE THREAD

**Issue by John189903** [vfsfitvnm/ViMusic#596]
### Steps to reproduce the bug

1. Click on the search icon
2. Start typing the song name
3. Suggestions are not coming up

### Expected behavior

Should see suggestions 

### Actual behavior

No suggestions 

### Screenshots/Screen recordings

![Screenshot_2022-11-06-11-57-25-22_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/110436305/200192444-0f75d8d1-c820-413a-9de3-30010fa80b22.jpg)

### ViMusic version

0.5.4

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
Duplicate of #569
