### ISSUE TITLE
User statistics

### ISSUE THREAD

**Issue by pluja** [vfsfitvnm/ViMusic#599]
### Feature description

Just like Spotify and other platforms allow you to see your historic statistics (most played songs, artist, play time, etc.), it would be great to have this on ViMusic.

This feature does not necessarily need to implement any UI for the statistics. I see it as just an option like "Collect statistics". Then, if enabled, every song you play, time, artist, etc. would get recorded on the Database. A new option, say "Export statistics", would appear that allows the user to export everything as a simple .json file.

Then, every user could parse the JSON file to get our own statistics. And I am sure that side-projects would appear to parse such files in a good-looking way.

### Why do you want this feature?

I think it is very nice to see how one listens to music, which artists are the most played, what songs, how much music does one play, genres....

**Comment by Jak2k** [comment]
You can already see most played and playtime

**Comment by vfsfitvnm** [comment]
Yeah, I won't add a dedicated screen for such content - you can already sort the songs by their playback time. If you want to extrapolate more information (i.e. the playback time for a given artist), you can just export the database and query it using `sqlite3` (or whatever).

The way youtube organizes its catalogue just makes this feature wobbly. _song_ <---> _artist_ links are missing sometimes, and _remixed song_ <---> _artist_ links are not conceived at all.
