### ISSUE TITLE
Youtube Playlist Add to the the App

### ISSUE THREAD

**Issue by arbintm** [vfsfitvnm/ViMusic#6]
Can you make  to  add  a  existing playlist from youtube to add  to the app, and  make some green round icon next  to the music  when it cached or somthing to know  wich music  we  can listen offline and a  settings to cache or only stream will be nice, btw  nice  app 👍👍👍👍

**Comment by arbintm** [comment]
Importing playlist from youtube is limited to 200, for the next  update 👍

**Comment by vfsfitvnm** [comment]
@arbintm 
Unfortunately, YTM currently has a limit of 200 queued songs - I don't think there's something effective I can currently do. I also believe this should be reported in another github issue.

Eventually youtube will increase its limit.
