### ISSUE TITLE
Data Saving option

### ISSUE THREAD

**Issue by nateRiver111** [vfsfitvnm/ViMusic#60]
### Feature description

It will be helpful an option to enable data saving mode. Stream quality dropping to the lowest and maybe thumbnails quality reduced too.

### Why do you want this feature?

I'm not a big audiophile and I REALLY need the data saving.

PS: the feature to play already streamed songs offline is awesome, thank you.

**Comment by JustNaturalCake** [comment]
I really like this, I do use 4G often when Im not home and music is my life. If we could download music that would be even better like how Spotify does it. 👍

**Comment by vfsfitvnm** [comment]
@JustNaturalCake Songs get cached when you play them for the first time. The next time you won't need an internet connection to play them.

**Comment by JustNaturalCake** [comment]
> @JustNaturalCake Songs get cached when you play them for the first time. The next time you won't need an internet connection to play them.

Oh thank you i didnt notice cause i am on wifi all day

**Comment by nateRiver111** [comment]
I'm using mobile data always and it will be very nice if this feature gets added.

Also a few line of code could do the trick, with an on-off switch that changes this `format.itag == 251 || format.itag == 140` for `format.itag == 249 || format.itag == 139`

I could be terrible wrong tho

**Comment by nateRiver111** [comment]
I was coming to send the comment and ended up closeing it cuz I'm idiot

**Comment by vfsfitvnm** [comment]
> I'm using mobile data always and it will be very nice if this feature gets added.
> 
> Also a few line of code could do the trick, with an on-off switch that changes this `format.itag == 251 || format.itag == 140` for `format.itag == 249 || format.itag == 139`
> 
> I could be terrible wrong tho

Unfortunately it's not that simple!

Changing the `itag` is not enough: you also need to change the cache key and perform a little refactoring to the database (I store the content length in bytes, and a lower quality will result in a lower content length of course, so I need a separate table for that).

All of this is doable, however there are other things to figure out:
- Is this really necessary? E.g. unless you listen to many different songs every day, I doubt you will run out of data (well, it probably depends on your mobile data plan). Also, lowering the quality would just postpone the problem.
- How many people do actually need this?
- Under a "data saving" mode, should I also load **every** thumbnails?

**Comment by nateRiver111** [comment]
> Unfortunately it's not that simple!

Yeah, that's what I thought.

> Is this really necessary? E.g. unless you listen to many different songs every day, I doubt you will run out of data (well, it probably depends on your mobile data plan).

My data plan is as bad as it can get so I will certainly run out of data.

> Also, lowering the quality would just postpone the problem.

I don't think so. Right now a song is about 3-4MB(1GB is about 290 songs) but in low quality songs are about 1-2MB(1GB is about 680 songs, that's more than twice the amount of song for the same data) and you probably can store more songs in the offline cache as they are smaller.

> How many people do actually need this?

That I can not answer, most of people has WiFi at home and such and with the feature that stores the chunks for offline playing I **guess** not many people will need this. Anyhow is a pretty common feature of streaming services.

> Under a "data saving" mode, should I also load every thumbnail?

Ideally the less downloads the better.

**Comment by vfsfitvnm** [comment]
I've been using the release build app for 56 days and I made 790MB of network requests - I listen to music 3 hours every other day, so 1.5 hours a day. My database has 116 songs (but there are more as I deleted a bunch of songs I didn't like - roughly 100MB of storage).

I don't want to prove anything, I just wanted to share my usage - it may helpful to you.

If you own a computer and you **absolutely** need to save data from today, you can clone the repository, edit the `itag` and make a release build. Of course, you could also use another app or service which immediately fits your needs.

I will probably support it at a certain point... who knows!

**Comment by vfsfitvnm** [comment]
To add more on this, I think a prior requirement is merging the application database (data.db) and the one exoplayer uses to track its cache (exoplayer_internal.db). This would help a lot.

Unfortunately, it doesn't seem possible yet: exoplayer uses `SQLite*` classes, but Room uses `SupportSQLite*` classes - they don't have any relationship.

Also, I need to customize / change the cache database schema to accomodate our needs.

So, the solution would be re-implementing the whole cache system - e.g. copy and paste exoplayer classes with little (?) modifications - and I honestly don't know how hard it would be... Also, I don't know how it would work with the existing classes like `DataSpec`.

**Comment by caveman1973** [comment]
I see no reason to lower the quality. Most of the songs you play are around 140 kbps. Less than that the quality decreases considerably. Even a "not audiophile" would notice.

Play the songs you like on WiFi to cache them. Delete garbage from your phone if you run out of storage.

I don't want to open a ticket but would be nice to play AAC 256 kbps. Vanced YouTube Music supposedly plays that when you choose high quality playback in options.

**Comment by vfsfitvnm** [comment]
> I don't want to open a ticket but would be nice to play AAC 256 kbps

This is just impossible. This quality is only available to youtube premium users - at that point there's no reason to use vimusic

**Comment by mhmdanas** [comment]
> Most of the songs you play are around 140 kbps. Less than that the quality decreases considerably. Even a "not audiophile" would notice.

It would indeed lower the quality noticeably, but some people (like me) just don't care that much.

**Comment by AndiLeni** [comment]
I'd like to see this feature too. 
As dumb as it sounds, mobile data plans in Germany are still quite expensive and small. 
Roaming in swiss costs 25 cents for one MB. 

And as far as sound quality is concerned, I actually don't care since I play my music in the car via Bluetooth.
