### ISSUE TITLE
UWP App

### ISSUE THREAD

**Issue by komals1** [vfsfitvnm/ViMusic#601]

**Comment by IntoTheVoid-900** [comment]
If you mean a Windows port, this app is built for Android. It would be a completely new app. I do want a desktop equivalent for this, though. The best ones I have found are [Spotube](https://spotube.netlify.app/) and [Youtube Music Desktop](https://th-ch.github.io/youtube-music/). Spotube tries to be a free, privacy respecting Spotify Premium, and syncs playlists with your Spotify account (a bit annoying to set up), while YouTube Music Desktop is just an electron app that loads the YouTube Music websites, and then lets you add its "plugins". Plugins include AdBlock, SponsorBlock, etc.

**Comment by IntoTheVoid-900** [comment]
There is also [Beatbump](https://github.com/snuffyDev/Beatbump), which is a website that you can install as a PWA. It is a quite buggy because it is mid-rewrite.
