### ISSUE TITLE
Playlist export Bluetooth 

### ISSUE THREAD

**Issue by Edotor** [vfsfitvnm/ViMusic#603]
### Feature description

If it's possible to add this feature, to export the playlist between two devices with vimusic installed in both by Bluetooth. This request because I have difficult to export from mobile phone to my Android car radio. If not possible by Bluetooth if you can make an online account like Google drive to export backup and take it from other device.
Thanks in advance 

### Why do you want this feature?

For better performance and a major usability

**Comment by vfsfitvnm** [comment]
Incorporating in #523
