### ISSUE TITLE
New button add

### ISSUE THREAD

**Issue by ErenYeager95** [vfsfitvnm/ViMusic#609]
### Feature description

Search for a song in the downloaded and favourites. There is no search button there is just shuffle button.

### Why do you want this feature?

So that I can find my offline song easily without scrolling and searching.

### Additional information

![Picsart_22-11-09_14-48-08-485](https://user-images.githubusercontent.com/117813860/200790121-a3ff1eea-5f9a-4f17-8b84-3479230c290d.jpg)

This is edited image by me this is what I ment....
Thank you and sorry for the trouble..

**Comment by vfsfitvnm** [comment]
You can search a local song in the search screen, tap the  "local" tab
