### ISSUE TITLE
Notification thumbnail and song mismatch

### ISSUE THREAD

**Issue by deepu2** [vfsfitvnm/ViMusic#61]
### Steps to reproduce the bug

1. Play a song from scratch
2. The thumbnail displays correctly only for the first song in queue
3. The second song' thumbnail will show first song's thumbnail
4. The third song's thumbnail will show the second song's thumbnail and so on..

This doesn't happen if you skip to the next song in queue. The successive songs show same behaviour if you let it play completely.

### Expected behavior

Thumbnail should show actual thumbnail instead of previous song's thumbnail

### Actual behavior

It shows previos thumbnail

### ViMusic version

0.1.7

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
This is solved in the upcoming release, however it still happens only when you spam the skip to next/previous button - the OS suppresses notification updates because of that spam
