### ISSUE TITLE
Search bug

### ISSUE THREAD

**Issue by rancidfrog** [vfsfitvnm/ViMusic#610]
The search has changed behaviour somehow.
Before when I searched using terms nothing showed up, but when I entered complete url it found the song.

Somehow, this has reversed.
Now when I search with Url, I get no results:
![](https://i.imgur.com/83aTkqR.png)

But, search terms are now working,
![](https://i.imgur.com/usbNHtQ.png)

Is there a reason why this is happening?
It is strange behaviour that one search works while the other does not, and how did it reverse behaviours, was there changes made to searching?

**Comment by vfsfitvnm** [comment]
The search results are returned by youtube. Ask youtube why it happens

**Comment by rancidfrog** [comment]
@vfsfitvnm

It is a problem with app,
Innertune returns the result:
https://www.youtube.com/watch?v=ZRmmUW9AwCQ

Innertune:
![](https://i.imgur.com/p94dA6P.png)

Vimusic:
![](https://i.imgur.com/tIHRYum.png)

**Comment by vfsfitvnm** [comment]
Tap the "video" tab in the search result screen
