### ISSUE TITLE
App closing issue 

### ISSUE THREAD

**Issue by Prasadmuthyala** [vfsfitvnm/ViMusic#611]
### Steps to reproduce the bug

While playing song i try to remove app from recent files (close app).but it is closed but song still playing 

### Expected behavior

When we remove application from recent files or close song should pause 

### Actual behavior

While playing song i try to remove app from recent files (close app).but it is closed but song still playing 

### ViMusic version

Version 0.5.2

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
See #153
