### ISSUE TITLE
Doesn't show up in Kustom apps as media player

### ISSUE THREAD

**Issue by cakePhone** [vfsfitvnm/ViMusic#619]
### Steps to reproduce the bug

Use any Kustom app and go to settings > general > Preferred music player. ViMusic doesn't appear.

### Expected behavior

ViMusic should appear as music player in Kustom apps

### Actual behavior

ViMusic doesn't show up in the options.

### ViMusic version

0.5.4

### Android version

Android 13

### Additional information

Bug also reported to Kustom bc idk if it depends on the individual apps or Kustom.

**Comment by NeeRaj-2401** [comment]
> Preferred music player. ViMusic doesn't appear.

Don't u know that ViMusic is music streaming app. It does not support local music player.

**Comment by vfsfitvnm** [comment]
Moreover, I don't even know what Kustom is

**Comment by cakePhone** [comment]
> Moreover, I don't even know what Kustom is

It's pretty much the team behind KLWP and KWGT, very good customisation apps to make custom widgets and live wallpapers. The issue in question here is that it allows for Music Info to be shown and controlled. There's a setting in the app that allows for you to choose the preferred music app and ViMusic doesn't show up there, which I found odd, and makes it impossible to use Kustom apps' functionality with ViMusic, not even if set to automatic (works by detecting current app playing media).

**Comment by vfsfitvnm** [comment]
ViMusic already implements the media session api (that's why you can install a third party widget that controls music), so I don't really know what's missing

**Comment by cakePhone** [comment]
> ViMusic already implements the media session api (that's why you can install a third party widget that controls music), so I don't really know what's missing

Alright thank you. I've contacted Kustom to try to see if I get something working.

**Comment by Ontega** [comment]
Try use persistent notification
$ni(s0, title)$
![Screenshot_20230329_213155](https://user-images.githubusercontent.com/104723005/228598869-ce49b155-354e-43bf-a323-d4a2507dc409.jpg)
