### ISSUE TITLE
Crash when searching lyrics online

### ISSUE THREAD

**Issue by TheAnonyUnknown** [vfsfitvnm/ViMusic#62]
### Steps to reproduce the bug

Play any song
Tap on lyrics button.
Now, tap on Search Online button.
The app crashes.

### Expected behavior

The app should search for lyrics on web upon clicking Search Online button.

### Actual behavior

The app crashes.

### Screenshots/Screen recordings

![IMG_20220629_204304](https://user-images.githubusercontent.com/87353286/176473026-0bbe5e24-9444-45dd-b226-8798d38b670b.jpg)

### ViMusic version

0.1.7

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
I cannot reproduce on A12 emulator.
What browser(s) did you install? Could you try install Firefox just to see if it works?

**Comment by TheAnonyUnknown** [comment]
https://user-images.githubusercontent.com/87353286/176586516-9bb090e1-787b-40bc-9410-48e760dba9a7.mp4

```ruby
Hope it'll help you to understand the issue better!
```

**Comment by vfsfitvnm** [comment]
The video doesn't load

**Comment by TheAnonyUnknown** [comment]
Oops, what's the issue!
I had uploaded successfully.

I'll re-upload.

**Comment by TheAnonyUnknown** [comment]
Re-uploaded, but still same issue.

Dropping uploadgram link: https://dl.uploadgram.me/62bd97756a431h

**Comment by vfsfitvnm** [comment]
Unfortunately the screen record is not helpful at all.
Would you provide a logcat?
Also, could you try install Firefox just to see if it works?

**Comment by TheAnonyUnknown** [comment]
I unfortunately, can't provide logs as I've neither a pc nor root access!

And, I'll check installing Firefox.

**Comment by vfsfitvnm** [comment]
I confirm `com.android.chrome` hasn't registered a `android.intent.action.WEB_SEARCH` intent filter.`android.intent.action.SEARCH` didn't work either.

However, I just added a check so it doesn't crash anymore.

**Comment by TheAnonyUnknown** [comment]
Hmm, nice.
