### ISSUE TITLE
Disable the Clear Data button in Application info of Manage Application

### ISSUE THREAD

**Issue by Vexcited** [vfsfitvnm/ViMusic#627]
### Feature description

Show a Manage Data button instead of Clear Data button in the Application storage's Informations.

### Why do you want this feature?

Basically, when you go to the storage information of an application, you have two options: `Clear data` and `Clear cache`.

Since the cached songs are stored in data and not cache, if some random optimizer application is running on the phone, the application's data will always get cleared (that's what I'm going through and I can't even disable it)

The solution to that is to disable that `Clear data` button and instead use the `Manage data` button which will redirect to the app and then you'll be able to manage the data in the app and prevent them to be cleared by any other application.

### Additional information

I don't know a lot about Kotlin or Android development, anyway I saw some SO questions like this one: `https://stackoverflow.com/a/7424193` so I think that it should be feasible to implement. Don't know if it's hard though.

**Comment by vfsfitvnm** [comment]
> Since the cached songs are stored in data and not cache,

Cached songs are stored in the cache, actually. 

> if some random optimizer application is running on the phone

Unless you are referring to a bloatware, the OS itself clears the cache of some applications when there isn't much storage space left.

You may be interested in #384
