### ISSUE TITLE
Playlsit url not recognized

### ISSUE THREAD

**Issue by farzana840** [vfsfitvnm/ViMusic#630]
### Steps to reproduce the bug

I made the playlist public, then pasted the link on vimusic. 

### Expected behavior

The app should open my playlist

### Actual behavior

No results. Also I'm not able to click the link and open it in vimusic. 

### ViMusic version

0.5.4

### Android version

Android 10

### Additional information

Here's the playlist link
https://youtube.com/playlist?list=PLrrmz_8mii2pmXgIcGbi7KEq9NP31f3Am

**Comment by vfsfitvnm** [comment]
Thanks, you can add the "www" part in the meantime

**Comment by NeeRaj-2401** [comment]
Or add "music" and then search
Then click on "view playlist"
![Screenshot_2022-11-13-15-42-39-98_6f55a3c4de83481ebdee1685416eed82](https://user-images.githubusercontent.com/88180887/201516624-0b94d308-6d17-4c69-ad59-c4b142d42717.jpg)

**Comment by farzana840** [comment]
> Thanks, you can add the "www" part in the meantime

Still doesn't work...

**Comment by farzana840** [comment]
Thanks!

**Comment by vfsfitvnm** [comment]
Paste https://www.youtube.com/playlist?list=PLrrmz_8mii2pmXgIcGbi7KEq9NP31f3Am
