### ISSUE TITLE
Relax Mode

### ISSUE THREAD

**Issue by AUDIOAGARdotCOM** [vfsfitvnm/ViMusic#631]
### Feature description

It would be funny to have a Relax Mode where all app notifications are silenced and you only can listen music! 

### Why do you want this feature?

To enjoy my music without getting bored by notification from WA or Gmail.

**Comment by NeeRaj-2401** [comment]
> To enjoy my music without getting bored by notification from WA or Gmail.

U can on DND mode or silent your notifications for that period of time

**Comment by vfsfitvnm** [comment]
I think this related to #584 (i.e. handle audio focus). Incorporating in #584
