### ISSUE TITLE
Refresh Feature 

### ISSUE THREAD

**Issue by slugsi** [vfsfitvnm/ViMusic#639]
### Feature description

A pull down to refresh feature in the quick picks.

### Why do you want this feature?

Whenever I want to look for new songs that aren't in my quick picks section, I would rather refresh to find new suggestions than make a search and restart the app for it to change.

**Comment by vfsfitvnm** [comment]
Quicks picks are automatically refreshed when the trending song changes. If you want to see other songs, long press the trending song (the one with the star) and tap "remove from quicks picks" (or something similar)
