### ISSUE TITLE
App crashes randomly

### ISSUE THREAD

**Issue by Chanaky4** [vfsfitvnm/ViMusic#640]
### Steps to reproduce the bug

Sometimes it happens when I click on playlists, artists, albums,etc
The app just crashes randomly but the previous version like the 0.4.0 were working perfectly fine.

### Expected behavior

Everything should run and open up without crashing the app.

### Actual behavior

App crashing randomly.

### ViMusic version

0.5.4

### Android version

Android 6.0

**Comment by vfsfitvnm** [comment]
Can you provide the logs (`adb logcat`)?
