### ISSUE TITLE
Video 

### ISSUE THREAD

**Issue by Ridwaan112** [vfsfitvnm/ViMusic#644]
### Feature description

The video feature doesn't work it just plays the track but does not launch the actual music video 

### Why do you want this feature?

Please fix the video feature in the app

**Comment by faustaahmad** [comment]
ViMusic is a music player
If you wanted to watch MV, just open it directly on youtube or use other apps/web (Newpipe, Invidious, Piped, etc)

**Comment by Ridwaan112** [comment]
Understandable, however there is a tab that is listed and named video in the app and one would expect a video to play when clicking on it. It is misleading! Please remove it if it's off no use or mod it to work with the list of video players you listed above
