### ISSUE TITLE
Song request section (with links as reference)

### ISSUE THREAD

**Issue by Arifimranh** [vfsfitvnm/ViMusic#649]
### Feature description

Adding one extra panel or option where people could request songs to be added into the app, with links ofcourse (maybe from youtube and such). 

### Why do you want this feature?

I'm trying to find the song Moon & stars by $not, but it's not available. I was trying to find the request option, but it's not available. Would be cool if you guys could add that feature of requesting song.

**Comment by vfsfitvnm** [comment]
![Screenshot_20221116-063932590](https://user-images.githubusercontent.com/46219656/202093121-e56f5077-0815-4174-8c5f-567a84363d98.jpg)
