### ISSUE TITLE
App does not display any songs

### ISSUE THREAD

**Issue by Gmaxipix** [vfsfitvnm/ViMusic#657]
### Steps to reproduce the bug

Simply launch the app

### Expected behavior

App should show songs normally

### Actual behavior

No songs displayed

### Screenshots/Screen recordings

![Screenshot_2022-11-18-07-50-41](https://user-images.githubusercontent.com/117945959/202640445-081bfd55-52df-46b1-b25a-0d6a0a8f409d.png)
![Screenshot_2022-11-18-07-50-00](https://user-images.githubusercontent.com/117945959/202640449-983e54ec-bd7f-4f4c-9720-623015771b5e.png)
![Screenshot_2022-11-18-07-49-16](https://user-images.githubusercontent.com/117945959/202640457-21a9a043-b55c-4166-a766-6a5e7e8171e9.png)

### ViMusic version

O.5.4

### Android version

Android 5.0

**Comment by vfsfitvnm** [comment]
Can't reproduce on Android 5 emulator!

**Comment by Mikiexe** [comment]
Have the same issue on Redmi Note 5 Android 9. Nothing displays unless I intentionally search for a song or artist. Then shows the recent played. I thought it should've been showing anything. 
App v0.1.7

**Comment by vfsfitvnm** [comment]
@Milo40 @Mikiexe @Gmaxipix Where are you from?

**Comment by Mikiexe** [comment]
> @Milo40 @Mikiexe @Gmaxipix Where are you from?

Spain, also have an update
Had to fully uninstall ViMusic, then downloaded the latest v from F-Droid and after the installation I got it running on v0.5.2 and it displays correctly now. So prolly some issues with that v specifically.

**Comment by Gmaxipix** [comment]
> @Milo40 @Mikiexe @Gmaxipix Where are you from?

I'm from Algeria, and now that you're asking I think it'ss because of legal issues with youtube music because even in youtube music I get an error message and have to use a vpn, so I think it's that.

**Comment by Milo40** [comment]
> @Milo40 @Mikiexe @Gmaxipix Where are you from?

Well, I'm from Cameroon.
I'm going to try installing an ulterior version and see if it helps since i don't think the issue is related to country restrictions cause i can use YouTube Music without [Most of the time] restrictions.

**Comment by mumiby** [comment]
I have the same issue on ViMusic. The app show nothing upon launch. I suspected it'll be the same issue I had with Spotiflyer (error while attempting to download any tracks) 
**Solved by using a VPN** The content loads without problem

**Comment by vfsfitvnm** [comment]
Yeah, youtube music isn't (completely) available on your countries!

**Comment by sajeeth-ahamed** [comment]
This issue continues. I have an Android smartphone that is powered by Android 11. 

1. Showing no songs
2. Do not get the output for the searched song
3. Recommended playlist in the Quick pick section has not contained any songs at all.

**Comment by mumiby** [comment]
@sajeeth-ahamed Have you tried with a VPN ?

**Comment by sajeeth-ahamed** [comment]
@mumiby  Yes, I have. Also, tried in my brother's Samsung Galaxy A52. Exact problem occurs in that too

**Comment by mumiby** [comment]
@sajeeth-ahamed That's weird. I don't think it has anything to do with the phone brand nor the android version. I can assume ytmusic is not available in your country. But which VPN did you use? And which country did you choose on the VPN?

**Comment by RCOM363** [comment]
The issue is still there
App version v0.54
Android v12
