### ISSUE TITLE
Display of the track that is playing

### ISSUE THREAD

**Issue by shpatter** [vfsfitvnm/ViMusic#664]
### Feature description

Displaying the track playback animation at the cover location in all tabs (albums, songs, etc.). When a track starts playing, an icon will appear in its place in the songs, albums, etc. tabs, indicating that the track is currently playing.

### Why do you want this feature?

You can often make a mistake when you look at an album and can't figure out which track is playing now.

**Comment by vfsfitvnm** [comment]
I don't think I will implement it. Too expensive

**Comment by Fatcakes** [comment]
@vfsfitvnm this isn't the first time I've heard you say that. Is this app somehow costing you money other than your time?

**Comment by vfsfitvnm** [comment]
Expensive = costly from a computational point of view
