### ISSUE TITLE
Clear query button

### ISSUE THREAD

**Issue by librafrog** [vfsfitvnm/ViMusic#673]
### Feature description

Hi. I want to bring your attention to the absence of a clear queue action on some non-Google Play systems. I'm using

- MFG Huawei Model № KOB2-L09
- Model: MatePad T8
- Android 10
- version 0.5.4

### Why do you want this feature?

We already have the ability to re-order queue by drag/drop or clicking it will be useful in addition to "Persistent query" which survives closing the app, from time to time to clear the list :smile:

### Additional information

One idea of design is 
- [ ] ![play](https://user-images.githubusercontent.com/79138819/203389792-60e06858-58fc-46cc-9fd6-c9d34b3ded5c.png)

- [ ] <img src="https://user-images.githubusercontent.com/79138819/203388563-e1e8864a-a7a5-40a0-94db-8416d0743d75.png" width="32" />

**Comment by vfsfitvnm** [comment]
What? I'm not following you

**Comment by librafrog** [comment]
> What? I'm not following you

Sorry, grammar error. In short, I meant "**clear queue**". We can add to it, re-arrange etc., but can't clear it at once
