### ISSUE TITLE
Music Collection Archiv

### ISSUE THREAD

**Issue by dAtA-TRoN** [vfsfitvnm/ViMusic#687]
### Feature description

I would like to have an archive function. This would require an "add to archive" entry in the various relevant context menus. The archive itself would be accessible via the side menu bar, for example. The structure of the archive could be almost identical to the structure of the music collection. The icing on the cake would be a filter option to show all items together, Unarchived as well as archived items. 

### Why do you want this feature?

It would help to better keep track of the relevant part of the music library. I think everyone knows the problem to have many artists, albums, songs or playlist that we don't want to be displayed permanently, because they are rarely played for different reasons. But we don't want to delete them from our music collection either. To overcome this problem, an archive functionality would be the perfect solution.

Sorry for my bad way of expressing myself, English is not my first language. That's all. All I can say is keep it up. You are doing God's work :D .

**Comment by vfsfitvnm** [comment]
Won't do. Sorry

**Comment by dAtA-TRoN** [comment]
Ok, thanks for letting me know.
