### ISSUE TITLE
Reverse playing order for playlists

### ISSUE THREAD

**Issue by skwita** [vfsfitvnm/ViMusic#69]
### Feature description

It would be great if you can play songs in playlist in reverse order (from last added song to first one).

### Why do you want this feature?

I am used to listening to music in this order like it's done in spotify for example.

**Comment by noClaps** [comment]
I think this issue should be expanded to include different sorting options in general. Users could have options to sort by Name, Artist, Album and A-Z or Z-A, for example.

**Comment by vfsfitvnm** [comment]
I second @noClaps. A future release (hopefully the next) will have a better song pagination and will include sorting options. I'm tracking this UI-related things in #11.
