### ISSUE TITLE
Trending Search 

### ISSUE THREAD

**Issue by junior-aghosh** [vfsfitvnm/ViMusic#693]
### Feature description

Show the list of most searched song from YouTube/Google in the search panel

> Suggestion to use a light subtle text font

> Suggestion to use a trending arrow button before each listed songs

### Why do you want this feature?

Because from the perspective of user while we are searching we definitely want to know what's trending at the moment as well as most competitor music app has this feature 

### Additional information

A request to keep this app free from tracker libraries and keep it simple and light.

Feel free to include a seperate payment gateway for donations within the app. You devs deserve to be paid

**Comment by vfsfitvnm** [comment]
Hey, incorporating in #36!
