### ISSUE TITLE
Persistent queue is not working

### ISSUE THREAD

**Issue by Coinflipz** [vfsfitvnm/ViMusic#695]
### Steps to reproduce the bug

I dont know why but looks like persistent queue is not working for me. Enabled it in settings. Also tried to give all app permissions. But player still doesnt appear after closing and reopening the app.

### Expected behavior

Player should keep the queue i guess.

### Actual behavior

Player does not appear after closing and reopening the app.

### ViMusic version

v0.5.4

### Android version

Android 8.0.0

**Comment by vfsfitvnm** [comment]
Depending on your vendor, you may have to enable _Settings > Other > Ignore battery restrictions_. If it's not enough, enable "invincible service" in the same panel

**Comment by Coinflipz** [comment]
Ignore battery optimizations: Already unrestricted gray text
Invincible service also turned on
still same issue :(
can it be something about miui optimizations?

**Comment by vfsfitvnm** [comment]
Yeah, it definitely is. The queue is saved once you close the app and the playback service is stopped. However, if the OS immediately kills the process, the "last will" of the app is skipped and so the queue isn't saved.

You may find this site useful: https://dontkillmyapp.com/xiaomi

**Comment by Coinflipz** [comment]
Yea looks like miui optimizations really was the issue, thx.
