### ISSUE TITLE
Add fast-forward and fast-backward buttons

### ISSUE THREAD

**Issue by KGriss** [vfsfitvnm/ViMusic#70]
### Feature description

It could be really great to add simple fast-forward and fast-backward buttons to the right and the left of the Play/Pause button. When pressed, it will go forward or backward on the song by 5 seconds. This duration could be changed in settings (like putting it to 10 seconds for exemple). The same buttons (or at least the fast-backward one) could be added to the notification bar.
It works like the YouTube's double-tap on video frame and looks like the NewPipe buttons in bar.

### Why do you want this feature?

It is much easier to navigate throw the song using these buttons than using the navigation bar which is imprecise and sometime not visible due to the lack of contrast on the notification bar.

### Additional information

A picture of the NewPipe navigation bar buttons
![Screenshot_20220701_152937](https://user-images.githubusercontent.com/37448271/176904887-802d6e29-b0ed-4e20-ab6b-745d605be9fe.jpg)

**Comment by vfsfitvnm** [comment]
Thanks for taking your time to file this feature request, I wish everyone could give as much details as you did.

Adding such feature wouldn't be that hard, however I have several doubts regarding its usefulness.

I have never wished to skip a second by 5 or 10 seconds, honestly. It breaks the immersion - it just doesn't make sense for music.
If I want to start listening to a song at X seconds, I simply use the seekbar, and if I miss X by Y seconds, I just wait. I'll eventually get better at finding the right spot (also, using the seekbar within the app is super simple).

That's said, is a _won't fix_ by me, however let's wait for other people to share their opinions.

**Comment by KGriss** [comment]
I see what you mean about the immersion and the usefullness.

In fact, I understand that this add may not be useful to everyone.

Actually, I don't use these buttons to start listening to a song from a certain second but I use them to listen again to what I just heard. When I hear a passage in a piece of (text) music that I like, I like to listen to it several times to understand what is being said. For this, these buttons (especially the fast-backward one) would be very useful and much more precise, to go back a few seconds, than the navigation bar.

Regarding the design, here is an image of what it could look like in the notification bar :

![ViMusic fast bacward notification](https://user-images.githubusercontent.com/37448271/177005848-bb802539-d4ba-47a8-83e2-663512a1cdab.jpg)

I putted the like button discussed here #34 and I feel that the rendering is quite balanced

**Comment by vfsfitvnm** [comment]
Thanks, that clarifies your use case.

**Comment by noClaps** [comment]
I understand the use case for this, and I can think of a few more, such as being able to skip the non-music parts of songs.

However, NewPipe is probably able to do this because they have the skip feature built into their regular player, so they're able to use that feature in the notification player as well. If the developer is planning to add the skip feature to the regular player then I could see this making sense, but otherwise I don't really see the point.

Plus, you can keep using NewPipe if you wish.

Disclaimer: I am not an Android developer, so I could be completely wrong about how NewPipe implemented this.

**Comment by vfsfitvnm** [comment]
Closing in favor in #131
