### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by inventor7** [vfsfitvnm/ViMusic#72]
### Steps to reproduce the bug

The app just doesn't work at all in my s9 plus android 10

### Expected behavior

It doesn't worl

### Actual behavior

Doesn't work

### Screenshots/Screen recordings

![Screenshot_20220701-204732](https://user-images.githubusercontent.com/63302853/176960032-c62f4add-5b31-4ce1-bee6-139c41f29e92.jpg)

### Logs

...

### ViMusic version

The latest on3

### Android version

10

**Comment by vfsfitvnm** [comment]
This is not helpful at all. Did you try to close and reopen the app?

**Comment by inventor7** [comment]
I'm sorry for the lack of information i had to give 
But yes i try everything
Is YouTube music has to be installed ?

**Comment by inventor7** [comment]
I just discovered the issue it's about my location 
I changed it with "locatin changer" and now it works 
Thanks

**Comment by vfsfitvnm** [comment]
Yup, youtube music is not available worldwide (#2).

**Comment by shehryaar1** [comment]
> Yup, youtube music is not available worldwide (#2).

please remove youtube music from this app make this app to search only from YouTube or spotify
