### ISSUE TITLE
Incorrect backup file extension

### ISSUE THREAD

**Issue by Denio-7** [vfsfitvnm/ViMusic#724]
### Steps to reproduce the bug

1. Create backup through Settings - Databases. 
2. Try to restore this backup. 

### Expected behavior

The backup file should be in previously selected directory, and should be restored. 

### Actual behavior

The backup file is not visible in the directory, although it is there.

Backup file have *.db extension. After changing extension to *.bin - everything work correctly. 

### Screenshots/Screen recordings
Screen record of whole process
https://cloud.mail.ru/public/8a4P/QWuEmNmYW

### ViMusic version

0.5.4

### Android version

10

### Additional information

MIUI 12.0.2 CN stock version

**Comment by vfsfitvnm** [comment]
Yeah, this is a regression (it only happens with mixplorer, though).
