### ISSUE TITLE
Can't interact with system equalizer in MIUI 12.5

### ISSUE THREAD

**Issue by lookerloo** [vfsfitvnm/ViMusic#73]
### Steps to reproduce the bug

Can't use system equalizer in MIUI 12.5 android 11

Device: Redmi note 8 pro

A screen recorder is available below.

### Expected behavior

But it working in android 7  perfectely.

Device: Motorola G4 Plus

### Actual behavior

The eqalizer part is grayed out or dimmed in MIUI 12.5 Android 11, which means can't open system equalizer.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/108591373/177014773-9451b70d-5e0b-4264-86ac-a942e82d17c3.mp4

### ViMusic version

0.1.7

### Android version

Android 11

**Comment by vfsfitvnm** [comment]
Thanks for reporting, are other third party apps (e.g. retro music player) able to open it?

**Comment by jojobozo** [comment]
> Thanks for reporting, are other third party apps (e.g. retro music player) able to open it?

Same issue for me but I'm on A12.1 and I can open the equalizer on retro music player

**Comment by jojobozo** [comment]
https://user-images.githubusercontent.com/98482700/177019774-b6a53bf2-9335-4e5d-bd36-f75cdce776fc.mp4

**Comment by vfsfitvnm** [comment]
@lookerloo @jojobozo 
Would you download the debug apk from [here](https://github.com/vfsfitvnm/ViMusic/actions/runs/2606679242) and see if the equalizer thing works?

**Comment by lookerloo** [comment]
> @lookerloo @jojobozo 
> Would you download the debug apk from [here](https://github.com/vfsfitvnm/ViMusic/actions/runs/2606679242) and see if the equalizer thing works?

Yah it works!

Great job👏

Thanks a million🎉


https://user-images.githubusercontent.com/108591373/177070759-4794c40c-6f1f-4973-a5ff-ea330e142092.mp4

**Comment by jojobozo** [comment]
> @lookerloo @jojobozo Would you download the debug apk from [here](https://github.com/vfsfitvnm/ViMusic/actions/runs/2606679242) and see if the equalizer thing works?

Yes it's working

**Comment by lookerloo** [comment]
> @lookerloo @jojobozo 
> Would you download the debug apk from [here](https://github.com/vfsfitvnm/ViMusic/actions/runs/2606679242) and see if the equalizer thing works?

There is a bug in equalizer;

There is a lose in effect of equalizer after couple of times even the equalizer in on state.

Only the effect retain when manually tapping the equalizer section in settings

I dont know this is app or operating system bug.

A screen recorder with audio is available below.

If you listen/observe closely, you can notice a slight volume increase when tapping on the equalizer part.



https://user-images.githubusercontent.com/108591373/177095861-964fb610-0f1f-4cf9-a975-0308b646e546.mp4

**Comment by vfsfitvnm** [comment]
@lookerloo Probably a "bug" on my side (I'd say I still have to do something). Spotify doesn't have this problem because it doesn't handle an implementation-specific thing I can deduct by their statement  "**Changes you apply also affect the sound of other apps.**". I'm going to see what's the best approach today.

**Comment by lookerloo** [comment]
> @lookerloo Probably a "bug" on my side (I'd say I still have to do something). Spotify doesn't have this problem because it doesn't handle an implementation-specific thing I can deduct by their statement  "**Changes you apply also affect the sound of other apps.**". I'm going to see what's the best approach today.

👍

**Comment by lookerloo** [comment]
> In my device, the equalizer remains applied even when closing/reopening the app, and it is applied system-wide (this is not expected). It looks like you have to reopen it to make the effects being applied (this is not an issue, I think I can solve it).
> 
> > If you listen/observe closely, you can notice a slight increase in volume and immersive effect in song when tapping on the equalizer part.
> 
> This happens because the equalizer is applied. However, it also happens on play/pause or even when a seek occurs - this is annoying.

Yah, that's super annoying.

**Comment by vfsfitvnm** [comment]
As stated here, it looks like an Android bug: https://github.com/TeamNewPipe/NewPipe/issues/2833. However it's curious Spotify doesn't have this problem, but unfortunate since I can't look at their workaround.
@lookerloo Does Spotify uses the system equalizer (the one ViMusic opens) as well?

**Comment by lookerloo** [comment]
> As stated here, it looks like an Android bug: https://github.com/TeamNewPipe/NewPipe/issues/2833. However it's curious Spotify doesn't have this problem, but unfortunate since I can't look at their workaround.
> @lookerloo Does Spotify uses the system equalizer (the one ViMusic opens) as well?

I used spotify a long time ago. That time I noticed anything like that. Recentely I used Vanced Music. I tested spotify again after your comment, sadly spotify has the same issue too.

This android bug is new knowledge to me and I think you too.

I'm very sorry to you for wasting a lot of time and effort behind these silly things and  appreciating your hardwork and sincerity too.

Thank you for all!

**Comment by vfsfitvnm** [comment]
I have tried another device and the volume spike does not occur. Unfortunately, some users (including me) can't use the equalizer due to that annoying bug.

However, I'm closing this issue as it is solved (the equalizer setting is not disabled anymore).
