### ISSUE TITLE
Support youtu.be links

### ISSUE THREAD

**Issue by Surendrajat** [vfsfitvnm/ViMusic#77]
### Feature description

Support youtu.be links such as https://youtu.be/dQw4w9WgXcQ

### Why do you want this feature?

It's a nice feature

**Comment by vfsfitvnm** [comment]
Is the path (`dQw4w9WgXcQ`) always guaranteed to be a video id?

**Comment by Surendrajat** [comment]
Yup

**Comment by Surendrajat** [comment]
[Yup](https://blog.youtube/news-and-events/make-way-for-youtube-links/).
