### ISSUE TITLE
Is it possible 320 kbps support?

### ISSUE THREAD

**Issue by lookerloo** [vfsfitvnm/ViMusic#78]
### Feature description

Is it possible 320kbps or atleast 256 kbps support?

### Why do you want this feature?

Higher resolution always enhances listening experience.
It improves audio clarity and lows, mids, vocals etc of music.

**Comment by vfsfitvnm** [comment]
Youtube doesn't have 320kbps songs; it provides 256kbps to premium users. Also, it would require a login feature, thing I don't plan to do.
