### ISSUE TITLE
Transfering offline music from one phone to another

### ISSUE THREAD

**Issue by Soapbosnia** [vfsfitvnm/ViMusic#781]
Greetings! As the title states, since I've bought a new phone, is there any way I can transfer the cached songs from my old phone to my new one? I didn't add the songs to a specific playlist and just kept them in the default 'Offline' one, and since there's no multi-select for items in the list, it's a pain in the ass to add song by song to a playlist, export database, and then just let the phone play trough all songs (which itself, will take a long time haha), it'd be appreciated if someone could help me out, thanks :)

**Comment by vfsfitvnm** [comment]
The `cache` folder can't be transferred, unfortunately. So you will have to listen to the songs again.
