### ISSUE TITLE
Won't change lockscreen wallpaper to ablum art

### ISSUE THREAD

**Issue by SuperAadhil** [vfsfitvnm/ViMusic#793]
### Steps to reproduce the bug

1.  Go to Settings
2. In Appearance tab, under 'Lockscreen' 
3. Even if "Show Song Cover" is on. The wallpaper on the lockscreen doesn't change.

### Expected behavior

The lockscreen wallpaper should be the album art of the song currently playing.

### Actual behavior

Instead there is no change in the locker wallpaper.

### ViMusic version

0.5.4

### Android version

Android 9

### Additional information

![Screenshot_20221209-141546_Settings](https://user-images.githubusercontent.com/86368955/206661712-98fc4e9a-9327-4671-b471-b2add61ab57d.jpg)

This the model I'm using Vimusic on. I have tried another device, Samsung Galaxy Tab A 8.0 on Android 11. But, the issue persists.

**Comment by vfsfitvnm** [comment]
You may have to enable it as well in your device system settings. If you can't find that option, your device simply doesn't support it. This feature was dropped in Android 11, but some vendors still kept it.

**Comment by JLiveOf** [comment]
Yeah i have Samsung's One UI 5.0 Android 12 and Samsung does not seem to support the music lockscreen wallpapers on One UI
