### ISSUE TITLE
Retain the settings and search button

### ISSUE THREAD

**Issue by lookerloo** [vfsfitvnm/ViMusic#80]
### Feature description

Can you retain the settings button and search button if there a long list of played song and playlist under the two button (search & settings button).

### Why do you want this feature?

If we scroll down to bottom, that time we can't access settings and search button until we reach at the top

### Additional information

For reference; VLC player settings (look into the search and back arrow button animation/action)

https://user-images.githubusercontent.com/108591373/177123608-0f8a3fbe-0df5-4d46-8233-4c67e8190e48.mp4

ViMusic

https://user-images.githubusercontent.com/108591373/177123788-d05f17ad-36d6-4a2a-b2dc-caf7ccd21ca3.mp4

**Comment by vfsfitvnm** [comment]
Yes, this requires a general layout redesign. Let's track this in #11
