### ISSUE TITLE
Bluetooth over Google Home only shows the first title

### ISSUE THREAD

**Issue by oktayacikalin** [vfsfitvnm/ViMusic#800]
1. I connected my Android device with my Google Home over bluetooth. That works fine.
2. I started playing a playlist.
3. I looked at my Brave browser, which can also show what is playing on the Google Home and play/pause/stop it.

Problem:
The title was still the first song of the playlist.

**Comment by vfsfitvnm** [comment]
I don't think there is a problem in ViMusic, as it correctly implements the media session callbacks.

**Comment by oktayacikalin** [comment]
Yeah, you're right. I've also tested it with YT Music. It happens when my laptop goes to sleep, my smartphone plays the next song and I wake my laptop up again. Then Brave does not update the title anymore. But when I restart Brave, it works again. Strange. Sorry for bothering :-).

**Comment by vfsfitvnm** [comment]
Thanks for the update :)

**Comment by oktayacikalin** [comment]
You don't have an idea what might go wrong there?
I will try it with Google Chrome later on.

**Comment by oktayacikalin** [comment]
Could it be a stale udp connection? For example, the browser and the Google Home do decide on the ports. But when I put my laptop to sleep, the Home sees the connection as stale and won't send updates to it anymore?
