### ISSUE TITLE
Add Album to Playlist

### ISSUE THREAD

**Issue by Soveien** [vfsfitvnm/ViMusic#802]
### Feature description

The ability to hold tap on an album and add it to a playlist.

### Why do you want this feature?

I constantly find myself wanting to add a few albums from artists I listen too, to my playlist. however, the only option is to add each song individually. which gets quite annoying when each album has 10+ songs each, and I want to add 2, or sometimes 5/20± albums.

**Comment by vfsfitvnm** [comment]
Tracking in #161!
