### ISSUE TITLE
Import Playlists from other Platforms.

### ISSUE THREAD

**Issue by CrazySnort45** [vfsfitvnm/ViMusic#81]
### Feature description

It will be really helpful if we can import Playlists from other platforms like Apple music, Spotify and Tidal. By simply pasting a Playlist Link the whole playlist can be imported 

### Why do you want this feature?

I recently switched to this platform and I really have a ton of playlists on other platforms and it will be really helpful If I can import the same.

### Additional information

TuneMyMusic is one such website which supports popular platforms.

https://www.tunemymusic.com

**Comment by vfsfitvnm** [comment]
I don't think I will implement this feature.

**Comment by Jak2k** [comment]
What about an import from Google-Takeout. That's just a zip with an YT(-Music) and Playlist subfolder. In that are some csv files with the playlist. Tge only disadvantage is, that it's localized, but the words "YouTube" and "playlist" should be the same.

**Comment by vfsfitvnm** [comment]
Closing as this won't be implemented and I won't accept external contributions for it.
