### ISSUE TITLE
Better amoled theme

### ISSUE THREAD

**Issue by jojobozo** [vfsfitvnm/ViMusic#82]
### Feature description

I think the amoled theme would look better if the bottom bar and "up next" "lyrics" was black too

### Why do you want this feature?

Because it looks better overall

### Additional information

Like that for example:

For the bottom bar
![177020161-c08c9dbe-2fb6-4b83-849b-ca48b5a2e2e4](https://user-images.githubusercontent.com/98482700/177202329-38ee6c44-85b6-4f24-a09b-5f737c410039.png)

For "up next" and "lyrics"
![177020164-4f06fcd7-c67b-48f9-acc1-f54e41670f0e](https://user-images.githubusercontent.com/98482700/177202352-b1b49334-894c-4b30-8b14-e5bc3e55012b.png)

**Comment by vfsfitvnm** [comment]
Yes, they should be black too and there should be a grey border (is the grey border really necessary?)

**Comment by jojobozo** [comment]
> Yes, they should be black too and there should be a grey border (is the grey border really necessary?)

No it's not necessary tbh

**Comment by vfsfitvnm** [comment]
This is indirectly fixed now (there's no "up next" and "lyrics" :P)
