### ISSUE TITLE
Easier playlist navigation using the lateral nav bar inside the playlists themselves

### ISSUE THREAD

**Issue by Monoxide8969** [vfsfitvnm/ViMusic#829]
### Feature description

I'd like to be able to navigate the playlists from inside the playlists, specifically using the lateral navigation menu placed in the left side of the screen, which currently has only the voice "songs" in it, and it's not intractable.

Insteads of "songs" it would be nice to have the names of all the other playlists created (favorites and offline too) and to be able to instantly opening them by clicking on their names.

I hope I made myself clear while explaining this.
![image3](https://user-images.githubusercontent.com/108904135/207422798-b73a3925-8d54-49aa-bcec-37f03442317d.jpg)

### Why do you want this feature?

I think it'd be a very nice UX addition. Not a groundbreaking one, but it'd make navigating the playlists quicker and easier, being able to switch playlist without ever leaving the song list.

### Additional information

This already happens (albeit in a limited way, since only two playlists are available) with the "Favorites" and "Offline" playlists. It's possible to switch seamlessly from one playlist to another, without ever leaving the playlists.
![image2](https://user-images.githubusercontent.com/108904135/207422844-ebbec003-865a-4c89-9229-b6aea703d477.jpg)

**Comment by vfsfitvnm** [comment]
I don't think this will be implemented - it really doesn't help when you have a lot of playlists (plus the titles would be hard to recognize)!
