### ISSUE TITLE
Cast Feature?

### ISSUE THREAD

**Issue by deeprathod** [vfsfitvnm/ViMusic#84]
### Feature description

Thank. you for developing the awesome app. It's amazing. How about adding the cast feature which can then open the doors of usability on wide devices. 

### Why do you want this feature?

Introducing a cast feature will open doors for using the app on a wide range of devices, including smart speakers, TV, etc.

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/38#issuecomment-1152973809

(Closing as duplicate)
