### ISSUE TITLE
Music playback keeps reappearing in notifications even after clearing.

### ISSUE THREAD

**Issue by ankushk1729** [vfsfitvnm/ViMusic#86]
### Steps to reproduce the bug

1. Play a song.
2. Clear the app from recents.
3. Music player still in notifications.
4. Clear the music playback from notifications by swiping and deleting.
5. Music player reappears again after a while.

### Expected behavior

The music playback after clearing once by swiping and deleting in notifications should not reappear.

### Actual behavior

The music playback after clearing once by swiping and deleting in notifications is reappearing after some time again and again until you force stop the app.

### ViMusic version

0.1.7

### Android version

11

**Comment by vfsfitvnm** [comment]
Hi, this is a `androidx.media3` bug (I guess) - I got rid of it in the master branch.
Would you download the debug apk (https://github.com/vfsfitvnm/ViMusic/suites/7212834982/artifacts/288766062) and see it still occurs? It will install another app named "Debug".

**Comment by ankushk1729** [comment]
Tried it many times but couldn't recreate the bug, I guess it's fixed in this debug version.

**Comment by vfsfitvnm** [comment]
Perfect! We can assume it's fixed. Hold on for the next release!
