### ISSUE TITLE
Playlist issue

### ISSUE THREAD

**Issue by Pratyush102** [vfsfitvnm/ViMusic#87]
I cant add more than 38 songs in a Playlist.

**Comment by Pratyush102** [comment]
I've created a Playlist and when I added 38 songs after that whenever I'm trying to add another song to it then the song doesn't gets added in that Playlist

**Comment by vfsfitvnm** [comment]
That's weird, I can't reproduce. Are you trying to add the same song twice?

**Comment by vfsfitvnm** [comment]
Thanks for the video, what happens if you try to add another song?

**Comment by Pratyush102** [comment]
No I am trying to add different song
But it isn't getting added in the playlist

**Comment by vfsfitvnm** [comment]
Would you share your database? You can export it in Settings > Backup & Restore > Backup

**Comment by vfsfitvnm** [comment]
Closing as no additional info was provided (can't reproduce)
