### ISSUE TITLE
Adding canvas video 

### ISSUE THREAD

**Issue by ZaldyColinares** [vfsfitvnm/ViMusic#872]
### Feature description

If you ever had Spotify, there's a feat where a loop of a music video to a certain music appears on the music player. It'd be cool if this was on ViMusic.

### Why do you want this feature?

I just have it in my thought also, it would look nice too. 

### Additional information

Hoping it'll be implemented, lol.

**Comment by ZaldyColinares** [comment]
Lmao 69 issues

**Comment by vfsfitvnm** [comment]
Not feasible / won't do
