### ISSUE TITLE
Image on the player sometimes bugs out

### ISSUE THREAD

**Issue by Mexiater** [vfsfitvnm/ViMusic#880]
### Steps to reproduce the bug

Play random music while checking the player,  sometimes it won't change the image

### Expected behavior

The image should change accordingly to the song you're listening to

### Actual behavior

The image remains the same as the one of the previous songs 

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/121111263/208972984-6da2dc58-8da2-42a9-bf99-644f883470ad.mp4

### ViMusic version

0.5.4

### Android version

Latest version

**Comment by vfsfitvnm** [comment]
You have Android 13 I guess. See #267

**Comment by Mexiater** [comment]
> You have Android 13 I guess. See #267 

Aah shit I'm sorry I haven't specified, I have android 12
