### ISSUE TITLE
Radio recommends the same songs

### ISSUE THREAD

**Issue by jojobozo** [vfsfitvnm/ViMusic#89]
### Steps to reproduce the bug

Go to the app
Click on a random song
Scroll down to up next and select the last song
As you can see the radio is recommending the same songs but in a different order

### Expected behavior

The radio should recommend other songs like in YT Music

### Actual behavior

It just recommend the same songs over and over

### ViMusic version

0.1.7

### Android version

Android 12.1

**Comment by nateRiver111** [comment]
Mine works properly

**Comment by jojobozo** [comment]
> Unfortunately YouTube Music started recommending the same songs (but in a different order) on desktop too if you are not logged in - so, I don't think there's something I can do.
> 
> The idea of removing the endless radio crossed my mind because it's now useless, e.g. if you start the radio, you'll only get the first 25 songs.

Is it possible to make the last song of the radio start a new one?

**Comment by vfsfitvnm** [comment]
> Is it possible to make the last song of the radio start a new one?

It may be a valid idea, but I am confident YouTube will restore the original algorithm. Also, I don't want to complicate things further. Closing for now.

**Comment by vfsfitvnm** [comment]
> Is it possible to make the last song of the radio start a new one?


I just realized the change would be minimal - I'm seeing if there are benefits

**Comment by vfsfitvnm** [comment]
These are the results (as number of different songs):

youtube: 25 - 30 - 32 (stuck at 32)
jojobozo: 25 - 37 - 43 - 53 (stuck at 53)

So there's an improvement, but I don't know if it's worth the extra code. I'd rather make jojobozo's implementation the only one. But @nateRiver111 said its radio work fine, so I don't know I have the rights to (possibly) ruin other's people radio

**Comment by vfsfitvnm** [comment]
https://user-images.githubusercontent.com/46219656/179530178-500db985-98b8-467f-98a2-20715a27ede6.mp4

This is how it looks like for me. You can notice the songs are almost the same. However, it wasn't like this a month ago (they changed something based on the visitor country).

**Comment by jojobozo** [comment]
> These are the results (as number of different songs):
> 
> youtube: 25 - 30 - 32 (stuck at 32) jojobozo: 25 - 37 - 43 - 53 (stuck at 53)
> 
> So there's an improvement, but I don't know if it's worth the extra code. I'd rather make jojobozo's implementation the only one. But @nateRiver111 said its radio work fine, so I don't know I have the rights to (possibly) ruin other's people radio

Can you make it as an option then? So people facing the issue can enable it

**Comment by jojobozo** [comment]
I tried with a VPN and it got fixed, so maybe implementing a proxy or something like that would be better than starting a new radio, but I don't think that you would be ok with this idea

**Comment by vfsfitvnm** [comment]
@jojobozo 
Yeah, unfortunately I won't do that (#2).

I'm closing for now.
