### ISSUE TITLE
App Crashed on Android 12 (Funtouch 10.5)

### ISSUE THREAD

**Issue by creativrss** [vfsfitvnm/ViMusic#91]
Runtime Exception Error
![IMG_20220707_213332](https://user-images.githubusercontent.com/90452541/177825602-746f434a-8a47-477a-b111-e8b8443b413f.jpg)

**Comment by vfsfitvnm** [comment]
Hmm, this isn't helpful at all.
Would you download and launch the latest debug apk ([link](https://github.com/vfsfitvnm/ViMusic/suites/7254313684/artifacts/291535266)) and send the the `logcat` of the crash?

**Comment by creativrss** [comment]
I have installed the debug app, how to get `logcat` from it!?

**Comment by vfsfitvnm** [comment]
you can either install an application or https://forum.xda-developers.com/t/tutorial-how-to-logcat.1726238/

**Comment by vfsfitvnm** [comment]
Closing as no more info was provided.
