### ISSUE TITLE
Offline Caches Keeps On Disappearing

### ISSUE THREAD

**Issue by Benjirep** [vfsfitvnm/ViMusic#911]
### Steps to reproduce the bug

Used the app normally as it is, played some music then checked the Offline Caches first time it was there but then i checked again it is empty

### Expected behavior

Offline Caches shouldn't disappear

### Actual behavior

Offline Caches dissap after some time

### Screenshots/Screen recordings

![Screenshot_20230109-014945](https://user-images.githubusercontent.com/94770273/211211182-63262b94-3240-4352-b4b0-539dd369ac5c.jpg)
![Screenshot_20230109-015024](https://user-images.githubusercontent.com/94770273/211211185-98b04f20-177e-4ecf-b072-77a2d844e4dd.jpg)

### ViMusic version

0.5.4

### Android version

Android 12

**Comment by vfsfitvnm** [comment]
See #289
