### ISSUE TITLE
Meaning of "Sort by clock" button

### ISSUE THREAD

**Issue by rentruewang** [vfsfitvnm/ViMusic#916]
### Steps to reproduce the bug

1. Open `song 1` from `album 1` (don't open the album! Just remember which album it's from)
2. Open `album 2`, play next on `song 2`.
3. Play next on `song 3` that's also on `album 1`.
4. Play next `song 4`  that's also in `album 2`.

**NOTE**: `song 4` precedes `song 2` in `album 2`

### Expected behavior

The order in played (the clock on main page) should be:
`song 1`
`song 2`
`song 3`
`song 4`

### Actual behavior

Because once an album is open, all songs are added at once:
`song 1`
`song 4`
`song 2`
`song 3`

### ViMusic version

v0.5.4

### Android version

Android 13

### Additional information

Probably because of this, however I don't do Android development so IDK how to fix.

However, by tracing the INSERT calls, I guess the issue is the INSERT all songs behavior here:

https://github.com/vfsfitvnm/ViMusic/blob/055ad86f2ca78a8f2a84d373a2d86ef76e8390ef/app/src/main/kotlin/it/vfsfitvnm/vimusic/ui/screens/album/AlbumScreen.kt#L63-L108

Maybe you could add a new attribute in the `Song` class here:

https://github.com/vfsfitvnm/ViMusic/blob/5c056a3b8406b567a505b55c7ab9effce09e4e36/app/src/main/kotlin/it/vfsfitvnm/vimusic/models/Song.kt#L9-L17

**Comment by vfsfitvnm** [comment]
Uhm, I don't really understand what the problem is. Could you provide a screen recording or a more detailed description of what's happening?

**Comment by elsayedalaa** [comment]
When next update my friend?

**Comment by rentruewang** [comment]
@vfsfitvnm 

> Uhm, I don't really understand what the problem is. Could you provide a screen recording or a more detailed description of what's happening?

There is a "sort by time" in the "song" panel (see image).

![vimusic-song](https://user-images.githubusercontent.com/32859905/212553048-55247ee2-603b-4fee-b605-4c906a9c5f53.jpg)

Apparantly this sort order is by `rowID` in the sqlite database, which becomes a problem because when an album is opened, all songs in the album seem to be added at once, causing this panel *not* to be an actual order of the songs played.

Unfortunately I couldn't do a screen recording at this time.

**Comment by vfsfitvnm** [comment]
Thanks for the clarification.

> Apparantly this sort order is by rowID in the sqlite database, which becomes a problem because when an album is opened, all songs in the album seem to be added at once (upon first open), causing this panel not to be an actual order of the songs played

This is intended: the "sort by clock icon" does not reflect your playback history, but the insertion order of the songs to the database - i.e. "_when you encountered a song for the first time_".
What you describe is an unfortunate side effect of this design decision - and I honestly don't think I will ever change it (not because I find it useful, but I don't have the time/will to think of and code another solution)...

**Comment by rentruewang** [comment]
@vfsfitvnm 

Thanks for the quick response!

I'm wondering maybe you could add a `firstListen` variable in the `Song` class? Then songs could be easily sorted by that attribute.

Or maybe a better solution is to use another icon instead of the "clock"?
Because e.g. spotify / YTM uses a clock icon for playback history, and I think that's what most people expect, perhaps using a different icon would help clarify what this button actually means.
