### ISSUE TITLE
Battery Optimization

### ISSUE THREAD

**Issue by NeeRaj-2401** [vfsfitvnm/ViMusic#92]

**Comment by NR8124** [comment]
Also can u provide some other platform such as telegram or discord for community communication because these small things be cleared there.. rather than opening new issues everytimee..

**Comment by NR8124** [comment]
Also can u provide some other platform such as telegram or discord for community communication because these small things be cleared there.. rather than opening new issues everytimee..

**Comment by vfsfitvnm** [comment]
https://github.com/vfsfitvnm/ViMusic/issues/24
