### ISSUE TITLE
Shuffle Button Action on Artists screen

### ISSUE THREAD

**Issue by NR8124** [vfsfitvnm/ViMusic#93]
### Feature description

shuffle button of artists screen always plays the same song and suggest the same list of songs to be played next.

### Why do you want this feature?

the basic idea of shuffle is to always randomize the song and upcoming list

### Additional information

Here is the video sample of the problem..

https://user-images.githubusercontent.com/88180887/178100797-878b499f-3ebe-4fa7-ac04-2bd9c2c84986.mp4

**Comment by vfsfitvnm** [comment]
That happens because I cache the shuffle and radio endpoints (I don't want to fire a network request everytime the artist page is opened). I'll find a solution; in the meantime you can tap the artist image to  refresh those endpoints

**Comment by NR8124** [comment]
Oh thanx :) i'll try that in next debug build
