### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by NoRecovery** [vfsfitvnm/ViMusic#94]
### Steps to reproduce the bug

1. Open ViMusic
2. Search any song
3. No results found
4. Go to artists
5. Click any u searched
6. Any option i click will close app

### Expected behavior

1. Open vi music
2. Search song
3. Play the desired song

### Actual behavior

App instantly crashing when selecting artist, no results when searching songs.

### Screenshots/Screen recordings

![Screenshot_20220709-141142](https://user-images.githubusercontent.com/108983435/178105200-2c0460ac-f492-4e41-8213-41db3a2da93e.jpg)

### ViMusic version

0.1.7

### Android version

Android 11

### Additional information

Also tried the app on Android 7. Tried with rooted and non rooted phone. Same result

**Comment by vfsfitvnm** [comment]
I can't reproduce. Do you have a VPN/Proxy settings active? Do you live in a country where youtube music is available?

**Comment by NoRecovery** [comment]
In fact im not in a country where youtube music is available, My bad. Turning on VPN fixes the issue.
