### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by MMMATRIX** [vfsfitvnm/ViMusic#940]
### Steps to reproduce the bug

When ever i open quick picks or online song search i does not load. Help please.😔

### Expected behavior

It should open

### Actual behavior

It doesn't.

### Screenshots/Screen recordings[](
![Screenshot_20230124_225233](https://user-images.githubusercontent.com/112827868/214429420-47d86edc-1a8d-49c4-950f-ee259bc44e07.jpg)

_No response_

### ViMusic version

0.5.4

### Android version

Android 12

**Comment by YarostheLaunchpadder** [comment]
Yeah, have the same issue!

**Comment by shompoe** [comment]
Me too

**Comment by MMMATRIX** [comment]
> Yeah, have the same issue!

Maybe yt music crashed or blocked vimusic

**Comment by chosinriver** [comment]
I have same issue

**Comment by raiyoku77** [comment]
Same issue here

**Comment by raiyoku77** [comment]
> > Yeah, have the same issue!
> 
> Maybe yt music crashed or blocked vimusic

Idk but it also stopped my Youtube Music Vanced from loading

**Comment by ranzouu** [comment]
Ok, everyone has the same loading, so what we do

**Comment by DALKUZ** [comment]
From what I've seen YouTube is having connection problems.![Screenshot_2023-01-24-15-43-12-345.jpg](https://user-images.githubusercontent.com/77499128/214437774-14919fee-84b8-4d58-91e4-e58825828a66.jpg)

**Comment by MMMATRIX** [comment]
> From what I've seen YouTube is having connection problems.![Screenshot_2023-01-24-15-43-12-345.jpg](https://user-images.githubusercontent.com/77499128/214437774-14919fee-84b8-4d58-91e4-e58825828a66.jpg)

Soooooo..... its gona be fixed soon....... i hope

**Comment by YarostheLaunchpadder** [comment]
It's working for me again

**Comment by MMMATRIX** [comment]
Fixed

**Comment by MMMATRIX** [comment]
Just a yt problem
