### ISSUE TITLE
Infinite Loading

### ISSUE THREAD

**Issue by raiyoku77** [vfsfitvnm/ViMusic#941]
### Steps to reproduce the bug

1 - Boot the app
2 - Select "Quick Picks"

### Expected behavior

It should load content

### Actual behavior

Infinite loading

### Screenshots/Screen recordings

![Screenshot_20230124-232306](https://user-images.githubusercontent.com/56881854/214435274-b0696737-a1bf-47ab-a984-5df6ecd9b0e8.png)

### ViMusic version

0.5.4

### Android version

Android 12

**Comment by jacobabahn** [comment]
Did you download it from F-Droid? I had the same issue when downloading from F-Droid. I was able to fix it by uninstalling the app and then installing from GitHub.

**Comment by raiyoku77** [comment]
I installed it from Github, but it seems the problem came from Youtube and not the app in the end. :)
