### ISSUE TITLE
Download Whole Playlist to Storage for Offline playback

### ISSUE THREAD

**Issue by KakarottoCake** [vfsfitvnm/ViMusic#95]
### Feature description

Don't close this issue please, read it before you do. I saw that you mentioned it could already played on the device offline after adding it. That's fine, but I'm primarily looking for downloading a whole playlist, and in addition, be able to access those music files from my storage device so I can also use the music on other devices. 

### Why do you want this feature?

I haven't found another app that provides this QoL feature, and this one shows promise.

**Comment by vfsfitvnm** [comment]
I think you want a "pre-cache" feature (#83)

**Comment by KakarottoCake** [comment]
Well, I guess? I mean tbh my thinking here's a little more straightforward. I just wanna be able to click the 3 dots on a playlist (like, an existing on from YouTube, not one I made in the app itself) click download, then have the mp3s (or whatever audio format they're in) be downloaded to the device so I can use them on my other music players. The closest I was able to find was with "Spotiflyer" but that's a hit or miss 50% of the time.

**Comment by vfsfitvnm** [comment]
Well, if you just need a downloader, you could use [youtube-dl](https://github.com/ytdl-org/youtube-dl). [Music](https://github.com/z-huang/music), [BlackHole](https://github.com/Sangwan5688/BlackHole)...

**Comment by KakarottoCake** [comment]
youtube-dl is a command line interface: no
Music is still in beta and is missing basic functionalities for downloading playlists: no
Black hole... Just doesn't even work in my country

**Comment by vfsfitvnm** [comment]
There are also plenty of websites that allows you to download albums or playlists I guess.

A download (download and export to external storage) feature is not planned because:
1- I don't need it;
2- The ability to play local music files should be implemented first (I don't need that too);
3- It has zero priority - songs are already downloaded and cached while being played;
4- I don't want to deal with file formats, headers and stuff - this is a music player, not an audio encoder/tagger/converter.

**Comment by santosp1** [comment]
I don't know if I can refer to a different project here, but a nice app for downloading playlist is [Spotiflyer](https://github.com/Shabinder/SpotiFlyer), currently running on desktop, android and web, and also available at F-droid.

**Comment by vfsfitvnm** [comment]
Closing (let's keep the download and export feature in #83)

**Comment by KakarottoCake** [comment]
😕

**Comment by Erik-vdb** [comment]
@KakarottoCake You are looking for [YMusic](https://ymusic.io/)
