### ISSUE TITLE
Incorrect album cover on notification tab

### ISSUE THREAD

**Issue by face-hh** [vfsfitvnm/ViMusic#958]
### Steps to reproduce the bug

1. Have a playlist with at least 3 songs
2. Play it
3. After the first song has finished, look at the notification tab inside notifications

As a note, this was done on Xiaomi Redmi Note 11, latest MiUI.

### Expected behavior

The album cover on the left should be corresponding to the current song.

### Actual behavior

The album cover is set to the first song played in the session, sometimes fixes on certain songs.

### Screenshots/Screen recordings

![Screenshot_2023-02-04-23-22-53-297-edit_com miui home](https://user-images.githubusercontent.com/69168154/216790344-c3d75e1f-3709-4044-97c0-3726c651268d.jpg)
![Screenshot_2023-02-04-23-29-44-229-edit_com android chrome](https://user-images.githubusercontent.com/69168154/216790346-c9b8b53f-4c56-45cb-8ffd-b5dbb42ab43e.jpg)

### ViMusic version

0.5.4

### Android version

Android 11

### Additional information

I am pretty sure additional information is required to determinate the cause of this bug.

**Comment by vfsfitvnm** [comment]
For the blurry cover, I suspect you need to enable "Show song cover" in Settings > Appearance.
The stale album cover is a problem of Android 13 (but that's not the case), so I think it's a MIUI bug

**Comment by face-hh** [comment]
> For the blurry cover, I suspect you need to enable "Show song cover" in Settings > Appearance
The description of that setting specifies that it will change the background on lockscreen, this bug happens in the notifications tab, and I don't think it's because of an error since sometimes it is in high quality

> The stale album cover is a problem of Android 13 (but that's not the case), so I think it's a MIUI bug
Yeah I also suspect that it's a MIUI bug since they're the ones that have split screen for notifications and quick options (not sure about other phones having that, I'm a Xiaomi user)

**Comment by vfsfitvnm** [comment]
Closing as there's no action I can take!
