### ISSUE TITLE
Sometimes when i play a music, its starting stuttering like lagging idk something like that, so the music didnt played well

### ISSUE THREAD

**Issue by samsi101** [vfsfitvnm/ViMusic#966]
### Steps to reproduce the bug

Change the songs

### Expected behavior

-

### Actual behavior

-

### ViMusic version

0.5.4

### Android version

Android 11

**Comment by lbrunkho** [comment]
Can you provide some additional information about your network connectivity (mobile data / WiFi) when you experience this? 
Do you have plenty of internet bandwidth when you notice this issue (>5MB/s download)? 
Does this happen for songs already in your offline playlist? 

It sounds like you are running into a buffering issue, but if that is the case it should not effect songs already in your cache (offline playlist). I have ran into "stuttering" but only when I'm on mobile data and in a rural area with poor cell coverage.

**Comment by samsi101** [comment]
It happened when i use mobile data for online songs (not the offline one),
then i got this reply and you said that it is caused by the internet issue,
i do agree and think that's the main problem, so i conclude that as an
internet connection issue, thanks for the follow up, really appreciate it
