### ISSUE TITLE
Lockscreen background does not work

### ISSUE THREAD

**Issue by SoSgAmEr7890r** [vfsfitvnm/ViMusic#975]
### Steps to reproduce the bug

I just activated the feature and it does not work

### Expected behavior

The song cover of the song that is playing at the moment should appear as wallpaper on my lockscreen

### Actual behavior

my self-selected current wallpaper is still there 

### Screenshots/Screen recordings

Here a proof video [lol](https://youtube.com/shorts/Eq1oVnGSCPw?feature=share)

### ViMusic version

0.5.4

### Android version

Android 11

### Additional information

My phone is rooted but i dont use a custom rom. Its just the default samsung system but yes just rooted.

**Comment by Syntax-Err5** [comment]
[Most manufacturers dropped the feature in Android 11](https://github.com/vfsfitvnm/ViMusic/issues/793#issuecomment-1344136312) so it may not work.

**Comment by SoSgAmEr7890r** [comment]
Ok thanks
