### ISSUE TITLE
Ok not a bug but a better make a discord server...

### ISSUE THREAD

**Issue by FaNticDaedlYs** [vfsfitvnm/ViMusic#976]
### Steps to reproduce the bug

Ok vfsfitnvm, make a discord server, if u want help u can surely ask me... But making discord server would be better as we can have a better method of communication.. also management and stuff would be easy and problem discussion will be efficient 

### Expected behavior

Make a discord server 🗿

### Actual behavior

Not a bug

### ViMusic version

Not a bug

### Android version

Not a bug

**Comment by rickdtc** [comment]
Or a telegram channel

**Comment by ikanakova** [comment]
If @vfsfitvnm was interested in a discussion, which I don't think he would be, I find GitHub Discussions ideal because not everyone has Discord/Telegram etc.

**Comment by vfsfitvnm** [comment]
I really have a hard time imagining how such 'community' could be helpful (to me) or relevant. I bet it would become a literal help desk (but with memes). I don't want to go through that right now.

I'm quite happy and satisfied to see this application has taken off.
However, I'm currently living a stage of "uncertainty" (at a personal level) and I really can't dedicate a single minute to this project again without feeling a sense of non-accomplishment.
Once things get more stable, I will certainly revive this application. The codebase is embarrassing, the performance isn't quite good (*cough cough* Jetpack Compose), the UI must be improved...

Currently, the project is in maintenance mode. 
That is, the application will be updated only if something breaks (I still use ViMusic everyday).
That's also why you can't (well, shouldn't) file new feature requests (and if you do, they are going to be deleted by me).

**Comment by rickdtc** [comment]
Understandable, You do you ❤

**Comment by Raj2032** [comment]
Why isn't "discussion" enabled anyways?
