### ISSUE TITLE
Add Sleep Timer to Dotted Menu

### ISSUE THREAD

**Issue by C2M6D** [vfsfitvnm/ViMusic#98]
### Feature description

To make the sleep timer accessible from the three-dotted menu when playing a song.

### Why do you want this feature?

So that I can easily access the sleep timer without having to go to the settings.

**Comment by vfsfitvnm** [comment]
Will do. Out of curiosity, do you use the sleep timer? If so, why?

**Comment by C2M6D** [comment]
> Will do. Out of curiosity, do you use the sleep timer? If so, why?

Yes, I do. I use it when I listen to music over set period of time. So, when the music stops, I know that its time to finish up. Obviously, I also use if I know that I might fall asleep  💤

**Comment by vfsfitvnm** [comment]
@C2M6D 
What if the sleep timer gets removed from settings? And just displayed on that menu?
