### ISSUE TITLE
Cannot play songs while on a phone call

### ISSUE THREAD

**Issue by VVarun97** [vfsfitvnm/ViMusic#998]
### Steps to reproduce the bug

1.While on a phone call
2. Not able to start/play songs 

### Expected behavior

Should be able to play songs in background while on a phone call.

### Actual behavior

Not able to play songs in background while on a phone call.

### ViMusic version

0.5.4

### Android version

Android 11

**Comment by VVarun97** [comment]
Other music apps allow it, which is why

**Comment by VVarun97** [comment]
Other music apps allow it, which is why

**Comment by vfsfitvnm** [comment]
Part of #584
